DROP TABLE OPERACION.SUBTIPO_ORDEN_ADC;

DROP TABLE OPERACION.TIPO_ORDEN_ADC;

DROP TABLE OPERACION.MATRIZ_TIPTRATIPSRVMOT_ADC;

DROP TABLE OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC;

DROP TABLE OPERACION.WORK_SKILL_ADC;

DROP TABLE OPERACION.DTH_PREASOCIACION_TMP;

DROP TABLE OPERACION.TMP_CAPACIDAD;

DROP TABLE OPERACION.TRANSACCION_WS_ADC;

DROP TABLE OPERACION.LOG_INSTALACION_EQUIPOS;

DROP TABLE OPERACION.PARAMETRO_DET_ADC;

DROP TABLE OPERACION.PARAMETRO_CAB_ADC;

DROP TABLE OPERACION.ZONA_ADC;

DROP TABLE OPERACION.PARAMETRO_VTA_PVTA_ADC;

DROP TABLE OPERACION.BUCKET_CONTRATA_ADC;

DROP TABLE OPERACION.CAMBIO_ESTADO_OT_ADC;

DROP TABLE OPERACION.ESTADO_ADC;

DROP TABLE OPERACION.ESTADO_MOTIVO_SGA_ADC;

DROP TABLE OPERACION.FRANJA_HORARIA;

DROP TABLE OPERACION.INVENTARIO_ENV_ADC_LOG_ERR;

DROP TABLE OPERACION.INVENTARIO_ENVIO_ETA_ERR;

DROP TABLE OPERACION.INVENTARIO_ENV_ADC;

DROP TABLE OPERACION.OPE_SOT_MASIVA_LOG;

DROP TABLE OPERACION.VTATABCLI_HIS;

DROP TABLE OPERACION.INVENTARIO_EM_ADC;

DROP TABLE OPERACION.LOG_ERROR_WS_ADC;

DROP TABLE OPERACION.CARGA_CLIENTES_VIP_LOG_ERR;

DROP SEQUENCE OPERACION.SEQ_TIPO_ORDEN_ADC;

DROP SEQUENCE OPERACION.SEQ_SUBTIPO_ORDEN_ADC;

DROP SEQUENCE OPERACION.SEQ_MATRIZ_TYSTIPSRV_TIPTRA;

DROP SEQUENCE OPERACION.SEQ_WORK_SKILL_ADC;

DROP SEQUENCE OPERACION.SEQ_TRANSACCION_WS_ADC;

DROP SEQUENCE OPERACION.SEQ_CAMBIO_ESTADO_OT_ADC;

DROP SEQUENCE OPERACION.SEQ_CARGA_CLIENTES_VIP_LOG_ERR;

DROP SEQUENCE OPERACION.SEQ_ID_ZONA_ADC;

DROP SEQUENCE OPERACION.SEQ_IDFRANJA;

DROP SEQUENCE OPERACION.SEQ_PARAMETRO_CAB_ADC;

DROP SEQUENCE OPERACION.SEQ_PARAMETRO_DET_ADC;

DROP SEQUENCE OPERACION.SEQ_VTATABCLI_HIS;

DROP SEQUENCE OPERACION.SQ_INVENTARIO_ENV_ADC;

DELETE 
  FROM operacion.ope_det_xml
 WHERE idcab IN (SELECT a.idcab
                   FROM operacion.ope_cab_xml a
                  WHERE a.programa IN
                        ('consultaCapacidadSGA',
                         'cancelarOrdenSGA_ADC',
                         'gestionarOrdenSGA_ADC',
                         'cargarInventarioTotalSGA_ADC',
                         'cargarInventarioIncrementalSGA_ADC'));

DELETE 
  FROM operacion.ope_cab_xml a
 WHERE a.programa IN ('consultaCapacidadSGA',
                      'cancelarOrdenSGA_ADC',
                      'XAServices_ToInstall',
                      'Services_ToInstall',
                      'gestionarOrdenSGA_ADC',
                      'cargarInventarioTotalSGA_ADC',
                      'cargarInventarioIncrementalSGA_ADC');

COMMIT;

ALTER TABLE operacion.tiptrabajo 
	DROP COLUMN id_tipo_orden;


DROP PACKAGE OPERACION.PQ_ADM_CUADRILLA; 

