-- SCRIPT VENTA
DELETE FROM OPERACION.TIPTRABAJO
WHERE DESCRIPCION = 'BAJA TOTAL 3PLAY INALAMBRICO';

DELETE FROM OPERACION.TIPTRABAJO
WHERE DESCRIPCION = 'SUSPENSION 3PLAY INALAMBRICO';

DELETE FROM OPERACION.TIPTRABAJO
WHERE DESCRIPCION = 'RECONEXION 3PLAY INALAMBRICO';

commit;
