--- CABECERA
--1
delete from OPERACION.TIPOPEDD where DESCRIPCION='TIPTRA PARA ALINEACION';
--2
delete from OPERACION.TIPOPEDD where DESCRIPCION='ESTADO ALINEACION';
--3
delete from OPERACION.TIPOPEDD where DESCRIPCION='TIPO PRODUCTO';
--3
delete from OPERACION.TIPOPEDD where DESCRIPCION='FLAG CONSULTA IW';
commit;

