--- DETALLE
--1
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--2
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;
--3
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--4
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--5
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--6
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--7
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--8
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--9
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--10
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--11
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--12
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--13
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>  
--14
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--15
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--16
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--17
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--18
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--19
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--20
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>;  
--21
delete FROM OPEDD  WHERE IDOPEDD =<Id_tabla_OPERACION.OPEDD>; 
COMMIT;