--- CABECERA
--1
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--2
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--3
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--4
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--5
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--6
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--7
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--8
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--9
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--10
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--11
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--12
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>; 
--13
DELETE FROM TIPOPEDD WHERE TIPOPEDD=<Id_tabla_OPERACION.TIPOPEDD>;

COMMIT; 