ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_direccion_nro;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_pais;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_zona_horaria;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_nom_departamento;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_nom_provincia;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_nom_distrito;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_codigo_postal;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_poblacion;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_provincia;
ALTER TABLE OPERACION.UBI_TECNICA DROP COLUMN ubitv_departamento;

DELETE FROM operacion.opedd WHERE abreviacion = 'ZONA_HORARIA';

COMMIT;
/
