alter table OPERACION.SIAC_INSTANCIA
drop column flg_tecn;

UPDATE OPERACION.opedd
SET CODIGON = null
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - TRASLADO EXTERNO';

UPDATE OPERACION.opedd
SET CODIGON = null
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - PUNTO ADICIONAL';

UPDATE OPERACION.opedd
SET CODIGON = null
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - TRASLADO INTERNO';
commit;
/