
-- Restaura Modificacion tabla OPERACION.SGAT_EF_ETAPA_CNFG
ALTER TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG DISABLE;

ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_SUBESCEN1 TO EFECN_DCMD;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_SUBESCEN2 TO EFECN_MCMD;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_SUBESCEN3 TO EFECN_MUMD;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG DROP (EFECN_ELEMENTO_SM);

COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_MCMD IS 'FLAG MISMO CLIENTE/MISMA DIRECCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_DCMD IS 'FLAG DIFERENTE CLIENTE/MISMA DIRECCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_MUMD IS 'FLAG MUFA MISMA DIRECCIÓN.';

-- Restaura Trigger OPERACION.SGATRU_EF_ETAPA_CNFG
CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG
BEFORE UPDATE ON OPERACION.SGAT_EF_ETAPA_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFECV_USUMOD := user;
  :new.EFECD_FECMOD := sysdate;
  
 IF UPDATING('EFECV_CODPAR') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECV_CODPAR',:OLD.EFECV_CODPAR ||' ===> '||:NEW.EFECV_CODPAR,'CÓDIGO DE NEGOCIO DE MO/MATERIALES');
  END IF; 
  IF UPDATING('EFECN_CANTIDAD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_CANTIDAD',:OLD.EFECN_CANTIDAD||' ===> '||:NEW.EFECN_CANTIDAD,'CANTIDAD');
  END IF;
  IF UPDATING('EFECN_MCMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_MCMD',:OLD.EFECN_MCMD||' ===> '||:NEW.EFECN_MCMD,'MISMO CLIENTE/MISMA DIRECCIÓN');
  END IF;
  IF UPDATING('EFECN_DCMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_DCMD',:OLD.EFECN_DCMD||' ===> '||:NEW.EFECN_DCMD,'DIFERENTE CLIENTE/MISMA DIRECCIÓN');
  END IF; 
  IF UPDATING('EFECN_MUMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_MUMD',:OLD.EFECN_MUMD||' ===> '||:NEW.EFECN_MUMD,'MUFA MISMA DIRECCIÓN');
  END IF;
  IF UPDATING('EFECN_ESTADO') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_ESTADO',:OLD.EFECN_ESTADO||' ===> '||:NEW.EFECN_ESTADO,'ESTADO DE LA CONFIGURACIÓN');
  END IF;   
END;
/

ALTER TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG ENABLE;
ALTER TRIGGER OPERACION.SGATRI_EF_ETAPA_CNFG COMPILE;


-- Restaura tabla OPERACION.SGAT_EF_ETAPA_PRM
ALTER TABLE  OPERACION.SGAT_EF_ETAPA_PRM 
DROP (
  EFEPN_CODN3,
  EFEPV_CODV3
  );
  
-- Restaura TABLA OPERACION.EFPTO
ALTER TABLE OPERACION.EFPTO
 DROP (EFPTN_LONFIBRA_PROY,
       EFPTV_RFS_GIS,
       EFPTV_POLITICA,
       EFPTN_EQUIPOPINT);

	   