-- GRANT/REVOKE OBJECT PRIVILEGES 
revoke execute on OPERACION.PKG_EF_COSTEO from USREAISGA;
revoke execute on OPERACION.PKG_FACTIBILIDAD from USREAISGA;
revoke execute on OPERACION.PKG_GESTION_RECURSOS from USREAISGA;
---
revoke execute on OPERACION.PKG_EF_COSTEO from R_PROD;
revoke execute on OPERACION.PKG_FACTIBILIDAD from R_PROD;
----
REVOKE SELECT ON FINANCIAL.SOLICITUD_MAT FROM OPERACION; 
REVOKE SELECT ON METASOLV.PEX_CAJTER FROM OPERACION;
REVOKE SELECT ON METASOLV.SGAT_PEX_FIBRA FROM OPERACION;
REVOKE SELECT ON METASOLV.EQUIPORED FROM OPERACION;
REVOKE SELECT ON METASOLV.TARJETAXEQUIPO FROM OPERACION;
REVOKE SELECT ON METASOLV.PUERTOXEQUIPO FROM OPERACION;
REVOKE SELECT ON SALES.VTADETPTOENL FROM OPERACION;
REVOKE SELECT ON BILLCOLPER.PRODUCTO FROM OPERACION;
REVOKE SELECT ON PRODUCCION.ALMTABMAT FROM OPERACION;
REVOKE SELECT ON METASOLV.SGAT_TIPAGR_EQUIPORED FROM OPERACION;
REVOKE SELECT ON METASOLV.PEX_TIPCABLE FROM OPERACION;
REVOKE SELECT ON METASOLV.PEX_CABLE FROM OPERACION;
REVOKE SELECT ON MARKETING.VTASUCCLI FROM OPERACION;
REVOKE SELECT ON FINANCIAL.Z_PS_VAL_BUSQUEDA_DET FROM OPERACION;
REVOKE SELECT ON MARKETING.SGAT_DIRGEOREF_SW FROM OPERACION;
/
