-- BORRAR REGISTROS CREADOS
DELETE FROM OPERACION.OPE_CAB_XML WHERE PROGRAMA = 'BSS_GestionSEFGIS';

DELETE FROM OPERACION.SGAT_EF_ETAPA_CNFG;
DELETE FROM OPERACION.SGAT_EF_ETAPA_SRVC;
DELETE FROM OPERACION.SGAT_EF_ETAPA_PRM WHERE EFEPN_ID >= 180;

UPDATE OPERACION.SGAT_EF_ETAPA_PRM
SET EFEPN_VALOR = NULL
WHERE EFEPN_ID IN (1, 24, 25, 164, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179);

COMMIT;

-- MODIFY COLUMN 
ALTER TABLE OPERACION.SGAT_EF_ETAPA_SRVC MODIFY EFESV_MODNEG NOT NULL;

-- DROP COLUMNS 
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG DROP (EFECN_COSTO, EFECN_COSTO_PROV);
ALTER TABLE OPERACION.SGAT_EF_ETAPA_SRVC DROP (EFESC_CODACT, EFESV_ACTIVIDAD);

-- DROP PACKAGE
DROP PACKAGE WEBSERVICE.PKG_GESTION_RECURSOS_WS;
DROP PACKAGE OPERACION.PKG_EF_COSTEO_FORMULA;
/