DROP TRIGGER OPERACION.SGATRI_TRAZA_DET_FACT;
DROP TRIGGER OPERACION.SGATRI_TRAZA_FACT;
DROP TRIGGER OPERACION.SGATRI_SGAT_EF_PARTIDA_DET;
DROP TRIGGER OPERACION.SGATRI_SGAT_EF_PARTIDA_CAB;
DROP TRIGGER OPERACION.SGATRI_EF_ETAPA_PRM;
/
