DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_DTH_ACTIONS');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_DTH_ACTIONS';

COMMIT
/