DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_DOCSIS';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_PACKETCABLE';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_ENDPOINTS';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_CALLFEATURES';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_DAC';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_SERV_ADIC';
DELETE FROM  OPERACION.CONSTANTE WHERE CONSTANTE='IW_SERV_VOD';
Commit;
