	delete from operacion.opedd where tipopedd = (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID') and codigoc in ('8','9');
	
	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('8', 807, 'Reconexion de equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 110);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('8', 843, 'Reconexion de equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 110);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('8', 845, 'Reconexion de equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 110);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('9', 806, 'Suspension de equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 108);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('9', 844, 'Desactivacion de Bouquets en equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 105);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('9', 847, 'Desactivacion de Bouquets en equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 105);

	insert into operacion.opedd (CODIGOC, CODIGON, DESCRIPCION, TIPOPEDD, CODIGON_AUX)
	values ('9', 803, 'Desactivacion de Bouquets en equipo DTH. LTE', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_CONTEGO_TIPTRA_ACTIONID'), 105);

COMMIT
/