DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'TIPOS_TRABAJO');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'TIPOS_TRABAJO';
DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'TIPOS_LINEAS');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'TIPOS_LINEAS';
DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'DIAS_CONFIG_LIBERACION');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'DIAS_CONFIG_LIBERACION';
DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONFIG_LIB');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONFIG_LIB';
DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'ESTADO_LIBERACION');
DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'ESTADO_LIBERACION';
COMMIT
/