DROP TABLE OPERACION.SGAT_TRXCONTEGO;
DROP TABLE OPERACION.SGAT_TRXCONTEGO_HIST;
DROP TABLE OPERACION.SGAT_LOGERR;
DROP SEQUENCE OPERACION.SGASEQ_CONTEGO;
DROP SEQUENCE OPERACION.SGASEQ_LOGERR;
DROP SEQUENCE OPERACION.SGASEQ_TRANSCONTEGO
/