DECLARE
AN_TIPOPEDD NUMBER;
BEGIN
	SELECT A.TIPOPEDD
	INTO AN_TIPOPEDD
	FROM OPERACION.TIPOPEDD A
	WHERE A.DESCRIPCION = 'PARAMETROS_DOCS_ELECT';
	
	DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = AN_TIPOPEDD AND DESCRIPCION = 'SERIES_PERMITIDAS';

	COMMIT;
END;
/