DECLARE
AN_TIPOPEDD NUMBER;
BEGIN
	SELECT A.TIPOPEDD
	INTO AN_TIPOPEDD
	FROM OPERACION.TIPOPEDD A
	WHERE A.DESCRIPCION = 'PARAMETROS_DOCS_ELECT';

	DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = AN_TIPOPEDD;

	DELETE FROM OPERACION.TIPOPEDD WHERE TIPOPEDD = AN_TIPOPEDD;

	COMMIT;
END;
/