--PAQUETE
drop package OPERACION.PKG_FLUJO_AUTOMATICO;
DROP PACKAGE OPERACION.PKG_CONSULTA_UNIFICADA_SGA;
DROP PACKAGE OPERACION.PKG_SOT_UNIFICADA;
DROP PACKAGE OPERACION.PKG_TRS_POSTVENTA;

DROP TABLE OPERACION.SGAT_POSTV_SERV_EXT;
DROP TABLE OPERACION.SGAT_POSTV_SERV;
DROP TABLE OPERACION.SGAT_POSTV_EXT;
DROP TABLE OPERACION.SGAT_POSTV;
DROP TABLE OPERACION.SGAT_TRAMA_POSTV_DET;
DROP TABLE OPERACION.SGAT_TRAMA_POSTV;

--SEQUENCES
drop sequence operacion.SGASEQ_POSTV;
drop sequence operacion.SGASEQ_POSTV_SERV;
drop sequence operacion.SGASEQ_POSTV_SERV_ID;