
DELETE FROM OPERACION.OPEDD
WHERE TIPOPEDD in
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD
       WHERE ABREV in ('No_Valida_Token', 'ALQ_OTT'));

DELETE FROM OPERACION.TIPOPEDD
WHERE ABREV in ('No_Valida_Token', 'ALQ_OTT');

COMMIT;

/
