DROP FUNCTION OPERACION.SGAFUN_GET_NRO_ORDEN_TOA;

DELETE FROM OPERACION.SGAT_RESERVA_TOA
 WHERE RESTV_NRO_ORDEN = 'RT1000'
   AND RESTN_SECUENCIA = 1000
   AND RESTN_ESTADO = 2;
   
ALTER TABLE OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC DROP COLUMN FLAG_RESERVA;

DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST');

DELETE FROM OPERACION.TIPOPEDD WHERE abrev = 'CEHFCPOST';

DROP TABLE OPERACION.SGAT_RESERVA_TOA;

DELETE FROM OPERACION.PARAMETRO_DET_ADC WHERE ID_PARAMETRO = '37' AND ABREVIATURA = 'MSJ_TIM_OUT';

DELETE FROM OPERACION.PARAMETRO_DET_ADC WHERE ID_PARAMETRO = '53' AND CODIGON IN (700,695,689,705,694,693,762,755,754); 

DROP PACKAGE OPERACION.PKG_RESERVA_TOA;

DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = (select o.tipopedd from operacion.tipopedd o where o.abrev = 'TIPO_TRANS_SIAC') AND CODIGON = 833;

COMMIT
/