--Eliminar Packages

DROP PACKAGE OPERACION.PQ_DTH_POSTPAGO;
COMMIT;

-- Eliminar Procedimientos

DROP PROCEDURE OPERACION.P_CONS_LINEA_JANUS_REG;
DROP PROCEDURE OPERACION.P_CONS_PROV_HIST_JANUS;
DROP PROCEDURE OPERACION.P_CONS_PROV_JANUS;
DROP PROCEDURE OPERACION.P_CONS_PROV_LLANOS;
DROP PROCEDURE OPERACION.P_CONS_SERVICIOS;
DROP PROCEDURE OPERACION.sp_procesa_sot_anula_adm;
DROP PROCEDURE OPERACION.sp_procesa_sot_baja_adm;
COMMIT;

-- Elimina Tablas creadas
drop  table OPERACION.BAJA_DTH_POS;
drop  table OPERACION.CONTRACT_ALTA_DTH_POST;
drop  table  OPERACION.CONTRACT_BAJA_DTH_POST;
drop  table OPERACION.RECONEXION_DTH_POS;
drop  table  OPERACION.REQUEST_ALTA_DTH_POST;
drop  table OPERACION.REQUEST_BAJA_DTH_POST;
COMMIT;

-- Eliminar parametro en la TIPOPEED

DELETE FROM OPEDD 
WHERE TIPOPEDD = (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'IND_ASIGNUMERO');

DELETE FROM OPERACION.TIPOPEDD 
WHERE ABREV = 'IND_ASIGNUMERO';
COMMIT;