----  Rollback Tabla OPERACION.SGAT_APINT_IMAGEN
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN DROP COLUMN apintn_idagenda;
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN DROP COLUMN apintv_cod_tipo_foto;
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN DROP COLUMN apintv_desc_img_1;
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN DROP COLUMN apintb_img_1;
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN DROP COLUMN apintn_flag_carga;

----  Rollback permisos
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_SERV FROM R_PROD;
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_FOTO FROM R_PROD;
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_REPORT FROM R_PROD;

DROP SEQUENCE OPERACION.SGASEQ_MATRIZ_SERV;
DROP SEQUENCE OPERACION.SGASEQ_MATRIZ_FOTO;
DROP SEQUENCE OPERACION.SGASEQ_MATRIZ_REPORT;

DROP TRIGGER  OPERACION.SGATRI_MATRIZ_SERV;
DROP TRIGGER  OPERACION.SGATRI_MATRIZ_FOTO;
DROP TRIGGER  OPERACION.SGATRI_MATRIZ_REPORT;

DROP TABLE  OPERACION.SGAT_MATRIZ_REPORT;
DROP TABLE  OPERACION.SGAT_MATRIZ_SERV;
DROP TABLE  OPERACION.SGAT_MATRIZ_FOTO;

