DELETE FROM CUSBRA.BR_SEL_WF T1 
WHERE T1.TIPTRA = (SELECT TIPTRA FROM TIPTRABAJO WHERE DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO')
AND T1.WFDEF = (SELECT WFDEF FROM WFDEF WHERE DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO');

DELETE FROM TAREAWFDEF T1
WHERE T1.WFDEF = (SELECT WFDEF FROM WFDEF WHERE DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO');

DELETE FROM OPEDD T1
WHERE T1.TIPOPEDD = 260
AND T1.CODIGON = (SELECT WFDEF FROM WFDEF  WHERE DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO');

DELETE FROM TAREADEF T1
WHERE T1.DESCRIPCION 
IN ('Cambiar estado a Pendiente de Portabilidad');

DELETE FROM WFDEF T1
WHERE T1.DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO';

DELETE FROM TIPTRABAJO T1
WHERE T1.DESCRIPCION = 'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO';


DELETE FROM OPEDD T1
WHERE T1.TIPOPEDD = (SELECT TIPOPEDD FROM TIPOPEDD WHERE ABREV = 'TIPTRABAJO')
AND T1.ABREVIACION = 'SISACT_WLL_PORTA';

DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD IN (SELECT TIPOPEDD FROM TIPOPEDD WHERE ABREV = 'PORT_IN');

DELETE FROM TIPOPEDD WHERE ABREV = 'PORT_IN';

commit;
