REVOKE EXECUTE ON operacion.PKG_MIGRACION_SGA_BSCS FROM USRSISACT;  
 
REVOKE SELECT  ON OPERACION.MIGRT_DET_TEMP_SOT FROM USRSISACT;

REVOKE SELECT, UPDATE  ON OPERACION.MIGRT_CAB_TEMP_SOT FROM USRSISACT; 

REVOKE INSERT ON OPERACION.MIGRT_ERROR_MIGRACION FROM USRSISACT;

