--Rollback
DELETE OPERACION.TIPTRABAJO WHERE DESCRIPCION IN('HFC/EAI - RECONEXION DEL SERVICIO','HFC/EAI - SUSPENSION DEL SERVICIO');
DELETE OPERACION.TIPOPEDD WHERE ABREV IN('PROVISION_EAI');
DELETE OPERACION.OPEDD WHERE ABREVIACION IN('PROVISION_EAI');
DELETE OPERACION.MOTOT WHERE DESCRIPCION='OAC-SAC';
DELETE OPERACION.TIPOPEDD WHERE ABREV IN('OAC_SAC_EAI');
DELETE OPERACION.OPEDD WHERE ABREVIACION IN('OAC_SAC_EAI');
DELETE OPEWF.TAREAWFDEF WHERE WFDEF IN(SELECT WFDEF FROM OPEWF.WFDEF WHERE DESCRIPCION IN('RECONEXIÓN DIRECTO EAI','SUSPENSIÓN DIRECTO EAI'));
DELETE OPEWF.WFDEF WHERE DESCRIPCION IN('RECONEXIÓN DIRECTO EAI','SUSPENSIÓN DIRECTO EAI');
ALTER TABLE OPERACION.TRSRECEAI DROP COLUMN TIPTRS;
COMMIT
/