
DECLARE 
 LN_CANT NUMBER;
 LV_CANT_CAB_ALTA INTEGER;
 LV_CANT_CAB_BAJA INTEGER;
 LV_CANT_CAB_SUSPENSION INTEGER;
 LV_CANT_CAB_RECONEXION INTEGER;
 LV_CANT_DET_ALTA INTEGER;
 LV_CANT_DET_BAJA INTEGER;
 LV_CANT_DET_SUSPENSION INTEGER;
 LV_CANT_DET_RECONEXION INTEGER;
 LV_CANT_CAB_METO INTEGER;
 LV_CANT_DET_METO INTEGER;

BEGIN 
  
   SELECT count(1)
     INTO LN_CANT
     FROM TIPOPEDD
    WHERE UPPER(ABREV) = 'TIPTRA_CONFIG_IL';
  
   IF LN_CANT >0 THEN
      delete from opedd where tipopedd = (select MAX(tipopedd) from tipopedd where upper(abrev) ='TIPTRA_CONFIG_IL');
      delete from tipopedd where upper(abrev) = 'TIPTRA_CONFIG_IL';
      commit;
   END IF;
   SELECT count(1)
     INTO LN_CANT
     FROM TIPOPEDD
    WHERE UPPER(ABREV) = 'MSJ_CAMPOS_FICHA';
  
   IF LN_CANT > 0 THEN
      delete from opedd where tipopedd = (select MAX(tipopedd) from tipopedd where upper(abrev) ='MSJ_CAMPOS_FICHA');
      delete from tipopedd where upper(abrev) = 'MSJ_CAMPOS_FICHA';
      commit;
   END IF;
   
   SELECT count(1)
     INTO LN_CANT
     FROM TIPOPEDD
    WHERE UPPER(ABREV) = 'NUMERO_FIC_FITEL';
    
   IF LN_CANT > 0 THEN
      delete from opedd where tipopedd = (select MAX(tipopedd) from tipopedd where upper(abrev) ='NUMERO_FIC_FITEL');
      delete from tipopedd where upper(abrev) = 'NUMERO_FIC_FITEL';
      COMMIT;
   END IF;
  /*FIN ROLLBACK OPEDD */
  commit;
  
  SELECT COUNT(1)
    INTO LV_CANT_CAB_ALTA
    FROM OPERACION.OPE_CAB_XML
   WHERE PROGRAMA = 'Transaccion Alta IL';

  SELECT COUNT(1)
    INTO LV_CANT_CAB_BAJA
    FROM OPERACION.OPE_CAB_XML
   WHERE PROGRAMA = 'Transaccion Baja IL';

  SELECT COUNT(1)
    INTO LV_CANT_CAB_SUSPENSION
    FROM OPERACION.OPE_CAB_XML
   WHERE PROGRAMA = 'Transaccion Suspension IL';

  SELECT COUNT(1)
    INTO LV_CANT_CAB_RECONEXION
    FROM OPERACION.OPE_CAB_XML
   WHERE PROGRAMA = 'Transaccion Reconexion IL';

  SELECT COUNT(1)
    INTO LV_CANT_DET_ALTA
    FROM OPERACION.OPE_DET_XML
   WHERE IDCAB = (SELECT MAX(IDCAB)
                    FROM OPERACION.OPE_CAB_XML
                   WHERE PROGRAMA = 'Transaccion Alta IL');

  SELECT COUNT(1)
    INTO LV_CANT_DET_BAJA
    FROM OPERACION.OPE_DET_XML
   WHERE IDCAB = (SELECT MAX(IDCAB)
                    FROM OPERACION.OPE_CAB_XML
                   WHERE PROGRAMA = 'Transaccion Baja IL');

  SELECT COUNT(1)
    INTO LV_CANT_DET_SUSPENSION
    FROM OPERACION.OPE_DET_XML
   WHERE IDCAB = (SELECT MAX(IDCAB)
                    FROM OPERACION.OPE_CAB_XML
                   WHERE PROGRAMA = 'Transaccion Suspension IL');

  SELECT COUNT(1)
    INTO LV_CANT_DET_RECONEXION
    FROM OPERACION.OPE_DET_XML
   WHERE IDCAB = (SELECT MAX(IDCAB)
                    FROM OPERACION.OPE_CAB_XML
                   WHERE PROGRAMA = 'Transaccion Reconexion IL');

  SELECT COUNT(1)
    INTO LV_CANT_CAB_METO
    FROM OPERACION.TIPOPEDD T
   WHERE T.ABREV = 'METODO_IL_TIPTRA';

  SELECT COUNT(1)
    INTO LV_CANT_DET_METO
    FROM OPERACION.OPEDD O
   WHERE O.ABREVIACION = 'METODO_IL_TIPTRA';


  IF LV_CANT_DET_ALTA > 0 THEN
    DELETE FROM OPERACION.OPE_DET_XML
     WHERE IDCAB = (SELECT MAX(IDCAB)
                      FROM OPERACION.OPE_CAB_XML
                     WHERE PROGRAMA = 'Transaccion Alta IL');
    COMMIT;
  END IF;

  IF LV_CANT_DET_BAJA > 0 THEN
    DELETE FROM OPERACION.OPE_DET_XML
     WHERE IDCAB = (SELECT MAX(IDCAB)
                      FROM OPERACION.OPE_CAB_XML
                     WHERE PROGRAMA = 'Transaccion Baja IL');
    COMMIT;
  END IF;

  IF LV_CANT_DET_SUSPENSION > 0 THEN
    DELETE FROM OPERACION.OPE_DET_XML
     WHERE IDCAB = (SELECT MAX(IDCAB)
                      FROM OPERACION.OPE_CAB_XML
                     WHERE PROGRAMA = 'Transaccion Suspension IL');
    COMMIT;
  END IF;

  IF LV_CANT_DET_RECONEXION > 0 THEN
    DELETE FROM OPERACION.OPE_DET_XML
     WHERE IDCAB = (SELECT MAX(IDCAB)
                      FROM OPERACION.OPE_CAB_XML
                     WHERE PROGRAMA = 'Transaccion Reconexion IL');
    COMMIT;
  END IF;

  IF LV_CANT_CAB_ALTA > 0 THEN
    DELETE FROM OPERACION.OPE_CAB_XML
     WHERE PROGRAMA = 'Transaccion Alta IL';
    COMMIT;
  END IF;

  IF LV_CANT_CAB_BAJA > 0 THEN
    DELETE FROM OPERACION.OPE_CAB_XML
     WHERE PROGRAMA = 'Transaccion Baja IL';
    COMMIT;
  END IF;

  IF LV_CANT_CAB_SUSPENSION > 0 THEN
    DELETE FROM OPERACION.OPE_CAB_XML
     WHERE PROGRAMA = 'Transaccion Suspension IL';
    COMMIT;
  END IF;

  IF LV_CANT_CAB_RECONEXION > 0 THEN
    DELETE FROM OPERACION.OPE_CAB_XML
     WHERE PROGRAMA = 'Transaccion Reconexion IL';
    COMMIT;
  END IF;

  IF LV_CANT_CAB_METO > 0 THEN
  
    DELETE FROM OPERACION.OPEDD O WHERE O.ABREVIACION = 'METODO_IL_TIPTRA';
    COMMIT;
  END IF;

  IF LV_CANT_DET_METO > 0 THEN
    DELETE FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'METODO_IL_TIPTRA';
    COMMIT;
  END IF;
  
  /*INICIO ROLLBACK TIPOS Y ESTADOS 01 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'TRANS_SGA');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'TRANS_SGA');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'TRANS_SGA';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'TRANS_SGA';
		COMMIT;
	END IF;
  /*FIN ROLLBACK TIPOS Y ESTADOS 01 */
  
  /*INICIO ROLLBACK TIPOS Y ESTADOS 02 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'EST_PROV_SGA');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'EST_PROV_SGA');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'EST_PROV_SGA';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'EST_PROV_SGA';
		COMMIT;
	END IF;
  /*FIN ROLLBACK TIPOS Y ESTADOS 02 */
  
  /*INICIO ROLLBACK TIPOS Y ESTADOS 03 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'EST_SERV_SGA');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'EST_SERV_SGA');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'EST_SERV_SGA';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'EST_SERV_SGA';
		COMMIT;
	END IF;
    /*FIN ROLLBACK TIPOS Y ESTADOS 03 */

    /*INICIO ROLLBACK TIPOS Y ESTADOS 04 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'TIMER-FITEL');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'TIMER-FITEL');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'TIMER-FITEL';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'TIMER-FITEL';
		COMMIT;
	END IF;
    /*FIN ROLLBACK TIPOS Y ESTADOS 04 */
  
    /*INICIO ROLLBACK TIPOS Y ESTADOS 05 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'TRANS_FITEL');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'TRANS_FITEL');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'TRANS_FITEL';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'TRANS_FITEL';
		COMMIT;
	END IF;
    /*FIN ROLLBACK TIPOS Y ESTADOS 05 */
  
    /*INICIO ROLLBACK TIPOS Y ESTADOS 06 */
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.OPEDD
	 WHERE TIPOPEDD IN (SELECT TIPOPEDD
						  FROM OPERACION.TIPOPEDD
						 WHERE UPPER(ABREV) = 'TIPTRA_FITEL_AUTO');
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.OPEDD DET
		 WHERE DET.TIPOPEDD IN
			   (SELECT TIPOPEDD
				  FROM OPERACION.TIPOPEDD
				 WHERE UPPER(ABREV) = 'TIPTRA_FITEL_AUTO');
		COMMIT;
	END IF;

    SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.TIPOPEDD
	 WHERE UPPER(ABREV) = 'TIPTRA_FITEL_AUTO';

	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) = 'TIPTRA_FITEL_AUTO';
		COMMIT;
	END IF;
    /*FIN ROLLBACK TIPOS Y ESTADOS 06 */
	
    /* Inicio Rollback Tipo de Trabajo x Area 01 */
	
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.TIPTRAXAREA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - SUSPENSION')
	   AND AREA IN (SELECT AREA
					  FROM OPERACION.AREAOPE
					 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
					 
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPTRAXAREA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - SUSPENSION')
		   AND AREA IN (SELECT AREA
						  FROM OPERACION.AREAOPE
						 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
		COMMIT;
	END IF;
    /* Fin    Rollback Tipo de Trabajo x Area 01 */	


    /* Inicio Rollback Tipo de Trabajo x Area 02 */	
	
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.TIPTRAXAREA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - RECONEXION')
	   AND AREA IN (SELECT AREA
					  FROM OPERACION.AREAOPE
					 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
					 
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPTRAXAREA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - RECONEXION')
		   AND AREA IN (SELECT AREA
						  FROM OPERACION.AREAOPE
						 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
		COMMIT;
	END IF;
    /* Fin    Rollback Tipo de Trabajo x Area 02 */	

    /* Inicio Rollback Tipo de Trabajo x Area 03 */	
	
	SELECT COUNT(1)
      INTO LN_CANT
	  FROM OPERACION.TIPTRAXAREA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - BAJA')
	   AND AREA IN (SELECT AREA
					  FROM OPERACION.AREAOPE
					 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
					 
	IF LN_CANT > 0 THEN
		DELETE FROM OPERACION.TIPTRAXAREA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - BAJA')
		   AND AREA IN (SELECT AREA
						  FROM OPERACION.AREAOPE
						 WHERE DESCRIPCION = 'OPERACIONES INALAMBRICO');
		COMMIT;
	END IF;					 
    /* Fin    Rollback Tipo de Trabajo x Area 03 */
	
	/*INICIO ROLLBACK MOTIVO 01 */
	SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.MOTOTXTIPTRA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - SUSPENSION');
	
	IF LN_CANT > 0 THEN 
		DELETE FROM OPERACION.MOTOTXTIPTRA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - SUSPENSION');
	   COMMIT;
	END IF;
	/*INICIO ROLLBACK MOTIVO 01 */
	
	/*INICIO ROLLBACK MOTIVO 02 */
	SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.MOTOTXTIPTRA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - RECONEXION');
					   
	IF LN_CANT > 0 THEN 
		DELETE FROM OPERACION.MOTOTXTIPTRA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - RECONEXION');
	    COMMIT;
	END IF;
	/*INICIO ROLLBACK MOTIVO 02 */
	
	/*INICIO ROLLBACK MOTIVO 03 */
	SELECT COUNT(1)
	  INTO LN_CANT
	  FROM OPERACION.MOTOTXTIPTRA
	 WHERE TIPTRA IN (SELECT TIPTRA
						FROM OPERACION.TIPTRABAJO
					   WHERE DESCRIPCION = 'FITEL - BAJA');
					   
	IF LN_CANT > 0 THEN 
		DELETE FROM OPERACION.MOTOTXTIPTRA
		 WHERE TIPTRA IN (SELECT TIPTRA
							FROM OPERACION.TIPTRABAJO
						   WHERE DESCRIPCION = 'FITEL - BAJA');
	    COMMIT;
	END IF;
	/*INICIO ROLLBACK MOTIVO 03 */
	
	
	/*INICIO ROLLBACK TIPOTRABAJO 01 */
		SELECT COUNT(1)
		  INTO LN_CANT
		  FROM OPERACION.TIPTRABAJO
		WHERE DESCRIPCION = 'FITEL - RECONEXION';
		
		IF LN_CANT > 0 THEN 
			DELETE FROM OPERACION.TIPTRABAJO
			WHERE DESCRIPCION = 'FITEL - RECONEXION';
			COMMIT;
		END IF;
	/*FIN    ROLLBACK TIPOTRABAJO 01 */
	/*INICIO ROLLBACK TIPOTRABAJO 02 */
		SELECT COUNT(1)
		  INTO LN_CANT
		  FROM OPERACION.TIPTRABAJO
		 WHERE DESCRIPCION = 'FITEL - SUSPENSION';
		 
		IF LN_CANT > 0 THEN 
			DELETE FROM OPERACION.TIPTRABAJO
			WHERE DESCRIPCION = 'FITEL - SUSPENSION';
			COMMIT;
		END IF;
	/*FIN    ROLLBACK TIPOTRABAJO 02 */
	/*INICIO ROLLBACK TIPOTRABAJO 03 */
		SELECT COUNT(1)
		  INTO LN_CANT
		  FROM OPERACION.TIPTRABAJO
		 WHERE DESCRIPCION = 'FITEL - BAJA';
		 
		IF LN_CANT > 0 THEN 
			DELETE FROM OPERACION.TIPTRABAJO
			WHERE DESCRIPCION = 'FITEL - BAJA';
			COMMIT;
		END IF;
	/*FIN    ROLLBACK TIPOTRABAJO 03 */
END;  
/
DROP TABLE OPERACION.SGAT_PROVSGA;
--rollback grant
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_APROVISION_LOG FROM WEBSERVICE;
REVOKE SELECT ON OPERACION.INSSRV FROM WEBSERVICE;

