REVOKE EXECUTE ON OPERACION.PQ_DECO_ADICIONAL_LTE FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN_LTE FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_TRASLADO_EXTERNO_LTE FROM USREAISGA;
REVOKE SELECT, INSERT, UPDATE ON OPERACION.SIAC_POSTVENTA_PROCESO FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_POSTVENTA FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PKG_SIAC_POSTVENTA FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PKG_SIAC_CAMBIO_NUMERO FROM USREAISGA;
REVOKE EXECUTE ON OPERACION.PKG_ASIGNAR_WF2 FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PKG_SIAC_CAMBIO_NUMERO FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PKG_SIAC_POSTVENTA FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_ADM_CUADRILLA FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_AGENDAMIENTO FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_CONSULTA_SIAC_PRE FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_DECO_ADICIONAL FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_DECO_ADICIONAL_LTE FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_INALAMBRICO FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_INTEGRACION_DTH FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SGA_BSCS FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SGA_JANUS FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SGA_SIAC FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SGA_TH FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN_LTE FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SIAC_POSTVENTA FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.PQ_SOLOT FROM USRSIACUNICO;
REVOKE EXECUTE ON OPERACION.SGASS_VAL_ORDEN_VISIT_CP FROM USRSIACUNICO
/