DECLARE
  LN_COUNT NUMBER;
BEGIN
  /* INICIO ROLLBACK */
  SELECT COUNT(*)
    INTO LN_COUNT
    FROM OPERACION.TIPOPEDD CAB 
   WHERE CAB.ABREV = 'CONF_TIPTRA_UNIF';
   
  IF LN_COUNT > 0 THEN 
    DELETE FROM OPERACION.OPEDD DET
     WHERE DET.TIPOPEDD IN
           (SELECT CAB.TIPOPEDD
              FROM OPERACION.TIPOPEDD CAB
             WHERE CAB.ABREV = 'CONF_TIPTRA_UNIF');
    DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_TIPTRA_UNIF';
    COMMIT;
  END IF;
  
  SELECT COUNT(*)
    INTO LN_COUNT
    FROM OPERACION.TIPOPEDD CAB 
   WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN';
   
  IF LN_COUNT > 0 THEN 
    DELETE FROM OPERACION.OPEDD DET
     WHERE DET.TIPOPEDD IN
           (SELECT CAB.TIPOPEDD
              FROM OPERACION.TIPOPEDD CAB
             WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN');
    DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_TIPTRA_TRAN';
    COMMIT;
  END IF;
  
  SELECT COUNT(*)
    INTO LN_COUNT
    FROM OPERACION.TIPOPEDD CAB 
   WHERE CAB.ABREV = 'CONF_MOTOT_UNIF';
   
  IF LN_COUNT > 0 THEN 
    DELETE FROM OPERACION.OPEDD DET
     WHERE DET.TIPOPEDD IN
           (SELECT CAB.TIPOPEDD
              FROM OPERACION.TIPOPEDD CAB
             WHERE CAB.ABREV = 'CONF_MOTOT_UNIF');
    DELETE FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_MOTOT_UNIF';
    COMMIT;
  END IF;
  /* FIN    ROLLBACK */
END;
/
DROP TABLE OPERACION.SGAT_TRS_VISITA_TECNICA;
