drop package operacion.pkg_portout_corp;
ALTER TABLE OPERACION.SGAT_PORTOUTCORPLOG DROP COLUMN pocv_ases_email;
ALTER TABLE OPERACION.SGAT_PORTOUTCORPLOG DROP COLUMN pocv_superv_email;
ALTER TABLE OPERACION.SGAT_PORTOUTCORPLOG DROP COLUMN pocn_estado;
ALTER TABLE OPERACION.SGAT_PORTOUTCORPLOG DROP COLUMN pocd_fecin;