DECLARE
  LN_COUNT NUMBER;
BEGIN

  -- CONSTANTE TIPSRV 

  SELECT COUNT(*)
    INTO LN_COUNT
    FROM OPERACION.CONSTANTE C
   WHERE C.CONSTANTE = 'TELEF_REDCLARO';

  IF LN_COUNT > 0 THEN
    DELETE FROM OPERACION.CONSTANTE C WHERE C.CONSTANTE = 'TELEF_REDCLARO';
    COMMIT;
  END IF;

END;
/

 
