-- DELETE TABLA OPEDD
DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'TIPTRA_TAREAS');
COMMIT;

-- DELETE TABLA TIPOPEDD
DELETE FROM OPERACION.TIPOPEDD WHERE DESCRIPCION = 'Tipo Trabajo - Tareas' AND ABREV = 'TIPTRA_TAREAS';
COMMIT;

-- DROP FUNCION F_VALIDA_RECHAZO
DROP FUNCTION OPERACION.F_VALIDA_RECHAZO;
COMMIT;
