--Delete Sequence
DROP SEQUENCE OPERACION.SGASEQ_NOTIFICACION_CLIENTE;


--Delete Tables
DROP TABLE OPERACION.SGAT_PROCESO_LIC_SOP_MAIL;
DROP TABLE OPERACION.SGAT_PROCESO_ENVIO_MAIL;
DROP TABLE OPERACION.SGAT_NOTIFICACION_CLIENTE;

-- Delete rows
--Tipo: Anticipación de Alertas

DELETE FROM operacion.opedd WHERE tipopedd IN (SELECT tipopedd FROM operacion.tipopedd WHERE ABREV = 'TIPO_ANTICIPACION_ALERTAS');
DELETE FROM operacion.tipopedd WHERE ABREV = 'TIPO_ANTICIPACION_ALERTAS';

COMMIT;
/
