ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA DROP CONSTRAINT PK_IDSEQ_SECUENCIAESTADOAGE CASCADE;
ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA MODIFY IDSEQ NULL;
ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA ADD CONSTRAINT PK_SEC_EST_AGE PRIMARY KEY (ESTAGENDAINI, ESTAGENDAFIN, TIPTRA);
