DELETE FROM OPERACION.OPEDD D WHERE D.TIPOPEDD = (SELECT T.TIPOPEDD  FROM OPERACION.TIPOPEDD T
												WHERE T.ABREV = 'TIPO_RED_APP');
  
DELETE FROM OPERACION.TIPOPEDD D WHERE D.ABREV = 'TIPO_RED_APP'; 
	
DELETE FROM OPERACION.OPEDD D WHERE D.TIPOPEDD = (SELECT T.TIPOPEDD  FROM OPERACION.TIPOPEDD T
												WHERE T.ABREV = 'TIPO_SERV_APP');
  
DELETE FROM OPERACION.TIPOPEDD D WHERE D.ABREV = 'TIPO_SERV_APP'; 
  
DELETE FROM OPERACION.OPEDD D WHERE D.TIPOPEDD = (SELECT T.TIPOPEDD  FROM OPERACION.TIPOPEDD T
												WHERE T.ABREV = 'TIPO_TRAB_APP');
  
DELETE FROM OPERACION.TIPOPEDD D WHERE D.ABREV = 'TIPO_TRAB_APP';   
  
COMMIT;
/