--ELIMINAR COLUMNA DNI_TECNICO DE LA TABLA AGENDAMIENTO
ALTER TABLE OPERACION.AGENDAMIENTO DROP COLUMN DNI_TECNICO; 

DELETE FROM AGENLIQ.SGAT_PARAMETROCAB C
 WHERE C.PARCV_ABREVIATURA = 'Cierre_val_WF_APP';

-- DELETE AGENLIQ.SGAT_PARAMETRODET                       
DELETE FROM AGENLIQ.SGAT_PARAMETRODET
 WHERE PARDV_ABREVIATURA = 'Cierre_val_WF_APP';

/