DROP TABLE OPERACION.SGAT_LOG_WS_FTTH;
DROP SEQUENCE OPERACION.SEQ_SGAT_LOG_WS_FTTH;
delete from OPERACION.OPE_det_XML where IDCAB in (select max(IDCAB) from OPERACION.OPE_CAB_XML);
delete from OPERACION.OPE_CAB_XML where IDCAB in (select max(IDCAB) from OPERACION.OPE_CAB_XML);
commit;
/