
drop package body OPERACION.PKG_ALINEA_BSCS_IMS_UDB_LTE;
drop package OPERACION.PKG_ALINEA_BSCS_IMS_UDB_LTE;

drop table OPERACION.PREV_PCRF;
drop table OPERACION.PREV_WIMAXF3;
drop table OPERACION.PREV_LTEINTERNETGRATIS;
drop table OPERACION.PREV_HFCACTSUS;
drop table OPERACION.PREV_LTEACTSUS;
drop table OPERACION.PREV_IMS_HFC;
drop table OPERACION.PREV_IMS_LTE;
drop table OPERACION.PREV_UDB_LTE;
drop table OPERACION.PREV_DIFPCRF;
