-- rollback a campos NOMBAN
alter table CUSBRA.CXCBOLETO add NOMBAN_bk varchar2(40);
update CUSBRA.CXCBOLETO set NOMBAN_bk = NOMBAN;
COMMIT;
update CUSBRA.CXCBOLETO set NOMBAN = NULL;
COMMIT;
alter table CUSBRA.CXCBOLETO modify NOMBAN varchar2(40);
update CUSBRA.CXCBOLETO set NOMBAN = NOMBAN_bk;
COMMIT;
alter table CUSBRA.CXCBOLETO drop column NOMBAN_bk;

alter table PRODUCCION.CAREMI add NOMBAN_bk varchar2(60);
update PRODUCCION.CAREMI set NOMBAN_bk = NOMBAN;
COMMIT;
update PRODUCCION.CAREMI set NOMBAN = NULL;
COMMIT;
alter table PRODUCCION.CAREMI modify NOMBAN varchar2(60);
update PRODUCCION.CAREMI set NOMBAN = NOMBAN_bk;
COMMIT;
alter table PRODUCCION.CAREMI drop column NOMBAN_bk;

alter table PRODUCCION.CTBBANCOS add NOMBAN_bk varchar2(60);
update PRODUCCION.CTBBANCOS set NOMBAN_bk = NOMBAN;
COMMIT;
update PRODUCCION.CTBBANCOS set NOMBAN = NULL;
COMMIT;
alter table PRODUCCION.CTBBANCOS modify NOMBAN varchar2(60);
update PRODUCCION.CTBBANCOS set NOMBAN = NOMBAN_bk;
COMMIT;
alter table PRODUCCION.CTBBANCOS drop column NOMBAN_bk;

alter table COLLECTIONS.TABBAN add NOMBAN_bk varchar2(40);
update COLLECTIONS.TABBAN set NOMBAN_bk = NOMBAN;
COMMIT;
alter table COLLECTIONS.TABBAN disable constraint CHK_TABBAN_0923;
alter table COLLECTIONS.TABBAN modify NOMBAN NULL;
update COLLECTIONS.TABBAN set NOMBAN = NULL;
COMMIT;
alter table COLLECTIONS.TABBAN modify NOMBAN varchar2(40);
update COLLECTIONS.TABBAN set NOMBAN = NOMBAN_bk;
COMMIT;
alter table COLLECTIONS.TABBAN enable constraint CHK_TABBAN_0923;
alter table COLLECTIONS.TABBAN modify NOMBAN NOT NULL;
alter table COLLECTIONS.TABBAN drop column NOMBAN_bk;

alter table CUSPER.OPE_INALAMBRICO_DOCUMENTOS add NOMBAN_bk varchar2(40);
update CUSPER.OPE_INALAMBRICO_DOCUMENTOS set NOMBAN_bk = NOMBAN;
COMMIT;
update CUSPER.OPE_INALAMBRICO_DOCUMENTOS set NOMBAN = NULL;
COMMIT;
alter table CUSPER.OPE_INALAMBRICO_DOCUMENTOS modify NOMBAN varchar2(40);
update CUSPER.OPE_INALAMBRICO_DOCUMENTOS set NOMBAN = NOMBAN_bk;
COMMIT;
alter table CUSPER.OPE_INALAMBRICO_DOCUMENTOS drop column NOMBAN_bk;

alter table SOPFIJA.TABPAGOS add NOMBAN_bk varchar2(40);
update SOPFIJA.TABPAGOS set NOMBAN_bk = NOMBAN;
COMMIT;
update SOPFIJA.TABPAGOS set NOMBAN = NULL;
COMMIT;
alter table SOPFIJA.TABPAGOS modify NOMBAN varchar2(40);
update SOPFIJA.TABPAGOS set NOMBAN = NOMBAN_bk;
COMMIT;
alter table SOPFIJA.TABPAGOS drop column NOMBAN_bk;

alter table ATCCORP.TEMP_DETALLE_PAGO add NOMBAN_bk varchar2(40);
update ATCCORP.TEMP_DETALLE_PAGO set NOMBAN_bk = NOMBAN;
COMMIT;
update ATCCORP.TEMP_DETALLE_PAGO set NOMBAN = NULL;
COMMIT;
alter table ATCCORP.TEMP_DETALLE_PAGO modify NOMBAN varchar2(40);
update ATCCORP.TEMP_DETALLE_PAGO set NOMBAN = NOMBAN_bk;
COMMIT;
alter table ATCCORP.TEMP_DETALLE_PAGO drop column NOMBAN_bk;
