/*INSSRV*/
ALTER TABLE operacion.inssrv DROP COLUMN flgsolmedida;

/************* EFPTOEQU *****************/

ALTER TABLE operacion.EFPTOEQU DROP COLUMN flgsolmedida;
  
ALTER TABLE operacion.EFPTOEQU DROP COLUMN codprovinstalacion;
  
ALTER TABLE operacion.EFPTOEQU DROP COLUMN codprovmantenim;

ALTER TABLE operacion.EFPTOEQU DROP COLUMN sla;

/********* OPERACION.LICITACION   **********/
ALTER TABLE OPERACION.LICITACION DROP COLUMN adp_respo;

ALTER TABLE OPERACION.LICITACION DROP COLUMN ampl_plazo;

ALTER TABLE OPERACION.LICITACION DROP COLUMN pend_preventa;
 
ALTER TABLE OPERACION.LICITACION DROP COLUMN pend_comercial;

ALTER TABLE OPERACION.LICITACION DROP COLUMN pend_compras;
  
ALTER TABLE OPERACION.LICITACION DROP COLUMN pend_legal;

ALTER TABLE OPERACION.LICITACION DROP COLUMN MONTOCONTR;
-- A confirmar creacion de campo ADP RESPONSABLE
 /********* OPERACION.CONTRATA   **********/
ALTER TABLE OPERACION.CONTRATA DROP COLUMN flg_si_proveedor; 


