DECLARE
   V_TIPOPEDD NUMBER;
BEGIN
   SELECT tipopedd INTO V_TIPOPEDD FROM operacion.tipopedd WHERE ABREV = 'GEN_UNIF_SOT';

   DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = V_TIPOPEDD;
   DELETE FROM OPERACION.TIPOPEDD WHERE TIPOPEDD = V_TIPOPEDD;

   COMMIT;
END;
/