/*Eliminar Secuencias*/
DROP SEQUENCE OPERACION.SGASEQ_EF_ETAPA_PRM;
DROP SEQUENCE OPERACION.SGASEQ_EF_EQUIPO_SRVC;
DROP SEQUENCE OPERACION.SGASEQ_EF_EQUIPO_CNFG;
DROP SEQUENCE OPERACION.SGASEQ_EF_ETAPA_SRVC;
DROP SEQUENCE OPERACION.SGASEQ_EF_ETAPA_CNFG;
DROP SEQUENCE OPERACION.SGASEQ_EF_REGLACOSTEO_PINT;

/*Eliminar Triggers*/
DROP TRIGGER OPERACION.SGATRI_EF_ETAPA_PRM;
DROP TRIGGER OPERACION.SGATRU_EF_ETAPA_PRM;
DROP TRIGGER OPERACION.SGATRI_EF_EQUIPO_SRVC;
DROP TRIGGER OPERACION.SGATRU_EF_EQUIPO_SRVC;
DROP TRIGGER OPERACION.SGATRI_EF_EQUIPO_CNFG;
DROP TRIGGER OPERACION.SGATRU_EF_EQUIPO_CNFG;
DROP TRIGGER OPERACION.SGATRI_EF_ETAPA_SRVC;
DROP TRIGGER OPERACION.SGATRU_EF_ETAPA_SRVC;
DROP TRIGGER OPERACION.SGATRI_EF_ETAPA_CNFG;
DROP TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG;
DROP TRIGGER OPERACION.SGATRI_EF_REGLACOSTEO_PINT;
DROP TRIGGER OPERACION.SGATRU_EF_REGLACOSTEO_PINT;

/*Eliminar Tablas*/
DROP TABLE OPERACION.SGAT_EF_ETAPA_PRM;
DROP TABLE OPERACION.SGAT_EF_EQUIPO_CNFG_LOG;
DROP TABLE OPERACION.SGAT_EF_EQUIPO_CNFG;
DROP TABLE OPERACION.SGAT_EF_EQUIPO_SRVC;
DROP TABLE OPERACION.SGAT_EF_ETAPA_CNFG_LOG;
DROP TABLE OPERACION.SGAT_EF_ETAPA_CNFG;
DROP TABLE OPERACION.SGAT_EF_ETAPA_SRVC; 
DROP TABLE OPERACION.SGAT_EF_REGLACOSTEO_PINT;

