--LIMPIAR CUSBRA.BR_SEL_WF
DELETE FROM CUSBRA.BR_SEL_WF WHERE TIPTRA IN (SELECT TIPTRA  FROM TIPTRABAJO T 
                                               WHERE T.DESCRIPCION IN ('HFC - ACTIVAR BONO','HFC - DESACTIVAR BONO'));
--LIMPIAR TIPTRABAJO
DELETE FROM TIPTRABAJO T WHERE T.DESCRIPCION IN ( 'HFC - ACTIVAR BONO','HFC - DESACTIVAR BONO');

--LIMPIAR TABLA CONFIGURACION DETALLE
DELETE FROM OPERACION.OPEDD P 
WHERE P.TIPOPEDD in (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A 
                         WHERE A.DESCRIPCION IN ('BONO AUMENTA VELOCIDAD','PARAMETROS BONO'));
--LIMPIAR TABLA CONFIGURACION CABECERA
DELETE FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION IN ('BONO AUMENTA VELOCIDAD','PARAMETROS BONO');

--LIMPIAR TAREAWFDEF
DELETE FROM OPEWF.TAREAWFDEF T WHERE T.DESCRIPCION IN ('BONO - INCOGNITO','BONO - SGA');

--LIMPIAR TAREADEF
DELETE FROM OPEWF.TAREADEF T WHERE T.DESCRIPCION IN ('BONO - INCOGNITO','BONO - SGA');

--LIMPIAR WFDEF
DELETE FROM OPEWF.WFDEF WHERE DESCRIPCION = 'HFC - CAMBIO DE VELOCIDAD (BONO)';

COMMIT;