REVOKE SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_WEBSERVICE FROM USREAISGA;
REVOKE SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_ESCENARIOS FROM USREAISGA;
REVOKE SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_PARAM_ING FROM USREAISGA;

REVOKE SELECT, UPDATE ON OPERACION.OT FROM USREAISGA; 
REVOKE SELECT, UPDATE ON OPERACION.SOLOT FROM USREAISGA; 
REVOKE SELECT, UPDATE ON OPERACION.SOLOTPTO FROM USREAISGA; 
REVOKE SELECT, UPDATE ON OPERACION.TMP_SOLOT_CODIGO FROM USREAISGA; 
REVOKE SELECT, UPDATE ON OPERACION.TRANSACCIONES FROM USREAISGA; 
REVOKE SELECT, UPDATE ON OPERACION.TRANSACCIONES_CABLE FROM USREAISGA; 

REVOKE SELECT ON OPERACION.ENVCORREO FROM USREAISGA; 
REVOKE SELECT ON OPERACION.ESTSOL FROM USREAISGA; 
REVOKE SELECT ON OPERACION.INCIDENCE_DTH FROM USREAISGA; 
REVOKE SELECT ON OPERACION.INSSRV FROM USREAISGA; 
REVOKE SELECT ON OPERACION.OPEDD FROM USREAISGA; 
REVOKE SELECT ON OPERACION.REGINSDTH FROM USREAISGA; 
REVOKE SELECT ON OPERACION.SOLOTCHGEST FROM USREAISGA;
REVOKE SELECT ON OPERACION.TIPESTSOL FROM USREAISGA; 
REVOKE SELECT ON OPERACION.TIPOPEDD FROM USREAISGA; 
REVOKE SELECT ON OPERACION.TIPTRABAJO FROM USREAISGA;
