REVOKE select ON OPERACION.PARAMETRO_CAB_ADC FROM AGENLIQ;
REVOKE select on OPERACION.PARAMETRO_DET_ADC FROM AGENLIQ;
REVOKE select, insert, update, delete ON OPERACION.SGAT_PO_TCRM FROM AGENLIQ;
REVOKE select, insert, update, delete ON OPERACION.SGAT_PS_TCRM FROM AGENLIQ;
REVOKE select, insert, update, delete ON OPERACION.SGAT_FAMILIA_TCRM FROM AGENLIQ;