DELETE 
FROM Operacion.Opedd 
WHERE Tipopedd = (SELECT op.TIPOPEDD FROM operacion.TIPOPEDD op  WHERE op.ABREV='ESTADOS-EN-CONSOLIDADO');

DELETE 
FROM Operacion.Tipopedd
WHERE ABREV='ESTADOS-EN-CONSOLIDADO';

COMMIT;

DELETE
FROM Operacion.Opedd
WHERE Tipopedd = (SELECT op.TIPOPEDD FROM operacion.TIPOPEDD op  WHERE op.ABREV='INCIDEN-AL-CONSOLIDAR_FIBRA_C');

DELETE 
FROM Operacion.Tipopedd
WHERE ABREV='INCIDEN-AL-CONSOLIDAR_FIBRA_C';

COMMIT;

DELETE 
FROM Operacion.Opedd
WHERE Tipopedd = (SELECT op.TIPOPEDD FROM operacion.TIPOPEDD op  WHERE op.ABREV='ORIGEN_INCIDEN_CONSOL');

DELETE
FROM Operacion.Tipopedd
WHERE ABREV='ORIGEN_INCIDEN_CONSOL';

COMMIT;
