DROP PACKAGE BODY OPERACION.PQ_SGA_TH;
DROP PACKAGE OPERACION.PQ_SGA_TH;


DROP SEQUENCE OPERACION.SQ_THIDPROCESO;
DROP TABLE OPERACION.THCODSOLOT;
DROP TABLE OPERACION.THCUSTOMERID;
DROP JAVA SOURCE OPERACION.com_creo_operacion_opth;

DELETE FROM OPERACION.CONSTANTE WHERE CONSTANTE = 'OPTHFCUSER';
DELETE FROM OPERACION.CONSTANTE WHERE CONSTANTE = 'OPTHFCPWD';
DELETE FROM OPERACION.CONSTANTE WHERE CONSTANTE = 'OPTHFCURL';
DELETE FROM OPERACION.CONSTANTE WHERE CONSTANTE = 'OPTHFCNUM';    
COMMIT;
