ALTER TABLE OPERACION.INVENTARIO_ENV_ADC DROP COLUMN FLG_DEL ;
  
      DELETE FROM OPERACION.PARAMETRO_DET_ADC
       WHERE ID_PARAMETRO IN
             (SELECT A.ID_PARAMETRO
                FROM OPERACION.PARAMETRO_CAB_ADC A
               WHERE A.ABREVIATURA = 'CARG_INV_USUARIOS');
               
      DELETE FROM OPERACION.PARAMETRO_CAB_ADC A
       WHERE A.ABREVIATURA = 'CARG_INV_USUARIOS';
       
       DELETE FROM OPERACION.PARAMETRO_DET_ADC
       WHERE ID_PARAMETRO IN
             (SELECT A.ID_PARAMETRO
                FROM OPERACION.PARAMETRO_CAB_ADC A
               WHERE A.ABREVIATURA = 'PARAMETROS');
               
      DELETE FROM OPERACION.PARAMETRO_CAB_ADC A
       WHERE A.ABREVIATURA = 'PARAMETROS';
       commit;
/
