DROP PACKAGE BODY OPERACION.PQ_REGLAS_CP;
DROP PACKAGE OPERACION.PQ_REGLAS_CP;

DROP SEQUENCE OPERACION.SQ_IDCAB;
DROP SEQUENCE OPERACION.SQ_IDDET;
DROP SEQUENCE OPERACION.SQ_IDSEQ;

DROP TABLE OPERACION.DETPROVCP;
DELETE FROM OPERACION.ACTIONCP WHERE CODACTION IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);
COMMIT;

ALTER TABLE OPERACION.DETCP DROP COLUMN IDCAB;
ALTER TABLE OPERACION.DETCP DROP COLUMN OBSERVACION;
ALTER TABLE OPERACION.DETCP DROP COLUMN TIPO_EQU_PROV;
ALTER TABLE OPERACION.DETCP DROP COLUMN CANT_TOTAL;
ALTER TABLE OPERACION.DETCP DROP COLUMN CANT_EFEC;
ALTER TABLE OPERACION.CABCP DROP COLUMN CODSOLOT;
ALTER TABLE OPERACION.ACTIONCP DROP COLUMN TIPSRV;