CREATE OR REPLACE FUNCTION OPERACION.SICEFUN_GETCODSOLOT_PVU(P_CO_ID OPERACION.SOLOT.COD_ID%TYPE)
  RETURN OPERACION.SOLOT.CODSOLOT%TYPE IS
  LN_CODSOLOT OPERACION.SOLOT.CODSOLOT%TYPE;
BEGIN
  SELECT B.NRO_SOT
    INTO LN_CODSOLOT
    FROM USRPVU.SISACT_AP_CONTRATO_DET@DBL_PVUDB A, USRPVU.SISACT_INFO_VENTA_SGA@DBL_PVUDB B
   WHERE A.ID_CONTRATO = B.ID_CONTRATO
     AND A.CO_ID = P_CO_ID
     AND ROWNUM = 1;
  RETURN LN_CODSOLOT;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/