CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG
BEFORE UPDATE ON OPERACION.SGAT_EF_ETAPA_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFECV_USUMOD := user;
  :new.EFECD_FECMOD := sysdate;
  
 IF UPDATING('EFECV_CODPAR') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECV_CODPAR',:OLD.EFECV_CODPAR ||' ===> '||:NEW.EFECV_CODPAR,'CÓDIGO DE NEGOCIO DE MO/MATERIALES');
  END IF; 
  IF UPDATING('EFECN_CANTIDAD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_CANTIDAD',:OLD.EFECN_CANTIDAD||' ===> '||:NEW.EFECN_CANTIDAD,'CANTIDAD');
  END IF;
  IF UPDATING('EFECN_SUBESCEN1') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_SUBESCEN1',:OLD.EFECN_SUBESCEN1||' ===> '||:NEW.EFECN_SUBESCEN1,'SUB ESCENARIO 1');
  END IF;
  IF UPDATING('EFECN_SUBESCEN2') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_SUBESCEN2',:OLD.EFECN_SUBESCEN2||' ===> '||:NEW.EFECN_SUBESCEN2,'SUB ESCENARIO 2');
  END IF; 
  IF UPDATING('EFECN_SUBESCEN3') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_SUBESCEN3',:OLD.EFECN_SUBESCEN3||' ===> '||:NEW.EFECN_SUBESCEN3,'SUB ESCENARIO 3');
  END IF;
  IF UPDATING('EFECN_ESTADO') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_ESTADO',:OLD.EFECN_ESTADO||' ===> '||:NEW.EFECN_ESTADO,'ESTADO DE LA CONFIGURACIÓN');
  END IF;   
END;
/