CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_EF_PARTIDA_CAB
  BEFORE INSERT ON OPERACION.SGAT_EF_PARTIDA_CAB
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  NUM_ID number;
BEGIN

  if :NEW.EFPCN_ID is null then
    select OPERACION.SGASEQ_EF_PARTIDA_CAB.NEXTVAL into NUM_ID from DUAL;
    :NEW.EFPCN_ID := NUM_ID;
  end if;

END;
/

CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_ETAPA_PRM
BEFORE INSERT ON  OPERACION.SGAT_EF_ETAPA_PRM
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
    WHEN(NEW.EFEPN_ID IS NULL) 

BEGIN
    SELECT OPERACION.SGASEQ_EF_ETAPA_PRM.NEXTVAL INTO :NEW.EFEPN_ID FROM DUAL;
END;
/
