CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_EF_PARTIDA_DET
  BEFORE INSERT ON OPERACION.SGAT_EF_PARTIDA_DET
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  NUM_ID number;
BEGIN

  if :NEW.EFPDN_IDDET is null then
    select OPERACION.SGASEQ_EF_PARTIDA_DET.NEXTVAL into NUM_ID from DUAL;
    :NEW.EFPDN_IDDET := NUM_ID;
  end if;

END;
/
