CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_AGEND
  BEFORE INSERT ON OPERACION.MIGRT_AGENDAMIENTO
  FOR EACH ROW

BEGIN
       IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_AGEND.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/