CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_DATAPRI
  BEFORE INSERT ON OPERACION.MIGRT_DATAPRINC
  FOR EACH ROW

BEGIN
	IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_DATAPRI.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/