CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_ERROR_M
  BEFORE INSERT ON OPERACION.MIGRT_ERROR_MIGRACION
  FOR EACH ROW

BEGIN
	IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_ERROR_M.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/  
