 
CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_DET_TEM
  BEFORE INSERT ON OPERACION.MIGRT_DET_TEMP_SOT
  FOR EACH ROW

BEGIN
	IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_DET_TEM.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/  
