CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_CAB_TEM
  BEFORE INSERT ON OPERACION.MIGRT_CAB_TEMP_SOT
  FOR EACH ROW

BEGIN
	IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_CAB_TEM.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/  
