CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_EQU_SGA
  BEFORE INSERT ON OPERACION.MIGRT_EQU_SGA_SISACT
  FOR EACH ROW

BEGIN
	IF :NEW.DATAN_ID IS NULL THEN
       SELECT OPERACION.MIGRSEQ_EQU_SGA.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/  
