CREATE OR REPLACE TRIGGER OPERACION.MIGRTRI_EQUIPOS
  BEFORE INSERT ON OPERACION.MIGRT_EQUIPOS_SGA_SISACT
  FOR EACH ROW

BEGIN
  IF :NEW.DATAN_ID IS NULL THEN
       select OPERACION.MIGRSEQ_EQ_EQUIPO.NEXTVAL INTO :NEW.DATAN_ID FROM DUAL;
    END IF;   
END;
/  