CREATE OR REPLACE TRIGGER OPERACION.PIVOT_SOT_DES_HIST_ERROR
  BEFORE INSERT ON OPERACION.PIVOT_SOT_DESPACHO_HIST_ERROR
  FOR EACH ROW

BEGIN
  IF :NEW.ID_SEC_HIS IS NULL THEN
       SELECT OPERACION.SEC_PIVOT_SOT_DES_ERROR.NEXTVAL INTO :NEW.ID_SEC_HIS FROM DUAL;
    END IF;   
END;
/  