CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_ETAPA_SRVC
BEFORE UPDATE ON OPERACION.SGAT_EF_ETAPA_SRVC
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFESV_USUMOD := user;
  :new.EFESD_FECMOD := sysdate;
END;
/