CREATE OR REPLACE TRIGGER OPERACION.SGATRU_SGAT_PROCESO_LIC_CAB_02
BEFORE UPDATE ON OPERACION.SGAT_PROCESO_LIC_CAB
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.lcabv_usumod := user;
  :new.lcabd_fecmod := sysdate;
  :new.LCABD_FECFINCONTRATO := :new.LCABD_FECINICONTRATO + :new.LCABI_DURACION;
END;
/