CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_ETAPA_CNFG
BEFORE INSERT ON  OPERACION.SGAT_EF_ETAPA_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
  WHEN (NEW.EFECN_ID IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_EF_ETAPA_CNFG.NEXTVAL INTO :NEW.EFECN_ID FROM DUAL;
END;
/