CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_ETAPA_PRM
BEFORE INSERT ON  OPERACION.SGAT_EF_ETAPA_PRM
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
    WHEN(NEW.EFEPN_ID IS NULL) 

BEGIN
    SELECT OPERACION.SGASEQ_EF_ETAPA_PRM.NEXTVAL INTO :NEW.EFEPN_ID FROM DUAL;
END;
/
