CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_ETAPA_SRVC
BEFORE INSERT ON  OPERACION.SGAT_EF_ETAPA_SRVC
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
  WHEN (NEW.EFESN_ID IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_EF_ETAPA_SRVC.NEXTVAL INTO :NEW.EFESN_ID FROM DUAL;
END;
/