CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_ETAPA_PRM
BEFORE UPDATE ON OPERACION.SGAT_EF_ETAPA_PRM
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFEPV_USUMOD := user;
  :new.EFEPD_FECMOD := sysdate;
END;
/