CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_EQUIPO_SRVC
BEFORE INSERT ON  OPERACION.SGAT_EF_EQUIPO_SRVC
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
  WHEN (NEW.EFEQN_ID IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_EF_EQUIPO_SRVC.NEXTVAL INTO :NEW.EFEQN_ID FROM DUAL;
END;
/