CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_PROCESO_LIC_SOP_01
BEFORE INSERT ON  OPERACION.SGAT_PROCESO_LIC_SOP
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.licsv_usureg := user;
  :new.licsd_fecreg := sysdate;
END;
/
