CREATE OR REPLACE TRIGGER OPERACION.SGATRU_SGAT_PROCESO_LSMAIL
BEFORE UPDATE ON OPERACION.SGAT_PROCESO_LIC_SOP_MAIL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.LICSV_USUMOD := user;
  :new.LICSD_FECMOD := sysdate;
END;