CREATE OR REPLACE TRIGGER OPERACION.SGATRU_SGAT_PROCESO_EMAIL_02
BEFORE UPDATE ON OPERACION.SGAT_PROCESO_ENVIO_MAIL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.PEMV_USUMOD := user;
  :new.PEMD_FECMOD := sysdate;
END;
/