CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_CID_SERV_LIC_01
BEFORE INSERT ON  OPERACION.SGAT_CID_SERV_LICENCIA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.serlv_usureg := user;
  :new.serld_fecreg := sysdate;
END;
/
