CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_PROCESO_LIC_SOP
  BEFORE INSERT ON OPERACION.SGAT_PROCESO_LIC_SOP
  FOR EACH ROW
  WHEN (NEW.LICSI_ID_LIC IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_SGAT_PROCESO_LIC_SOP.NEXTVAL INTO :NEW.LICSI_ID_LIC FROM DUAL;
END;
/
