CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_REGLACOSTEO_PINT
BEFORE INSERT ON  OPERACION.SGAT_EF_REGLACOSTEO_PINT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
  WHEN (NEW.EFRCN_ID IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_EF_REGLACOSTEO_PINT.NEXTVAL INTO :NEW.EFRCN_ID FROM DUAL;
END;
/