CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG
BEFORE UPDATE ON OPERACION.SGAT_EF_ETAPA_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFECV_USUMOD := user;
  :new.EFECD_FECMOD := sysdate;
  
 IF UPDATING('EFECV_CODPAR') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECV_CODPAR',:OLD.EFECV_CODPAR ||' ===> '||:NEW.EFECV_CODPAR,'CÓDIGO DE NEGOCIO DE MO/MATERIALES');
  END IF; 
  IF UPDATING('EFECN_CANTIDAD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_CANTIDAD',:OLD.EFECN_CANTIDAD||' ===> '||:NEW.EFECN_CANTIDAD,'CANTIDAD');
  END IF;
  IF UPDATING('EFECN_MCMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_MCMD',:OLD.EFECN_MCMD||' ===> '||:NEW.EFECN_MCMD,'MISMO CLIENTE/MISMA DIRECCIÓN');
  END IF;
  IF UPDATING('EFECN_DCMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_DCMD',:OLD.EFECN_DCMD||' ===> '||:NEW.EFECN_DCMD,'DIFERENTE CLIENTE/MISMA DIRECCIÓN');
  END IF; 
  IF UPDATING('EFECN_MUMD') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_MUMD',:OLD.EFECN_MUMD||' ===> '||:NEW.EFECN_MUMD,'MUFA MISMA DIRECCIÓN');
  END IF;
  IF UPDATING('EFECN_ESTADO') THEN
      INSERT INTO SGAT_EF_ETAPA_CNFG_LOG(EECLN_ID,EECLV_NOMC,EECLV_DCAM,EECLV_DESC)
                  VALUES(:NEW.EFECN_ID,'EFECN_ESTADO',:OLD.EFECN_ESTADO||' ===> '||:NEW.EFECN_ESTADO,'ESTADO DE LA CONFIGURACIÓN');
  END IF;   
END;
/