CREATE OR REPLACE TRIGGER OPERACION.SGATRI_SGAT_PROCESO_LIC_CAB_01
BEFORE INSERT ON  OPERACION.SGAT_PROCESO_LIC_CAB
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.lcabv_usureg := user;
  :new.lcabd_fecreg := sysdate;
END;
/
