CREATE OR REPLACE TRIGGER OPERACION.SGATRU_SGAT_PROCESO_LIC_SOP_02
BEFORE UPDATE ON OPERACION.SGAT_PROCESO_LIC_SOP
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.licsv_usumod := user;
  :new.licsd_fecmod := sysdate;
END;
/
