CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_EQUIPO_SRVC
BEFORE UPDATE ON OPERACION.SGAT_EF_EQUIPO_SRVC
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFEQV_USUMOD := user;
  :new.EFEQD_FECMOD := sysdate;
END;
/