CREATE OR REPLACE TRIGGER OPERACION.SGATRI_EF_EQUIPO_CNFG
BEFORE INSERT ON  OPERACION.SGAT_EF_EQUIPO_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
  WHEN (NEW.EFQCN_ID IS NULL)
BEGIN
  SELECT OPERACION.SGASEQ_EF_EQUIPO_CNFG.NEXTVAL INTO :NEW.EFQCN_ID FROM DUAL;
END;
/
