CREATE OR REPLACE TRIGGER OPERACION.SGATRU_EF_EQUIPO_CNFG
BEFORE UPDATE ON OPERACION.SGAT_EF_EQUIPO_CNFG
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.EFQCV_USUMOD := user;
  :new.EFQCD_FECMOD := sysdate;
   IF UPDATING('EFQCV_CODMAT') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCV_CODMAT',:OLD.EFQCV_CODMAT ||' ===> '||:NEW.EFQCV_CODMAT,'CÓDIGO DE MATERIAL.');
  END IF; 
  IF UPDATING('EFQCN_ESTADO') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCN_ESTADO',:OLD.EFQCN_ESTADO||' ===> '||:NEW.EFQCN_ESTADO,'ESTADO DE LA ACTIVIDAD.');
  END IF;
  IF UPDATING('EFQCV_USUREG') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCV_USUREG',:OLD.EFQCV_USUREG||' ===> '||:NEW.EFQCV_USUREG,'USUARIO DE REGISTRO.');
  END IF; 
  IF UPDATING('EFQCD_FECREG') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCD_FECREG',:OLD.EFQCD_FECREG||' ===> '||:NEW.EFQCD_FECREG,'FECHA DE REGISTRO.');
  END IF;   
  IF UPDATING('EFQCV_USUMOD') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCV_USUMOD',:OLD.EFQCV_USUMOD||' ===> '||:NEW.EFQCV_USUMOD,'USUARIO DE MODIFICACIÓN.');
  END IF; 
  IF UPDATING('EFQCD_FECMOD') THEN
      INSERT INTO SGAT_EF_EQUIPO_CNFG_LOG(EEQLN_ID,EEQLV_NOMC,EEQLV_DCAM,EEQLV_DESC)
                  VALUES(:NEW.EFQCN_ID,'EFQCD_FECMOD',:OLD.EFQCD_FECMOD||' ===> '||:NEW.EFQCD_FECMOD,'FECHA DE MODIFICACIÓN.');
  END IF;     
END;
/