CREATE OR REPLACE TRIGGER OPERACION.SGATRU_SGAT_PROCESO_LIC_DET_02
BEFORE UPDATE ON OPERACION.SGAT_PROCESO_LIC_DET
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.licdv_usumod := user;
  :new.licdd_fecmod := sysdate;
END;
/
