CREATE OR REPLACE TRIGGER OPERACION.T_ACTIVIDAD_BU
 BEFORE UPDATE ON ACTIVIDAD
FOR EACH ROW
BEGIN
--	if updating('DESCRIPCION') or then

	insert into actividad_his(CODACT, DESCRIPCION, CODUND, COSTO, ESPERMISO, MONEDA, CODUBI, ESTADO, TIPO, FLGCAN, FLGPRYLIQ)
   values(:old.CODACT, :old.DESCRIPCION, :old.CODUND, :old.COSTO, :old.ESPERMISO, :old.MONEDA, :old.CODUBI, :old.ESTADO,
   :old.TIPO, :old.FLGCAN, :old.FLGPRYLIQ );

END T_ACTIVIDAD_BU;
/



