CREATE OR REPLACE TRIGGER OPERACION.T_AGENDA_TAREAS_AIUD
AFTER INSERT OR UPDATE OR DELETE
ON AGENDA_TAREAS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE

V_DATA_LOG DATE;
V_ACAO_LOG CHAR(1);
V_USER_NOLOG NUMBER(1) :=0;
nSecuencial number;

BEGIN
-- VERIFICAR SE USUARIO GERA HISTORICO
SELECT COUNT(1) INTO V_USER_NOLOG FROM DUAL
WHERE USER IN (SELECT USUARIO FROM HISTORICO.USER_NOLOG);

IF V_USER_NOLOG <> 1 THEN
  SELECT SQ_AGENDA_TAREAS_LOG.NEXTVAL  INTO nSecuencial FROM dual;

    IF INSERTING THEN
       V_ACAO_LOG := 'I';
       INSERT INTO OPERACION.AGENDA_TAREAS_LOG
       (IDSEQ,
        IDAGENDA,
        CODCON,
        CODCLI,
        FECPROG,
        FECAGENDA,
        CODINCIDENCE,
        ESTAGE,
        OBSERVACION,
        ACTA_INSTALACION
       )
       VALUES
       (nSecuencial,
        :NEW.IDAGENDA,
        :NEW.CODCON,
        :NEW.CODCLI,
        :NEW.FECPROG,
        :NEW.FECAGENDA,
        :NEW.CODINCIDENCE,
        :NEW.ESTAGE,
        :NEW.OBSERVACION,
        :NEW.ACTA_INSTALACION);
    ELSIF UPDATING THEN
       V_ACAO_LOG := 'U';
       INSERT INTO OPERACION.AGENDA_TAREAS_LOG
       (IDSEQ,
        IDAGENDA,
        CODCON,
        CODCLI,
        FECPROG,
        FECAGENDA,
        CODINCIDENCE,
        ESTAGE,
        OBSERVACION,
        ACTA_INSTALACION
       )
       VALUES
       (nSecuencial,
        :NEW.IDAGENDA,
        :NEW.CODCON,
        :NEW.CODCLI,
        :NEW.FECPROG,
        :NEW.FECAGENDA,
        :NEW.CODINCIDENCE,
        :NEW.ESTAGE,
        :NEW.OBSERVACION,
        :NEW.ACTA_INSTALACION);
    ELSIF DELETING THEN
       V_ACAO_LOG := 'D';
       INSERT INTO OPERACION.AGENDA_TAREAS_LOG
       (IDSEQ,
        IDAGENDA,
        CODCON,
        CODCLI,
        FECPROG,
        FECAGENDA,
        CODINCIDENCE,
        ESTAGE,
        OBSERVACION,
        ACTA_INSTALACION)
       VALUES
       (nSecuencial,
        :OLD.IDAGENDA,
        :OLD.CODCON,
        :OLD.CODCLI,
        :OLD.FECPROG,
        :OLD.FECAGENDA,
        :OLD.CODINCIDENCE,
        :OLD.ESTAGE,
        :OLD.OBSERVACION,
        :OLD.ACTA_INSTALACION);
    END IF;
END IF;

END;
/



