CREATE OR REPLACE TRIGGER OPERACION.T_BOUQUET_TBI
  BEFORE INSERT ON OPERACION.BOUQUET
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  id     number(15);
BEGIN
  SELECT OPERACION.SQ_BOUQUETS.NEXTVAL INTO id FROM dual;
  :new.IDBOUQUET := id;
END;
/



