CREATE OR REPLACE TRIGGER OPERACION.T_CONFIG_EQUCOM_CP_BI
  BEFORE INSERT ON OPERACION.CONFIG_EQUCOM_CP
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  ln_id operacion.CONFIG_EQUCOM_CP.id%type;
BEGIN
  IF :new.id IS NULL THEN
    SELECT operacion.SEQ_CONFIG_EQUCOM_CP.nextval
      INTO ln_id
      FROM dual;
    :new.id := ln_id;
  END IF;
END;
/