CREATE OR REPLACE TRIGGER OPERACION.T_CONFIG_EQUCOM_CP_BU
BEFORE UPDATE ON  OPERACION.CONFIG_EQUCOM_CP
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
  :new.usumod := user;
  :new.fecmod := sysdate;
END;
/