CREATE OR REPLACE TRIGGER OPERACION.T_EFAUTOMATICO_BI
BEFORE INSERT
ON OPERACION.EFAUTOMATICO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
   -- Se obtiene el numero de la llave
   IF :NEW.ID IS NULL THEN
      SELECT F_Get_Clave_EFAUTOMATICO() INTO :NEW.ID FROM DUAL;
   END IF;
END;
/



