CREATE OR REPLACE TRIGGER OPERACION.T_EFAUTOXAREA_BI
  BEFORE INSERT
  ON EFAUTOXAREA
  FOR EACH ROW
DECLARE
ln_idarea NUMBER;
BEGIN
   IF :NEW.idarea IS NULL THEN
      SELECT NVL(MAX(idarea),0) + 1 INTO ln_idarea FROM EFAUTOXAREA;
      :NEW.idarea :=  ln_idarea;
   END IF;

END;
/



