CREATE OR REPLACE TRIGGER OPERACION.T_EFPTO_BD
AFTER INSERT
ON OPERACION.EFPTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  lc_codcli ef.codcli%type;
BEGIN
	if not (:old.TIPRECHAZO_OPE is null and :old.TIPRECHAZO_FNZ is null) then

   	insert into efpto_rec (
      CODEF, PUNTO, DESCRIPCION, CODINSSRV, CODSUC, CODUBI, POP, DIRECCION, CODSRV, BW, COSMO, COSMAT, COSEQU,
      COSMOCLI, COSMATCLI, FECINI, NUMDIAPLA, FECFIN, OBSERVACION, COORDX1, COORDY1, COORDX2, COORDY2, FECUSU, CODUSU,
      TIPTRA, NROLINEAS, NROFACREC, NROHUNG, NROIGUAL, COSMO_S, COSMAT_S, CODTIPFIBRA, LONFIBRA, ACTCAD, NROCANAL,
      TIPTRAEF, TIPRECHAZO_OPE, TIPRECHAZO_FNZ )
   	values (
      :old.CODEF, :old.PUNTO, :old.DESCRIPCION, :old.CODINSSRV, :old.CODSUC, :old.CODUBI, :old.POP, :old.DIRECCION,
      :old.CODSRV, :old.BW, :old.COSMO, :old.COSMAT, :old.COSEQU, :old.COSMOCLI, :old.COSMATCLI, :old.FECINI, :old.NUMDIAPLA,
      :old.FECFIN, :old.OBSERVACION, :old.COORDX1, :old.COORDY1, :old.COORDX2, :old.COORDY2, :old.FECUSU, :old.CODUSU,
      :old.TIPTRA, :old.NROLINEAS, :old.NROFACREC, :old.NROHUNG, :old.NROIGUAL, :old.COSMO_S, :old.COSMAT_S, :old.CODTIPFIBRA,
      :old.LONFIBRA, :old.ACTCAD, :old.NROCANAL, :old.TIPTRAEF, :old.TIPRECHAZO_OPE, :old.TIPRECHAZO_FNZ );


   end if;

END;
/



