CREATE OR REPLACE TRIGGER OPERACION.T_ESTSOLEF_DIAS_UTILES_TBI
  BEFORE INSERT ON OPERACION.ESTSOLEF_DIAS_UTILES
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  id     number(15);
BEGIN
  SELECT OPERACION.SQ_ESTSOLEF_DIAS_UTILES.NEXTVAL INTO id FROM dual;
  :new.idsec := id;
END;
/



