CREATE OR REPLACE TRIGGER OPERACION.T_ESTREGDTH_TBI
  BEFORE INSERT ON OPERACION.ESTREGDTH
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  id     number(2);
BEGIN
  SELECT OPERACION.SQ_ESTREGDTH.NEXTVAL INTO id FROM dual;
  :new.CODESTDTH := LPAD(id,2,'0');
END;
/



