CREATE OR REPLACE TRIGGER OPERACION.T_FLUJOESTDTH_TBU
  BEFORE UPDATE ON OPERACION.FLUJOESTDTH
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  :NEW.USUMOD := USER;
  :NEW.FECMOD := SYSDATE;
END;
/



