CREATE OR REPLACE TRIGGER OPERACION.T_INT_SERVICIO_PLATAFORMA_BI
BEFORE INSERT
ON operacion.INT_SERVICIO_PLATAFORMA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE

BEGIN
  IF :NEW.IDSEQ IS NULL THEN
    SELECT SQ_INT_SERVICIO_PLAT_IDSEQ.NEXTVAL INTO :NEW.IDSEQ FROM dual;
  END IF;
END;
/



