CREATE OR REPLACE TRIGGER OPERACION.T_INT_OPERACION_TAREADEFOPC_BU
 BEFORE UPDATE ON OPERACION.INT_OPERACION_TAREADEF_OPC
FOR EACH ROW
BEGIN
   :new.usumod := user;
   :new.fecmod := sysdate;

END;
/



