CREATE OR REPLACE TRIGGER OPERACION.T_LICENCIAANTIVIRUS_BI
BEFORE INSERT
ON OPERACION.LICENCIAANTIVIRUS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
declare
  id   number;

BEGIN
      select operacion.SQ_LICENCIAANTIVIRUS.Nextval into id from dual;
      :NEW.idlicencia:=id;

END;
/



