CREATE OR REPLACE TRIGGER OPERACION.T_LOG_ENV_DESPAREO_MASIVO_BI
  BEFORE INSERT ON OPERACION.LOG_ENV_DESPAREO_MASIVO
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  id number(15);
BEGIN
  SELECT OPERACION.SQ_IDLOGENVDES.NEXTVAL INTO id FROM dual;
  :new.idlogenv := id;
END;
/



