CREATE OR REPLACE TRIGGER OPERACION.T_MAESTRO_SERIES_EQU_TXITW_BU
BEFORE UPDATE
ON OPERACION.MAESTRO_SERIES_EQU_TXITW
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
:new.usumod := user;
:new.fecmod := sysdate;
end T_MAESTRO_SERIES_EQU_TXITW_BU;
/



