CREATE OR REPLACE TRIGGER OPERACION.T_MAESTRO_SERIES_EQU_BU
 BEFORE UPDATE ON MAESTRO_SERIES_EQU
FOR EACH ROW
declare
 ln_cont number(6);
BEGIN
   :NEW.FECUSUMOD := Sysdate;
   :NEW.CODUSUMOD := User;

END;
/



