CREATE OR REPLACE TRIGGER OPERACION.T_MOT_SOLUCION_GRUPO_AIUD
AFTER INSERT OR UPDATE OR DELETE
ON OPERACION.MOT_SOLUCION_GRUPO REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
 /**************************************************************************
   NOMBRE:     T_MOT_SOLUCION_GRUPO_AIUD
   1.0        16/09/2012  Edilberto Astulle PROY-4854_Modificación de work flow de Wimax y HFC Claro Empresas
   **************************************************************************/

DECLARE
nSecuencial number;
BEGIN
  IF INSERTING THEN
     INSERT INTO HISTORICO.MOT_SOLUCION_GRUPO_LOG
     ( TIPO_ACC  ,CODMOT_GRUPO,DESCRIPCION ,ESTADO )
     VALUES('I', :NEW.CODMOT_GRUPO, :NEW.DESCRIPCION, :NEW.ESTADO );
  ELSIF UPDATING THEN
     INSERT INTO HISTORICO.MOT_SOLUCION_GRUPO_LOG
     ( TIPO_ACC  ,CODMOT_GRUPO,DESCRIPCION ,ESTADO )
     VALUES('U', :NEW.CODMOT_GRUPO, :NEW.DESCRIPCION, :NEW.ESTADO );
  ELSIF DELETING THEN
     INSERT INTO HISTORICO.MOT_SOLUCION_GRUPO_LOG
     ( TIPO_ACC  ,CODMOT_GRUPO,DESCRIPCION ,ESTADO )
     VALUES('D', :OLD.CODMOT_GRUPO, :OLD.DESCRIPCION, :OLD.ESTADO );
  END IF;

END;
/