CREATE OR REPLACE TRIGGER OPERACION.T_OPE_WS_SGASAP_LOG
  BEFORE DELETE ON OPERACION.OPE_WS_SGASAP
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  v_idseq HISTORICO.OPE_WS_SGASAP_LOG.IDSEQ%TYPE;
BEGIN
  select HISTORICO.SQ_OPE_WS_SGASAP_LOG.nextval into v_idseq from dual;
  insert into HISTORICO.OPE_WS_SGASAP_LOG
    (IDSEQ,
     IDTRS,
     TIPO,
     CODSOLOT,
     ID_UBITECNICA,
     RESPUESTAXML,
     ESQUEMAXML,
     RESULTADO,
     NUMSLC,
     ERROR,
     IPAPP,
     USUARIOAPP,
     FECUSU,
     PCAPP,
     FECACTWS)
  values
    (v_idseq,
     :OLD.IDTRS,
     :OLD.TIPO,
     :OLD.CODSOLOT,
     :OLD.ID_UBITECNICA,
     :OLD.RESPUESTAXML,
     :OLD.ESQUEMAXML,
     :OLD.RESULTADO,
     :OLD.NUMSLC,
     :OLD.ERROR,
     :OLD.IPAPP,
     :OLD.USUARIOAPP,
     :OLD.FECUSU,
     :OLD.PCAPP,
     :OLD.FECACTWS);
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20500, 'ERROR');
END;
/
