CREATE OR REPLACE TRIGGER OPERACION.T_OPE_SP_MAT_EQU_DET_AIUD
    AFTER INSERT OR UPDATE OR DELETE
   ON OPERACION.OPE_SP_MAT_EQU_DET
   REFERENCING OLD AS OLD NEW AS NEW
   FOR EACH ROW
  /************************************************************
       REVISIONS:
       Ver        Date        Author           Description
       --------  ----------  --------------  ------------------------
       1.0       16/09/2011  Tommy Arakaki   Creacion, REQ 159960, registro en log
  ***********************************************************/
DECLARE
V_USUARIO_LOG VARCHAR2(100);
V_ACCION CHAR(1);
ID     NUMBER(18);
BEGIN

   SELECT MAX(osuser) INTO V_USUARIO_LOG
      FROM v$session
      WHERE AUDSID = ( SELECT USERENV('SESSIONID') FROM dummy_ope);

   SELECT HISTORICO.SQ_OPE_SP_MAT_EQU_DET_LOG.NEXTVAL INTO ID FROM dummy_ope; --2.0

   V_USUARIO_LOG := trim(RPAD(USER||'-'||V_USUARIO_LOG,50));

   IF INSERTING THEN
      V_ACCION := 'I';
      INSERT INTO HISTORICO.OPE_SP_MAT_EQU_DET_LOG(
IDSPDET,
IDSPCAB,
SOT,
EF,
LINEA,
PEDIDO,
CONTRATA,
CODMAT,
CANTIDAD,
IMPUTACION,
VALOR_INPUT,
PRECIO_UNI,
OBSERVACION1,
OBSERVACION2,
FEC_INGRESO,
FEC_ENTREGA,
FEC_GEN_SP,
FEC_APR_SP,
EST_APR_SP,
NRO_SOLPED,
NRO_PEDIDO,
FEC_GEN_PC,
FEC_APR_PC,
EST_APR_PC,
FEC_ENVIO,
DESCRIPCION,
MONEDA_ID,
CODUND,
IDENTIFICA_SP,
COD_SAP,
USUREG,
FECREG,
USUMOD,
FECMOD,
GRUPO,
CENTRO,
ALMACEN,
ACCION
      ) VALUES (
:new.IDSPDET,
:new.IDSPCAB,
:new.SOT,
:new.EF,
:new.LINEA,
:new.PEDIDO,
:new.CONTRATA,
:new.CODMAT,
:new.CANTIDAD,
:new.IMPUTACION,
:new.VALOR_INPUT,
:new.PRECIO_UNI,
:new.OBSERVACION1,
:new.OBSERVACION2,
:new.FEC_INGRESO,
:new.FEC_ENTREGA,
:new.FEC_GEN_SP,
:new.FEC_APR_SP,
:new.EST_APR_SP,
:new.NRO_SOLPED,
:new.NRO_PEDIDO,
:new.FEC_GEN_PC,
:new.FEC_APR_PC,
:new.EST_APR_PC,
:new.FEC_ENVIO,
:new.DESCRIPCION,
:new.MONEDA_ID,
:new.CODUND,
:new.IDENTIFICA_SP,
:new.COD_SAP,
:new.USUREG,
:new.FECREG,
:new.USUMOD,
:new.FECMOD,
:new.GRUPO,
:new.CENTRO,
:new.ALMACEN,
V_ACCION);
   ELSIF UPDATING OR DELETING THEN
      IF UPDATING THEN
         V_ACCION := 'U';
      ELSIF DELETING THEN
         V_ACCION := 'D';
      END IF;
      INSERT INTO HISTORICO.OPE_SP_MAT_EQU_DET_LOG(
IDSPDET,
IDSPCAB,
SOT,
EF,
LINEA,
PEDIDO,
CONTRATA,
CODMAT,
CANTIDAD,
IMPUTACION,
VALOR_INPUT,
PRECIO_UNI,
OBSERVACION1,
OBSERVACION2,
FEC_INGRESO,
FEC_ENTREGA,
FEC_GEN_SP,
FEC_APR_SP,
EST_APR_SP,
NRO_SOLPED,
NRO_PEDIDO,
FEC_GEN_PC,
FEC_APR_PC,
EST_APR_PC,
FEC_ENVIO,
DESCRIPCION,
MONEDA_ID,
CODUND,
IDENTIFICA_SP,
COD_SAP,
USUREG,
FECREG,
USUMOD,
FECMOD,
GRUPO,
CENTRO,
ALMACEN,
ACCION
      ) VALUES (
:old.IDSPDET,
:old.IDSPCAB,
:old.SOT,
:old.EF,
:old.LINEA,
:old.PEDIDO,
:old.CONTRATA,
:old.CODMAT,
:old.CANTIDAD,
:old.IMPUTACION,
:old.VALOR_INPUT,
:old.PRECIO_UNI,
:old.OBSERVACION1,
:old.OBSERVACION2,
:old.FEC_INGRESO,
:old.FEC_ENTREGA,
:old.FEC_GEN_SP,
:old.FEC_APR_SP,
:old.EST_APR_SP,
:old.NRO_SOLPED,
:old.NRO_PEDIDO,
:old.FEC_GEN_PC,
:old.FEC_APR_PC,
:old.EST_APR_PC,
:old.FEC_ENVIO,
:old.DESCRIPCION,
:old.MONEDA_ID,
:old.CODUND,
:old.IDENTIFICA_SP,
:old.COD_SAP,
       user,
       sysdate,
       user,
       sysdate,
:old.GRUPO,
:old.CENTRO,
:old.ALMACEN,       
V_ACCION
         );
   END IF;
END;
/