CREATE OR REPLACE TRIGGER OPERACION.T_OPE_SOT_CAMBIO_EST_BI
BEFORE INSERT
ON operacion.OPE_SOT_CAMBIO_EST
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE

BEGIN
  IF :NEW.IDSEQ IS NULL THEN
     SELECT SQ_OPE_SOT_CAMBIO_EST.NEXTVAL INTO :NEW.IDSEQ FROM dual;
  END IF;
END;
/



