CREATE TRIGGER OPERACION.T_OPE_CONFIG_ACCION_JANUS
  BEFORE INSERT ON OPERACION.OPE_CONFIG_ACCION_JANUS
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.CODIGO IS NULL )
  THEN
    SELECT OPERACION.SEQ_OPE_CONFIG_ACCION_JANUS.nextval
      INTO :new.CODIGO
      FROM dual;
  END IF;
END;
/