CREATE OR REPLACE TRIGGER OPERACION.T_PAQUETE_VENTAXFOR_AIUD
AFTER INSERT OR UPDATE OR DELETE
ON OPERACION.PAQUETE_VENTAXFOR REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
 /**************************************************************************
   NOMBRE:     T_PAQUETE_VENTAXFOR_AIUD
   1.0        16/09/2012  Edilberto Astulle PROY-4854_Modificación de work flow de Wimax y HFC Claro Empresas
   **************************************************************************/

DECLARE
nSecuencial number;
BEGIN
  IF INSERTING THEN
     INSERT INTO HISTORICO.PAQUETE_VENTAXFOR_LOG
     ( TIPO_ACC  ,CODFOR,IDPAQ )
     VALUES('I', :NEW.CODFOR, :NEW.IDPAQ );
  ELSIF UPDATING THEN
     INSERT INTO HISTORICO.PAQUETE_VENTAXFOR_LOG
     ( TIPO_ACC  ,CODFOR,IDPAQ )
     VALUES('U', :NEW.CODFOR, :NEW.IDPAQ );
  ELSIF DELETING THEN
     INSERT INTO HISTORICO.PAQUETE_VENTAXFOR_LOG
     ( TIPO_ACC  ,CODFOR,IDPAQ )
     VALUES('D', :NEW.CODFOR, :NEW.IDPAQ );
  END IF;

END;
/