CREATE OR REPLACE TRIGGER OPERACION.T_REG_SERV_ADI_DTH_BU
BEFORE UPDATE
ON OPERACION.REG_SERV_ADI_DTH
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
:new.usumod := user;
:new.fecmod := sysdate;
end T_REG_SERV_ADI_DTH_BU;
/



