CREATE OR REPLACE TRIGGER OPERACION.T_REGINSDTH_TAIUD
AFTER INSERT OR UPDATE OR DELETE
ON OPERACION.REGINSDTH
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
/************************************************************
     REVISIONS:
     Ver        Fecha      Autor           Solicitado por   Description
     --------  ----------  --------------  ---------------  ----------------------
     1.0       16/09/2010  Antonio Lagos   Juan Gallegos    REQ 142338,Migracion DTH
     2.0       06/10/2010                      REQ.139588 Cambio de Marca
***********************************************************/
DECLARE
  V_USUARIO_LOG VARCHAR2(50);
  V_DATE_LOG DATE;
  V_TIPO_LOG CHAR(1);
  ID     NUMBER(18);
  --ini 1.0
  ls_mensaje varchar2(300);
  --fin 1.0

BEGIN
  SELECT MAX(OSUSER) INTO V_USUARIO_LOG
  FROM V$SESSION
  WHERE AUDSID = ( SELECT USERENV('SESSIONID') FROM DUAL);

  SELECT HISTORICO.SQ_REGINSDTH_LOG.NEXTVAL INTO ID FROM DUAL;

  V_USUARIO_LOG := V_USUARIO_LOG || '-' || USER;

  SELECT SYSDATE INTO V_DATE_LOG FROM DUAL;

  IF INSERTING THEN
    V_TIPO_LOG := 'I';
    insert into HISTORICO.REGINSDTH_LOG
    (  IDSEC,
    NUMREGISTRO,
    NOMCLI,
    TIPDOC,
    NUMDOC,
    NOMCONTACTO,
    TELEFONO1,
    TELEFONO2,
    IDPAQ,
    IDEQUIPO,
    IDTARJETA,
    OBSERVACION,
    CODINSTALADOR,
    CODUSU,
    FECREG,
    FECACTCONAX,
    ESTADO,
    CODSOLOT,
    NUMSLC,
    CODCLI,
    FECBAJACONAX,
    FECANULACONAX,
    UNITADDRESS,
    CODCON,
    TIPOPAGODTH,
    PAGOINSTAL,
    PAGOBANCO,
    PAGOOFICINA,
    FLG_PREACTIVADO,
    PID,
    CODINSSRV,
    FLG_VERIFTEC,
    FECINIVIG,
    FECFINVIG,
    FECALERTA,
    FECCORTE,
    MESESSINSRV,
    FLG_FACTURABLE,
    SERSUT,
    NUMSUT,
    TIPDOCFAC,
    FLG_TIP_PROY,
    BOUQUETS,
    CODSUC,
    DIRSUC,
    CODSOL,
    FLG_VALIDADO,
    NRODOCCON,
    TIPDOCCON,
    CODUSUMOD,
    FECUSUMOD,
    CODSUCFAC,
    DIRSUCFAC,
    FLG_RESERVA,
    PLAZO_SRV,
    FLG_RECARGA,
    CODMOTIVO_LV,
    CODMOTIVO_TC,
    CODMOTIVO_CO,
    CODMOTIVO_TF,
    VALIDASERIE,
    CODIGO_RECARGA,
    ESTADO_OBJETIVO,
    USUARIO_LOG,
    DATE_LOG,
    TIPO_LOG )
     values
     (
    id,
    :new.NUMREGISTRO,
    :new.NOMCLI,
    :new.TIPDOC,
    :new.NUMDOC,
    :new.NOMCONTACTO,
    :new.TELEFONO1,
    :new.TELEFONO2,
    :new.IDPAQ,
    :new.IDEQUIPO,
    :new.IDTARJETA,
    :new.OBSERVACION,
    :new.CODINSTALADOR,
    :new.CODUSU,
    :new.FECREG,
    :new.FECACTCONAX,
    :new.ESTADO,
    :new.CODSOLOT,
    :new.NUMSLC,
    :new.CODCLI,
    :new.FECBAJACONAX,
    :new.FECANULACONAX,
    :new.UNITADDRESS,
    :new.CODCON,
    :new.TIPOPAGODTH,
    :new.PAGOINSTAL,
    :new.PAGOBANCO,
    :new.PAGOOFICINA,
    :new.FLG_PREACTIVADO,
    :new.PID,
    :new.CODINSSRV,
    :new.FLG_VERIFTEC,
    :new.FECINIVIG,
    :new.FECFINVIG,
    :new.FECALERTA,
    :new.FECCORTE,
    :new.MESESSINSRV,
    :new.FLG_FACTURABLE,
    :new.SERSUT,
    :new.NUMSUT,
    :new.TIPDOCFAC,
    :new.FLG_TIP_PROY,
    :new.BOUQUETS,
    :new.CODSUC,
    :new.DIRSUC,
    :new.CODSOL,
    :new.FLG_VALIDADO,
    :new.NRODOCCON,
    :new.TIPDOCCON,
    :new.CODUSUMOD,
    :new.FECUSUMOD,
    :new.CODSUCFAC,
    :new.DIRSUCFAC,
    :new.FLG_RESERVA,
    :new.PLAZO_SRV,
    :new.FLG_RECARGA,
    :new.CODMOTIVO_LV,
    :new.CODMOTIVO_TC,
    :new.CODMOTIVO_CO,
    :new.CODMOTIVO_TF,
    :new.VALIDASERIE,
    :new.CODIGO_RECARGA,
    :new.ESTADO_OBJETIVO,
    V_USUARIO_LOG,
    V_DATE_LOG,
    V_TIPO_LOG);
    --ini 1.0
    ls_mensaje := 'Se insertó el número de registo: ' || to_char(:new.NUMREGISTRO) ||
    ' ,por el usuario: ' || to_char(V_USUARIO_LOG);
    opewf.pq_send_mail_job.p_send_mail('REGINSDTH - inserción',
                                         'DL-PE-ITSoportealNegocio@claro.com.pe',--2.0
                                         ls_mensaje);
    --fin 1.0
  ELSIF UPDATING THEN
    V_TIPO_LOG := 'U';
    insert into HISTORICO.REGINSDTH_LOG
    (  IDSEC,
    NUMREGISTRO,
    NOMCLI,
    TIPDOC,
    NUMDOC,
    NOMCONTACTO,
    TELEFONO1,
    TELEFONO2,
    IDPAQ,
    IDEQUIPO,
    IDTARJETA,
    OBSERVACION,
    CODINSTALADOR,
    CODUSU,
    FECREG,
    FECACTCONAX,
    ESTADO,
    CODSOLOT,
    NUMSLC,
    CODCLI,
    FECBAJACONAX,
    FECANULACONAX,
    UNITADDRESS,
    CODCON,
    TIPOPAGODTH,
    PAGOINSTAL,
    PAGOBANCO,
    PAGOOFICINA,
    FLG_PREACTIVADO,
    PID,
    CODINSSRV,
    FLG_VERIFTEC,
    FECINIVIG,
    FECFINVIG,
    FECALERTA,
    FECCORTE,
    MESESSINSRV,
    FLG_FACTURABLE,
    SERSUT,
    NUMSUT,
    TIPDOCFAC,
    FLG_TIP_PROY,
    BOUQUETS,
    CODSUC,
    DIRSUC,
    CODSOL,
    FLG_VALIDADO,
    NRODOCCON,
    TIPDOCCON,
    CODUSUMOD,
    FECUSUMOD,
    CODSUCFAC,
    DIRSUCFAC,
    FLG_RESERVA,
    PLAZO_SRV,
    FLG_RECARGA,
    CODMOTIVO_LV,
    CODMOTIVO_TC,
    CODMOTIVO_CO,
    CODMOTIVO_TF,
    VALIDASERIE,
    CODIGO_RECARGA,
    ESTADO_OBJETIVO,
    USUARIO_LOG,
    DATE_LOG,
    TIPO_LOG )
     values
    (
    id,
    :old.NUMREGISTRO,
    :old.NOMCLI,
    :old.TIPDOC,
    :old.NUMDOC,
    :old.NOMCONTACTO,
    :old.TELEFONO1,
    :old.TELEFONO2,
    :old.IDPAQ,
    :old.IDEQUIPO,
    :old.IDTARJETA,
    :old.OBSERVACION,
    :old.CODINSTALADOR,
    :old.CODUSU,
    :old.FECREG,
    :old.FECACTCONAX,
    :old.ESTADO,
    :old.CODSOLOT,
    :old.NUMSLC,
    :old.CODCLI,
    :old.FECBAJACONAX,
    :old.FECANULACONAX,
    :old.UNITADDRESS,
    :old.CODCON,
    :old.TIPOPAGODTH,
    :old.PAGOINSTAL,
    :old.PAGOBANCO,
    :old.PAGOOFICINA,
    :old.FLG_PREACTIVADO,
    :old.PID,
    :old.CODINSSRV,
    :old.FLG_VERIFTEC,
    :old.FECINIVIG,
    :old.FECFINVIG,
    :old.FECALERTA,
    :old.FECCORTE,
    :old.MESESSINSRV,
    :old.FLG_FACTURABLE,
    :old.SERSUT,
    :old.NUMSUT,
    :old.TIPDOCFAC,
    :old.FLG_TIP_PROY,
    :old.BOUQUETS,
    :old.CODSUC,
    :old.DIRSUC,
    :old.CODSOL,
    :old.FLG_VALIDADO,
    :old.NRODOCCON,
    :old.TIPDOCCON,
    :old.CODUSUMOD,
    :old.FECUSUMOD,
    :old.CODSUCFAC,
    :old.DIRSUCFAC,
    :old.FLG_RESERVA,
    :old.PLAZO_SRV,
    :old.FLG_RECARGA,
    :old.CODMOTIVO_LV,
    :old.CODMOTIVO_TC,
    :old.CODMOTIVO_CO,
    :old.CODMOTIVO_TF,
    :old.VALIDASERIE,
    :old.CODIGO_RECARGA,
    :old.ESTADO_OBJETIVO,
    V_USUARIO_LOG,
    V_DATE_LOG,
    V_TIPO_LOG);
    --ini 1.0
    ls_mensaje := 'Se actualizó el número de registo: ' || to_char(:old.NUMREGISTRO) ||
    ' ,por el usuario: ' || to_char(V_USUARIO_LOG);
    opewf.pq_send_mail_job.p_send_mail('REGINSDTH - actualización',
                                         'DL-PE-ITSoportealNegocio@claro.com.pe',--2.0
                                         ls_mensaje);
    --fin 1.0
  ELSIF DELETING THEN
    V_TIPO_LOG := 'D';
    insert into HISTORICO.REGINSDTH_LOG
    (IDSEC,
    NUMREGISTRO,
    NOMCLI,
    TIPDOC,
    NUMDOC,
    NOMCONTACTO,
    TELEFONO1,
    TELEFONO2,
    IDPAQ,
    IDEQUIPO,
    IDTARJETA,
    OBSERVACION,
    CODINSTALADOR,
    CODUSU,
    FECREG,
    FECACTCONAX,
    ESTADO,
    CODSOLOT,
    NUMSLC,
    CODCLI,
    FECBAJACONAX,
    FECANULACONAX,
    UNITADDRESS,
    CODCON,
    TIPOPAGODTH,
    PAGOINSTAL,
    PAGOBANCO,
    PAGOOFICINA,
    FLG_PREACTIVADO,
    PID,
    CODINSSRV,
    FLG_VERIFTEC,
    FECINIVIG,
    FECFINVIG,
    FECALERTA,
    FECCORTE,
    MESESSINSRV,
    FLG_FACTURABLE,
    SERSUT,
    NUMSUT,
    TIPDOCFAC,
    FLG_TIP_PROY,
    BOUQUETS,
    CODSUC,
    DIRSUC,
    CODSOL,
    FLG_VALIDADO,
    NRODOCCON,
    TIPDOCCON,
    CODUSUMOD,
    FECUSUMOD,
    CODSUCFAC,
    DIRSUCFAC,
    FLG_RESERVA,
    PLAZO_SRV,
    FLG_RECARGA,
    CODMOTIVO_LV,
    CODMOTIVO_TC,
    CODMOTIVO_CO,
    CODMOTIVO_TF,
    VALIDASERIE,
    CODIGO_RECARGA,
    ESTADO_OBJETIVO,
    USUARIO_LOG,
    DATE_LOG,
    TIPO_LOG )
    VALUES
   (
    id,
    :old.NUMREGISTRO,
    :old.NOMCLI,
    :old.TIPDOC,
    :old.NUMDOC,
    :old.NOMCONTACTO,
    :old.TELEFONO1,
    :old.TELEFONO2,
    :old.IDPAQ,
    :old.IDEQUIPO,
    :old.IDTARJETA,
    :old.OBSERVACION,
    :old.CODINSTALADOR,
    :old.CODUSU,
    :old.FECREG,
    :old.FECACTCONAX,
    :old.ESTADO,
    :old.CODSOLOT,
    :old.NUMSLC,
    :old.CODCLI,
    :old.FECBAJACONAX,
    :old.FECANULACONAX,
    :old.UNITADDRESS,
    :old.CODCON,
    :old.TIPOPAGODTH,
    :old.PAGOINSTAL,
    :old.PAGOBANCO,
    :old.PAGOOFICINA,
    :old.FLG_PREACTIVADO,
    :old.PID,
    :old.CODINSSRV,
    :old.FLG_VERIFTEC,
    :old.FECINIVIG,
    :old.FECFINVIG,
    :old.FECALERTA,
    :old.FECCORTE,
    :old.MESESSINSRV,
    :old.FLG_FACTURABLE,
    :old.SERSUT,
    :old.NUMSUT,
    :old.TIPDOCFAC,
    :old.FLG_TIP_PROY,
    :old.BOUQUETS,
    :old.CODSUC,
    :old.DIRSUC,
    :old.CODSOL,
    :old.FLG_VALIDADO,
    :old.NRODOCCON,
    :old.TIPDOCCON,
    :old.CODUSUMOD,
    :old.FECUSUMOD,
    :old.CODSUCFAC,
    :old.DIRSUCFAC,
    :old.FLG_RESERVA,
    :old.PLAZO_SRV,
    :old.FLG_RECARGA,
    :old.CODMOTIVO_LV,
    :old.CODMOTIVO_TC,
    :old.CODMOTIVO_CO,
    :old.CODMOTIVO_TF,
    :old.VALIDASERIE,
    :old.CODIGO_RECARGA,
    :old.ESTADO_OBJETIVO,
    V_USUARIO_LOG,
    V_DATE_LOG,
    V_TIPO_LOG);
  END IF;
END;
/



