CREATE OR REPLACE TRIGGER operacion.t_solotptoequ_ad
  AFTER INSERT OR UPDATE OR DELETE ON operacion.solotptoequ
  FOR EACH ROW

  /***************************************************************************
    NOMBRE    : t_solotptoequ_ad
    PROPOSITO : Genera log de operacion.solotptoequ
    
    REVISIONES:
    Ver.    Fecha       Autor                 Descripción 
    ------  ----------  --------------------  ------------------------------
    1.0     28/11/2019  Janpierre Benito      Creación de Trigger
  ***************************************************************************/

DECLARE
  n_secuencial NUMBER;
BEGIN

  SELECT historico.sq_solotptoequ_log.NEXTVAL
    INTO n_secuencial
    FROM dummy_ope;

  IF DELETING THEN
  
    INSERT INTO historico.solotptoequ_log
      (idseq,
       codsolot,
       punto,
       orden,
       tipequ,
       cantidad,
       tipprp,
       costo,
       numserie,
       fecins,
       instalado,
       estado,
       codequcom,
       tipo,
       flginv,
       fecinv,
       tipcompra,
       observacion,
       codusu,
       fecusu,
       codot,
       enacta,
       pccodtarea,
       pctipgasto,
       pcidorggasto,
       flgsol,
       flgreq,
       codeta,
       codalmacen,
       flg_ventas,
       codalmof,
       fecfins,
       fecfdis,
       id_sol,
       tran_solmat,
       codusudis,
       nro_res,
       nro_res_l,
       pep,
       pep_leasing,
       mac,
       fecgenreserva,
       usugenreserva,
       flg_ingreso,
       centrosap,
       almacensap,
       flg_despacho,
       valida_almacen,
       trans_despacho,
       imsi,
       nro_pin,
       flg_recuperacion,
       recuperable,
       aplica_cliente,
       idagenda,
       codsolot_recuperacion,
       acta,
       idspcab,
       iddet,
       pep_pe05,
       pepleasing_pe05,
       centrosap_pe05,
       canliq,
       estadoequ,
       fec_recupero,
       fec_almacen,
       codmotivo_averia,
       flg_proceso,
       sptoc_est_despacho,
       spton_dctosap,
       idppto,
       clase_val,
       flg_adc,
       semana_liq,
       cant_despacho,
       saldo_despacho,
       doc_sap_despacho,
       fecha_despacho,
       fec_val_desp,
       cod_rpta_val_desp,
       msg_rpta_val_desp,
       cod_material,
       cod_mat,
       cod_marrt,
       id_seq,
       acc_log)
    VALUES
      (n_secuencial,
       :OLD.CODSOLOT,
       :OLD.PUNTO,
       :OLD.ORDEN,
       :OLD.TIPEQU,
       :OLD.CANTIDAD,
       :OLD.TIPPRP,
       :OLD.COSTO,
       :OLD.NUMSERIE,
       :OLD.FECINS,
       :OLD.INSTALADO,
       :OLD.ESTADO,
       :OLD.CODEQUCOM,
       :OLD.TIPO,
       :OLD.FLGINV,
       :OLD.FECINV,
       :OLD.TIPCOMPRA,
       :OLD.OBSERVACION,
       :OLD.CODUSU,
       :OLD.FECUSU,
       :OLD.CODOT,
       :OLD.ENACTA,
       :OLD.PCCODTAREA,
       :OLD.PCTIPGASTO,
       :OLD.PCIDORGGASTO,
       :OLD.FLGSOL,
       :OLD.FLGREQ,
       :OLD.CODETA,
       :OLD.CODALMACEN,
       :OLD.FLG_VENTAS,
       :OLD.CODALMOF,
       :OLD.FECFINS,
       :OLD.FECFDIS,
       :OLD.ID_SOL,
       :OLD.TRAN_SOLMAT,
       :OLD.CODUSUDIS,
       :OLD.NRO_RES,
       :OLD.NRO_RES_L,
       :OLD.PEP,
       :OLD.PEP_LEASING,
       :OLD.MAC,
       :OLD.FECGENRESERVA,
       :OLD.USUGENRESERVA,
       :OLD.FLG_INGRESO,
       :OLD.CENTROSAP,
       :OLD.ALMACENSAP,
       :OLD.FLG_DESPACHO,
       :OLD.VALIDA_ALMACEN,
       :OLD.TRANS_DESPACHO,
       :OLD.IMSI,
       :OLD.NRO_PIN,
       :OLD.FLG_RECUPERACION,
       :OLD.RECUPERABLE,
       :OLD.APLICA_CLIENTE,
       :OLD.IDAGENDA,
       :OLD.CODSOLOT_RECUPERACION,
       :OLD.ACTA,
       :OLD.IDSPCAB,
       :OLD.IDDET,
       :OLD.PEP_PE05,
       :OLD.PEPLEASING_PE05,
       :OLD.CENTROSAP_PE05,
       :OLD.CANLIQ,
       :OLD.ESTADOEQU,
       :OLD.FEC_RECUPERO,
       :OLD.FEC_ALMACEN,
       :OLD.CODMOTIVO_AVERIA,
       :OLD.FLG_PROCESO,
       :OLD.SPTOC_EST_DESPACHO,
       :OLD.SPTON_DCTOSAP,
       :OLD.IDPPTO,
       :OLD.CLASE_VAL,
       :OLD.FLG_ADC,
       :OLD.SEMANA_LIQ,
       :OLD.CANT_DESPACHO,
       :OLD.SALDO_DESPACHO,
       :OLD.DOC_SAP_DESPACHO,
       :OLD.FECHA_DESPACHO,
       :OLD.FEC_VAL_DESP,
       :OLD.COD_RPTA_VAL_DESP,
       :OLD.MSG_RPTA_VAL_DESP,
       :OLD.COD_MATERIAL,
       :OLD.COD_MAT,
       :OLD.COD_MARRT,
       :OLD.ID_SEQ,
       'D');
  
  END IF;

END;
/
