CREATE OR REPLACE TRIGGER OPERACION.T_SOLOTPTO_ID_ESTREQU_BU
BEFORE UPDATE
ON OPERACION.SOLOTPTO_ID
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN

   IF UPDATING ('ESTREQUISIC') THEN
      :new.CODUSUESTREQU := user ;
   END IF;
   IF :new.estado<>:old.estado THEN
      :new.FECESTPROG:=sysdate;
      :new.CODUSUESTREQU := user ;
   END IF;

EXCEPTION
  WHEN OTHERS THEN
  NULL;

END;
/



