CREATE OR REPLACE TRIGGER OPERACION.T_TECNICO_BI
  BEFORE INSERT ON OPERACION.TECNICO
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
declare
  -- local variables here
begin
      SELECT (nvl(MAX(CODTEC),0) + 1) into :NEW.CODTEC FROM TECNICO;
end T_TECNICO_BI;
/



