CREATE OR REPLACE TRIGGER OPERACION.t_TIPEQU_bi
BEFORE INSERT
ON TIPEQU
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   if :new.tipequ is null then
     select NVL(MAX(TIPEQU),0) + 1 into :NEW.TIPEQU from TIPEQU;
   end if;
END;
/



