CREATE OR REPLACE TRIGGER OPERACION.T_TIPESTDTH_TBI
  BEFORE INSERT ON OPERACION.TIPESTDTH
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  id     number(3);
BEGIN
  SELECT OPERACION.SQ_TIPESTDTH.NEXTVAL INTO id FROM dual;
  :new.TIPOESTADO := id;
END;
/



