CREATE OR REPLACE TRIGGER OPERACION.T_TIPESTDTH_TBU
  BEFORE UPDATE ON OPERACION.TIPESTDTH
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  :NEW.USUMOD := USER;
  :NEW.FECMOD := SYSDATE;
END;
/



