CREATE OR REPLACE TRIGGER OPERACION.T_TRASLADO_ALMACEN_BI
BEFORE INSERT
ON operacion.TRASLADO_ALMACEN
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
declare
ln_ID number;
BEGIN
   if :new.ORD_TRAS is null then
      :new.ORD_TRAS := F_GET_ORD_TRAS;
   end if;

exception
when others then
     RAISE_APPLICATION_ERROR(-20500,'ERROR AL GENERAR EL ID DE TRASLADO');
END;
/



