CREATE OR REPLACE TRIGGER OPERACION.T_TRS_PPTO_LOG
  BEFORE DELETE ON OPERACION.TRS_PPTO
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  v_idseq HISTORICO.TRS_PPTO_LOG.IDSEQ%TYPE;
BEGIN
  select HISTORICO.SQ_TRS_PPTO_LOG.nextval into v_idseq from dual;
  insert into HISTORICO.TRS_PPTO_LOG
    (IDSEQ,
     IDPPTO,
     TIPO,
     TOTAL_PEP,
     IDAGENDA,
     PROCESADO,
     RECIBIDO,
     IDLOTEPPTO,
     CODSOLOT,
     PEP,
     PROVEEDOR_SAP,
     CENTRO,
     ALMACEN,
     DOCUMENTO,
     CONTRATO,
     RESPUESTA_SAP,
     MENSAJE_SAP,
     CENTROSRV,
     NUMRESERVA,
     PUNTO,
     ORDEN,
     IPAPLICACION,
     PCAPLICACION,
     CODUSU,
     FECUSU,
     CODETA,
     SERVICIO,
     IDPROCESO,
     N_REINTENTOS_PPTO,
     FECACTSRV)
  values
    (v_idseq,
     :OLD.IDPPTO,
     :OLD.TIPO,
     :OLD.TOTAL_PEP,
     :OLD.IDAGENDA,
     :OLD.PROCESADO,
     :OLD.RECIBIDO,
     :OLD.IDLOTEPPTO,
     :OLD.CODSOLOT,
     :OLD.PEP,
     :OLD.PROVEEDOR_SAP,
     :OLD.CENTRO,
     :OLD.ALMACEN,
     :OLD.DOCUMENTO,
     :OLD.CONTRATO,
     :OLD.RESPUESTA_SAP,
     :OLD.MENSAJE_SAP,
     :OLD.CENTROSRV,
     :OLD.NUMRESERVA,
     :OLD.PUNTO,
     :OLD.ORDEN,
     :OLD.IPAPLICACION,
     :OLD.PCAPLICACION,
     :OLD.CODUSU,
     :OLD.FECUSU,
     :OLD.CODETA,
     :OLD.SERVICIO,
     :OLD.IDPROCESO,
     :OLD.N_REINTENTOS_PPTO,
     :OLD.FECACTSRV);
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20500, 'ERROR');
END;
/
