CREATE OR REPLACE TRIGGER OPERACION.T_ZONABLOQUEHORARIO_BI
BEFORE INSERT
ON OPERACION.ZONABLOQUEHORARIO REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
   if :new.idbloque is null then
      select nvl(max(idbloque),0) + 1 into :new.idbloque  from ZONABLOQUEHORARIO;
   end if;
END;
/



