--
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.OPE_PARAM_XML TO WEBSERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.OPE_PARAM_XML TO R_PROD;
--
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_BSCSIX_CBIO TO WEBSERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_BSCSIX_CBIO TO R_PROD;
