-- Grant/Revoke object privileges 
grant select on OPERACION.OPE_SINERGIA_FILTROS_TMP to CONSULTA_OPERACION;
grant delete on OPERACION.OPE_SINERGIA_FILTROS_TMP to R_PROD;
grant select on OPERACION.OPE_SINERGIA_FILTROS_TMP to R_SOAP_PREPAGO;
grant select on OPERACION.OPE_SINERGIA_FILTROS_TMP to T12397_BD;
grant select on OPERACION.OPE_SINERGIA_FILTROS_TMP to T14686;
grant select on OPERACION.OPE_SINERGIA_FILTROS_TMP to T14973_BD;
grant delete on OPERACION.LICITACIONXSOT to R_PROD;
