GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF TO USRBDBTCHSGA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF_HIST TO USRBDBTCHSGA;
COMMIT;
