-- GRANT/REVOKE OBJECT PRIVILEGES 
grant execute on OPERACION.PKG_EF_COSTEO to USREAISGA;
grant execute on OPERACION.PKG_FACTIBILIDAD to USREAISGA;
grant execute on OPERACION.PKG_GESTION_RECURSOS to USREAISGA;
---
grant execute on OPERACION.PKG_EF_COSTEO to R_PROD;
grant execute on OPERACION.PKG_FACTIBILIDAD to R_PROD;
---
GRANT SELECT ON FINANCIAL.SOLICITUD_MAT TO OPERACION; 
GRANT SELECT ON METASOLV.PEX_CAJTER TO OPERACION;
GRANT SELECT ON METASOLV.SGAT_PEX_FIBRA TO OPERACION;
GRANT SELECT ON METASOLV.EQUIPORED TO OPERACION;
GRANT SELECT ON METASOLV.TARJETAXEQUIPO TO OPERACION;
GRANT SELECT ON METASOLV.PUERTOXEQUIPO TO OPERACION;
GRANT SELECT ON SALES.VTADETPTOENL TO OPERACION;
GRANT SELECT ON BILLCOLPER.PRODUCTO TO OPERACION;
GRANT SELECT ON PRODUCCION.ALMTABMAT TO OPERACION;
GRANT SELECT ON METASOLV.SGAT_TIPAGR_EQUIPORED TO OPERACION;
GRANT SELECT ON METASOLV.PEX_TIPCABLE TO OPERACION;
GRANT SELECT ON METASOLV.PEX_CABLE TO OPERACION;
GRANT SELECT ON MARKETING.VTASUCCLI TO OPERACION;
GRANT SELECT ON FINANCIAL.Z_PS_VAL_BUSQUEDA_DET TO OPERACION;
GRANT SELECT ON MARKETING.SGAT_DIRGEOREF_SW TO OPERACION;
/
