GRANT SELECT ON OPERACION.INSSRV TO WEBSERVICE;
GRANT EXECUTE, DEBUG ON OPERACION.PKG_TRANSACCIONES_SGA TO WEBSERVICE; 
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_APROVISION_LOG TO WEBSERVICE;
GRANT EXECUTE, DEBUG ON OPERACION.PKG_TRANSACCIONES_SGA TO R_PROD; 