GRANT EXECUTE ON OPERACION.PKG_CONSULTA_UNIFICADA_SGA TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_SOT_UNIFICADA TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_TRS_POSTVENTA TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_FLUJO_AUTOMATICO TO USREAISGA;