GRANT EXECUTE ON OPERACION.PQ_DECO_ADICIONAL_LTE TO USREAISGA;
GRANT EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN_LTE TO USREAISGA;
GRANT EXECUTE ON OPERACION.PQ_SIAC_TRASLADO_EXTERNO_LTE TO USREAISGA;
GRANT SELECT, INSERT, UPDATE ON OPERACION.SIAC_POSTVENTA_PROCESO TO USREAISGA;
GRANT EXECUTE ON OPERACION.PQ_SIAC_POSTVENTA TO USREAISGA;
GRANT EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_SIAC_POSTVENTA TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_SIAC_CAMBIO_NUMERO TO USREAISGA;
GRANT EXECUTE ON OPERACION.PKG_ASIGNAR_WF2 TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PKG_SIAC_CAMBIO_NUMERO TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PKG_SIAC_POSTVENTA TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_ADM_CUADRILLA TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_AGENDAMIENTO TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_CONSULTA_SIAC_PRE TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_DECO_ADICIONAL TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_DECO_ADICIONAL_LTE TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_INALAMBRICO TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_INTEGRACION_DTH TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SGA_BSCS TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SGA_JANUS TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SGA_SIAC TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SGA_TH TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SIAC_CAMBIO_PLAN_LTE TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SIAC_POSTVENTA TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.PQ_SOLOT TO USRSIACUNICO;
GRANT EXECUTE ON OPERACION.SGASS_VAL_ORDEN_VISIT_CP TO USRSIACUNICO;
--Permisos para la aplicacion Paqueta consulta deuda apadece
GRANT EXECUTE ON OPERACION.PKG_SIAC_CAMBIO_NUMERO TO R_PROD;
GRANT EXECUTE ON OPERACION.PKG_SIAC_POSTVENTA TO R_PROD
/