-- grant
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_SERV TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_REPORT TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_MATRIZ_FOTO TO R_PROD;
