-- GRANT/REVOKE OBJECT PRIVILEGES 
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_ETAPA_PRM TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_EQUIPO_SRVC TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_EQUIPO_CNFG TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_EQUIPO_CNFG_LOG TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_ETAPA_SRVC TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_ETAPA_CNFG TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_ETAPA_CNFG_LOG TO R_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACION.SGAT_EF_REGLACOSTEO_PINT TO R_PROD;
