CREATE INDEX OPERACION.IDX_RESTV_NRO_ORDEN ON OPERACION.SGAT_RESERVA_TOA(RESTV_NRO_ORDEN);
CREATE INDEX OPERACION.IDX_RESTN_ID_ETA ON OPERACION.SGAT_RESERVA_TOA(RESTN_ID_ETA);
CREATE INDEX OPERACION.IDX_RESTN_NRO_SOLOT ON OPERACION.SGAT_RESERVA_TOA(RESTN_NRO_SOLOT);
CREATE INDEX OPERACION.IDX_RESTN_ID_CONSULTA ON OPERACION.SGAT_RESERVA_TOA(RESTN_ID_CONSULTA);
CREATE INDEX OPERACION.IDX_RESTN_ESTADO ON OPERACION.SGAT_RESERVA_TOA(RESTN_ESTADO);
CREATE INDEX OPERACION.IDX_RESTD_FECHA_GENERADA ON OPERACION.SGAT_RESERVA_TOA(RESTD_FECHA_GENERADA);
CREATE INDEX OPERACION.IDX_RESTN_NUM_SEC ON OPERACION.SGAT_RESERVA_TOA(RESTN_NUM_SEC);
commit;
\