-- CREATE/RECREATE INDEXES 
CREATE UNIQUE INDEX OPERACION.IX_SGA_PROCESO_LIC_CAB_01 ON OPERACION.SGAT_PROCESO_LIC_CAB (LCABC_NUMSLC, LCABC_CODCLI)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
