-- CREATE/RECREATE INDEXES 
CREATE INDEX OPERACION.IX_SGAT_NOTIFICACION_CLIENTE ON OPERACION.SGAT_NOTIFICACION_CLIENTE (CLIND_FECENVIO)
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
