-- CREATE/RECREATE INDEXES 
CREATE INDEX OPERACION.IX_SGAT_PROCESO_LIC_DET ON OPERACION.SGAT_PROCESO_LIC_DET (LICDC_NUMSLC, LICDN_CID)
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
