-- CREATE/RECREATE INDEXES 
CREATE INDEX OPERACION.IX_SGAT_PROCESO_CID_SERV ON OPERACION.SGAT_CID_SERV_LICENCIA (SERLC_NUMSLC, SERLN_CID)
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
