CREATE INDEX OPERACION.IX_SGA_PROCESO_LIC_SOP_01 ON OPERACION.SGAT_PROCESO_LIC_SOP (LICSD_FECINICIO, LICSD_FECFIN)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE INDEX OPERACION.IX_SGA_PROCESO_LIC_SOP_02 ON OPERACION.SGAT_PROCESO_LIC_SOP (LICSI_CODPROV)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
CREATE INDEX OPERACION.IX_SGA_PROCESO_LIC_SOP_03 ON OPERACION.SGAT_PROCESO_LIC_SOP (LICSI_TIPO, LICSN_ESTADOLIC)
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
