CREATE TABLE OPERACION.AGENDAMIENTO_LOG
(
  IDAGENDA          NUMBER,
  CODCON            NUMBER,
  CODCLI            CHAR(8 BYTE),
  FECPROG           DATE,
  FECAGENDA         DATE,
  HORAS             NUMBER,
  CODINCIDENCE      NUMBER(8),
  ESTAGE            NUMBER(2),
  TIPO_ACC_LOG      CHAR(1 BYTE),
  IDSEQ             NUMBER                      NOT NULL,
  OBSERVACION       VARCHAR2(500 BYTE),
  ACTA_INSTALACION  VARCHAR2(50 BYTE),
  CODCNT            CHAR(8 BYTE),
  INSTALADOR        VARCHAR2(50 BYTE),
  USUREG            VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  FECREG            DATE                        DEFAULT sysdate               NOT NULL,
  USUMOD            VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  FECMOD            DATE                        DEFAULT sysdate               NOT NULL,
  AREA              NUMBER(4)
);

COMMENT ON TABLE OPERACION.AGENDAMIENTO_LOG IS 'Historial de estados de agendamiento';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.IDAGENDA IS 'Id Agenda';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.FECPROG IS 'Fecha de Programación de Visita';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.FECAGENDA IS 'Fecha de Agenda Ejecución';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.HORAS IS 'Tiempo de Visita';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.CODINCIDENCE IS 'Incidencia';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.ESTAGE IS 'Estado de Agenda';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.TIPO_ACC_LOG IS 'Tipo de accion que se realizo';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.IDSEQ IS 'Secuencial del log';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.OBSERVACION IS 'Observaciones';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.ACTA_INSTALACION IS 'Acta de Instalacion';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.CODCNT IS 'Codigo de Contacto';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.INSTALADOR IS 'Instalador en Sitio';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.FECREG IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.USUMOD IS 'Usuario que modificó el registro';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.FECMOD IS 'Fecha que se modificó el registro';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.CODCLI IS 'Codigo Cliente';

COMMENT ON COLUMN OPERACION.AGENDAMIENTO_LOG.AREA IS 'Area';


