CREATE TABLE OPERACION.AGENDA_TAREAS
(
  IDTAREA            NUMBER,
  CODCON             NUMBER,
  CODCLI             VARCHAR2(8 BYTE),
  SOLOT              NUMBER,
  DIRECCION          VARCHAR2(480 BYTE),
  CODUSU             VARCHAR2(100 BYTE)         DEFAULT user,
  FECUSU             DATE                       DEFAULT sysdate,
  STATUS             VARCHAR2(100 BYTE),
  PROYECTO           VARCHAR2(10 BYTE),
  IDZONA             CHAR(3 BYTE),
  FECHA_INSTALACION  DATE,
  OBSERVACION        VARCHAR2(500 BYTE),
  REFERENCIA         VARCHAR2(500 BYTE),
  IDAGENDA           NUMBER,
  FECPROG            DATE,
  FECAGENDA          DATE,
  HORAS              NUMBER,
  CODINCIDENCE       NUMBER(8),
  ESTAGE             NUMBER(2),
  CODUBI             CHAR(10 BYTE),
  TIPO_AGENDA        NUMBER(2),
  CODSUC             CHAR(10 BYTE),
  ACTA_INSTALACION   VARCHAR2(50 BYTE),
  CINTILLO           VARCHAR2(15 BYTE)
);

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.IDAGENDA IS 'PK agendamiento';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.FECAGENDA IS 'Fecha de Agenda';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.FECPROG IS 'Fecha de programacion';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.HORAS IS 'Horas de Programación';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.CODINCIDENCE IS 'Codigo de Incidencia';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.ESTAGE IS 'Estado de Agenda';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.CODUBI IS 'Codigo UBI';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.TIPO_AGENDA IS 'Tipo de Agenda';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.CODSUC IS 'Codigo de Sucursal';

COMMENT ON COLUMN OPERACION.AGENDA_TAREAS.ACTA_INSTALACION IS 'Acta de Instalacion de Contrata';


