CREATE TABLE OPERACION.BLOQUEO_DESBLOQUEO
(
  BLOQUEO_DESBLOQUEO  CHAR(1 BYTE)              NOT NULL,
  DESCRIPCION         VARCHAR2(200 BYTE)        NOT NULL,
  FECUSU              DATE                      DEFAULT SYSDATE               NOT NULL,
  CODUSU              VARCHAR2(30 BYTE)         DEFAULT user                  NOT NULL
);

COMMENT ON TABLE OPERACION.BLOQUEO_DESBLOQUEO IS 'Categorización de los tipos de trabajo';

COMMENT ON COLUMN OPERACION.BLOQUEO_DESBLOQUEO.BLOQUEO_DESBLOQUEO IS 'Codigo de BLOQUEO_DESBLOQUEO';

COMMENT ON COLUMN OPERACION.BLOQUEO_DESBLOQUEO.DESCRIPCION IS 'Descripcion de BLOQUEO_DESBLOQUEO';


