CREATE TABLE OPERACION.BOUQUETXREGINSDTH
(
  NUMREGISTRO            CHAR(10 BYTE),
  CODSRV                 CHAR(4 BYTE),
  BOUQUETS               VARCHAR2(500 BYTE),
  TIPO                   NUMBER,
  ESTADO                 NUMBER,
  CODUSU                 VARCHAR2(30 BYTE)      DEFAULT user,
  FECUSU                 DATE                   DEFAULT sysdate,
  FLG_TRANSFERIR         NUMBER(1)              DEFAULT 0,
  FECULTENV              DATE,
  USUMOD                 VARCHAR2(30 BYTE)      DEFAULT USER,
  FECMOD                 DATE                   DEFAULT SYSDATE,
  FECHA_INICIO_VIGENCIA  DATE,
  FECHA_FIN_VIGENCIA     DATE,
  IDCUPON                NUMBER,
  FLG_INSTANTANEA        NUMBER(1)              DEFAULT 0,
  IDGRUPO                NUMBER(5),
  PID                    NUMBER(10)
);

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.NUMREGISTRO IS 'Númreo de registro de instalación de DTH';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.CODSRV IS 'Código de servicio';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.BOUQUETS IS 'Bouquets de Canales DTH';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.TIPO IS 'Tipo 0: Servicio Adicional, 1: Servicio Principal, 2: Promociones';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.ESTADO IS 'Estado 0: No activo el servicio, 1: Activo el servicio';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.CODUSU IS 'Código de Usuario ';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FLG_TRANSFERIR IS 'Flag de trasferencia ';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FECULTENV IS 'Fecha de ultimo envio';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.USUMOD IS 'Usuario modificador';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FECMOD IS 'Fecha de modificacion';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FECHA_INICIO_VIGENCIA IS 'Fecha Inicio de Vigencia del Bouquet adicional';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FECHA_FIN_VIGENCIA IS 'Fecha Fin de Vigencia del Bouquet adicional';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.IDCUPON IS 'Identificador del cupón que desencadenó la promoción';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.FLG_INSTANTANEA IS 'Flag que identifica si proviene de un lote de Promociones Instantaneas';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.IDGRUPO IS 'Identificador del grupo de bouquet DTH OPE_GRUPO_BOUQUET_CAB';

COMMENT ON COLUMN OPERACION.BOUQUETXREGINSDTH.PID IS 'Numero de la instancia de producto INSPRD';


