CREATE TABLE OPERACION.CFGDW
(
  ID          NUMBER,
  DW          VARCHAR2(200 BYTE),
  CAMPO       VARCHAR2(200 BYTE),
  VISIBLE     NUMBER,
  ORDEN       NUMBER,
  USUARIO     VARCHAR2(200 BYTE)                DEFAULT user,
  DESC_CAMPO  VARCHAR2(200 BYTE),
  ANCHO       NUMBER,
  CABECERA    VARCHAR2(200 BYTE),
  FECUSU      DATE                              DEFAULT SYSDATE,
  TXTCAMPO    VARCHAR2(200 BYTE),
  DBNAME      VARCHAR2(200 BYTE),
  COLOR       NUMBER
);


