CREATE TABLE OPERACION.CONF_INCIXAGE
(
  TIPTRA      NUMBER,
  CODSUBTYPE  NUMBER,
  ESTAGE      NUMBER,
  CODSTATUS   NUMBER,
  USUREG      VARCHAR2(30 BYTE)                 DEFAULT user                  NOT NULL,
  FECREG      DATE                              DEFAULT sysdate               NOT NULL,
  USUMOD      VARCHAR2(30 BYTE),
  FECMOD      DATE
);

COMMENT ON TABLE OPERACION.CONF_INCIXAGE IS 'Configuración de Estado Agenda-Incidencia';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.TIPTRA IS 'Tipo de Trabajo';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.CODSUBTYPE IS 'Tipo de Incidencia';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.ESTAGE IS 'Estado de Agenda';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.CODSTATUS IS 'Codigo estado incidencia';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.USUREG IS 'Usuario registro';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.FECREG IS 'Fecha registro';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.USUMOD IS 'Usuario modificacion';

COMMENT ON COLUMN OPERACION.CONF_INCIXAGE.FECMOD IS 'Fecha modificacion';


