CREATE TABLE OPERACION.CONSTANTE
(
  CONSTANTE    CHAR(15 BYTE)                    NOT NULL,
  DESCRIPCION  VARCHAR2(200 BYTE)               NOT NULL,
  TIPO         CHAR(1 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  VALOR        VARCHAR2(100 BYTE),
  OBS          VARCHAR2(2000 BYTE)
);

COMMENT ON TABLE OPERACION.CONSTANTE IS 'Listado de constantes';

COMMENT ON COLUMN OPERACION.CONSTANTE.CONSTANTE IS 'Llave primaria de la tabla';

COMMENT ON COLUMN OPERACION.CONSTANTE.DESCRIPCION IS 'Descripcion de la constante';

COMMENT ON COLUMN OPERACION.CONSTANTE.TIPO IS 'Tipo de constante';

COMMENT ON COLUMN OPERACION.CONSTANTE.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.CONSTANTE.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.CONSTANTE.VALOR IS 'Valor del constante';

COMMENT ON COLUMN OPERACION.CONSTANTE.OBS IS 'Observacion';


