CREATE TABLE OPERACION.CONTROL_CORTE_DTH
(
  IDCTRLCORTE   NUMBER,
  NUMREGISTRO   CHAR(10 BYTE),
  FECCORTEPRG   DATE,
  FECCORTEREAL  DATE,
  ESTCORTE      NUMBER,
  MOTIVO        VARCHAR2(100 BYTE),
  TIPO          VARCHAR2(100 BYTE),
  MENSAJE       VARCHAR2(100 BYTE),
  CODUSU        VARCHAR2(30 BYTE)               DEFAULT user,
  FECUSU        DATE                            DEFAULT sysdate,
  CODSOLOT      NUMBER(8)
);

COMMENT ON COLUMN OPERACION.CONTROL_CORTE_DTH.CODSOLOT IS 'Solicitud que realiza el corte';


