CREATE TABLE OPERACION.CONTACTO_EMAIL_BLOQUEO
(
  IDCONTACTO     NUMBER(5)                      NOT NULL,
  EMAIL_ORIGEN   VARCHAR2(200 BYTE)             NOT NULL,
  EMAIL_DESTINO  VARCHAR2(2000 BYTE)            NOT NULL,
  ESTADO         NUMBER(1)                      DEFAULT 0,
  MOTIVO         CHAR(15 BYTE)                  NOT NULL,
  USUREG         VARCHAR2(30 BYTE)              DEFAULT USER,
  FECREG         DATE                           DEFAULT SYSDATE,
  USUMOD         VARCHAR2(30 BYTE)              DEFAULT USER,
  FECMOD         DATE                           DEFAULT SYSDATE,
  ASUNTO_CORREO  VARCHAR2(200 BYTE),
  CUERPO_CORREO  VARCHAR2(2000 BYTE)
);

COMMENT ON TABLE OPERACION.CONTACTO_EMAIL_BLOQUEO IS 'CORREO DE BLOQUEO DESBLOQUE POR FCO';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.IDCONTACTO IS 'Identificador único de email de contacto';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.EMAIL_ORIGEN IS 'Correo Origen: De';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.EMAIL_DESTINO IS 'Correo Destino: Para';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.ESTADO IS '0=Inactivo, 1=Activo';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.MOTIVO IS 'Motivo de Correo: ''BLOQUEO''=Error Bloqueo; ''DESBLOQUEO''=Error Desbloqueo';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.FECREG IS 'Fecha que inserto el registro';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.USUMOD IS 'Usuario que modificó el registro';

COMMENT ON COLUMN OPERACION.CONTACTO_EMAIL_BLOQUEO.FECMOD IS 'Fecha que se modificó el registro';


