CREATE TABLE OPERACION.DATA_EMTA
(
  BUSINESS_UNIT     CHAR(5 BYTE),
  LICENSE_PLATE_ID  VARCHAR2(14 BYTE),
  ITEM_ID           CHAR(6 BYTE),
  SERIAL_ID         CHAR(15 BYTE),
  CMAC_ADDRESS      CHAR(12 BYTE),
  MTA_MAC_ADDRESS   CHAR(12 BYTE),
  CUSTOMER_PO       CHAR(10 BYTE)
);


