CREATE TABLE OPERACION.DEPTXCONTRATA
(
  IDSUCXCONTRATA  NUMBER(6)                     NOT NULL,
  CODEST          CHAR(3 BYTE)                  NOT NULL,
  PRIORIDAD       NUMBER(6)                     DEFAULT 1,
  CODCON          NUMBER(6),
  FECUSU          DATE                          DEFAULT sysdate,
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT user
);

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.IDSUCXCONTRATA IS 'ID de Sucursal por Contrata';

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.CODEST IS 'Codigo de Departamento';

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.PRIORIDAD IS 'Prioridad de Sucursal';

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.FECUSU IS 'Fecha Creacion registro';

COMMENT ON COLUMN OPERACION.DEPTXCONTRATA.CODUSU IS 'Usuario Creacion registro';


