CREATE TABLE OPERACION.DESPACHO_MASIVO
(
  ID_TRS            NUMBER                      NOT NULL,
  TRANS_DESPACHO    NUMBER(8),
  CODSOLOT          NUMBER(8)                   NOT NULL,
  TIPEQU            NUMBER(6)                   NOT NULL,
  COD_SAP           VARCHAR2(10 BYTE),
  CANTIDAD          NUMBER(8,2)                 DEFAULT 0                     NOT NULL,
  COSTO             NUMBER(8,2)                 DEFAULT 0                     NOT NULL,
  NUMSERIE          VARCHAR2(2000 BYTE),
  FECINS            DATE,
  OBSERVACION       VARCHAR2(240 BYTE),
  CODUSU            VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  FECUSU            DATE                        DEFAULT SYSDATE               NOT NULL,
  FLGREQ            NUMBER(3)                   DEFAULT 0                     NOT NULL,
  FECFDIS           DATE,
  ID_SOL            NUMBER,
  TRAN_SOLMAT       NUMBER,
  NRO_RES           NUMBER,
  NRO_RES_L         NUMBER,
  PEP               VARCHAR2(40 BYTE),
  PEP_LEASING       VARCHAR2(40 BYTE),
  CODCON            NUMBER,
  IDSUCXCONTRATA    NUMBER,
  CENTROSAP         VARCHAR2(4 BYTE),
  ALMACENSAP        VARCHAR2(4 BYTE),
  FLG_DESPACHO      NUMBER                      DEFAULT 0,
  ACTA_INSTALACION  VARCHAR2(50 BYTE),
  TIPPROYECTO       NUMBER
);

COMMENT ON TABLE OPERACION.DESPACHO_MASIVO IS 'Tabla preliminar para el Despacho Masivo';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.ID_TRS IS 'Secuencial, PK de la Tabla';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.CODSOLOT IS 'Codigo de SOT';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.TIPEQU IS 'Codigo del tipo de equipo';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.COD_SAP IS 'Codigo de SAP';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.CANTIDAD IS 'Cantidad de Material';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.COSTO IS 'Costo de Material';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.NUMSERIE IS 'Numero de serie';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.FECINS IS 'Fecha de instalación';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.FLGREQ IS 'Flag de Generar Despacho';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.FECFDIS IS 'Fecha de Envio para el Despacho';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.NRO_RES IS 'Número de Reserva';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.NRO_RES_L IS 'Número de Reserva Leasing';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.PEP IS 'PEP';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.PEP_LEASING IS 'PEP Leasing';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.IDSUCXCONTRATA IS 'Operador o identificador de Centro Almacen';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.CENTROSAP IS 'Centro SAP';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.ALMACENSAP IS 'Almacen SAP';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.FLG_DESPACHO IS 'Indica si se realizo el despacho de esta linea de Equipo';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.ACTA_INSTALACION IS 'Acta de Instalación';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.TIPPROYECTO IS 'Tipo de Proyecto(1:DTH,2:HFC,3:CDMA)';

COMMENT ON COLUMN OPERACION.DESPACHO_MASIVO.TRANS_DESPACHO IS 'Agregar campo para registrar la transacción del Despacho Masivo';


