CREATE TABLE OPERACION.DISTRITOXCONTRATA
(
  CODCON     NUMBER(6)                          NOT NULL,
  CODUBI     CHAR(10 BYTE),
  CODUSU     VARCHAR2(30 BYTE)                  DEFAULT USER,
  FECUSU     DATE                               DEFAULT SYSDATE,
  ESTADO     NUMBER(1)                          DEFAULT 1,
  TIPTRA     NUMBER,
  PRIORIDAD  NUMBER(1)                          DEFAULT 1
);

COMMENT ON TABLE OPERACION.DISTRITOXCONTRATA IS 'DISTRITO X CONTRATA';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.CODUBI IS 'UBIGEO de la sucursal de contrata';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.CODUSU IS 'codigo usario';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.FECUSU IS 'fecha registro';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.TIPTRA IS 'Tipo de Trabajo';

COMMENT ON COLUMN OPERACION.DISTRITOXCONTRATA.PRIORIDAD IS 'Prioridad de la contrata para ubicacion y tipo de trabajo.';


