CREATE TABLE OPERACION.EFAUTOMATICO
(
  ID          NUMBER                            NOT NULL,
  TIPSRV      CHAR(4 BYTE),
  IDCAMPANHA  NUMBER(6),
  ACCESO      NUMBER,
  TIPTRA      NUMBER(4),
  IDPRODUCTO  NUMBER,
  CID         NUMBER(10),
  PREPROC     VARCHAR2(200 BYTE)
);


