CREATE TABLE OPERACION.EQUIPOSDTH
(
  NUMREGISTRO  CHAR(10 BYTE),
  CODEQUCOM    CHAR(4 BYTE),
  TIPEQUOPE    NUMBER(6),
  GRUPOEQU     NUMBER(5),
  SERIE        VARCHAR2(30 BYTE),
  UNITADDRESS  VARCHAR2(30 BYTE),
  CANTIDAD     NUMBER,
  IDPAQ        NUMBER(10),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user,
  FECUSU       DATE                             DEFAULT sysdate
);


