CREATE TABLE OPERACION.EQUXCID
(
  CID          NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(5)                        NOT NULL,
  ORDENPAD     NUMBER(5),
  TIPEQU       NUMBER(6),
  CANTIDAD     NUMBER(10),
  NIVEL        NUMBER(1)                        DEFAULT 0                     NOT NULL,
  FECINS       DATE,
  FECRET       DATE,
  FECCHG       DATE,
  ESTADO       VARCHAR2(30 BYTE),
  NUMSERIE     VARCHAR2(50 BYTE),
  PROPIETARIO  VARCHAR2(50 BYTE),
  IOS          VARCHAR2(50 BYTE),
  OBSERVACION  VARCHAR2(1000 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT USER                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  RED          VARCHAR2(30 BYTE),
  AREA         NUMBER(4)
);

COMMENT ON TABLE OPERACION.EQUXCID IS 'Relacion de los equipos por CID';

COMMENT ON COLUMN OPERACION.EQUXCID.CID IS 'Circuito id';

COMMENT ON COLUMN OPERACION.EQUXCID.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.EQUXCID.ORDENPAD IS 'Orden padre de la tabla';

COMMENT ON COLUMN OPERACION.EQUXCID.TIPEQU IS 'Codigo de tipo de equipo';

COMMENT ON COLUMN OPERACION.EQUXCID.CANTIDAD IS 'Cantidad de equipo';

COMMENT ON COLUMN OPERACION.EQUXCID.NIVEL IS 'Nivel del equipo';

COMMENT ON COLUMN OPERACION.EQUXCID.FECINS IS 'Fecha de instalación';

COMMENT ON COLUMN OPERACION.EQUXCID.FECRET IS 'Fecha de retiro';

COMMENT ON COLUMN OPERACION.EQUXCID.FECCHG IS 'Fecha de cambio de equipo';

COMMENT ON COLUMN OPERACION.EQUXCID.ESTADO IS 'Estado del equipo por cada cid';

COMMENT ON COLUMN OPERACION.EQUXCID.NUMSERIE IS 'Numero de serie';

COMMENT ON COLUMN OPERACION.EQUXCID.PROPIETARIO IS 'Propietario';

COMMENT ON COLUMN OPERACION.EQUXCID.IOS IS 'IOS';

COMMENT ON COLUMN OPERACION.EQUXCID.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.EQUXCID.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.EQUXCID.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.EQUXCID.RED IS 'Red';

COMMENT ON COLUMN OPERACION.EQUXCID.AREA IS 'Area al que pertenece el usuario que inserta el registro';


