CREATE TABLE OPERACION.ERROR_DESPACHO_MASIVO
(
  ID_ERROR    NUMBER,
  DESC_ERROR  VARCHAR2(400 BYTE),
  ERROR_SQLM  VARCHAR2(400 BYTE),
  CODCON      NUMBER,
  MATERIAL    VARCHAR2(30 BYTE),
  CENTRO      VARCHAR2(10 BYTE),
  ALMACEN     VARCHAR2(10 BYTE),
  CODSOLOT    NUMBER,
  FECUSU      DATE                              DEFAULT SYSDATE,
  CODUSU      VARCHAR2(30 BYTE)                 DEFAULT USER
);


