CREATE TABLE OPERACION.ESTDOCXCLI
(
  ESTDOCXCLI   NUMBER(2)                        NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)               NOT NULL,
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT sysdate               NOT NULL,
  NIVEL        NUMBER(1)
);

COMMENT ON TABLE OPERACION.ESTDOCXCLI IS 'No es usada';

COMMENT ON COLUMN OPERACION.ESTDOCXCLI.ESTDOCXCLI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.ESTDOCXCLI.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.ESTDOCXCLI.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.ESTDOCXCLI.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.ESTDOCXCLI.NIVEL IS 'No se utiliza';


