CREATE TABLE OPERACION.ESTPROF24H
(
  ESTPROF24H   CHAR(2 BYTE)                     NOT NULL,
  DESCRIPCION  VARCHAR2(480 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user,
  FECUSU       DATE                             DEFAULT sysdate,
  FLAG         NUMBER(2)
);

COMMENT ON TABLE OPERACION.ESTPROF24H IS 'Registro de estados del servicio de Profesor 24 horas';

COMMENT ON COLUMN OPERACION.ESTPROF24H.ESTPROF24H IS 'Codigo';

COMMENT ON COLUMN OPERACION.ESTPROF24H.DESCRIPCION IS 'Descripción del estado';

COMMENT ON COLUMN OPERACION.ESTPROF24H.FECUSU IS 'Fecha de registro';


