CREATE TABLE OPERACION.ESTPREUBI
(
  ESTPREUBI    NUMBER                           NOT NULL,
  DESCRIPCION  VARCHAR2(20 BYTE),
  ABREV        CHAR(2 BYTE)
);

COMMENT ON TABLE OPERACION.ESTPREUBI IS 'Estado de cada detalle del presupuesto';

COMMENT ON COLUMN OPERACION.ESTPREUBI.ESTPREUBI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.ESTPREUBI.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.ESTPREUBI.ABREV IS 'Abreviatura';


