CREATE TABLE OPERACION.FACTURAPEX
(
  FACTURA      NUMBER(8)                        NOT NULL,
  TIPO         NUMBER(1),
  NROFAC       VARCHAR2(15 BYTE),
  CODCON       NUMBER(6),
  FECHA        DATE                             NOT NULL,
  ESTFAC       CHAR(2 BYTE),
  ESTGAR       CHAR(2 BYTE)                     DEFAULT 'PE'                  NOT NULL,
  MONEDA       CHAR(1 BYTE)                     DEFAULT 'S'                   NOT NULL,
  TIPCAM       NUMBER(18,4)                     DEFAULT 0                     NOT NULL,
  MONTOFAC     NUMBER(18,4)                     DEFAULT 0                     NOT NULL,
  MONTOGAR     NUMBER(18,4)                     DEFAULT 0                     NOT NULL,
  MONTOMUL     NUMBER(18,4)                     DEFAULT 0                     NOT NULL,
  NROMUL       VARCHAR2(15 BYTE),
  FECREC       DATE                             NOT NULL,
  FECGAR       DATE,
  NROCARTA     VARCHAR2(15 BYTE),
  FECVENCARTA  DATE,
  OBSERVACION  VARCHAR2(500 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  FLGCIERRE    CHAR(1 BYTE)                     DEFAULT '0'
);

COMMENT ON TABLE OPERACION.FACTURAPEX IS 'Factura de pex ';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FACTURA IS 'Numero de factura';

COMMENT ON COLUMN OPERACION.FACTURAPEX.TIPO IS 'Tipo de la factura';

COMMENT ON COLUMN OPERACION.FACTURAPEX.NROFAC IS 'Numero de factura';

COMMENT ON COLUMN OPERACION.FACTURAPEX.CODCON IS 'Codigo del contratista';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FECHA IS 'Fecha de la factura';

COMMENT ON COLUMN OPERACION.FACTURAPEX.ESTFAC IS 'Estado de la factura';

COMMENT ON COLUMN OPERACION.FACTURAPEX.ESTGAR IS 'Estado de la garantia';

COMMENT ON COLUMN OPERACION.FACTURAPEX.MONEDA IS 'Codigo de moneda';

COMMENT ON COLUMN OPERACION.FACTURAPEX.TIPCAM IS 'Tipo de cambio';

COMMENT ON COLUMN OPERACION.FACTURAPEX.MONTOFAC IS 'Monto de la facturación';

COMMENT ON COLUMN OPERACION.FACTURAPEX.MONTOGAR IS 'Monto de garantia';

COMMENT ON COLUMN OPERACION.FACTURAPEX.MONTOMUL IS 'Monto de la multa';

COMMENT ON COLUMN OPERACION.FACTURAPEX.NROMUL IS 'Numero de multa';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FECREC IS 'Fecha de recepción';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FECGAR IS 'Fecha de garantia';

COMMENT ON COLUMN OPERACION.FACTURAPEX.NROCARTA IS 'Numero de carta';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FECVENCARTA IS 'Fecha de vencimiento de carta';

COMMENT ON COLUMN OPERACION.FACTURAPEX.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.FACTURAPEX.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.FACTURAPEX.FECUSU IS 'Fecha de registro';


