CREATE TABLE OPERACION.GRUPOACTIVIDAD
(
  GRUPO   VARCHAR2(5 BYTE)                      NOT NULL,
  CODACT  NUMBER(5)                             NOT NULL,
  CODUSU  VARCHAR2(30 BYTE)                     DEFAULT user                  NOT NULL,
  FECUSU  DATE                                  DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.GRUPOACTIVIDAD IS 'No es usada';

COMMENT ON COLUMN OPERACION.GRUPOACTIVIDAD.CODACT IS 'Codigo de la actividad';

COMMENT ON COLUMN OPERACION.GRUPOACTIVIDAD.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.GRUPOACTIVIDAD.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.GRUPOACTIVIDAD.GRUPO IS 'Grupo de la actividad';


