CREATE TABLE OPERACION.INCIDENCE_DTH
(
  IDINCDTH          NUMBER,
  CODINCIDENCE      NUMBER(8),
  CUSTOMERSEQUENCE  NUMBER(6),
  CUSTOMERCODE      CHAR(8 BYTE),
  SERVICE           VARCHAR2(30 BYTE),
  SERVICENUMBER     VARCHAR2(30 BYTE),
  NUMREGISTRO       VARCHAR2(30 BYTE),
  FECREG            DATE,
  ESTADO            NUMBER(1),
  CODASSOCIATED     NUMBER(3),
  CODUSU            VARCHAR2(30 BYTE)           DEFAULT user,
  FECUSU            DATE                        DEFAULT sysdate
);


