CREATE TABLE OPERACION.INSSRVXINSSRV
(
  CODINSSRVXINSSRV  NUMBER(10)                  NOT NULL,
  CODINSSRV_PADRE   NUMBER(10),
  CODINSSRV_HIJO    NUMBER(10),
  CODTIPREL         NUMBER(2),
  CODUSU            VARCHAR2(30 BYTE)           DEFAULT USER                  NOT NULL,
  FECUSU            DATE                        DEFAULT SYSDATE               NOT NULL,
  NUMSLC            CHAR(10 BYTE)
);

COMMENT ON TABLE OPERACION.INSSRVXINSSRV IS 'No es usada';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.CODINSSRVXINSSRV IS 'Llave primaria de la tabla';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.CODINSSRV_PADRE IS 'Codigo de instancia de servicio padre';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.CODINSSRV_HIJO IS 'Codigo de instancia de servicio hijo';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.CODTIPREL IS 'Tipo de relación entre las instancias de servicio';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.INSSRVXINSSRV.NUMSLC IS 'Numero de proyecto';


