CREATE TABLE OPERACION.INSSRVEQU
(
  CODINSSRV    NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(5)                        NOT NULL,
  CODTIPEQU    CHAR(15 BYTE),
  TIPPRP       NUMBER(2),
  CANTIDAD     NUMBER(8,2)                      DEFAULT 1                     NOT NULL,
  CODEQUCOM    CHAR(4 BYTE),
  FECINS       DATE,
  NUMSERIE     VARCHAR2(20 BYTE),
  OBSERVACION  VARCHAR2(200 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  TIPEQU       NUMBER(6)                        NOT NULL,
  CODELERED    NUMBER(10),
  FECDINST     DATE,
  ESTADO       CHAR(1 BYTE)                     DEFAULT 'I'
);

COMMENT ON TABLE OPERACION.INSSRVEQU IS 'Equipos asociados al SID';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CODINSSRV IS 'Codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRVEQU.ORDEN IS 'Orden de la instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CODTIPEQU IS 'Codigo del tipo de equipo';

COMMENT ON COLUMN OPERACION.INSSRVEQU.TIPPRP IS 'Tipo de propiedad';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CANTIDAD IS 'Cantidad de equipo';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CODEQUCOM IS 'Codigo del equipo comercial';

COMMENT ON COLUMN OPERACION.INSSRVEQU.FECINS IS 'Fecha de instalación';

COMMENT ON COLUMN OPERACION.INSSRVEQU.NUMSERIE IS 'Numero de serie';

COMMENT ON COLUMN OPERACION.INSSRVEQU.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.INSSRVEQU.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.INSSRVEQU.TIPEQU IS 'Codigo de tipo de equipo';

COMMENT ON COLUMN OPERACION.INSSRVEQU.CODELERED IS 'Codigo de elemento de red';

COMMENT ON COLUMN OPERACION.INSSRVEQU.FECDINST IS 'Fecha de instalación';

COMMENT ON COLUMN OPERACION.INSSRVEQU.ESTADO IS 'Estado del equipo';


