CREATE TABLE OPERACION.INSSRV
(
  CODINSSRV       NUMBER(10)                    NOT NULL,
  CODCLI          CHAR(8 BYTE)                  NOT NULL,
  CODSRV          CHAR(4 BYTE)                  NOT NULL,
  ESTINSSRV       NUMBER(2)                     NOT NULL,
  TIPINSSRV       NUMBER(2)                     NOT NULL,
  DESCRIPCION     VARCHAR2(100 BYTE)            NOT NULL,
  DIRECCION       VARCHAR2(480 BYTE),
  FECINI          DATE,
  FECACTSRV       DATE,
  FECFIN          DATE,
  NUMERO          VARCHAR2(20 BYTE),
  CODSUC          CHAR(10 BYTE),
  BW              NUMBER(10,2),
  POP             NUMBER(10),
  NUMSLC          CHAR(10 BYTE),
  NUMPTO          CHAR(5 BYTE),
  OBSERVACION     VARCHAR2(200 BYTE),
  FECUSU          DATE                          DEFAULT SYSDATE               NOT NULL,
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT user                  NOT NULL,
  CODELERED       NUMBER(10),
  CODEQUPOP       NUMBER(10),
  INTERFACE       VARCHAR2(10 BYTE),
  CODUBI          CHAR(10 BYTE),
  TIPSRV          CHAR(4 BYTE),
  CID             NUMBER(10),
  CODINSSRV_ORI   NUMBER(10),
  CODINSSRV_DES   NUMBER(10),
  CODINSSRV_PAD   NUMBER(10),
  IDTIPFAC_INI    NUMBER(3),
  GRUPO_INI       NUMBER(5),
  CODSUCCOB_INI   CHAR(10 BYTE),
  CODPOSTAL       VARCHAR2(30 BYTE),
  CAMPO1          VARCHAR2(50 BYTE),
  CICFAC_INI      NUMBER(5),
  CODMOTINSSRV    NUMBER(3),
  CORREO          VARCHAR2(50 BYTE),
  IDPAQ           NUMBER(10),
  NUMSLC_P        CHAR(10 BYTE),
  TAP             VARCHAR2(4 BYTE),
  BORNE           NUMBER(1),
  NCOS            NUMBER(2),
  CHARGING_AREA1  NUMBER(8),
  CHARGING_AREA2  NUMBER(8),
  CHARGING_AREA3  NUMBER(8),
  NCOS_OLD        VARCHAR2(150 BYTE),
  NCOS_NEW        VARCHAR2(150 BYTE),
  FECINIVIG       DATE,
  FECFINVIG       DATE,
  IDPLATAFORMA    NUMBER
);

COMMENT ON TABLE OPERACION.INSSRV IS 'Listado de las instancia de Servicio (SID)';

COMMENT ON COLUMN OPERACION.INSSRV.CODINSSRV IS 'Codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.INSSRV.CODSRV IS 'Codigo de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.ESTINSSRV IS 'Codigo del estado de la instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.TIPINSSRV IS 'Tipo de instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.DESCRIPCION IS 'Descripcion de la instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.DIRECCION IS 'DIRECCION';

COMMENT ON COLUMN OPERACION.INSSRV.FECINI IS 'Fecha de inicio';

COMMENT ON COLUMN OPERACION.INSSRV.FECACTSRV IS 'Fecha de acta de servcio';

COMMENT ON COLUMN OPERACION.INSSRV.FECFIN IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.INSSRV.NUMERO IS 'NUMERO';

COMMENT ON COLUMN OPERACION.INSSRV.CODSUC IS 'Codigo de la sucursal';

COMMENT ON COLUMN OPERACION.INSSRV.BW IS 'Ancho de banda';

COMMENT ON COLUMN OPERACION.INSSRV.POP IS 'POP';

COMMENT ON COLUMN OPERACION.INSSRV.NUMSLC IS 'Numero del proyecto';

COMMENT ON COLUMN OPERACION.INSSRV.NUMPTO IS 'Punto del proyecto';

COMMENT ON COLUMN OPERACION.INSSRV.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.INSSRV.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.INSSRV.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.INSSRV.CODELERED IS 'Codigo de elemento de red';

COMMENT ON COLUMN OPERACION.INSSRV.CODEQUPOP IS 'EQUIPO DE RED AL CUAL ESTA CONECTADO';

COMMENT ON COLUMN OPERACION.INSSRV.INTERFACE IS 'Interfase que utiliza el circuito';

COMMENT ON COLUMN OPERACION.INSSRV.CODUBI IS 'Codigo del distrito';

COMMENT ON COLUMN OPERACION.INSSRV.TIPSRV IS 'Codigo del tipo de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.CID IS 'Circuito id';

COMMENT ON COLUMN OPERACION.INSSRV.CODINSSRV_ORI IS 'Codigo de instancia de servicio origen';

COMMENT ON COLUMN OPERACION.INSSRV.CODINSSRV_DES IS 'Codigo de instancia de servicio destino';

COMMENT ON COLUMN OPERACION.INSSRV.CODINSSRV_PAD IS 'Codigo de instancia de servicio padre';

COMMENT ON COLUMN OPERACION.INSSRV.IDTIPFAC_INI IS 'Id del tipo de facturacion inicial';

COMMENT ON COLUMN OPERACION.INSSRV.GRUPO_INI IS 'Grupo inicial';

COMMENT ON COLUMN OPERACION.INSSRV.CODSUCCOB_INI IS 'Codigo de la sucursal';

COMMENT ON COLUMN OPERACION.INSSRV.CODPOSTAL IS 'Codigo postal';

COMMENT ON COLUMN OPERACION.INSSRV.CAMPO1 IS 'Observacion 1';

COMMENT ON COLUMN OPERACION.INSSRV.CICFAC_INI IS 'Ciclo de facturacion inicial';

COMMENT ON COLUMN OPERACION.INSSRV.CODMOTINSSRV IS 'Codigo del motivo de la instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRV.IDPAQ IS 'Id Paquete de Producto';

COMMENT ON COLUMN OPERACION.INSSRV.NUMSLC_P IS 'N#mero de proyecto padre';

COMMENT ON COLUMN OPERACION.INSSRV.NCOS IS 'Valor NCOS en la central telefónica.';

COMMENT ON COLUMN OPERACION.INSSRV.CHARGING_AREA1 IS 'Zona de Movilidad 1 vigente';

COMMENT ON COLUMN OPERACION.INSSRV.CHARGING_AREA2 IS 'Zona de Movilidad 2 vigente';

COMMENT ON COLUMN OPERACION.INSSRV.CHARGING_AREA3 IS 'Zona de Movilidad 3 vigente';

COMMENT ON COLUMN OPERACION.INSSRV.IDPLATAFORMA IS 'Identificador de la plataforma';


