CREATE TABLE OPERACION.INSSRVSLA
(
  IDINSSRVSLA     NUMBER(10),
  CODINSSRV       NUMBER(10)                    NOT NULL,
  IDSLA           NUMBER(5),
  REPARACION      NUMBER(2),
  DISPONIBILIDAD  NUMBER(10,2),
  VALIDO          NUMBER                        DEFAULT 0,
  IDINSSLA        NUMBER(10),
  FECUSU          DATE                          DEFAULT sysdate,
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT user
);

COMMENT ON TABLE OPERACION.INSSRVSLA IS 'Listado de las instancia de Servicio X SLA';

COMMENT ON COLUMN OPERACION.INSSRVSLA.IDINSSRVSLA IS 'Codigo de Instancia de SLA';

COMMENT ON COLUMN OPERACION.INSSRVSLA.CODINSSRV IS 'Codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.INSSRVSLA.IDSLA IS 'Id de la tabla VTATABSLC';

COMMENT ON COLUMN OPERACION.INSSRVSLA.REPARACION IS 'Tiempo de Reparación en Horas';

COMMENT ON COLUMN OPERACION.INSSRVSLA.DISPONIBILIDAD IS 'Disponibilidad en Porcentaje';

COMMENT ON COLUMN OPERACION.INSSRVSLA.VALIDO IS 'Instancia Valida';


