CREATE TABLE OPERACION.INT_SERVICIO_PLATAFORMA
(
  IDSEQ        NUMBER                           NOT NULL,
  CODSOLOT     NUMBER(8),
  IDTAREAWF    NUMBER(8),
  CODINSSRV    NUMBER(10),
  PID          NUMBER(10),
  CODNUMTEL    NUMBER(8),
  IMSI         NUMBER,
  ESN          VARCHAR2(12 BYTE),
  IDDEFOPE     NUMBER(5),
  NUMSLC       CHAR(10 BYTE),
  IDLOTE       NUMBER(10),
  ESTADO       NUMBER(1)                        DEFAULT 0,
  OBSERVACION  VARCHAR2(4000 BYTE),
  USUREG       VARCHAR2(30 BYTE)                DEFAULT USER,
  FECREG       DATE                             DEFAULT SYSDATE,
  USUMOD       VARCHAR2(30 BYTE)                DEFAULT USER,
  FECMOD       DATE                             DEFAULT SYSDATE,
  MONTO        NUMBER(10,2),
  VIGENCIA     NUMBER(10),
  NUMSERIE     NUMBER(10,2),
  IDPLAN       NUMBER(4)
);

COMMENT ON COLUMN OPERACION.INT_SERVICIO_PLATAFORMA.ESTADO IS '0-generado,1-enviado,2-procesado,3-error, 4-Anulado';

COMMENT ON COLUMN OPERACION.INT_SERVICIO_PLATAFORMA.MONTO IS 'Monto de pago';

COMMENT ON COLUMN OPERACION.INT_SERVICIO_PLATAFORMA.VIGENCIA IS 'Vigencia de la recarga';

COMMENT ON COLUMN OPERACION.INT_SERVICIO_PLATAFORMA.NUMSERIE IS 'Numero de serie,identificador de recarga en plataforma';

COMMENT ON COLUMN OPERACION.INT_SERVICIO_PLATAFORMA.IDPLAN IS 'Identificar de plan, tabla plan_redint';


