CREATE TABLE OPERACION.INTERFTELEFONIALOG
(
  IDLOGTELEFONIA    NUMBER                      NOT NULL,
  IDTIPOINCIDENCIA  NUMBER,
  IDTIPOEJECUCION   NUMBER,
  CLG_NUM           VARCHAR2(30 BYTE),
  FECEJE            DATE                        DEFAULT sysdate,
  DESCRIPCION       VARCHAR2(400 BYTE),
  COMMAND           VARCHAR2(300 BYTE),
  TIPTRA            NUMBER(4),
  CODMOTOT          NUMBER(3),
  IDWF              NUMBER(8),
  ABRIRTAREA        NUMBER
);

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.IDLOGTELEFONIA IS 'PK';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.IDTIPOINCIDENCIA IS 'Código de tipo de incidencia';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.CLG_NUM IS 'Numero telefonico';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.FECEJE IS 'Fecha de ejecución';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.DESCRIPCION IS 'Breve descripcion del comando ejecutado';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.TIPTRA IS 'Tipo de trabajo SOT';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.CODMOTOT IS 'Motivo de trabajo SOT';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.IDWF IS 'Id del workflow asociado';

COMMENT ON COLUMN OPERACION.INTERFTELEFONIALOG.ABRIRTAREA IS '0= Comando exitoso, no se abre tarea; 1= Comando falla, abrir tarea.';


