-- Create table
create table OPERACION.IW_CALLFEATURES
(
  IDTRANSACCION   NUMBER,
  IDSERVICIO      VARCHAR2(20),
  IDPRODUCTO      VARCHAR2(20),
  IDVENTA         VARCHAR2(20),
  IDSERVICIOPADRE VARCHAR2(20),
  IDPRODUCTOPADRE VARCHAR2(20),
  IDVENTAPADRE    VARCHAR2(20),
  CFCRMID         VARCHAR2(20),
  CFCMSID         VARCHAR2(20),
  CFNAME          VARCHAR2(50),
  CFSVSUBSCRIBED  VARCHAR2(10),
  CFIWSUBSCRIBED  VARCHAR2(10),
  CFACTIVE        VARCHAR2(10),
  IPAPLICACION    VARCHAR2(30) default SYS_CONTEXT('USERENV','IP_ADDRESS'),
  USUARIOAPP      VARCHAR2(30) default USER,
  FECUSU          DATE default SYSDATE,
  PCAPLICACION    VARCHAR2(50) default SYS_CONTEXT('USERENV', 'TERMINAL')
)
tablespace OPERACION_DAT ;
-- Add comments to the columns 
comment on column OPERACION.IW_CALLFEATURES.IDTRANSACCION
  is 'Ticket de IW';
comment on column OPERACION.IW_CALLFEATURES.IDSERVICIO
  is 'Id Servicio';
comment on column OPERACION.IW_CALLFEATURES.IDPRODUCTO
  is 'Id Producto';
comment on column OPERACION.IW_CALLFEATURES.IDVENTA
  is 'IDVENTA';
comment on column OPERACION.IW_CALLFEATURES.IDSERVICIOPADRE
  is 'Srv Padre';
comment on column OPERACION.IW_CALLFEATURES.IDPRODUCTOPADRE
  is 'Prd Padre';
comment on column OPERACION.IW_CALLFEATURES.IDVENTAPADRE
  is 'Vta Padre';
comment on column OPERACION.IW_CALLFEATURES.CFCRMID
  is 'CFC RMID';
comment on column OPERACION.IW_CALLFEATURES.CFCMSID
  is 'CFC SID';
comment on column OPERACION.IW_CALLFEATURES.CFNAME
  is 'CF NAME';
comment on column OPERACION.IW_CALLFEATURES.CFSVSUBSCRIBED
  is 'CF SV SUBSCRIBED';
comment on column OPERACION.IW_CALLFEATURES.CFIWSUBSCRIBED
  is 'CF IW SUBSCRIBED';
comment on column OPERACION.IW_CALLFEATURES.CFACTIVE
  is 'CF ACTIVE';
comment on column OPERACION.IW_CALLFEATURES.IPAPLICACION
  is 'IP Aplicacion';
comment on column OPERACION.IW_CALLFEATURES.USUARIOAPP
  is 'Usuario APP';
comment on column OPERACION.IW_CALLFEATURES.FECUSU
  is 'Fecha de Registro';
comment on column OPERACION.IW_CALLFEATURES.PCAPLICACION
  is 'PC Aplicacion';
-- Create/Recreate indexes 
create index OPERACION.IDX_IW_CALLFEATURES on OPERACION.IW_CALLFEATURES (IDTRANSACCION)
  tablespace OPERACION_DAT;