-- Create table
create table OPERACION.IW_SOFTSWITCH
(
  IDTRANSACCION          NUMBER,
  SOFTSWITCHTYPE         VARCHAR2(30),
  SOFTSWITCHNAME         VARCHAR2(30),
  SOFTSWITCHCRMID        VARCHAR2(30),
  GATEWAYCONTROLLERNAME  VARCHAR2(30),
  GATEWAYCONTROLLERCRMID VARCHAR2(30),
  IPAPLICACION           VARCHAR2(30) default SYS_CONTEXT('USERENV','IP_ADDRESS'),
  USUARIOAPP             VARCHAR2(30) default USER,
  FECUSU                 DATE default SYSDATE,
  PCAPLICACION           VARCHAR2(50) default SYS_CONTEXT('USERENV', 'TERMINAL')
)
tablespace OPERACION_DAT ;
-- Add comments to the columns 
comment on column OPERACION.IW_SOFTSWITCH.IDTRANSACCION
  is 'Ticket de IW';
comment on column OPERACION.IW_SOFTSWITCH.SOFTSWITCHTYPE
  is 'SOFTSWITCH TYPE';
comment on column OPERACION.IW_SOFTSWITCH.SOFTSWITCHNAME
  is 'SOFTSWITCH NAME';
comment on column OPERACION.IW_SOFTSWITCH.SOFTSWITCHCRMID
  is 'SOFTSWITCH CRMID';
comment on column OPERACION.IW_SOFTSWITCH.GATEWAYCONTROLLERNAME
  is 'GATEWAY CONTROLLER NAME';
comment on column OPERACION.IW_SOFTSWITCH.GATEWAYCONTROLLERCRMID
  is 'GATEWAY CONTROLLER CRMID';
comment on column OPERACION.IW_SOFTSWITCH.IPAPLICACION
  is 'IP Aplicacion';
comment on column OPERACION.IW_SOFTSWITCH.USUARIOAPP
  is 'Usuario APP';
comment on column OPERACION.IW_SOFTSWITCH.FECUSU
  is 'Fecha de Registro';
comment on column OPERACION.IW_SOFTSWITCH.PCAPLICACION
  is 'PC Aplicacion';
-- Create/Recreate indexes 
create index OPERACION.IDX_IW_SOFTSWITCH on OPERACION.IW_SOFTSWITCH (IDTRANSACCION)
  tablespace OPERACION_DAT ;