CREATE TABLE OPERACION.LOG_REG_ARCHIVOS_ENVIADOS
(
  NUMREGENV      VARCHAR2(6 BYTE),
  NUMREGINS      VARCHAR2(10 BYTE),
  FILENAME       VARCHAR2(50 BYTE),
  FECENV         DATE                           DEFAULT sysdate,
  USUARIO        VARCHAR2(50 BYTE)              DEFAULT user,
  LASTNUMREGENV  VARCHAR2(6 BYTE),
  CODIGO_EXT     VARCHAR2(20 BYTE),
  TIPO_PROCESO   CHAR(1 BYTE),
  NUMTRANS       NUMBER(15)                     NOT NULL,
  UNITADDRESS    VARCHAR2(32 BYTE),
  IDTARJETA      VARCHAR2(32 BYTE)
);


