CREATE TABLE OPERACION.LOG_ENV_FILEXBOUQUET
(
  IDLOGENV     NUMBER(15)                       NOT NULL,
  IDTARJETA    VARCHAR2(11 BYTE),
  BOUQUETS     VARCHAR2(500 BYTE),
  CODCLI       CHAR(8 BYTE),
  NOMCLI       VARCHAR2(200 BYTE),
  TIPDOC       CHAR(3 BYTE),
  NUMDOC       VARCHAR2(15 BYTE),
  TELEFONO1    VARCHAR2(20 BYTE),
  CODSOLOT     NUMBER(8),
  NUMSLC       CHAR(10 BYTE),
  IDPAQ        NUMBER(10),
  UNITADDRESS  VARCHAR2(32 BYTE),
  TIPOENVIO    NUMBER,
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user,
  FECREG       DATE                             DEFAULT sysdate,
  NUMREGISTRO  CHAR(10 BYTE)
);


