CREATE TABLE OPERACION.MAESTRO_SERIES_EQU_TXITW
(
  IDALM              NUMBER                     NOT NULL,
  ID_LOTE            NUMBER                     NOT NULL,
  ID_INTERFASE       VARCHAR2(30 BYTE),
  ID_ESTADO          VARCHAR2(30 BYTE),
  ID_PRODUCTO        VARCHAR2(30 BYTE),
  ID_ERROR_ENV       NUMBER,
  ID_ERROR_RSP       NUMBER,
  MENSAJE            VARCHAR2(3200 BYTE),
  SENDTOCONTROLER    VARCHAR2(30 BYTE),
  ID_ACTIVACION      VARCHAR2(32 BYTE),
  MODELO             VARCHAR2(32 BYTE),
  CODIGO_EXT         VARCHAR2(150 BYTE),
  ID_PRODUCTO_PADRE  VARCHAR2(30 BYTE),
  ENVIO              NUMBER,
  ESTADO             NUMBER,
  FLAG               NUMBER(1),
  USUREG             VARCHAR2(30 BYTE)          DEFAULT USER                  NOT NULL,
  FECREG             DATE                       DEFAULT SYSDATE               NOT NULL,
  USUMOD             VARCHAR2(30 BYTE)          DEFAULT USER                  NOT NULL,
  FECMOD             DATE                       DEFAULT SYSDATE               NOT NULL,
  FASE               NUMBER(1)
);

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.IDALM IS 'ID ALMACEN';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_LOTE IS 'ID LOTE DE ENVIO';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_INTERFASE IS 'INTERFACE DE ENVIO A INTRAWAY';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_ESTADO IS 'ESTADO ';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_PRODUCTO IS 'PRODUCTO';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_ERROR_ENV IS 'ID ERROR DE ENVIO';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.ID_ERROR_RSP IS 'ID ERROR DE RESPUESTA';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_TXITW.FASE IS '1: ONPLANT, 2: OFFPLANT';


