CREATE TABLE OPERACION.MAESTRO_SERIES_EQU
(
  COD_SAP        VARCHAR2(20 BYTE),
  NROSERIE       VARCHAR2(100 BYTE),
  CENTRO         VARCHAR2(10 BYTE),
  ALMACEN        VARCHAR2(10 BYTE),
  SA             VARCHAR2(10 BYTE),
  EQUIPO         VARCHAR2(10 BYTE),
  IDALM          NUMBER                         NOT NULL,
  CODUSU         VARCHAR2(30 BYTE)              DEFAULT user,
  FECUSU         DATE                           DEFAULT sysdate,
  FLG_PROCESO    NUMBER                         DEFAULT 1,
  DESPACHADO     NUMBER                         DEFAULT 0,
  MAC1           VARCHAR2(30 BYTE),
  MAC2           VARCHAR2(30 BYTE),
  MAC3           VARCHAR2(30 BYTE),
  MAC4           VARCHAR2(30 BYTE),
  MAC5           VARCHAR2(30 BYTE),
  DISPONIBLE     NUMBER,
  MODELOEQUITW   VARCHAR2(150 BYTE),
  ESTADOITW      NUMBER(2),
  FECUSUMOD      DATE,
  CODUSUMOD      VARCHAR2(30 BYTE),
  ID_PRODUCTO    VARCHAR2(30 BYTE),
  FASE           NUMBER(1),
  ID_ACTIVACION  VARCHAR2(32 BYTE)
);

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.COD_SAP IS 'Codigo SAP';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.NROSERIE IS 'Numero de Serie';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.CENTRO IS 'Centro';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.ALMACEN IS 'Almacen';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.SA IS 'Tipo de Stock';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.EQUIPO IS 'Equipo';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.IDALM IS 'Identificador PK Tabla';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.CODUSU IS 'Usuario que registro';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.FLG_PROCESO IS '1 Se proceso , 0 : Cargado inicialmente';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.DESPACHADO IS '1 Se esta usando, 0 : Disponible';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MAC1 IS 'Mac 1';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MAC2 IS 'Mac 2';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MAC3 IS 'Mac 3';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MAC4 IS 'Mac 4';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MAC5 IS 'Mac5';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.MODELOEQUITW IS 'Modelo que maneja el Intraway';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.ESTADOITW IS 'Estado del Preaprovisionamiento';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.FECUSUMOD IS 'Fecha de Modificación';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.CODUSUMOD IS 'Usuario de Modificación';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU.ID_PRODUCTO IS 'Producto para intraway';


