CREATE TABLE OPERACION.MAESTRO_STOCK_MAT
(
  IDALM          NUMBER                         NOT NULL,
  COD_SAP        NUMBER,
  CENTRO         VARCHAR2(4 BYTE),
  ALMACEN        VARCHAR2(4 BYTE),
  CANTTOTALPROC  NUMBER,
  CANTCONSUMIDA  NUMBER,
  CANTIDAD       NUMBER,
  TRANSACCION    NUMBER,
  OPERADOR       NUMBER,
  UNIDAD         VARCHAR2(10 BYTE),
  CODUSU         VARCHAR2(30 BYTE)              DEFAULT user,
  FECUSU         DATE                           DEFAULT sysdate
);

COMMENT ON TABLE OPERACION.MAESTRO_STOCK_MAT IS 'Tabla consolidado de Material por Contrata,Almacen y Material';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.IDALM IS 'Identificador PK Tabla';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.COD_SAP IS 'Código SAP';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.CENTRO IS 'Centro';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.ALMACEN IS 'Almacen';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.CANTIDAD IS 'Cantidad de Material en Almacén descargado de SAP';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.OPERADOR IS 'Código de Centro Almacén';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.UNIDAD IS 'Unidad de Medida';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.CODUSU IS 'Usuario que registro';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.TRANSACCION IS 'Ticket para transacción';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.CANTTOTALPROC IS 'Cantidad Total a Procesar';

COMMENT ON COLUMN OPERACION.MAESTRO_STOCK_MAT.CANTCONSUMIDA IS 'Cantidad Consumida durante el proceso de descarga';


