--tabla con todos los clientes que deberian migrar generados en SGA HFC Masivos
create table OPERACION.MIGRT_DATAPRINC
(
  datan_id              NUMBER not null,
  datac_tipo_persona    CHAR(1),
  datac_codcli          CHAR(8),
  datav_nomabr          VARCHAR2(200),
  datav_nomcli          VARCHAR2(200),
  datav_apepat          VARCHAR2(50),
  datav_apemat          VARCHAR2(50),
  datac_tipdoc          CHAR(3),
  datav_descdoc         VARCHAR2(10),
  datav_numdoc          VARCHAR2(15),
  datad_fecnac          DATE,
  datad_fechaini        DATE,
  datad_fechafin        DATE,
  datav_emailprinc      VARCHAR2(200),
  datav_email1          VARCHAR2(200),
  datav_email2          VARCHAR2(200),
  datac_tipsrv          CHAR(4),
  datav_desctipsrv      VARCHAR2(50),
  datan_codcamp         NUMBER(6),
  datav_descamp         VARCHAR2(200),
  datan_codplazo        NUMBER(4),
  datav_descplazo       VARCHAR2(80),
  datan_idsolucion      NUMBER(10),
  datav_solucion        VARCHAR2(100),
  datan_idpaq           NUMBER(10),
  datav_paquete         VARCHAR2(4000),
  datac_tipprod         CHAR(4),
  datav_desctipprod     VARCHAR2(50),
  datan_idprod          NUMBER(10),
  datav_prod            VARCHAR2(100),
  datav_eq_prod_sisact  VARCHAR2(4),
  datac_codsrv          CHAR(4),
  datav_servicio        VARCHAR2(50),
  datav_eq_serv_sisact  VARCHAR2(4),
  datav_descplan        VARCHAR2(200),
  datav_tiposervicio    VARCHAR2(50),
  datan_idestserv       NUMBER(2),
  datav_descestserv     VARCHAR2(100),
  datan_idtipinss       NUMBER(2),
  datav_tipinss         VARCHAR2(100),
  datan_codinssrv       NUMBER(10),
  datan_pid             NUMBER(10),
  datan_idmarcaequipo   NUMBER(2),
  datav_marcaequipo     VARCHAR2(50),
  datac_codtipequ       CHAR(15),
  datan_tipequ          NUMBER(6),
  datav_tipo_equipo     VARCHAR2(100),
  datav_equ_tipo        VARCHAR2(30),
  datac_cod_equipo      CHAR(4),
  datav_modelo_equipo   VARCHAR2(200),
  datav_tipo            VARCHAR2(10),
  datav_numero          VARCHAR2(20),
  datan_control         NUMBER(1) default 0,
  datac_idproyecto      CHAR(10),
  datav_play            VARCHAR2(10),
  datan_cargofijo       NUMBER(18,4),
  datan_cantidad        NUMBER(10),
  datac_publicar        CHAR(2),
  datan_idciclo         NUMBER(5),
  datav_desciclo        VARCHAR2(100),
  datan_bw              NUMBER(10,2),
  datan_cidventa        NUMBER(10),
  datac_codsucursal     CHAR(10),
  datac_codubigeo       CHAR(10),
  datav_dirventa        VARCHAR2(480),
  datav_codposventa     VARCHAR2(30),
  datav_descventa       VARCHAR2(100),
  datac_cod_ev          CHAR(8),
  datac_idtipdoc_ev     CHAR(3),
  datav_tipdoc_ev       VARCHAR2(10),
  datav_numdoc_ev       VARCHAR2(15),
  datav_nom_ev          VARCHAR2(60),
  datac_idtipven        CHAR(2),
  datav_tipven          VARCHAR2(50),
  datav_idcont          VARCHAR2(15),
  datan_nrocart         NUMBER(15),
  datac_codope          CHAR(2),
  datav_operador        VARCHAR2(30),
  datan_presus          NUMBER(1),
  datan_publi           NUMBER(1),
  datan_idtipenvio      NUMBER,
  datav_tipenvio        VARCHAR2(100),
  datav_corelec         VARCHAR2(100),
  datav_iddep_dircli    VARCHAR2(3),
  datac_idprov_dircli   CHAR(3),
  datac_iddist_dircli   CHAR(3),
  datav_depa_dircli     VARCHAR2(40),
  datav_prov_dircli     VARCHAR2(40),
  datav_dist_dircli     VARCHAR2(40),
  datav_dircli          VARCHAR2(480),
  datac_codubidir       CHAR(10),
  datac_ubigeodir       CHAR(6),
  datac_idtipoviadir    CHAR(2),
  datav_tipoviadir      VARCHAR2(30),
  datav_nomviadir       VARCHAR2(60),
  datav_numviadir       VARCHAR2(50),
  datan_idtipodomidir   NUMBER(2),
  datav_tipodomidir     VARCHAR2(50),
  datav_nomurbdir       VARCHAR2(50),
  datan_idzonadir       NUMBER(3),
  datav_zonadir         VARCHAR2(50),
  datav_referenciadir   VARCHAR2(340),
  datav_telf1dir        VARCHAR2(50),
  datav_telf2dir        VARCHAR2(50),
  datav_codposdir       VARCHAR2(20),
  datav_manzanadir      VARCHAR2(5),
  datav_lotedir         VARCHAR2(5),
  datav_sectordir       VARCHAR2(5),
  datan_codedifdir      NUMBER(8),
  datav_edificdir       VARCHAR2(50),
  datan_pisodir         NUMBER,
  datav_interiordir     VARCHAR2(60),
  datav_num_interiordir VARCHAR2(15),
  datav_idplanodir      VARCHAR2(10),
  datav_planodir        VARCHAR2(100),
  datav_iddepi          VARCHAR2(3),
  datac_idprovi         CHAR(3),
  datac_iddisti         CHAR(3),
  datav_departamentoi   VARCHAR2(40),
  datav_provinciai      VARCHAR2(40),
  datav_distritoi       VARCHAR2(40),
  datav_dirsuci         VARCHAR2(1000),
  datav_nomsuci         VARCHAR2(100),
  datac_ubisuci         CHAR(10),
  datac_ubigeoi         CHAR(6),
  datac_idtipoviai      CHAR(2),
  datav_tipoviai        VARCHAR2(30),
  datav_nomviai         VARCHAR2(60),
  datav_numviai         VARCHAR2(50),
  datan_idtipodomii     NUMBER(2),
  datav_tipodomii       VARCHAR2(50),
  datan_idtipurbi       NUMBER(4),
  datav_nomurbi         VARCHAR2(50),
  datan_idzonai         NUMBER(3),
  datav_zonai           VARCHAR2(50),
  datav_referenciai     VARCHAR2(340),
  datav_telf1i          VARCHAR2(50),
  datav_telf2i          VARCHAR2(50),
  datav_codposi         VARCHAR2(20),
  datav_manzanai        VARCHAR2(5),
  datav_lotei           VARCHAR2(5),
  datav_sectori         VARCHAR2(5),
  datan_codedifi        NUMBER(8),
  datav_edificioi       VARCHAR2(50),
  datan_pisoi           NUMBER(3),
  datav_interiori       VARCHAR2(60),
  datav_num_interiori   VARCHAR2(15),
  datav_idplanoi        VARCHAR2(10),
  datav_planoi          VARCHAR2(100),
  datav_iddepf          VARCHAR2(3),
  datac_idprovf         CHAR(3),
  datac_iddistf         CHAR(3),
  datav_departamentof   VARCHAR2(40),
  datav_provinciaf      VARCHAR2(40),
  datav_distritof       VARCHAR2(40),
  datav_dirsucf         VARCHAR2(1000),
  datav_nomsucf         VARCHAR2(100),
  datac_ubisucf         CHAR(10),
  datac_ubigeof         CHAR(6),
  datac_idtipoviaf      CHAR(2),
  datav_tipoviaf        VARCHAR2(30),
  datav_nomviaf         VARCHAR2(60),
  datav_numviaf         VARCHAR2(50),
  datan_idtipodomif     NUMBER(2),
  datav_tipodomif       VARCHAR2(50),
  datan_idtipurbf       NUMBER(4),
  datav_nomurbf         VARCHAR2(50),
  datan_idzonaf         NUMBER(3),
  datav_zonaf           VARCHAR2(50),
  datav_referenciaf     VARCHAR2(340),
  datav_telf1f          VARCHAR2(50),
  datav_telf2f          VARCHAR2(50),
  datav_codposf         VARCHAR2(20),
  datav_manzanaf        VARCHAR2(5),
  datav_lotef           VARCHAR2(5),
  datav_sectorf         VARCHAR2(5),
  datan_codediff        NUMBER(8),
  datav_edificiof       VARCHAR2(50),
  datan_pisof           NUMBER(3),
  datav_interiorf       VARCHAR2(60),
  datav_num_interiorf   VARCHAR2(15),
  datav_idplanof        VARCHAR2(10),
  datav_planof          VARCHAR2(100),
  datan_solotactv       NUMBER(8),
  datai_tipoagenda      INTEGER,
  datai_prerequisito    INTEGER default 0,
  datai_blacklistcli    INTEGER default 0,
  datai_blacklistplan   INTEGER default 0,
  datai_procesado       INTEGER default 0,
  datad_fecproceso      DATE,
  datan_codsotbajaadm   NUMBER(8),
  datan_estsotbaja      NUMBER(2),
  datan_codsolot        NUMBER(8),
  datan_estsotalta      NUMBER(2),
  datan_cod_id          NUMBER,
  datan_customer_id     NUMBER,
  datan_numsec          NUMBER(20),
  datac_estsec          CHAR(2),
  datai_procsisact      INTEGER default 0,
  datad_fecprocsisact   DATE,
  datai_procagensga     INTEGER default 0,
  datad_fecprocagensga  DATE,
  datai_prociw          INTEGER default 0,
  datad_fecprociw       DATE
)
tablespace OPERACION_DAT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );   

comment on column OPERACION.MIGRT_DATAPRINC.DATAN_ID
  is 'IDENTIFICADOR DE LA TABLA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_TIPO_PERSONA
  is 'TIPO DE PERSONA DEL CLIENTE: N NATURAL, J JURIDICA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODCLI
  is 'ID DEL CLIENTE CODCLI';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMABR
  is 'NOMBRE ABREVIADO DEL CLIENTE';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMCLI
  is 'NOMBRE DEL CLIENTE';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_APEPAT
  is 'APELLIDO PATERNO DEL CLIENTE'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_APEMAT
  is 'APELLIDO MATERNO DEL CLIENTE'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_TIPDOC
  is 'ID DE TIPO DE DOCUMENTO TIPDIDE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCDOC
  is 'TIPO DE DOCUMENTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMDOC
  is 'NUMERO DE DOCUMENTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECNAC
  is 'FECHA DE NACIMIENTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECHAINI
  is 'FECHA DE INICIO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECHAFIN
  is 'FECHA DE FIN';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EMAILPRINC
  is 'EMAIL PRINCIPAL';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EMAIL1
  is 'EMAIL1';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EMAIL2
  is 'EMAIL2';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_TIPSRV
  is 'ID DE FAMILIA DE SERVICIO DEL PROYECTO TIPSRV';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCTIPSRV
  is 'FAMILIA DE SERVICIO DEL PROYECTO'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODCAMP
  is 'ID DE CAMPAÑA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCAMP
  is 'CAMPAÑA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODPLAZO
  is 'ID DEL PLAZO';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCPLAZO
  is 'PLAZO'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDSOLUCION
  is 'ID DE SOLUCION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_SOLUCION
  is 'SOLUCION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDPAQ
  is 'ID DE PAQUETE IDPAQ';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PAQUETE
  is 'PAQUETE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_TIPPROD
  is 'ID DE FAMILIA DE PRODUCTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCTIPPROD
  is 'FAMILIA DE PRODUCTO';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDPROD
  is 'ID DE PRODUCTO IDPRODUCTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PROD
  is 'PRODUCTO';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EQ_PROD_SISACT
  is 'EQUIVALENTE DEL PRODUCTO EN SISACT';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODSRV
  is 'ID DE SERVICIO/PLAN CODSRV'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_SERVICIO
  is 'SERVICIO/EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EQ_SERV_SISACT
  is 'EQUIVALENTE DEL SERVICIO EN SISACT';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCPLAN
  is 'DESCRIPCION DEL PLAN';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPOSERVICIO
  is 'TIPO DE SERVICIO';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDESTSERV
  is 'ID DE ESTADO DE SERVICIO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCESTSERV
  is 'ESTADO DE SERVICIO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPINSS
  is 'ID DE TIPO DE INSTANCIA DE SERVICIO TIPINSSRV';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPINSS
  is 'TIPO DE INSTANCIA DE SERVICIO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODINSSRV
  is 'ID DE INSTANCIA DE SERVICIO CODINSSRV';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PID
  is 'ID DE INSTANCIA DE PRODUCTO PID';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDMARCAEQUIPO
  is 'ID DE MARCA DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_MARCAEQUIPO
  is 'MARCA DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODTIPEQU
  is 'CODIGO DE TIPO DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_TIPEQU
  is 'CODIGO DE TIPO DE EQUIPO2';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPO_EQUIPO
  is 'TIPO DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EQU_TIPO
  is 'CLASE DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_COD_EQUIPO
  is 'CODIGO DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_MODELO_EQUIPO
  is 'MODELO DE EQUIPO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPO
  is 'TIPO: SERVICIO O EQUIPO';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMERO
  is 'NUMERO';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CONTROL
  is 'ES LINEA CONTROL';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDPROYECTO
  is 'CODIGO DE PROYECTO NUMSLC';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PLAY
  is 'TIPO DE PLAY';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CARGOFIJO
  is 'CARGO FIJO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CANTIDAD
  is 'CANTIDAD';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_PUBLICAR
  is 'SE DEBE PUBLICAR EN LINEAS BLANCAS: Si/No';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDCICLO
  is 'ID DE CICLO DE FACTURACION CICFAC';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCICLO
  is 'CICLO DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_BW
  is 'ANCHO DE BANDA BW';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CIDVENTA
  is 'CIRCUITO ID CID';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODSUCURSAL
  is 'ID DE SUCURSAL CODSUC ASOCIADO A LA VENTA';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODUBIGEO
  is 'ID DE UBIGEO CODUBI ASOCIADO A LA VENTA';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DIRVENTA
  is 'DIRECCION DEL CLIENTE ASOCIADO A LA VENTA';                
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_CODPOSVENTA
  is 'CODIGO POSTAL ASOCIADO A LA VENTA';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DESCVENTA
  is 'DESCRIPCION DE LA VENTA';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_COD_EV
  is 'CODIGO DEL CONSULTOR O AGENTE DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDTIPDOC_EV
  is 'ID DEL TIPO DE DOCUMENTO DEL VENDEDOR O EJECUTIVO DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPDOC_EV
  is 'TIPO DE DOCUMENTO DEL CONSULTOR O AGENTE DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMDOC_EV
  is 'NUMERO DE DOCUMENTO DEL CONSULTOR O AGENTE DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOM_EV
  is 'CONSULTOR O AGENTE DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDTIPVEN
  is 'ID DEL TIPO DE VENTA O DE DOCUMENTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPVEN
  is 'TIPO DE VENTA O DE DOCUMENTO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDCONT
  is 'NUMERO DEL DOCUMENTO DE VENTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_NROCART
  is 'CARTA DE LA PRESUSCRIPCION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODOPE
  is 'ID DEL OPERADOR DE LA PRESUSCRIPCION  EN SGA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_OPERADOR
  is 'OPERADOR DE LA PRESUSCRIPCION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PRESUS
  is 'FLAG PRESUSCRIPCION';              
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PUBLI
  is 'PUBLICAR CONTRATO';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPENVIO
  is 'ID DEL TIPO DE ENVIO';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPENVIO
  is 'TIPO DE ENVIO DEL RECIBO';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_CORELEC
  is 'CORREO ELECTRONICO A ENVIAR';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDDEP_DIRCLI
  is 'ID DEL DEPARTAMENTO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDPROV_DIRCLI
  is 'ID DE LA PROVINCIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDDIST_DIRCLI
  is 'ID DEL DISTRITO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DEPA_DIRCLI
  is 'DEPARTAMENTO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PROV_DIRCLI
  is 'PROVINCIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DIST_DIRCLI
  is 'DISTRITO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DIRCLI
  is 'DIRECCION DEL CLIENTE';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_CODUBIDIR
  is 'ID DEL UBIGEO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_UBIGEODIR
  is 'UBIGEO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDTIPOVIADIR
  is 'ID DEL TIPO DE VIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPOVIADIR
  is 'TIPO DE VIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMVIADIR
  is 'NOMBRE DE LA VIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMVIADIR
  is 'NUMERO DE LA VIA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPODOMIDIR
  is 'ID DEL TIPO DE DOMICILIO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPODOMIDIR
  is 'TIPO DE DOMICILIO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMURBDIR
  is 'URBANIZACION DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDZONADIR
  is 'ID DE  LA ZONA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_ZONADIR
  is 'ZONA DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_REFERENCIADIR
  is 'REFERENCIA DEL DOMICILIO DE LA DIRECCION DEL CLIENTE';                          
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF1DIR
  is 'TELEFONO1 DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF2DIR
  is 'TELEFONO2 DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_CODPOSDIR
  is 'CODIGO POSTAL DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_MANZANADIR
  is 'MANZANA DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_LOTEDIR
  is 'LOTE DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_SECTORDIR
  is 'SECTOR DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODEDIFDIR
  is 'ID DE EDIFICIO DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EDIFICDIR
  is 'EDIFICIO DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PISODIR
  is 'PISO DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_INTERIORDIR
  is 'INTERIOR DE LA DIRECCION DEL CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUM_INTERIORDIR
  is 'NUMERO DE INTERIOR DE LA DIRECCION DEL CLIENTE';                    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDPLANODIR
  is 'ID DE PLANO DE LA DIRECCION DEL CLIENTE';    
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PLANODIR
  is 'PLANO DE LA DIRECCION DEL CLIENTE';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDDEPI
  is 'ID DEL DEPARTAMENTO DE LA SUCURSAL DE INSTALACION';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDPROVI
  is 'ID DE LA PROVINCIA DE LA SUCURSAL DE INSTALACION';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDDISTI
  is 'ID DEL DISTRITO DE LA SUCURSAL DE INSTALACION';        
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DEPARTAMENTOI
  is 'DEPARTAMENTO DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PROVINCIAI
  is 'PROVINCIA DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DISTRITOI
  is 'DISTRITO DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DIRSUCI
  is 'DIRECCION DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMSUCI
  is 'NOMBRE DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_UBISUCI
  is 'ID DEL UBIGEO DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_UBIGEOI
  is 'UBIGEO DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDTIPOVIAI
  is 'ID DEL TIPO DE VIA DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPOVIAI
  is 'TIPO DE VIA DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMVIAI
is 'NOMBRE DE LA VIA DE LA SUCURSAL DE INSTALACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMVIAI
is 'NUMERO DE LA VIA DE LA SUCURSAL DE INSTALACION';          
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPODOMII
is 'ID DEL TIPO DE DOMICILIO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPODOMII
is 'TIPO DE DOMICILIO DE LA SUCURSAL DE INSTALACION'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPURBI
is 'ID DEL TIPO DE URBANIZACION DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMURBI
is 'URBANIZACION DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDZONAI
is 'ID DE  LA ZONA DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_ZONAI
is 'ZONA DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_REFERENCIAI
is 'REFERENCIA DEL DOMICILIO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF1I
is 'TELEFONO1 DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF2I
is 'TELEFONO2 DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_CODPOSI
is 'CODIGO POSTAL DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_MANZANAI
is 'MANZANA DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_LOTEI
is 'LOTE DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_SECTORI
is 'SECTOR DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODEDIFI
is 'ID DE EDIFICIO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EDIFICIOI
is 'EDIFICIO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PISOI
is 'PISO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_INTERIORI
is 'INTERIOR DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUM_INTERIORI
is 'NUMERO DE INTERIOR DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDPLANOI
is 'ID DE PLANO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PLANOI
is 'PLANO DE LA SUCURSAL DE INSTALACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDDEPF
  is 'ID DEL DEPARTAMENTO DE LA SUCURSAL DE FACTURACION';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDPROVF
  is 'ID DE LA PROVINCIA DE LA SUCURSAL DE FACTURACION';      
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDDISTF
  is 'ID DEL DISTRITO DE LA SUCURSAL DE FACTURACION';        
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DEPARTAMENTOF
  is 'DEPARTAMENTO DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PROVINCIAF
  is 'PROVINCIA DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DISTRITOF
  is 'DISTRITO DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_DIRSUCF
  is 'DIRECCION DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMSUCF
  is 'NOMBRE DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_UBISUCF
  is 'ID DEL UBIGEO DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_UBIGEOF
  is 'UBIGEO DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_IDTIPOVIAF
  is 'ID DEL TIPO DE VIA DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPOVIAF
  is 'TIPO DE VIA DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMVIAF
is 'NOMBRE DE LA VIA DE LA SUCURSAL DE FACTURACION';
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUMVIAF
is 'NUMERO DE LA VIA DE LA SUCURSAL DE FACTURACION';          
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPODOMIF
is 'ID DEL TIPO DE DOMICILIO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TIPODOMIF
is 'TIPO DE DOMICILIO DE LA SUCURSAL DE FACTURACION'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDTIPURBF
is 'ID DEL TIPO DE URBANIZACION DE LA SUCURSAL DE FACTURACION';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NOMURBF
is 'URBANIZACION DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_IDZONAF
is 'ID DE  LA ZONA DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_ZONAF
is 'ZONA DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_REFERENCIAF
is 'REFERENCIA DEL DOMICILIO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF1F
is 'TELEFONO1 DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_TELF2F
is 'TELEFONO2 DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_CODPOSF
is 'CODIGO POSTAL DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_MANZANAF
is 'MANZANA DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_LOTEF
is 'LOTE DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_SECTORF
is 'SECTOR DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODEDIFF
is 'ID DE EDIFICIO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_EDIFICIOF
is 'EDIFICIO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_PISOF
is 'PISO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_INTERIORF
is 'INTERIOR DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_NUM_INTERIORF
is 'NUMERO DE INTERIOR DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_IDPLANOF
is 'ID DE PLANO DE LA SUCURSAL DE FACTURACION';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAV_PLANOF
is 'PLANO DE LA SUCURSAL DE FACTURACION'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_SOLOTACTV
  is 'ULTIMA SOT ACTIVA DEL CLIENTE GENERADO DESDE EL SGA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_TIPOAGENDA
is 'TIPO DE AGENDAMIENTO: 1 POR CAMPO O VISITA, 2 POR SISTEMA';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_PREREQUISITO
  is 'APRUEBA PREREQUISITO';
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_BLACKLISTCLI
  is 'NO PROCESAR CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_BLACKLISTPLAN
  is 'NO PROCESAR PLAN DE CLIENTE';
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_PROCESADO
  is 'PROCESO EXITOSO DE LA BAJA ADMINISTRATIVA EN SGA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECPROCESO
  is 'FECHA DEL PROCESO EXITOSO DE LA BAJA ADMINISTRATIVA EN SGA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODSOTBAJAADM
  is 'SOT DE BAJA ADMINISTRATIVA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_ESTSOTBAJA
  is 'ESTADO DE LA SOT DE BAJA ADMINISTRATIVA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CODSOLOT
  is 'SOT DE ALTA GENERADO DESDE EL SISACT';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_ESTSOTALTA
  is 'ESTADO DE LA SOT DE ALTA';  
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_COD_ID
  is 'CODIGO DE CONTRATO GENERADO DESDE EL SISACT DURANTE LA ALTA';
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_CUSTOMER_ID
  is 'CODIGO DE CLIENTE GENERADO DESDE EL SISACT DURANTE LA ALTA';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAN_NUMSEC
  is 'ID DEL REGISTRO DE LA VENTA DEL SERVICIO GENERADO DESDE EL SISACT DURANTE LA ALTA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAC_ESTSEC
  is 'ESTADO DEL REGISTRO DE LA VENTA DEL SERVICIO GENERADO DESDE EL SISACT DURANTE LA ALTA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_PROCSISACT
  is 'PROCESO EXITOSO EN SISACT'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECPROCSISACT
  is 'FECHA DEL PROCESO EXITOSO EN SISACT'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_PROCAGENSGA
  is 'PROCESO EXITOSO DEL AGENDAMIENTO EN SGA'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECPROCAGENSGA
  is 'FECHA DEL PROCESO EXITOSO DEL AGENDAMIENTO EN SGA';   
comment on column OPERACION.MIGRT_DATAPRINC.DATAI_PROCIW
  is 'PROCESO EXITOSO DEL AGENDAMIENTO EN INTRAWAY'; 
comment on column OPERACION.MIGRT_DATAPRINC.DATAD_FECPROCIW
  is 'FECHA DEL PROCESO EXITOSO DEL AGENDAMIENTO EN INTRAWAY';         
  
alter table OPERACION.MIGRT_DATAPRINC
  add constraint PK_MIGRT_DATAN_ID primary key (DATAN_ID)
  using index 
  tablespace OPERACION_DAT
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
