CREATE TABLE OPERACION.MIGRACION_CDMA
(
  IMSI        NUMBER,
  ESN         VARCHAR2(40 BYTE),
  AKEY        VARCHAR2(40 BYTE),
  MODELO      VARCHAR2(40 BYTE),
  NUMERO      VARCHAR2(40 BYTE),
  ESTADO      VARCHAR2(40 BYTE),
  TIPO        VARCHAR2(40 BYTE),
  ESTADO_REG  NUMBER(1)                         DEFAULT 0,
  MENSAJE     VARCHAR2(4000 BYTE),
  CODSOLOT    NUMBER,
  CODINSSRV   NUMBER
);

COMMENT ON COLUMN OPERACION.MIGRACION_CDMA.ESTADO_REG IS '0 - cargado, 1-ok , 2 - error';


