CREATE TABLE OPERACION.OMMEMORIA
(
  CODOM        NUMBER(8)                        NOT NULL,
  CODOT        NUMBER(8)                        NOT NULL,
  ORDEN        NUMBER(8)                        NOT NULL,
  NUMSLC       CHAR(10 BYTE),
  FECEMI       DATE,
  CODCLI       CHAR(10 BYTE),
  CODINSSRV    NUMBER(10),
  CODUSU       CHAR(30 BYTE)                    DEFAULT USER,
  FECUSU       DATE                             DEFAULT sysdate,
  OBSERVACION  VARCHAR2(500 BYTE),
  TIPO         NUMBER(2),
  TEXTO_A      VARCHAR2(2000 BYTE),
  TEXTO_B      VARCHAR2(2000 BYTE),
  TEXTO_C      VARCHAR2(2000 BYTE),
  TEXTO_D      VARCHAR2(2000 BYTE),
  DESCRIPCION  VARCHAR2(4000 BYTE),
  DIRECOBRA    VARCHAR2(480 BYTE),
  DISTOBRA     VARCHAR2(50 BYTE),
  CONTROL      NUMBER(6),
  FECEJE       DATE,
  POP          NUMBER(10),
  ESTOM        NUMBER(2),
  CODPRE       NUMBER(8),
  IDUBI        NUMBER(10),
  SUBTIPO      NUMBER(2)
);

COMMENT ON TABLE OPERACION.OMMEMORIA IS 'No es usada';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODOM IS 'Codigo de la orden de mantenimiento';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODOT IS 'Codigo de la orden de trabajo';

COMMENT ON COLUMN OPERACION.OMMEMORIA.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.OMMEMORIA.NUMSLC IS 'Numero de proyecto';

COMMENT ON COLUMN OPERACION.OMMEMORIA.FECEMI IS 'Fecha de emision';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODINSSRV IS 'Codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.OMMEMORIA.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.OMMEMORIA.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.OMMEMORIA.TIPO IS 'Tipo de la orden de mantenimiento';

COMMENT ON COLUMN OPERACION.OMMEMORIA.TEXTO_A IS 'Texto A';

COMMENT ON COLUMN OPERACION.OMMEMORIA.TEXTO_B IS 'Texto B';

COMMENT ON COLUMN OPERACION.OMMEMORIA.TEXTO_C IS 'Texto C';

COMMENT ON COLUMN OPERACION.OMMEMORIA.TEXTO_D IS 'Texto D';

COMMENT ON COLUMN OPERACION.OMMEMORIA.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.OMMEMORIA.DIRECOBRA IS 'Direccion de la obra';

COMMENT ON COLUMN OPERACION.OMMEMORIA.DISTOBRA IS 'Distrito de la obra';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CONTROL IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.OMMEMORIA.FECEJE IS 'Fecha de ejecución';

COMMENT ON COLUMN OPERACION.OMMEMORIA.POP IS 'Pop';

COMMENT ON COLUMN OPERACION.OMMEMORIA.ESTOM IS 'Estado de la orden de mantenimiento';

COMMENT ON COLUMN OPERACION.OMMEMORIA.CODPRE IS 'Codigo de la solcitud de ot';

COMMENT ON COLUMN OPERACION.OMMEMORIA.IDUBI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.OMMEMORIA.SUBTIPO IS 'Sub tipo de la orden de mantenimiento';


