CREATE TABLE OPERACION.OPE_SOT_BAJA_ALTA_REL
(
  CODSOLOT_BAJA      NUMBER(8)                  NOT NULL,
  CODSOLOT_ALTA_OLD  NUMBER(8)                  NOT NULL,
  CODSOLOT_ALTA_NEW  NUMBER(8)                  NOT NULL,
  NUMSLC_BAJA        CHAR(10 BYTE),
  NUMSLC_ALTA        CHAR(10 BYTE),
  USUREG             VARCHAR2(30 BYTE)          DEFAULT user,
  FECREG             DATE                       DEFAULT sysdate,
  USUMOD             VARCHAR2(30 BYTE)          DEFAULT user,
  FECMOD             DATE                       DEFAULT sysdate
);

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.CODSOLOT_BAJA IS 'Sot de Baja';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.CODSOLOT_ALTA_OLD IS 'Sot de Alta OLD';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.FECREG IS 'Fecha que inserto el registro';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.USUMOD IS 'Usuario que modificó el registro';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.FECMOD IS 'Fecha que se modificó el registro';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.NUMSLC_BAJA IS 'Proyecto de Baja';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.NUMSLC_ALTA IS 'Proyecto de Alta';

COMMENT ON COLUMN OPERACION.OPE_SOT_BAJA_ALTA_REL.CODSOLOT_ALTA_NEW IS 'Sot de Alta NEW';


