CREATE TABLE OPERACION.OPE_MATRIZ_APROBACION_RES_MAE
(
  IDMATRIZ        NUMBER(10)                    NOT NULL,
  AREA_EJEC       NUMBER(4)                     NOT NULL,
  IDTIPO          NUMBER(5)                     NOT NULL,
  AREA_RESP       NUMBER(4)                     NOT NULL,
  USU_JEFE_APROB  VARCHAR2(30 BYTE),
  USU_APROB       VARCHAR2(30 BYTE)             NOT NULL,
  ESTADO          NUMBER(4)                     DEFAULT 1,
  USUREG          VARCHAR2(30 BYTE)             DEFAULT USER,
  FECREG          DATE                          DEFAULT SYSDATE,
  USUMOD          VARCHAR2(30 BYTE)             DEFAULT USER,
  FECMOD          DATE                          DEFAULT SYSDATE,
  USU_ADM_REC     VARCHAR2(30 BYTE),
  CORREO          VARCHAR2(1000 BYTE)
);

COMMENT ON TABLE OPERACION.OPE_MATRIZ_APROBACION_RES_MAE IS 'Registra las matrices de aprobación de restricciones de activación';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.IDMATRIZ IS 'Identificador de la matriz de aprobación';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.AREA_EJEC IS 'Area ejecutora';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.IDTIPO IS 'Tipo de Restricción';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.AREA_RESP IS 'Area responsable';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.USU_JEFE_APROB IS 'Jefe de usuario aprobador';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.USU_APROB IS 'Usuario aprobador';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.ESTADO IS 'Estado de la matriz de aprobación';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.FECREG IS 'Fecha que inserto el registro';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.USUMOD IS 'Usuario que modificó el registro';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.FECMOD IS 'Fecha que se modificó el registro';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.USU_ADM_REC IS 'Usuario administrador de solicitudes rechazadas';

COMMENT ON COLUMN OPERACION.OPE_MATRIZ_APROBACION_RES_MAE.CORREO IS 'Correo al cual se notificará las solicitudes rechazadas';


