CREATE TABLE OPERACION.OPE_RESUMEN_PUERTA
(
  CODCLI           CHAR(8 BYTE)                 NOT NULL,
  NOMCLI           VARCHAR2(150 BYTE)           NOT NULL,
  CID              NUMBER(10),
  SID              NUMBER(10)                   NOT NULL,
  DESITM           VARCHAR2(1000 BYTE),
  BANWID           NUMBER(10),
  FACTURA          CHAR(12 BYTE),
  NUMITM           CHAR(4 BYTE),
  FECINIFAC        DATE,
  FECCORFAC        DATE,
  FECEMI           DATE,
  TIPO_SERVICIO    VARCHAR2(50 BYTE),
  PRODUCTO         VARCHAR2(100 BYTE),
  CANTIDAD_FAC     NUMBER(10),
  SUCURSAL         VARCHAR2(100 BYTE),
  DIRECCION        VARCHAR2(480 BYTE),
  DOLARES_CID      NUMBER,
  DOLARES_FACTURA  NUMBER,
  SITE             VARCHAR2(100 BYTE)
);


