CREATE TABLE OPERACION.OPE_PARAMETROS_GLOBALES_AUX
(
  NOMBRE_PARAMETRO  VARCHAR2(250 BYTE)          NOT NULL,
  VALORPARAMETRO    VARCHAR2(2000 BYTE),
  DESCRIPCION       VARCHAR2(2000 BYTE),
  USUREG            VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  FECREG            DATE                        DEFAULT SYSDATE               NOT NULL,
  USUMOD            VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  FECMOD            DATE                        DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.OPE_PARAMETROS_GLOBALES_AUX IS 'Para para configuracion de parametros globales';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.NOMBRE_PARAMETRO IS 'Nombre del parametro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.VALORPARAMETRO IS 'Valor parametro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.DESCRIPCION IS 'Texto explicativo de la funcionalidad del parametro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.USUREG IS 'Usuario que creo el registro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.FECREG IS 'Fecha de creacion del registro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.USUMOD IS 'Usuario que modifico el registro';

COMMENT ON COLUMN OPERACION.OPE_PARAMETROS_GLOBALES_AUX.FECMOD IS 'Fecha modificacion del registro';


