CREATE TABLE OPERACION.OPE_AGENDA_MASIVA_REG
(
  IDCARGA      NUMBER(6)                        NOT NULL,
  ORDEN        NUMBER(6)                        NOT NULL,
  CODSOLOT     NUMBER(8)                        NOT NULL,
  CODCON       NUMBER(6)                        NOT NULL,
  INSTALADOR   VARCHAR2(50 BYTE),
  FEC_PROG     DATE                             NOT NULL,
  ESTADO       NUMBER(1)                        DEFAULT 0,
  OBSERVACION  VARCHAR2(200 BYTE),
  IDAGENDA     NUMBER(8),
  USUREG       VARCHAR2(30 BYTE)                DEFAULT USER                  NOT NULL,
  FECREG       DATE                             DEFAULT SYSDATE               NOT NULL,
  USUMOD       VARCHAR2(30 BYTE)                DEFAULT USER                  NOT NULL,
  FECMOD       DATE                             DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.OPE_AGENDA_MASIVA_REG IS 'Registros carga para agendamiento masivo';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.IDCARGA IS 'Identificador de la tabla';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.ORDEN IS 'Secuencial por idcarga';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.CODSOLOT IS 'Codigo de SOT';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.INSTALADOR IS 'Instalador';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.FEC_PROG IS 'Fecha de programación';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.ESTADO IS 'Estado: 0 pendiente,1 procesado,2 error proceso';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.IDAGENDA IS 'ID de tabla agendamiento';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.FECREG IS 'Fecha que inserto el registro';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.USUMOD IS 'Usuario que modificó el registro';

COMMENT ON COLUMN OPERACION.OPE_AGENDA_MASIVA_REG.FECMOD IS 'Fecha que se modificó el registro';


