CREATE TABLE OPERACION.OPE_REGISTROS_TMP
(
  IDSEQ         NUMBER,
  NUMREGISTRO   CHAR(10 BYTE),
  IDAPLICACION  NUMBER,
  CODEXT        VARCHAR2(100 BYTE),
  PROMOCION     NUMBER,
  IDGRUPO       NUMBER
);


