CREATE TABLE OPERACION.OPE_CONCEPTO_ALQUILER_MAE
(
  IDCPTO      NUMBER(4)                         NOT NULL,
  TIPSRV      VARCHAR2(4 BYTE)                  NOT NULL,
  FLG_ACTIVO  NUMBER(2)                         DEFAULT 1                     NOT NULL,
  USUREG      VARCHAR2(30 BYTE)                 DEFAULT user,
  FECREG      DATE                              DEFAULT sysdate,
  USUMOD      VARCHAR2(30 BYTE)                 DEFAULT user,
  FECMOD      DATE                              DEFAULT sysdate
);

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.IDCPTO IS 'ID concepto de detalle factura';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.TIPSRV IS 'Tipo de servicio';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.FLG_ACTIVO IS 'Estado 1:activo, 0:no activo';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.USUREG IS 'Usuario de creacion';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.FECREG IS 'Fecha de creacion';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.USUMOD IS 'Usuario modificacion';

COMMENT ON COLUMN OPERACION.OPE_CONCEPTO_ALQUILER_MAE.FECMOD IS 'Fecha modificacion';


