CREATE TABLE OPERACION.OPE_CARGASRV_AUX
(
  IDLOTE       NUMBER(10)                       NOT NULL,
  IDDET        NUMBER(5)                        NOT NULL,
  ESTADO       CHAR(1 BYTE),
  DSCERROR     VARCHAR2(500 BYTE),
  CODERROR     NUMBER(2),
  CODINSSRV    NUMBER(10),
  NROTARJETA   VARCHAR2(30 BYTE),
  NTDIDE       VARCHAR2(15 BYTE),
  IDMOTIVO     NUMBER(2),
  TIPOSOL      NUMBER(2),
  IDGRUPO      NUMBER(5),
  USUARIO      VARCHAR2(30 BYTE),
  TRAMA        VARCHAR2(2000 BYTE),
  FECREG       DATE                             DEFAULT SYSDATE,
  USUREG       VARCHAR2(30 BYTE)                DEFAULT USER,
  FECMOD       DATE                             DEFAULT sysdate,
  USUMOD       VARCHAR2(30 BYTE)                DEFAULT USER,
  FLG          CHAR(1 BYTE),
  SECDET       NUMBER(5),
  CANTTARJ     NUMBER(5),
  IDTIPDET     NUMBER(2),
  UNITADDRESS  VARCHAR2(32 BYTE)
);

COMMENT ON TABLE OPERACION.OPE_CARGASRV_AUX IS 'Detalle del Lote de Carga de Servicios Inalambricos';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.ESTADO IS '1: Cargado, 2: Procesado, 3: Procesado con Errores, 4: Anulado';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.CODINSSRV IS 'ID de la Instancia del Servicio';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.NROTARJETA IS 'Numero de Tarjeta';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.NTDIDE IS 'DNI del cliente';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.IDMOTIVO IS 'ID del Motivo';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.TIPOSOL IS 'Tipo Solicitud 1: Activación, 2: Desactivación';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.IDGRUPO IS 'ID del Grupo Bouquet (ope_grupo_bouquet_cab)';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.USUARIO IS 'Usuario Registro';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.FLG IS 'Verificación correcta';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.SECDET IS 'Numero Secuencial del Lote';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.CANTTARJ IS 'Cantidad de Tarjetas Encontradas';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.IDTIPDET IS 'Tipo de detalle (1: Identificable 2: No Identificable)';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.UNITADDRESS IS 'Número MAC del DECO';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.IDLOTE IS 'ID del Lote de carga (VTATABLOTE)';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.IDDET IS 'ID del detalle de carga';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.DSCERROR IS 'Descripción de Error';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.CODERROR IS 'Código de Error';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.TRAMA IS 'Trama, concatenacion de campos';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.FECREG IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.USUREG IS 'Usuario de registro';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.FECMOD IS 'Fecha de modificación';

COMMENT ON COLUMN OPERACION.OPE_CARGASRV_AUX.USUMOD IS 'Usuario de modificación';


