-- CREATE TABLE
CREATE TABLE OPERACION.OPE_LOG_CARGA_INCIDENCE
(
  IDLOG        NUMBER(15) NOT NULL,
  IDTIPOLOG    NUMBER(5),
  DESCRIPCION  VARCHAR2(4000),
  CODUSU       VARCHAR2(30) DEFAULT USER,
  FECUSU       DATE DEFAULT SYSDATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.OPE_LOG_CARGA_INCIDENCE.IDLOG
  IS 'Codigo de log';
COMMENT ON COLUMN OPERACION.OPE_LOG_CARGA_INCIDENCE.IDTIPOLOG
  IS 'Tipo de log';
COMMENT ON COLUMN OPERACION.OPE_LOG_CARGA_INCIDENCE.DESCRIPCION
  IS 'Descripción';
COMMENT ON COLUMN OPERACION.OPE_LOG_CARGA_INCIDENCE.CODUSU
  IS 'Usuario de Registro';
COMMENT ON COLUMN OPERACION.OPE_LOG_CARGA_INCIDENCE.FECUSU
  IS 'Fecha de Registro';
  
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE OPERACION.OPE_LOG_CARGA_INCIDENCE
  ADD CONSTRAINT PK_LOG_CARGA_INCIDENCE PRIMARY KEY (IDLOG)
  USING INDEX 
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

