CREATE TABLE OPERACION.OPEDD_LOG
(
  IDOPEDD      NUMBER(6),
  CODIGOC      VARCHAR2(30 BYTE),
  CODIGON      NUMBER(10),
  DESCRIPCION  VARCHAR2(100 BYTE),
  ABREVIACION  VARCHAR2(30 BYTE),
  TIPOPEDD     NUMBER(6),
  TIPO         CHAR(1 BYTE),
  USUMOD       VARCHAR2(30 BYTE),
  FECMOD       DATE
);

COMMENT ON TABLE OPERACION.OPEDD_LOG IS 'Log del Listado de los tipo usados en operaciones';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.IDOPEDD IS 'Llave primaria de la tabla';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.CODIGOC IS 'Codigo en formato string';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.CODIGON IS 'Codigo en formato numerico';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.DESCRIPCION IS 'Descripcion de la clasificacion de los tipos de operaciones';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.ABREVIACION IS 'Abreviatura';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.TIPOPEDD IS 'Tipo de la clasificacion de operaciones';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.TIPO IS 'I: Insertar, U: Update, D: Delete';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.USUMOD IS 'Usuario que modifica';

COMMENT ON COLUMN OPERACION.OPEDD_LOG.FECMOD IS 'Fecha en que se modifica';


