CREATE TABLE OPERACION.PLANO
(
  IDPLANO         NUMBER,
  CODSOLOT        NUMBER(8),
  PUNTO           NUMBER(10),
  ORDEN           NUMBER(4),
  CODUBIRED1      NUMBER(6),
  CODUBIRED2      NUMBER(6),
  ARCHIVADOR      VARCHAR2(50 BYTE),
  NOMBREARCHIVO   VARCHAR2(50 BYTE),
  MEDIO           NUMBER,
  FECUSU          DATE                          DEFAULT SYSDATE               NOT NULL,
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT user                  NOT NULL,
  UBICACION       NUMBER,
  DIGITALIZACION  NUMBER,
  TIPOPLANO       VARCHAR2(5 BYTE),
  LAMINA          VARCHAR2(50 BYTE),
  TAMANO          NUMBER,
  IDTAREAWF       NUMBER,
  OBSERVACIONES   VARCHAR2(400 BYTE)
);

COMMENT ON COLUMN OPERACION.PLANO.IDPLANO IS 'Id Plano';

COMMENT ON COLUMN OPERACION.PLANO.CODSOLOT IS 'SOT';

COMMENT ON COLUMN OPERACION.PLANO.PUNTO IS 'Punto';

COMMENT ON COLUMN OPERACION.PLANO.ORDEN IS 'Orden';

COMMENT ON COLUMN OPERACION.PLANO.CODUBIRED1 IS 'Site Primario';

COMMENT ON COLUMN OPERACION.PLANO.CODUBIRED2 IS 'Site Secundario';

COMMENT ON COLUMN OPERACION.PLANO.ARCHIVADOR IS 'Archivador ';

COMMENT ON COLUMN OPERACION.PLANO.NOMBREARCHIVO IS 'Nombre Archivo Digital';

COMMENT ON COLUMN OPERACION.PLANO.MEDIO IS 'Medio ';

COMMENT ON COLUMN OPERACION.PLANO.UBICACION IS 'Ubicacion';

COMMENT ON COLUMN OPERACION.PLANO.DIGITALIZACION IS 'Estado de la Digitalización';

COMMENT ON COLUMN OPERACION.PLANO.TIPOPLANO IS 'Tipo e Plano';

COMMENT ON COLUMN OPERACION.PLANO.LAMINA IS 'Nombre de Lamina';

COMMENT ON COLUMN OPERACION.PLANO.TAMANO IS 'Tamaño';

COMMENT ON COLUMN OPERACION.PLANO.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OPERACION.PLANO.IDTAREAWF IS 'Id Tarea WF';


