CREATE TABLE OPERACION.PLANTILLA_TRASLADO
(
  IDPLANTILLA  NUMBER                           NOT NULL,
  CODPERFIL    NUMBER,
  TIPEQU       NUMBER(6),
  CENTRO_ORI   VARCHAR2(4 BYTE),
  ALMACEN_ORI  VARCHAR2(4 BYTE),
  CENTRO_DES   VARCHAR2(4 BYTE),
  ALMACEN_DES  VARCHAR2(4 BYTE),
  USUREG       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECREG       DATE                             DEFAULT sysdate               NOT NULL,
  USUMOD       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECMOD       DATE                             DEFAULT sysdate               NOT NULL
);

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.IDPLANTILLA IS 'PK de Plantilla';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.CODPERFIL IS 'Perfil de Plantilla';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.TIPEQU IS 'Codigo del tipo de equipo';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.CENTRO_ORI IS 'Centro Origen de Traslado';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.ALMACEN_ORI IS 'Almacen Origen de Traslado';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.CENTRO_DES IS 'Centro Destino de Traslado';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.ALMACEN_DES IS 'Almacen Destino de Traslado';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.USUREG IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.FECREG IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.USUMOD IS 'Codigo de Usuario modificador';

COMMENT ON COLUMN OPERACION.PLANTILLA_TRASLADO.FECMOD IS 'Fecha de modificación';


