CREATE TABLE OPERACION.PREDOCETA
(
  IDDOC   NUMBER(8)                             NOT NULL,
  CODETA  NUMBER(6)                             NOT NULL,
  DESMET  VARCHAR2(300 BYTE),
  UNIMET  VARCHAR2(30 BYTE),
  CANMET  VARCHAR2(50 BYTE),
  DESCRO  VARCHAR2(300 BYTE),
  TPOCRO  VARCHAR2(50 BYTE),
  CANCRO  VARCHAR2(50 BYTE),
  CODUSU  CHAR(30 BYTE)                         DEFAULT USER                  NOT NULL,
  FECUSU  DATE                                  DEFAULT sysdate               NOT NULL
);

COMMENT ON TABLE OPERACION.PREDOCETA IS 'No es usada';

COMMENT ON COLUMN OPERACION.PREDOCETA.IDDOC IS 'Id del documento';

COMMENT ON COLUMN OPERACION.PREDOCETA.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.PREDOCETA.DESMET IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREDOCETA.UNIMET IS 'Unidad metrica';

COMMENT ON COLUMN OPERACION.PREDOCETA.CANMET IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREDOCETA.DESCRO IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREDOCETA.TPOCRO IS 'Tiempo';

COMMENT ON COLUMN OPERACION.PREDOCETA.CANCRO IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREDOCETA.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREDOCETA.FECUSU IS 'Fecha de registro';


