CREATE TABLE OPERACION.PRESUPUESTO
(
  CODPRE    NUMBER(8)                           NOT NULL,
  NUMSLC    CHAR(10 BYTE),
  CODSOLOT  NUMBER(8),
  TIPSRV    CHAR(4 BYTE),
  ESTPRO    NUMBER(2),
  ESTDIS    NUMBER(2),
  ESTINS    NUMBER(2),
  ESTLIQ    NUMBER(2),
  CODCLI    CHAR(8 BYTE),
  FECINI    DATE,
  FECFIN    DATE,
  CODUSU    VARCHAR2(30 BYTE)                   DEFAULT USER                  NOT NULL,
  FECUSU    DATE                                DEFAULT SYSDATE               NOT NULL,
  TIPTRA    NUMBER(4),
  FECCOM    DATE
);

COMMENT ON TABLE OPERACION.PRESUPUESTO IS 'Presupuesto (No es usada, reemplazado por WF)';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.NUMSLC IS 'Numero de proyecto';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.TIPSRV IS 'Codigo del tipo de servicio';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.ESTPRO IS 'Estado proyectado';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.ESTDIS IS 'Estado del diseño';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.ESTINS IS 'Estado de instalación';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.ESTLIQ IS 'Estado de liquidación';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.FECINI IS 'Fecha de inicio';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.FECFIN IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.TIPTRA IS 'Codigo del tipo de trabajo';

COMMENT ON COLUMN OPERACION.PRESUPUESTO.FECCOM IS 'Fecha de compromiso';


