CREATE TABLE OPERACION.PRETIPDOC
(
  TIPDOC    NUMBER(2)                           NOT NULL,
  DESTIP    VARCHAR2(100 BYTE),
  DESFOR    VARCHAR2(100 BYTE),
  TEXTO_A   VARCHAR2(4000 BYTE),
  TITULO_A  VARCHAR2(100 BYTE),
  TEXTO_B   VARCHAR2(4000 BYTE),
  TITULO_B  VARCHAR2(100 BYTE),
  TEXTO_C   VARCHAR2(4000 BYTE),
  TITULO_C  VARCHAR2(100 BYTE),
  TEXTO_D   VARCHAR2(4000 BYTE),
  TITULO_D  VARCHAR2(100 BYTE),
  CODUSU    VARCHAR2(30 BYTE)                   DEFAULT USER                  NOT NULL,
  FECUSU    DATE                                DEFAULT SYSDATE               NOT NULL,
  FLGTIPO   NUMBER(1)
);

COMMENT ON TABLE OPERACION.PRETIPDOC IS 'Tipos de documentos';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TIPDOC IS 'Tipo de documento';

COMMENT ON COLUMN OPERACION.PRETIPDOC.DESTIP IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PRETIPDOC.DESFOR IS 'Descripcion de la formula';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TEXTO_A IS 'Texto A';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TITULO_A IS 'Titulo A';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TEXTO_B IS 'Texto B';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TITULO_B IS 'Titulo B';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TEXTO_C IS 'Texto C';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TITULO_C IS 'Titulo C';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TEXTO_D IS 'Texto D';

COMMENT ON COLUMN OPERACION.PRETIPDOC.TITULO_D IS 'Titulo D';

COMMENT ON COLUMN OPERACION.PRETIPDOC.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PRETIPDOC.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PRETIPDOC.FLGTIPO IS 'No se utiliza';


