CREATE TABLE OPERACION.PREUBIETAFAC
(
  CODPRE       NUMBER(8)                        NOT NULL,
  IDUBI        NUMBER(10)                       NOT NULL,
  CODETA       NUMBER(5)                        NOT NULL,
  ORDEN        NUMBER(5)                        NOT NULL,
  FACTURA      NUMBER(8),
  MONTOMO      NUMBER(10,2),
  MONTOMAT     NUMBER(10,2),
  OBSERVACION  VARCHAR2(500 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.PREUBIETAFAC IS 'Facturacion de cada etapa del presupuesto  (No es usada, reemplazado por WF)';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.IDUBI IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.FACTURA IS 'Factura';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.MONTOMO IS 'Monto de mano de obra';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.MONTOMAT IS 'Monto de material';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBIETAFAC.FECUSU IS 'Fecha de registro';


