CREATE TABLE OPERACION.PREUBIPOS
(
  CODPRE       NUMBER(8)                        NOT NULL,
  IDUBI        NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(10)                       NOT NULL,
  POSTE        VARCHAR2(30 BYTE),
  PROPIETARIO  VARCHAR2(30 BYTE),
  TIPO         VARCHAR2(30 BYTE),
  TAMANO       NUMBER(4),
  CODUBI       CHAR(10 BYTE),
  OBSERVACION  VARCHAR2(500 BYTE),
  FLGPROY      NUMBER(1)                        DEFAULT 0                     NOT NULL
);

COMMENT ON TABLE OPERACION.PREUBIPOS IS 'No es usada';

COMMENT ON COLUMN OPERACION.PREUBIPOS.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIPOS.IDUBI IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIPOS.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.PREUBIPOS.POSTE IS 'Numero de poste';

COMMENT ON COLUMN OPERACION.PREUBIPOS.PROPIETARIO IS 'Propietario';

COMMENT ON COLUMN OPERACION.PREUBIPOS.TIPO IS 'Tipo de poste';

COMMENT ON COLUMN OPERACION.PREUBIPOS.TAMANO IS 'Tamaño del poste';

COMMENT ON COLUMN OPERACION.PREUBIPOS.CODUBI IS 'Codigo del distrito';

COMMENT ON COLUMN OPERACION.PREUBIPOS.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.PREUBIPOS.FLGPROY IS 'No se utiliza';


