CREATE TABLE OPERACION.PREUBIEST
(
  CODSOLOT   NUMBER(8)                          NOT NULL,
  PUNTO      NUMBER(10)                         NOT NULL,
  IDITEM     NUMBER(8)                          NOT NULL,
  FECINI     DATE,
  ESTUBI     NUMBER(2),
  CODUSU     VARCHAR2(30 BYTE)                  DEFAULT user,
  ESTUBIOLD  NUMBER(2)
);

COMMENT ON TABLE OPERACION.PREUBIEST IS 'Cambios de estado del detalle del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIEST.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.PREUBIEST.PUNTO IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIEST.IDITEM IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIEST.FECINI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIEST.ESTUBI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIEST.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBIEST.ESTUBIOLD IS 'No se utiliza';


