CREATE TABLE OPERACION.PREUBIETA
(
  CODPRE       NUMBER(8)                        NOT NULL,
  IDUBI        NUMBER(10)                       NOT NULL,
  CODETA       NUMBER(5)                        NOT NULL,
  ESTETA       NUMBER(2),
  CODCON       NUMBER(6),
  RESPONSABLE  VARCHAR2(30 BYTE),
  FECINI       DATE,
  FECFIN       DATE,
  OBSERVACION  VARCHAR2(400 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT USER,
  FECUSU       DATE                             DEFAULT SYSDATE,
  FECCON       DATE,
  FLGLIQ       NUMBER(1),
  FECLIQ       DATE,
  FECPER       DATE,
  OBSVAL       VARCHAR2(400 BYTE)
);

COMMENT ON TABLE OPERACION.PREUBIETA IS 'Etapa del detalle del presupuesto (No es usada, reemplazado por WF)';

COMMENT ON COLUMN OPERACION.PREUBIETA.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETA.IDUBI IS 'No usada';

COMMENT ON COLUMN OPERACION.PREUBIETA.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETA.ESTETA IS 'Estado de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETA.CODCON IS 'Codigo del contratista';

COMMENT ON COLUMN OPERACION.PREUBIETA.RESPONSABLE IS 'No usada';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECINI IS 'Fecha de inicio';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECFIN IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBIETA.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.PREUBIETA.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECCON IS 'Fecha de contratista';

COMMENT ON COLUMN OPERACION.PREUBIETA.FLGLIQ IS 'No usada';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECLIQ IS 'Fecha de liquidación';

COMMENT ON COLUMN OPERACION.PREUBIETA.FECPER IS 'Fecha de permiso';

COMMENT ON COLUMN OPERACION.PREUBIETA.OBSVAL IS 'No usada';


