CREATE TABLE OPERACION.PREUBIETAACT
(
  CODPRE       NUMBER(8)                        NOT NULL,
  IDUBI        NUMBER(10)                       NOT NULL,
  CODETA       NUMBER(5)                        NOT NULL,
  IDACT        NUMBER(10)                       NOT NULL,
  CODACT       NUMBER(5)                        NOT NULL,
  MONEDA       CHAR(1 BYTE)                     DEFAULT 'D'                   NOT NULL,
  CANPRO       NUMBER(8,2)                      DEFAULT 0,
  COSPRO       NUMBER(10,2)                     DEFAULT 0,
  CANDIS       NUMBER(8,2)                      DEFAULT 0,
  COSDIS       NUMBER(10,2)                     DEFAULT 0,
  CANINS       NUMBER(8,2)                      DEFAULT 0,
  COSINS       NUMBER(10,2),
  UNIMETINS    VARCHAR2(30 BYTE),
  TPOCROINS    VARCHAR2(30 BYTE),
  FLGCASOINS   NUMBER(1),
  CANLIQ       NUMBER(8,2)                      DEFAULT 0,
  COSLIQ       NUMBER(10,2)                     DEFAULT 0,
  UNIMETLIQ    VARCHAR2(30 BYTE),
  TPOCROLIQ    VARCHAR2(30 BYTE),
  FLGASOLIQ    NUMBER(1),
  CONTRATA     NUMBER(1)                        DEFAULT 0,
  OBSERVACION  VARCHAR2(400 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT USER                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  UNIMETDIS    VARCHAR2(30 BYTE),
  TPOCRODIS    VARCHAR2(30 BYTE),
  FLGASODIS    NUMBER(1)
);

COMMENT ON TABLE OPERACION.PREUBIETAACT IS 'Actividades de cada etapa del presupuesto (No es usada, reemplazado por WF)';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.IDUBI IS 'Id de la tabla preubi';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.IDACT IS 'Id de la tabla';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CODACT IS 'Codigo de la actividad';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.MONEDA IS 'Codigo de moneda';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CANPRO IS 'Cantidad de la actividad en la fase proyectada (No se utiliza)';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.COSPRO IS 'Costo proyectado (No se utiliza)';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CANDIS IS 'Cantidad de la actividad en la fase diseño';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.COSDIS IS 'Costo de diseño';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CANINS IS 'Cantidad de la actividad en la fase instalación';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.COSINS IS 'Costo de instalación de la actividad';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.UNIMETINS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.TPOCROINS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.FLGCASOINS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CANLIQ IS 'Cantidad de la actividad en la fase liquidación';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.COSLIQ IS 'Costo de liquidación de la actividad';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.UNIMETLIQ IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.TPOCROLIQ IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.FLGASOLIQ IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CONTRATA IS 'Identifica si la actividad es ejecutada por el contratista';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.OBSERVACION IS 'Observacion';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.UNIMETDIS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.TPOCRODIS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBIETAACT.FLGASODIS IS 'No se utiliza';


