CREATE TABLE OPERACION.PREUBI
(
  CODPRE        NUMBER(8),
  IDUBI         NUMBER(10)                      NOT NULL,
  CID           NUMBER(10),
  CODUBIRED     NUMBER(6),
  DISOBRA       CHAR(10 BYTE),
  DIROBRA       VARCHAR2(480 BYTE),
  CODINSSRV     NUMBER(10),
  FECINI        DATE,
  FECFIN        DATE,
  FECUSU        DATE                            DEFAULT SYSDATE               NOT NULL,
  CODUSU        VARCHAR2(30 BYTE)               DEFAULT USER                  NOT NULL,
  DESCRIPCION   VARCHAR2(200 BYTE),
  ESTUBI        NUMBER(2)                       DEFAULT 1,
  CODCON        NUMBER(6),
  FECINIDGO     DATE,
  FECFINDGO     DATE,
  FECINIINS     DATE,
  FECFININS     DATE,
  FECINILIQ     DATE,
  FECFINLIQ     DATE,
  FECINILIQDGO  DATE,
  FECFINLIQDGO  DATE,
  FECFINLOG     DATE,
  FECFINCAD     DATE,
  FECINILDS     DATE,
  FECFINLDS     DATE,
  PUNTO         NUMBER(10),
  CODSOLOT      NUMBER(8),
  PA_ATT_9      NUMBER(3),
  PA_ATT_11     NUMBER(3),
  PA_LDS_C      NUMBER(3),
  PA_LDS_M      NUMBER(3),
  PA_EN_C       NUMBER(3),
  PA_EN_M       NUMBER(3),
  PA_BELL       NUMBER(3),
  PA_TELE       NUMBER(3),
  PO_ATT_9      NUMBER(3),
  PO_ATT_11     NUMBER(3),
  CABLE_LONG    NUMBER(8,2),
  CABLE_TIPO    NUMBER(2),
  ASIG_FIBRA    VARCHAR2(60 BYTE),
  AUTOCON       NUMBER(1),
  CABLE_DUCTO   NUMBER(8,2),
  PA_ANCLA      NUMBER(8,2),
  OBSERVACION   VARCHAR2(1000 BYTE),
  REQLDS        NUMBER(1)                       DEFAULT 1                     NOT NULL,
  REQDGO        NUMBER(1)                       DEFAULT 1                     NOT NULL,
  DIARETCONDIS  NUMBER(5),
  FECPROG       DATE,
  RESPONSABLE   VARCHAR2(30 BYTE),
  FECASIG       DATE,
  FECINILDS2    DATE,
  FLGNULL       NUMBER(1)                       DEFAULT 0                     NOT NULL
);

COMMENT ON TABLE OPERACION.PREUBI IS 'Detalle del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBI.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBI.IDUBI IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBI.CID IS 'Circuito id';

COMMENT ON COLUMN OPERACION.PREUBI.CODUBIRED IS 'Codigo del site';

COMMENT ON COLUMN OPERACION.PREUBI.DISOBRA IS 'Distrito de la obra';

COMMENT ON COLUMN OPERACION.PREUBI.DIROBRA IS 'Direccion de la obra';

COMMENT ON COLUMN OPERACION.PREUBI.CODINSSRV IS 'Codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.PREUBI.FECINI IS 'Fecha de inicio';

COMMENT ON COLUMN OPERACION.PREUBI.FECFIN IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBI.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PREUBI.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBI.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.ESTUBI IS 'Estado del punto';

COMMENT ON COLUMN OPERACION.PREUBI.CODCON IS 'Codigo del contratista';

COMMENT ON COLUMN OPERACION.PREUBI.FECINIDGO IS 'Fecha de inicio de permiso';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINDGO IS 'Fecha de fin de permiso';

COMMENT ON COLUMN OPERACION.PREUBI.FECINIINS IS 'Fecha de inicio de instalación';

COMMENT ON COLUMN OPERACION.PREUBI.FECFININS IS 'Fecha de fin de instalación';

COMMENT ON COLUMN OPERACION.PREUBI.FECINILIQ IS 'Fecha de inicio de liquidación';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINLIQ IS 'Fecha de fin de liquidacion';

COMMENT ON COLUMN OPERACION.PREUBI.FECINILIQDGO IS 'Fecha de inicio de liquidación permiso';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINLIQDGO IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINLOG IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINCAD IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBI.FECINILDS IS 'Fecha de inicio de instalación';

COMMENT ON COLUMN OPERACION.PREUBI.FECFINLDS IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBI.PUNTO IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBI.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.PREUBI.PA_ATT_9 IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_ATT_11 IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_LDS_C IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_LDS_M IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_EN_C IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_EN_M IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_BELL IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PA_TELE IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PO_ATT_9 IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.PO_ATT_11 IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.CABLE_LONG IS 'Longitud del cable';

COMMENT ON COLUMN OPERACION.PREUBI.CABLE_TIPO IS 'Tipo de cable';

COMMENT ON COLUMN OPERACION.PREUBI.ASIG_FIBRA IS 'Asignacion de fibra';

COMMENT ON COLUMN OPERACION.PREUBI.AUTOCON IS 'Permite seleccionar el contratista automaticamente';

COMMENT ON COLUMN OPERACION.PREUBI.CABLE_DUCTO IS 'Cantidad de ducto en el cable';

COMMENT ON COLUMN OPERACION.PREUBI.PA_ANCLA IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.PREUBI.REQLDS IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.REQDGO IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.PREUBI.DIARETCONDIS IS 'No se utiliza';


