CREATE TABLE OPERACION.PREUBISEG
(
  CODPRE       NUMBER(8)                        NOT NULL,
  IDUBI        NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(8)                        NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL,
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT USER                  NOT NULL,
  OBSERVACION  VARCHAR2(4000 BYTE)
);

COMMENT ON TABLE OPERACION.PREUBISEG IS 'No es usada';

COMMENT ON COLUMN OPERACION.PREUBISEG.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBISEG.IDUBI IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBISEG.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.PREUBISEG.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.PREUBISEG.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.PREUBISEG.OBSERVACION IS 'Observación';


