CREATE TABLE OPERACION.PREUBIETAEST
(
  CODPRE  NUMBER(8)                             NOT NULL,
  IDUBI   NUMBER(10)                            NOT NULL,
  CODETA  NUMBER(5)                             NOT NULL,
  IDITEM  NUMBER(8)                             NOT NULL,
  FECINI  DATE,
  FECFIN  DATE,
  ESTETA  NUMBER(2),
  CODUSU  VARCHAR2(30 BYTE)                     DEFAULT user
);

COMMENT ON TABLE OPERACION.PREUBIETAEST IS 'Estado de la etapa del presupuesto  (No es usada, reemplazado por WF)';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.CODPRE IS 'Codigo del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.IDUBI IS 'Punto del presupuesto';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.IDITEM IS 'Iditem';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.FECINI IS 'Fecha de inicio';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.FECFIN IS 'Fecha de fin';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.ESTETA IS 'Estado de la etapa';

COMMENT ON COLUMN OPERACION.PREUBIETAEST.CODUSU IS 'Codigo de Usuario registro';


