CREATE TABLE OPERACION.PROMOPLAYXCLIENTE
(
  CODSOLOT     NUMBER(8)                        NOT NULL,
  CODCLI       CHAR(8 BYTE)                     NOT NULL,
  CODSRV       CHAR(4 BYTE),
  CODSRV_PROM  CHAR(4 BYTE),
  ID_PRODUCTO  NUMBER(10),
  FECINI       DATE,
  FECFIN       DATE,
  PID_SGA      NUMBER(10),
  NUMSLC       CHAR(10 BYTE),
  FLGESTADO    NUMBER(1),
  USUREG       VARCHAR2(30 BYTE),
  FECREG       DATE,
  USUMOD       VARCHAR2(30 BYTE),
  FECMOD       DATE
);

COMMENT ON TABLE OPERACION.PROMOPLAYXCLIENTE IS 'Lista de clientes a los que se les venficio con alguna promocion';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.CODSOLOT IS 'Codigo de la solicitud de la orden de trabajo';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.CODSRV IS 'Codigo del servicio inicial';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.CODSRV_PROM IS 'Codigo del servicio asignado por promocion';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.ID_PRODUCTO IS 'id del producto';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.FECINI IS 'fecha inicio promocion';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.FECFIN IS 'fecha fin promocion';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.PID_SGA IS 'pid en el sistema SGA';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.NUMSLC IS 'Numero del proyecto';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.FLGESTADO IS 'Estado del cliente    1  tiene promocion   0 no tiene promocion';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.USUREG IS 'Codigó usuario creación';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.FECREG IS 'Fecha de creación del registro';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.USUMOD IS 'Codigó usuaior modificación';

COMMENT ON COLUMN OPERACION.PROMOPLAYXCLIENTE.FECMOD IS 'Fecha modificación';


