CREATE TABLE OPERACION.PUERTOXEQUIPO_LOG
(
  FECEJE      DATE,
  USUMOD      VARCHAR2(30 BYTE),
  CODPUERTO   NUMBER(8),
  CODEQUIPO   NUMBER(6),
  CODPRD      NUMBER(5),
  CODTARJETA  NUMBER(6),
  ESTADO      NUMBER(2)                         DEFAULT 99,
  IDE         NUMBER(10),
  ESTADOANT   NUMBER(2)                         DEFAULT 99
);


