CREATE TABLE OPERACION.RECONEXIONPORPAGO_BOGA_OLD_3
(
  IDRECPAGO       NUMBER                        NOT NULL,
  IDFAC           CHAR(10 BYTE),
  CODCLI          CHAR(8 BYTE),
  NOMABR          VARCHAR2(50 BYTE),
  FECREG          DATE,
  USUREG          VARCHAR2(30 BYTE),
  FLGLEIDO        CHAR(1 BYTE),
  FLGRECONECTADO  CHAR(1 BYTE),
  OBS             VARCHAR2(200 BYTE),
  FLGCABLE        CHAR(1 BYTE)
);


