CREATE TABLE OPERACION.RECONEXIONPORPAGO_BOGA
(
  IDRECPAGO       NUMBER                        NOT NULL,
  IDFAC           CHAR(10 BYTE),
  CODCLI          CHAR(8 BYTE),
  NOMABR          VARCHAR2(50 BYTE),
  FECREG          DATE                          DEFAULT SYSDATE,
  USUREG          VARCHAR2(30 BYTE),
  FLGLEIDO        CHAR(1 BYTE)                  DEFAULT 0,
  FLGRECONECTADO  CHAR(1 BYTE)                  DEFAULT 0,
  OBS             VARCHAR2(200 BYTE),
  FLGCABLE        CHAR(1 BYTE)
);

COMMENT ON COLUMN OPERACION.RECONEXIONPORPAGO_BOGA.FLGCABLE IS 'INDICA SI EL RECIBE PROVIENE DE UN SERVICIO DE CABLE';


