CREATE TABLE OPERACION.RECONEXIONPORPAGO_OLD
(
  IDRECPAGO       NUMBER                        NOT NULL,
  IDFAC           NUMBER,
  CODCLI          CHAR(8 BYTE),
  NOMABR          VARCHAR2(50 BYTE),
  FECREG          DATE,
  USUREG          VARCHAR2(30 BYTE),
  FLGLEIDO        CHAR(1 BYTE),
  FLGRECONECTADO  CHAR(1 BYTE),
  OBS             VARCHAR2(200 BYTE)
);


