CREATE TABLE OPERACION.REGINSDTH_VIGENCIA
(
  IDVIGENCIA          NUMBER(15),
  CODINCIDENCE        NUMBER(8),
  NUMREGISTRO         CHAR(10 BYTE),
  ESTADO_OLD          CHAR(2 BYTE),
  FECFINVIG_OLD       DATE,
  ESTADO_NEW          CHAR(2 BYTE),
  FECFINVIG_NEW       DATE,
  FLG_GEN_CORTE       NUMBER(1)                 DEFAULT 0,
  FLG_GEN_RECONEXION  NUMBER(1)                 DEFAULT 0,
  CODUSU              VARCHAR2(30 BYTE)         DEFAULT user,
  FECUSU              DATE                      DEFAULT sysdate,
  OBSERVACIONES       VARCHAR2(500 BYTE),
  DIAS                NUMBER(8),
  MONTO               NUMBER(18,4),
  IDCUPON             NUMBER,
  USUMOD              VARCHAR2(30 BYTE)         DEFAULT user,
  FECMOD              DATE                      DEFAULT sysdate
);

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.CODINCIDENCE IS 'Codigo de la Incidencia';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.IDVIGENCIA IS 'Id de la ampliacion';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.NUMREGISTRO IS 'Numero del registro DTH (Reginsdth)';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.ESTADO_OLD IS 'Estado Actual';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FECFINVIG_OLD IS 'Fecha Fin de Vigencia Actual';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.ESTADO_NEW IS 'Estado Nuevo';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FECFINVIG_NEW IS 'Fecha Fin de Vigencia Nuevo';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FLG_GEN_CORTE IS 'Flag de generacion de corte';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FLG_GEN_RECONEXION IS 'Flag de generacion de reconexion';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.CODUSU IS 'Usuario creador';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FECUSU IS 'Fecha de creación';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.DIAS IS 'Dias de ampliacion';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.MONTO IS 'Monto de la ampliacion';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.IDCUPON IS 'Id del Cupon de Recarga DTH Vigente';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.USUMOD IS 'Usuario modificador';

COMMENT ON COLUMN OPERACION.REGINSDTH_VIGENCIA.FECMOD IS 'Fecha de modificacion';


