CREATE TABLE OPERACION.REGINSPROF24H
(
  NUM_CONTROL   CHAR(10 BYTE)                   NOT NULL,
  IDPAQ         NUMBER(10),
  ESTPROF24H    CHAR(2 BYTE)                    DEFAULT '01',
  CODSOLOT      NUMBER(8),
  NUMSLC        CHAR(10 BYTE),
  CODCLI        CHAR(8 BYTE),
  PID           NUMBER(10),
  CODINSSRV     NUMBER(10),
  CODSUC        CHAR(10 BYTE),
  DIRSUC        VARCHAR2(480 BYTE),
  CODSOL        CHAR(8 BYTE),
  TIPDOCCON     CHAR(2 BYTE),
  NOMBRES       VARCHAR2(30 BYTE),
  CORREO        VARCHAR2(30 BYTE),
  ESTENV        NUMBER,
  NUMINT        NUMBER,
  TIPO_PLAN     CHAR(2 BYTE),
  FLG_REC_PASS  NUMBER,
  CODUSU        VARCHAR2(30 BYTE)               DEFAULT user,
  FECUSU        DATE                            DEFAULT sysdate,
  CODINSSRVINF  NUMBER(10)
);

COMMENT ON TABLE OPERACION.REGINSPROF24H IS 'Registro de operacion de los servicios de Profesor 24 horas';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.NUM_CONTROL IS 'Codigo';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.IDPAQ IS 'Paquete del servicio';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.ESTPROF24H IS 'Estado';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODSOLOT IS 'Codigo de Solicitud de Orden de Trabajo';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.NUMSLC IS 'Numero del proyecto';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.PID IS 'Codigo de instancia del producto';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODINSSRV IS 'Codigo de instancia del servicio';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODSUC IS 'Codigo de la sucursal del cliente';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.DIRSUC IS 'Direccion de la sucursal';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODSOL IS 'Codigo de consultor';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.TIPDOCCON IS 'Tipo de documento del contrato';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.ESTENV IS 'flag de envio (0: sin enviar, 1: enviado)';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.NUMINT IS 'numero de intentos de envio';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.TIPO_PLAN IS 'A:Anual ; M:Mensual';

COMMENT ON COLUMN OPERACION.REGINSPROF24H.CODINSSRVINF IS 'Codigo de instancia del servicio del servicio de internet asociado';


