CREATE TABLE OPERACION.REPORTE
(
  CODRPT        NUMBER(8)                       NOT NULL,
  NOMBRE        VARCHAR2(100 BYTE),
  DESCRIPCION   VARCHAR2(200 BYTE),
  CONSULTA      VARCHAR2(4000 BYTE),
  FORMATO       VARCHAR2(4000 BYTE),
  CON_DISTINCT  NUMBER(1)                       DEFAULT 0                     NOT NULL,
  TABLA         VARCHAR2(100 BYTE),
  CODUSU        VARCHAR2(30 BYTE)               DEFAULT USER                  NOT NULL,
  FECUSU        DATE                            DEFAULT SYSDATE               NOT NULL,
  SINTAXIS      LONG
);

COMMENT ON TABLE OPERACION.REPORTE IS 'No es usada';

COMMENT ON COLUMN OPERACION.REPORTE.CODRPT IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.NOMBRE IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.CONSULTA IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.FORMATO IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.CON_DISTINCT IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.TABLA IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.REPORTE.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.REPORTE.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.REPORTE.SINTAXIS IS 'No se utiliza';


