CREATE TABLE OPERACION.REQUIS
(
  RESERVATION_BATCH_ID  NUMBER,
  DEMAND_SOURCE_NAME    VARCHAR2(30 BYTE),
  REQUIREMENT_DATE      DATE,
  ATTENTION_DATE        DATE,
  SUBINVENTORY_CODE     VARCHAR2(10 BYTE),
  ID_NAME               NUMBER,
  NAME                  VARCHAR2(100 BYTE),
  ID_APPROVATE_NAME     NUMBER,
  APPROVATE_NAME        VARCHAR2(100 BYTE),
  USER_ID               NUMBER,
  CID                   NUMBER,
  FASE_NAME             VARCHAR2(50 BYTE),
  SUPPLIER_NAME         VARCHAR2(100 BYTE),
  REQUEST_ID            NUMBER,
  POINT_ID              NUMBER,
  ORGANIZATION_ID       NUMBER,
  STATUS_DOC            NUMBER,
  STATUS_FLUJO          NUMBER,
  CUSTOMER_NAME         VARCHAR2(150 BYTE),
  ORDEN                 NUMBER,
  ID_PROJECT            NUMBER,
  PROJECT_NAME          VARCHAR2(100 BYTE),
  CODALIAS              VARCHAR2(30 BYTE),
  OM                    NUMBER,
  OBSERVATION           VARCHAR2(150 BYTE),
  VOID_OBS              VARCHAR2(150 BYTE),
  FECHA_APROBACION      DATE,
  CONCEPTOS             VARCHAR2(150 BYTE),
  SID                   NUMBER(10)
);


