CREATE TABLE OPERACION.REQUISDET
(
  INTERFASE_ID          NUMBER,
  RESERVATION_BATCH_ID  NUMBER                  NOT NULL,
  INVENTORY_ITEM_ID     NUMBER                  NOT NULL,
  RESERVATION_UOM_CODE  VARCHAR2(3 BYTE),
  RESERVATION_QUANTITY  NUMBER,
  PROJECT_ID            NUMBER,
  TASK_ID               NUMBER,
  EXPENDITURE_ORG       NUMBER,
  EXPENDITURE_TYPE      VARCHAR2(30 BYTE),
  EXPENDITURE_ORG_ID    NUMBER,
  EXPENDITURE_ORG_NAME  VARCHAR2(100 BYTE),
  OBSERVATION           VARCHAR2(150 BYTE)
);


