CREATE TABLE OPERACION.RESTARWF
(
  TAREA        NUMBER(6),
  IDWF         NUMBER(8),
  DESCRIPCION  VARCHAR2(100 BYTE)               NOT NULL,
  TIPO         NUMBER(1),
  AREA         NUMBER(4),
  RESPONSABLE  VARCHAR2(30 BYTE),
  WFDEF        NUMBER(6),
  TAREADEF     NUMBER(6),
  EST_TAREA    VARCHAR2(30 BYTE),
  PRE_TAREAS   VARCHAR2(200 BYTE),
  POS_TAREAS   VARCHAR2(200 BYTE),
  PLAZO        NUMBER(10,2),
  IDTAREAWF    NUMBER(8)                        NOT NULL,
  TIPESTTAR    NUMBER(2),
  ESTTAREA     NUMBER(4),
  FECCOM       DATE,
  FECINI       DATE,
  FECFIN       DATE
);


