-- Create table
create table OPERACION.SGA_AP_PARAMETRO
(
  PRMTN_CORRELATIVO  NUMBER not null,
  PRMTC_TIPO_PARAM   VARCHAR2(5) not null,
  PRMTN_CODIGO_PARAM NUMBER not null,
  PRMTV_DESCRIPCION  VARCHAR2(40) not null,
  PRMTC_ESTADO       CHAR(1) not null,
  PRMTV_USUARIO_CREA VARCHAR2(10) default user not null ,
  PRMTD_FECHA_CREA   DATE default sysdate not null ,
  PRMTV_VALOR        VARCHAR2(4000)
);
-- Add comments to the columns 
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTN_CORRELATIVO
  is 'CORRELATIVO DE LA TABLA';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTC_TIPO_PARAM
  is 'TIPO DE PARAMETRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTN_CODIGO_PARAM
  is 'CODIGO DEL PARAMETRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTV_DESCRIPCION
  is 'DESCRIPCION DEL PARAMETRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTC_ESTADO
  is 'ESTADO DEL PARAMETRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTV_USUARIO_CREA
  is 'USUARIO QUIEN CREA EL REGISTRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTD_FECHA_CREA
  is 'FECHA DE CREACION DE REGISTRO';
comment on column OPERACION.SGA_AP_PARAMETRO.PRMTV_VALOR
  is 'VALOR';
-- Create/Recreate primary, unique and foreign key constraints 
alter table OPERACION.SGA_AP_PARAMETRO
  add constraint PK_PRMTN_CODIGO_PARAM primary key (PRMTN_CORRELATIVO);
