-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_CID_SERV_LICENCIA
(
  SERLC_NUMSLC      CHAR(10) NOT NULL,
  SERLN_CID         NUMBER(10) NOT NULL,
  SERLN_CODSOLOT    NUMBER(8),
  SERLI_SECUENCIA   INTEGER NOT NULL,
  SERLC_CODSRV      CHAR(4) NOT NULL,
  SERLD_FECINISRV   DATE,
  SERLD_FECFINSRV   DATE,
  SERLI_PERRENSRV   INTEGER,
  SERLV_OBSERVACION VARCHAR2(250),
  SERLV_USUREG      VARCHAR2(30) DEFAULT USER,
  SERLD_FECREG      DATE DEFAULT SYSDATE,
  SERLV_USUMOD      VARCHAR2(30),
  SERLD_FECMOD      DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLC_NUMSLC
  IS 'NÚMERO DE PROYECTO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLN_CID
  IS 'CIRCUITO ID.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLN_CODSOLOT
  IS 'CÓDIGO DE SOLICITUD DE ORDEN TRABAJO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLI_SECUENCIA
  IS 'NÚMERO DE SECUENCIA.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLC_CODSRV
  IS 'CÓDIGO DEL SERVICIO PRINCIPAL.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLD_FECINISRV
  IS 'FECHA DE INICIO DEL SERVICIO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLD_FECFINSRV
  IS 'FECHA FIN DEL SERVICIO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLI_PERRENSRV
  IS 'PERIODO DE RENOVACIÓN DEL SERVICIO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLV_OBSERVACION
  IS 'ARGUMENTO DE LA LICENCIA O SOPORTE AL EQUIPO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_CID_SERV_LICENCIA.SERLD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';

