-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_EF_EQUIPO_CNFG
(
  EFQCN_ID     NUMBER(5) NOT NULL,
  EFEQN_ID     NUMBER(5) NOT NULL,
  EFQCN_ESTADO NUMBER(1) DEFAULT 1 NOT NULL,
  EFQCV_USUREG VARCHAR2(30) DEFAULT USER NOT NULL,
  EFQCD_FECREG DATE DEFAULT SYSDATE NOT NULL,
  EFQCV_USUMOD VARCHAR2(30),
  EFQCD_FECMOD DATE,
  EFQCV_CODMAT CHAR(15) NOT NULL
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCN_ID
  IS 'ID.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFEQN_ID
  IS 'ID EQUIPO SERVICIO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCN_ESTADO
  IS 'ESTADO DE LA ACTIVIDAD POR EQUIPO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG.EFQCV_CODMAT
  IS 'CÓDIGO DE MATERIAL.';
