-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_NOTIFICACION_CLIENTE
(
  CLINN_ID        NUMBER(10) NOT NULL,
  CLINC_NUMSLC    CHAR(10) NOT NULL,
  CLINN_CID       NUMBER(10) NOT NULL,
  CLINN_CODSOLOT  NUMBER(8),
  CLINV_RUC       VARCHAR2(15) NOT NULL,
  CLINC_CODCLI    CHAR(8) NOT NULL,
  CLINN_IDMSJ     NUMBER(3) NOT NULL,
  CLINI_ID_LIC    INTEGER NOT NULL,
  CLINI_SECUENCIA INTEGER NOT NULL,
  CLINI_TIPSRV    INTEGER NOT NULL,
  CLIND_FECINICIO DATE NOT NULL,
  CLIND_FECFIN    DATE NOT NULL,
  CLINI_ESTADO    NUMBER(1) DEFAULT 0,
  CLINI_CANTNOTIF NUMBER(10),
  CLIND_FECENVIO  CHAR(8),
  CLINV_USUREG    VARCHAR2(30) NOT NULL,
  CLIND_FECREG    DATE NOT NULL,
  CLINV_USUMOD    VARCHAR2(30),
  CLIND_FECMOD    DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINN_ID
  IS 'IDENTIFICADOR UNICO DE REGISTRO';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINC_NUMSLC
  IS 'NÚMERO DE SOLICITUD.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINN_CID
  IS 'CÓDIGO CID.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINN_CODSOLOT
  IS 'CÓDIGO DE SOLICITUD.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINV_RUC
  IS 'RUC DEL CLIENTE';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINC_CODCLI
  IS 'CODIGO DEL CLIENTE';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINN_IDMSJ
  IS 'CÓDIGO DE MENSAJE';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINI_ID_LIC
  IS 'IDENTIFICADOR DE LICENCIA O SOPORTE';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINI_SECUENCIA
  IS 'IDENTIIFICADOR DE SECUENCIA DE LA LICENCIA.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINI_TIPSRV
  IS '1: LICENCIA 2: SOPORTE.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLIND_FECINICIO
  IS 'FECHA DE INICIO DE LICENCIA O SOPORTE.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLIND_FECFIN
  IS 'FECHA DE FIN DE LICENCIA O SOPORTE.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINI_ESTADO
  IS 'ESTADO DE NOTICACION. 0: NO SE NOTIFICÓ 1: SE NOTIFICÓ.';
COMMENT ON COLUMN OPERACION.SGAT_NOTIFICACION_CLIENTE.CLINI_CANTNOTIF
  IS 'CANTIDAD DE NOTIFICACIONES POR ENVIAR.';
comment on column OPERACION.SGAT_NOTIFICACION_CLIENTE.clind_fecenvio
  is 'FECHA DE ULTIMO ENVIO.';
comment on column OPERACION.SGAT_NOTIFICACION_CLIENTE.clinv_usureg
  is 'USUARIO DE REGISTRO.';
comment on column OPERACION.SGAT_NOTIFICACION_CLIENTE.clind_fecreg
  is 'FECHA DE REGISTRO.';
comment on column OPERACION.SGAT_NOTIFICACION_CLIENTE.clinv_usumod
  is 'USUARIO DE MODIFICACIÓN.';
comment on column OPERACION.SGAT_NOTIFICACION_CLIENTE.clind_fecmod
  is 'FECHA DE MODIFICACIÓN.';