-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_TRAMA_POSTV_DET
(
  TPOSTD_TRAMAID       NUMBER NOT NULL,
  TPOSTD_ORDEN         NUMBER NOT NULL,
  TPOSTD_COLUMN_NAME   VARCHAR2(100) NOT NULL,
  TPOSTD_COLUMN_TYPE   VARCHAR2(100) NOT NULL,
  TPOSTD_NIVEL         VARCHAR2(400) NOT NULL,
  TPOSTD_DESCRIPTION   VARCHAR2(400) NOT NULL,
  TPOSTD_ESTADO        NUMBER,
  TPOSTD_FLG_TABLE     NUMBER
)
tablespace OPERACION_DAT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
