-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_POSTV_SERV
(
  IDINTERACCION      NUMBER,
  ID_POSTV_SERV      NUMBER,
  SERVICIO           VARCHAR2(50),
  IDGRUPO_PRINCIPAL  VARCHAR2(50),
  IDGRUPO            VARCHAR2(50),
  CANTIDAD_INSTANCIA VARCHAR2(12),
  DSCSRV             VARCHAR2(200),
  BANDWID            VARCHAR2(50),
  FLAG_LC            VARCHAR2(50),
  CANTIDAD_IDLINEA   VARCHAR2(12),
  TIPEQU             VARCHAR2(50),
  CODTIPEQU          VARCHAR2(50),
  CANTIDAD           VARCHAR2(12),
  DSCEQU             VARCHAR2(200),
  CODIGO_EXT         VARCHAR2(50),
  FECUSU             DATE DEFAULT SYSDATE,
  CODUSU             VARCHAR2(30) DEFAULT USER,
  SNCODE             VARCHAR2(30),
  SPCODE             VARCHAR2(30),
  CARGOFIJO          NUMBER(10,2),
  CODSOLOT           NUMBER(8),
  FLAG_ACCION        VARCHAR2(3),
  CODINSSRV          NUMBER,
  NUM_SERIE          VARCHAR2(100),
  ASOC               VARCHAR2(3)
)
tablespace OPERACION_DAT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_POSTV_SERV.IDINTERACCION
  IS 'IDENTIFICADOR DE TRANSACCION';
COMMENT ON COLUMN OPERACION.SGAT_POSTV_SERV.ID_POSTV_SERV
  IS 'IDENTIFICADOR UNICO DE LA TABLA';
