-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_EF_EQUIPO_CNFG_LOG
(
  EEQLN_ID     NUMBER(5),
  EEQLV_NOMC   VARCHAR2(30),
  EEQLV_DCAM   VARCHAR2(2000),
  EEQLV_DESC   VARCHAR2(120),
  EEQLV_USUREG VARCHAR2(30) DEFAULT USER,
  EEQLD_FECREG DATE DEFAULT SYSDATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLN_ID
  IS 'ID.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLV_NOMC
  IS 'NOMBRE DE COLUMNA.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLV_DCAM
  IS 'DESCRIPCIÓN DEL CAMBIO REALIZADO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLV_DESC
  IS 'DESCRIPCIÓN DE COLUMNA.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_CNFG_LOG.EEQLD_FECREG
  IS 'FECHA DE REGISTRO.';

