-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_PROCESO_ENVIO_MAIL
(
  PEMN_IDMSJ   NUMBER(3) NOT NULL,
  PEMV_ASUNTO  VARCHAR2(200) NOT NULL,
  PEMV_CUERPO  VARCHAR2(1000) NOT NULL,
  PEMN_INTENTO NUMBER(1) NOT NULL,
  PEMN_ESTMSJ  NUMBER(1) NOT NULL,
  PEMV_USUREG  VARCHAR2(30) NOT NULL,
  PEMD_FECREG  DATE NOT NULL,
  PEMV_USUMOD  VARCHAR2(30),
  PEMD_FECMOD  DATE,
  PEMV_FROM    VARCHAR2(200) NOT NULL
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMN_IDMSJ
  IS 'CÓDIGO DE MENSAJE.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMV_ASUNTO
  IS 'ASUNTO DEL CORREO ENVIADO O RECEPCIONADO,CORREO QUE CONTENDRÁ EL ARCHIVO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMV_CUERPO
  IS 'MENSAJE DE CORREO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMN_INTENTO
  IS 'NÚMERO DE INTENTOS PARA ENVIAR EL CORREO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMN_ESTMSJ
  IS 'ESTADO DEL MENSAJE. 1-ACTIVO,0-INACTIVO';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_ENVIO_MAIL.PEMV_FROM
  IS 'CORREO DEL REMITENTE.';
