-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_PROCESO_LIC_DET
(
  LICDC_NUMSLC      CHAR(10) NOT NULL,
  LICDN_CID         NUMBER(10) NOT NULL,
  LICDI_SECUENCIA   INTEGER NOT NULL,
  LICDC_CODMODELO   CHAR(15),
  LICDV_NUMSERIE    VARCHAR2(50),
  LICDV_DESCRIPCION VARCHAR2(250),
  LICDC_CODMAT      CHAR(15),
  LICDI_UBICACION   INTEGER DEFAULT 0,
  LICDC_CODEST      CHAR(3),
  LICDC_CODPVC      CHAR(3),
  LICDC_CODDST      CHAR(10),
  LICDV_DIRECCION   VARCHAR2(250),
  LICDI_TIPOSRV     INTEGER DEFAULT 3,
  LICDI_CODPROV     INTEGER,
  LICDD_FECINICIO   DATE,
  LICDD_FECFIN      DATE,
  LICDV_NOMBRE      VARCHAR2(250),
  LICDC_NUMEROOC    CHAR(20),
  LICDI_POSICIONOC  INTEGER,
  LICDI_ESTADO      INTEGER DEFAULT 0,
  LICDV_OBSERVACION VARCHAR2(250),
  LICDV_USUREG      VARCHAR2(30) DEFAULT USER,
  LICDD_FECREG      DATE DEFAULT SYSDATE,
  LICDV_USUMOD      VARCHAR2(30),
  LICDD_FECMOD      DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_NUMSLC
  IS 'NÚMERO DEL PROYECTO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDN_CID
  IS 'CIRCUITO ID.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_SECUENCIA
  IS 'NÚMERO DE SECUENCIA.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_CODMODELO
  IS 'CÓDIGO DE MODELO DEL EQUIPO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_NUMSERIE
  IS 'NÚMERO DE SERIE DEL EQUIPO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_DESCRIPCION
  IS 'DESCRIPCIÓN DEL MANTENIMIENTO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_CODMAT
  IS 'CÓDIGO DE MATERIAL DEL EQUIPO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_UBICACION
  IS '0: ALMACEN CLARO 1: CLIENTE 2: PROVEEDOR 3: MARCA (OPEDD)';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_CODEST
  IS 'DEPARTAMENTO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_CODPVC
  IS 'PROVINCIA.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_CODDST
  IS 'DISTRITO - CÓDIGO DE UBIGEO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_DIRECCION
  IS 'DIRECCIÓN ACTUAL DEL CLIENTE.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_TIPOSRV
  IS '0: INICIO. 1:SPARE 2: RMA 3: NO EQUIPO. (OPEDD)';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_CODPROV
  IS 'CÓDIGO DEL PROVEEDOR.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDD_FECINICIO
  IS 'FECHA DE INICIO';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDD_FECFIN
  IS 'FECHA FIN';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_NOMBRE
  IS 'DESCRIPCIÓN';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDC_NUMEROOC
  IS 'NÚMERO DE ORDEN DE COMPRA.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_POSICIONOC
  IS 'POSICIÓN DE LA ORDEN DE COMPRA.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDI_ESTADO
  IS '0: ACTIVO 1: VENCIDO. (OPEDD)';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_OBSERVACION
  IS 'DESCRIPCIÓN DEL PROCESO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_DET.LICDD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';

