-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_POSTV_SERV_EXT
(
  ID_POSTV_SERV     NUMBER NOT NULL,
  PSRVN_ATRIBUTO 	VARCHAR2(50) NOT NULL,
  PSRVN_VALOR       VARCHAR2(50),
  PSRVN_ORDEN       NUMBER,
  PSRVN_FECUSU      DATE DEFAULT SYSDATE,
  PSRVN_CODUSU      VARCHAR2(30) DEFAULT USER
)
tablespace OPERACION_DAT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_POSTV_SERV_EXT.ID_POSTV_SERV
  IS 'IDENTIFICADOR FK DE LA TABLA SGAT_POSTV_SERV(ID_POSTV_SERV)';