-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_EF_ETAPA_CNFG
(
  EFECN_ID       NUMBER(5) NOT NULL,
  EFESN_ID       NUMBER(5) NOT NULL,
  EFECV_CODPAR   CHAR(15) NOT NULL,
  EFECN_CANTIDAD NUMBER(5,2) NOT NULL,
  EFECN_MCMD     NUMBER(1) DEFAULT 0 NOT NULL,
  EFECN_DCMD     NUMBER(1) DEFAULT 0 NOT NULL,
  EFECN_MUMD     NUMBER(1) DEFAULT 0 NOT NULL,
  EFECN_ESTADO   NUMBER(1) DEFAULT 1 NOT NULL,
  EFECV_USUREG   VARCHAR2(30) DEFAULT USER NOT NULL,
  EFECD_FECREG   DATE DEFAULT SYSDATE NOT NULL,
  EFECV_USUMOD   VARCHAR2(30),
  EFECD_FECMOD   DATE,
  EFECN_TIPASG   NUMBER(1)
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_ID
  IS 'ID.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFESN_ID
  IS 'ID ETAPA SERVICIO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECV_CODPAR
  IS 'CÓDIGO DE PARTIDAS MO/MATERIALES.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_CANTIDAD
  IS 'CANTIDAD UNITARIA DE LA ACTIVIDAD.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_MCMD
  IS 'FLAG MISMO CLIENTE/MISMA DIRECCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_DCMD
  IS 'FLAG DIFERENTE CLIENTE/MISMA DIRECCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_MUMD
  IS 'FLAG MUFA MISMA DIRECCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_ESTADO
  IS 'ESTADO DE LA ACTIVIDAD POR ETAPA.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_TIPASG
  IS 'TIPO DE ASIGNACIÓN MANO DE OBRA/MATERIALES.';
