-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_PROCESO_LIC_SOP_MAIL
(
  LICSI_ID_LIC    INTEGER NOT NULL,
  LICSV_CORREOLIC VARCHAR2(120) NOT NULL,
  LICSN_ESTADOLIC NUMBER(1) DEFAULT 0 NOT NULL,
  LICSV_USUREG    VARCHAR2(30) DEFAULT USER NOT NULL,
  LICSD_FECREG    DATE DEFAULT SYSDATE NOT NULL,
  LICSV_USUMOD    VARCHAR2(30),
  LICSD_FECMOD    DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSI_ID_LIC
  IS 'IDENTIFICACOR DE LA LICENCIA O SOPORTE.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSV_CORREOLIC
  IS 'CORREO DEL PROVEEDOR.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSN_ESTADOLIC
  IS 'ESTADO DEL CORREO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_SOP_MAIL.LICSD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';
