-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_EF_EQUIPO_SRVC
(
  EFEQN_ID          NUMBER(5) NOT NULL,
  EFEQV_DESCRIPCION VARCHAR2(50) NOT NULL,
  EFEQN_ESTADO      NUMBER(1) DEFAULT 1 NOT NULL,
  EFEQV_USUREG      VARCHAR2(30) DEFAULT USER NOT NULL,
  EFEQD_FECREG      DATE DEFAULT SYSDATE NOT NULL,
  EFEQV_USUMOD      VARCHAR2(30),
  EFEQD_FECMOD      DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQN_ID
  IS 'ID.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQV_DESCRIPCION
  IS 'DESCRIPCIÓN DE MODELO EQUIPO DE ACCESO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQN_ESTADO
  IS 'ESTADO DE EQUIPO DE ACCESO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';
