-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_EF_ETAPA_CNFG_LOG
(
  EECLN_ID     NUMBER(5) NOT NULL,
  EECLV_NOMC   VARCHAR2(30) NOT NULL,
  EECLV_DCAM   VARCHAR2(2000) NOT NULL,
  EECLV_DESC   VARCHAR2(120) NOT NULL,
  EECLV_USUREG VARCHAR2(30) DEFAULT USER,
  EECLD_FECREG DATE DEFAULT SYSDATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLN_ID
  IS 'ID.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLV_NOMC
  IS 'NOMBRE DE COLUMNA.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLV_DCAM
  IS 'DESCRIPCIÓN DEL CAMBIO REALIZADO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLV_DESC
  IS 'DESCRIPCIÓN DE COLUMNA.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG_LOG.EECLD_FECREG
  IS 'FECHA DE REGISTRO.';
