-- CREATE TABLE
CREATE TABLE OPERACION.SGAT_PROCESO_LIC_CAB
(
  LCABC_NUMSLC         CHAR(10) NOT NULL,
  LCABC_CODCLI         CHAR(8) NOT NULL,
  LCABV_DESCSOLUCION   VARCHAR2(4000),
  LCABD_FECINICONTRATO DATE,
  LCABI_DURACION       INTEGER,
  LCABD_FECFINCONTRATO DATE,
  LCABV_ADP            VARCHAR2(50),
  LCABV_INGPREVTA      VARCHAR2(50),
  LCABI_CONTPREVIO     INTEGER DEFAULT 0,
  LCABV_USUREG         VARCHAR2(30) DEFAULT USER,
  LCABD_FECREG         DATE DEFAULT SYSDATE,
  LCABV_USUMOD         VARCHAR2(30),
  LCABD_FECMOD         DATE
)
TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABC_NUMSLC
  IS 'NÚMERO DE PROYECTO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABC_CODCLI
  IS 'CÓDIGO DEL CLIENTE.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABV_DESCSOLUCION
  IS 'DESCRIPCIÓN DE LA SOLUCIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABD_FECINICONTRATO
  IS 'FECHA DE INICIO DE CONTRATO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABI_DURACION
  IS 'DURACIÓN';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABD_FECFINCONTRATO
  IS 'FECHA DE FIN DE CONTRATO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABV_INGPREVTA
  IS 'INGENIERO DE PREVENTA.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABI_CONTPREVIO
  IS 'EXISTE CONTRATO PREVIO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABV_USUREG
  IS 'USUARIO DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABD_FECREG
  IS 'FECHA DE REGISTRO.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABV_USUMOD
  IS 'USUARIO DE MODIFICACIÓN.';
COMMENT ON COLUMN OPERACION.SGAT_PROCESO_LIC_CAB.LCABD_FECMOD
  IS 'FECHA DE MODIFICACIÓN.';


