CREATE TABLE OPERACION.SOLOTPTOETAPER
(
  CODPERMISO       NUMBER(10)                   NOT NULL,
  CODSOLOT         NUMBER(8)                    NOT NULL,
  PUNTO            NUMBER(10)                   NOT NULL,
  ORDEN            NUMBER(5)                    NOT NULL,
  TIPAUTORIZACION  NUMBER(2),
  CODUBI           CHAR(10 BYTE),
  NROPERMISO       VARCHAR2(50 BYTE),
  EXPEDIENTE       VARCHAR2(50 BYTE),
  FECINGRESO       DATE,
  MTOCAJA          NUMBER(10,2),
  MTOCHEQUE        NUMBER(10,2),
  OBSERVACION      VARCHAR2(200 BYTE),
  FECUSU           DATE                         DEFAULT SYSDATE,
  CODUSU           VARCHAR2(30 BYTE)            DEFAULT USER
);

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.CODPERMISO IS 'Código de la tabla';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.CODSOLOT IS 'Código de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.PUNTO IS 'Punto de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.TIPAUTORIZACION IS 'Tipo de autorización';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.CODUBI IS 'Código de ubigeo';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.NROPERMISO IS 'Nro. de permiso';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.EXPEDIENTE IS 'Nro. de Expediente';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.FECINGRESO IS 'Fecha de ingreso del permiso';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.MTOCAJA IS 'Monto de caja';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.MTOCHEQUE IS 'Monto de cheque';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAPER.OBSERVACION IS 'Observación del permiso';


