CREATE TABLE OPERACION.SOLOTPTO_ID_HISTORICO
(
  CODSOLOT         NUMBER(8)                    NOT NULL,
  PUNTO            NUMBER(10)                   NOT NULL,
  HISTORICO        NUMBER(8)                    NOT NULL,
  MEDIO            VARCHAR2(50 BYTE),
  ESTADO           VARCHAR2(30 BYTE),
  FECASIG_COM      DATE,
  RESPONSABLE_COM  VARCHAR2(30 BYTE),
  FECASIG_PI       DATE,
  RESPONSABLE_PI   VARCHAR2(30 BYTE),
  FECPEX           DATE,
  FECDIS_PI        DATE,
  FECFIN_PI        DATE,
  FECLINK_PI       DATE,
  FLG_COM          NUMBER(1)                    DEFAULT 0,
  FLG_PI           NUMBER(1)                    DEFAULT 0,
  FECCFG_DAT       DATE,
  FECCFG_VOZ       DATE,
  FECPRU_SRV       DATE,
  FECINS_EQU_TMP   DATE,
  FECINS_EQU_DEF   DATE,
  FECRET_EQU       DATE,
  FECVIS_PI        DATE,
  FECVIS_COM       DATE,
  FECACTA_INS      DATE,
  FECACTA_SRV      DATE,
  FECACTA_RET      DATE,
  FECDOC           DATE,
  FLGDOC           NUMBER(1)                    DEFAULT 0                     NOT NULL,
  RESPONSABLE_DOC  VARCHAR2(30 BYTE),
  ESTDOCOPE        NUMBER(2),
  FLGDOC_CONF      NUMBER(1)                    DEFAULT 0                     NOT NULL,
  FLGDOC_DESC      NUMBER(1)                    DEFAULT 0                     NOT NULL,
  FLGDOC_GRAF      NUMBER(1)                    DEFAULT 0                     NOT NULL,
  FECDOC_CONF      DATE,
  FECDOC_DESC      DATE,
  FECDOC_GRAF      DATE,
  FECPROG          DATE,
  PRIORIZADO       VARCHAR2(30 BYTE),
  FECPRIOR         DATE,
  NROREQ           VARCHAR2(100 BYTE),
  OBSERVACION      VARCHAR2(400 BYTE)
);

COMMENT ON TABLE OPERACION.SOLOTPTO_ID_HISTORICO IS 'Log de las programaciones de instalaciones';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.PUNTO IS 'Punto de la solicitud de ot';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.HISTORICO IS 'Id de la tabla';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.MEDIO IS 'Medio de transporte';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.ESTADO IS 'Estado de la programacion';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECASIG_COM IS 'Fecha de asignación de comunicación';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.RESPONSABLE_COM IS 'Responsable de comunicación';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECASIG_PI IS 'Fecha de asignación de planta interna';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.RESPONSABLE_PI IS 'Responsable de planta interna';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECPEX IS 'Fecha de planta externa';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECDIS_PI IS 'Fecha de diseño de planta interna';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECFIN_PI IS 'Fecha de fin de planta interna';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECLINK_PI IS 'Fecha de instalacion del equipo';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLG_COM IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLG_PI IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECCFG_DAT IS 'Fecha de configuración de datos';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECCFG_VOZ IS 'Fecha de configuración de voz';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECPRU_SRV IS 'Fecha de prueba del servicio';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECINS_EQU_TMP IS 'Fecha de instalacion del equipo temporal';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECINS_EQU_DEF IS 'Fecha de instalacion del equipo';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECRET_EQU IS 'Fecha de retiro del equipo';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECVIS_PI IS 'Fecha de visita de planta interna';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECVIS_COM IS 'Fecha de visita de comunicacion';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECACTA_INS IS 'Fecha de acta de instalacion';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECACTA_SRV IS 'Fecha de acta de servcio';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECACTA_RET IS 'Fecha de acta de retiro';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECDOC IS 'Fecha de documento';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLGDOC IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.RESPONSABLE_DOC IS 'Responsable de la documentación';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.ESTDOCOPE IS 'Estado del documento de operaciones';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLGDOC_CONF IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLGDOC_DESC IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FLGDOC_GRAF IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECDOC_CONF IS 'Fecha de documento de configuración';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECDOC_DESC IS 'Fecha de documento de descripcion';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECDOC_GRAF IS 'Fecha de documento de grafico';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECPROG IS 'Fecha de programación';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.PRIORIZADO IS 'Indica la priorizacion';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.FECPRIOR IS 'Fecha de priorización';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.NROREQ IS 'Numero de requerimiento';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_HISTORICO.OBSERVACION IS 'Observación';


