CREATE TABLE OPERACION.SOLOTPTOPOS
(
  CODSOLOT     NUMBER(8)                        NOT NULL,
  PUNTO        NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(10)                       NOT NULL,
  POSTE        VARCHAR2(30 BYTE),
  PROPIETARIO  VARCHAR2(30 BYTE),
  TIPO         VARCHAR2(30 BYTE),
  TAMANO       NUMBER(4),
  CODUBI       CHAR(10 BYTE),
  OBSERVACION  VARCHAR2(500 BYTE),
  FLGPROY      NUMBER(1)                        DEFAULT 0                     NOT NULL,
  USO          NUMBER(4),
  DIRECCION    VARCHAR2(30 BYTE),
  ESTADO       NUMBER(2),
  ESTADOPOSTE  NUMBER(2)
);

COMMENT ON TABLE OPERACION.SOLOTPTOPOS IS 'Listado de postes por cada detalle de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.PUNTO IS 'Punto de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.ORDEN IS 'Orden de la tabla';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.POSTE IS 'Numero de poste';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.PROPIETARIO IS 'Propietario';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.TIPO IS 'Tipo de poste';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.TAMANO IS 'Tamaño del poste';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.CODUBI IS 'Codigo del distrito';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.SOLOTPTOPOS.FLGPROY IS 'No se utiliza';


