CREATE TABLE OPERACION.SOLOTPTOETAFAC
(
  CODSOLOT     NUMBER(8)                        NOT NULL,
  PUNTO        NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(5)                        NOT NULL,
  ORDENCMP     NUMBER(5)                        NOT NULL,
  CODETA       NUMBER(5),
  FACTURA      NUMBER(8),
  MONTOMO      NUMBER(10,2),
  MONTOMAT     NUMBER(10,2),
  OBSERVACION  VARCHAR2(500 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.SOLOTPTOETAFAC IS 'Listado de facturas por cada etapa del detalle de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.PUNTO IS 'Punto de la solicitud de ot';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.ORDEN IS 'Orden de la tabla factura ';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.ORDENCMP IS 'Orden del componente de la tabla factura ';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.CODETA IS 'Codigo de la etapa';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.FACTURA IS 'Numero de factura';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.MONTOMO IS 'Monto de mano de obra';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.MONTOMAT IS 'Monto de material';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFAC.FECUSU IS 'Fecha de registro';


