CREATE TABLE OPERACION.SOLOTPTODOC
(
  CODSOLOT     NUMBER(8)                        NOT NULL,
  PUNTO        NUMBER(10)                       NOT NULL,
  ORDEN        NUMBER(5)                        NOT NULL,
  CODINSSRV    NUMBER(10),
  TIPDOC       NUMBER(2),
  ESTADO       NUMBER(2),
  DESCRIPCION  VARCHAR2(100 BYTE),
  OBSERVACION  VARCHAR2(500 BYTE),
  FLGFASE      NUMBER(2),
  CODCON       NUMBER(6),
  DATA         BLOB,
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user,
  FECUSU       DATE                             DEFAULT sysdate,
  MONTOTOTAL   NUMBER(10,2)
);

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.CODSOLOT IS 'Nro de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.PUNTO IS 'Punto de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.CODINSSRV IS 'SID';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.TIPDOC IS 'Tipo de documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.ESTADO IS 'Estado del documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.DESCRIPCION IS 'Descripción del documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.OBSERVACION IS 'Observacion del documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.FLGFASE IS 'Fase del documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.CODCON IS 'Contratista responsable del documento';

COMMENT ON COLUMN OPERACION.SOLOTPTODOC.DATA IS 'Descripción del documento';


