CREATE TABLE OPERACION.SOLOTPTOETA_LOG
(
  FECEJE    DATE,
  USUMOD    VARCHAR2(30 BYTE),
  ID        NUMBER(25),
  ESTANT    NUMBER(2),
  ESTNUE    NUMBER(2),
  CODSOLOT  NUMBER(8),
  PUNTO     NUMBER(10),
  ORDEN     NUMBER(4),
  CODETA    NUMBER(5),
  TIPO      VARCHAR2(1 BYTE),
  CODCON    NUMBER(6),
  IDLIQANT  NUMBER,
  IDLIQNUE  NUMBER
);


