CREATE TABLE OPERACION.SOLOTPTO_ID_REQ
(
  IDNROREQ  NUMBER(10),
  CODSOLOT  NUMBER(8),
  PUNTO     NUMBER(10),
  NROREQ    VARCHAR2(100 BYTE),
  AREA      NUMBER(4),
  FLGREQ    NUMBER(2),
  CODUSU    VARCHAR2(30 BYTE)                   DEFAULT USER,
  FECUSU    DATE                                DEFAULT SYSDATE
);


