CREATE TABLE OPERACION.SOLOTPTOETAFOR
(
  CODSOLOT  NUMBER(8)                           NOT NULL,
  PUNTO     NUMBER(10)                          NOT NULL,
  CODETA    NUMBER(5)                           NOT NULL,
  CODFOR    NUMBER(5)                           NOT NULL,
  CANTIDAD  NUMBER(8,2)                         DEFAULT 0                     NOT NULL,
  FECUSU    DATE                                DEFAULT SYSDATE               NOT NULL,
  CODUSU    VARCHAR2(30 BYTE)                   DEFAULT USER                  NOT NULL
);

COMMENT ON TABLE OPERACION.SOLOTPTOETAFOR IS 'FORMULA POR SOLOT';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.CODSOLOT IS 'CODIGO DEL SOLOT';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.PUNTO IS 'PUNTO DE LA ORDEN DE LA SOLOT';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.CODETA IS 'CODIGO DE LA ETAPA';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.CODFOR IS 'CODIGO DE LA FORMULA';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.CANTIDAD IS 'CANTIDAD DE EQUIPO EN LA FORMULA';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.FECUSU IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN OPERACION.SOLOTPTOETAFOR.CODUSU IS 'CODIGO DE USUARIO QUE REGISTRO';


