CREATE TABLE OPERACION.SOLOT_PEP_ANTERIOR
(
  NUMSLC        VARCHAR2(10 BYTE),
  SID           NUMBER,
  ITEM          VARCHAR2(122 BYTE),
  ELEMENTO_PEP  VARCHAR2(40 BYTE),
  RUBINV        CHAR(2 BYTE),
  CTGINV        CHAR(3 BYTE),
  TIPCOM        VARCHAR2(3 BYTE),
  UBICACION     VARCHAR2(30 BYTE),
  CODMAT        VARCHAR2(15 BYTE)
);


