CREATE TABLE OPERACION.SOLOTPTO_ID_LOG_AGE
(
  CODSOLOT        NUMBER(8)                     NOT NULL,
  PUNTO           NUMBER(10)                    NOT NULL,
  ORDEN           NUMBER                        NOT NULL,
  FECREAGENDA     DATE                          DEFAULT sysdate               NOT NULL,
  USUREAGENDA     VARCHAR2(30 BYTE)             DEFAULT user                  NOT NULL,
  CODCONREAGENDA  NUMBER
);

COMMENT ON TABLE OPERACION.SOLOTPTO_ID_LOG_AGE IS 'Tabla de Log de Asignacion de Contrata';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.PUNTO IS 'Punto de la solicitud';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.ORDEN IS 'Secuencia de Orden';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.FECREAGENDA IS 'Fecha de Reagenda';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.USUREAGENDA IS 'Usuario de Reagenda';

COMMENT ON COLUMN OPERACION.SOLOTPTO_ID_LOG_AGE.CODCONREAGENDA IS 'Contrata asignada';


