CREATE TABLE OPERACION.SOTS_PENDIENTES_ITW
(
  CODCLI                 CHAR(8 BYTE)           NOT NULL,
  NOMCLI                 VARCHAR2(200 BYTE),
  CODSOLOT               NUMBER(8)              NOT NULL,
  TIPSRV                 CHAR(4 BYTE),
  DSCTIPSRV              VARCHAR2(50 BYTE),
  TIPTRA                 NUMBER(4),
  DESCRIPCION_TIPTRA     VARCHAR2(200 BYTE),
  ESTSOL                 NUMBER(2),
  DESCRIPCION_ESTSOL     VARCHAR2(100 BYTE),
  TIP_SERV               VARCHAR2(100 BYTE),
  ESTADO_ITW             VARCHAR2(100 BYTE),
  FLG_ACTUAL             NUMBER(1)              DEFAULT 0                     NOT NULL,
  FECGEN_SOT             DATE                   NOT NULL,
  FECUSU                 DATE                   DEFAULT SYSDATE               NOT NULL,
  CODUSU                 VARCHAR2(30 BYTE)      DEFAULT user                  NOT NULL,
  CINTILLO               VARCHAR2(15 BYTE),
  DIRECCION              VARCHAR2(480 BYTE),
  DISTRITO               VARCHAR2(40 BYTE),
  PROVINCIA              VARCHAR2(40 BYTE),
  DEPARTAMENTO           VARCHAR2(40 BYTE),
  PLANO                  VARCHAR2(10 BYTE),
  DOCUMENTO_TRANSACCION  CHAR(20 BYTE),
  FEC_VEN_DOCUMENTO      DATE,
  SALDO_DOCUMENTO        NUMBER(18,4),
  URBANIZACION           VARCHAR2(50 BYTE)
);

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.CODCLI IS 'Codigo del cliente';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.NOMCLI IS 'Nombre del cliente';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.CODSOLOT IS 'Codigo de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.TIPSRV IS 'Tipo de servicio';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DSCTIPSRV IS 'Descripción del tipo de servicio';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.TIPTRA IS 'Tipo de trabajo de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DESCRIPCION_TIPTRA IS 'Descripcion del tipo de trabajo de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.ESTSOL IS 'Estado de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DESCRIPCION_ESTSOL IS 'Descripcion del estado de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.TIP_SERV IS 'Tipo de servicio, Digital o Hibrido';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.ESTADO_ITW IS 'Estado en Intraway, Manual o Regularizado';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.FLG_ACTUAL IS 'Flag actual, indica si el registro pertenece al reporte actual';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.FECGEN_SOT IS 'Fecha de generacion de la sot';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.CINTILLO IS 'cintillo';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DIRECCION IS 'Direccion de la SOT';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DISTRITO IS 'Distrito';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.PROVINCIA IS 'Provincia';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DEPARTAMENTO IS 'Departamento';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.PLANO IS 'Plano';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.DOCUMENTO_TRANSACCION IS 'Documento que genera transaccion';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.FEC_VEN_DOCUMENTO IS 'Fecha de Vencimiento del Documento que genera la transaccion';

COMMENT ON COLUMN OPERACION.SOTS_PENDIENTES_ITW.SALDO_DOCUMENTO IS 'Saldo Actual del Documento';


