CREATE TABLE OPERACION.SUCURSALXCONTRATA
(
  IDSUCXCONTRATA  NUMBER(6)                     NOT NULL,
  CODCON          NUMBER(6)                     NOT NULL,
  DESCRIPCION     VARCHAR2(200 BYTE),
  DIRECCION       VARCHAR2(200 BYTE),
  CODUBI          CHAR(10 BYTE),
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT USER,
  FECUSU          DATE                          DEFAULT SYSDATE
);

COMMENT ON TABLE OPERACION.SUCURSALXCONTRATA IS 'Sucursales por Contrata';

COMMENT ON COLUMN OPERACION.SUCURSALXCONTRATA.IDSUCXCONTRATA IS 'ID Sucursal Por contrata';

COMMENT ON COLUMN OPERACION.SUCURSALXCONTRATA.CODCON IS 'Codigo de Contrata';

COMMENT ON COLUMN OPERACION.SUCURSALXCONTRATA.DESCRIPCION IS 'Descripcion de Sucursal de Contrata';

COMMENT ON COLUMN OPERACION.SUCURSALXCONTRATA.DIRECCION IS 'Direccion de Sucursal de Contrata';

COMMENT ON COLUMN OPERACION.SUCURSALXCONTRATA.CODUBI IS 'UBIGEO de la sucursal de contrata';


