CREATE TABLE OPERACION.T_CENTRALES
(
  ID_CENTRAL  VARCHAR2(50 BYTE),
  CENTRAL     VARCHAR2(50 BYTE),
  USUARIO     VARCHAR2(50 BYTE),
  PASSWORD    VARCHAR2(50 BYTE),
  IP          VARCHAR2(50 BYTE),
  PUERTO      VARCHAR2(50 BYTE)
);


