CREATE TABLE OPERACION.T_CMD
(
  IDCMD          NUMBER                         NOT NULL,
  ID_CENTRAL     NUMBER,
  ID_ORDEN       VARCHAR2(50 BYTE),
  TIPO_ORDEN     VARCHAR2(200 BYTE),
  CX             VARCHAR2(50 BYTE),
  CMD1           VARCHAR2(1000 BYTE),
  CMD2           VARCHAR2(1000 BYTE),
  CMD3           VARCHAR2(1000 BYTE),
  CMD4           VARCHAR2(4000 BYTE),
  CMD5           VARCHAR2(4000 BYTE),
  CMD6           VARCHAR2(4000 BYTE),
  CMD7           VARCHAR2(4000 BYTE),
  TIPO_SERVICIO  VARCHAR2(50 BYTE),
  CODMOTOT       NUMBER(3),
  TIPTRA         NUMBER(4)
);

COMMENT ON COLUMN OPERACION.T_CMD.IDCMD IS 'Id comando';


