CREATE TABLE OPERACION.T_TEMP_ACT_EFEQU_STD
(
  IDPAQ      NUMBER,
  PUNTO      NUMBER,
  ORDEN      NUMBER,
  ORDENCMP   NUMBER,
  CANTIDAD   NUMBER,
  CODTIPEQU  CHAR(15 BYTE),
  TIPEQU     NUMBER,
  COSTO      NUMBER
);


