/*-----------CREACION DE LA TABLA MAESTRO_SERIES_EQU_DET------------*/
CREATE TABLE OPERACION.MAESTRO_SERIES_EQU_DET
(
  IDSEQ        NUMBER,
  CODIGO_SAP   VARCHAR2(20), 
  NRO_SERIE    VARCHAR2(50), 
  DNI          VARCHAR2(20),
  MTA_MAC_CM   VARCHAR2(50), 
  MTA_MAC_MTA  VARCHAR2(50), 
  UNIT_ADDRESS VARCHAR2(50),
  FECHA_CARGA  DATE         DEFAULT SYSDATE,
  IPAPLICACION VARCHAR2(30) DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS'),
  PCAPLICACION VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'TERMINAL'),
  CODUSU       VARCHAR2(30) DEFAULT USER,
  FECUSU       DATE         DEFAULT SYSDATE
);

tablespace OPERACION_DAT
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
  
COMMENT ON TABLE OPERACION.MAESTRO_SERIES_EQU_DET
IS 'Tabla de carga masiva de inventarios';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.IDSEQ
IS 'Identificador de secuencia';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.CODIGO_SAP
IS 'Código SAP';

COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.NRO_SERIE
IS 'Número de serie';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.DNI
IS 'DNI de técnico';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.MTA_MAC_CM
IS 'MAC address para internet';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.MTA_MAC_MTA
IS 'MAC address para telefonía';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.UNIT_ADDRESS
IS 'Unit address';
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.FECHA_CARGA
IS 'Fecha de carga'; 
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.IPAPLICACION
IS 'IP'; 
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.PCAPLICACION
IS 'Nombre de PC'; 
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.CODUSU
IS 'Código de usuario'; 
 
COMMENT ON COLUMN OPERACION.MAESTRO_SERIES_EQU_DET.FECUSU
IS 'Fecha de usuario';
 
ALTER TABLE operacion.maestro_series_equ_det
ADD CONSTRAINT pk_maestro_series_equ_det PRIMARY KEY (idseq);



 
 
