CREATE TABLE OPERACION.CLRHT_TRMODELO 
   (  TRV_MODELO VARCHAR2(50) NOT NULL ENABLE, 
  TRV_GRUPO VARCHAR2(100) NOT NULL ENABLE, 
  TRV_ESTADO VARCHAR2(100) NOT NULL ENABLE, 
  TRV_BANDA VARCHAR2(50)
   );
COMMENT ON COLUMN OPERACION.CLRHT_TRMODELO.TRV_MODELO IS 'Modelo CM';
COMMENT ON COLUMN OPERACION.CLRHT_TRMODELO.TRV_GRUPO IS 'Grupo de modelo CM';
COMMENT ON COLUMN OPERACION.CLRHT_TRMODELO.TRV_ESTADO IS '(1: Liberada, 2: No disponible para consulta API)';
COMMENT ON COLUMN OPERACION.CLRHT_TRMODELO.TRV_BANDA IS '(1: 2.4Ghz, 2: 5Ghz, 3:Dual Band)';