CREATE TABLE OPERACION.TIPDOCARCH
(
  TIPDOCARCH   NUMBER(2)                        NOT NULL,
  DESCRIPCION  VARCHAR2(200 BYTE)               NOT NULL,
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT user                  NOT NULL,
  FECUSU       DATE                             DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE OPERACION.TIPDOCARCH IS 'No es usada';

COMMENT ON COLUMN OPERACION.TIPDOCARCH.TIPDOCARCH IS 'Tipo de documento del archivo';

COMMENT ON COLUMN OPERACION.TIPDOCARCH.DESCRIPCION IS 'No se utiliza';

COMMENT ON COLUMN OPERACION.TIPDOCARCH.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.TIPDOCARCH.FECUSU IS 'Fecha de registro';


