CREATE TABLE OPERACION.TIPESTSOL
(
  TIPESTSOL    NUMBER(2)                        NOT NULL,
  DESCRIPCION  VARCHAR2(30 BYTE)
);

COMMENT ON TABLE OPERACION.TIPESTSOL IS 'Tipos de estados para las SOT';

COMMENT ON COLUMN OPERACION.TIPESTSOL.TIPESTSOL IS 'Tipo de estado de la solicitud';

COMMENT ON COLUMN OPERACION.TIPESTSOL.DESCRIPCION IS 'Descripcion del tipo de estado de solicitud';


