CREATE TABLE OPERACION.TIPEQU
(
  CODTIPEQU      CHAR(15 BYTE),
  ESTEQU         NUMBER(2)                      NOT NULL,
  DESCRIPCION    VARCHAR2(100 BYTE)             NOT NULL,
  COSTO          NUMBER(10,2)                   DEFAULT 0                     NOT NULL,
  TIPEQU         NUMBER(6)                      NOT NULL,
  COSTO_REAL     NUMBER(10,2),
  GRPTIPEQU      NUMBER(2),
  ABREV          VARCHAR2(30 BYTE),
  TIPO           VARCHAR2(30 BYTE),
  MONEDA_ID      NUMBER(10),
  TIPTEC         NUMBER(2),
  IDPROTOCOLO    NUMBER(2),
  NUMPORT        NUMBER(2),
  TIPO_MATERIAL  NUMBER(6),
  USUREG         VARCHAR2(30 BYTE)              DEFAULT user,
  FECREG         DATE                           DEFAULT sysdate
);

COMMENT ON TABLE OPERACION.TIPEQU IS 'Tipos de equipos';

COMMENT ON COLUMN OPERACION.TIPEQU.CODTIPEQU IS 'Codigo del tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.ESTEQU IS 'ESTEQU';

COMMENT ON COLUMN OPERACION.TIPEQU.DESCRIPCION IS 'Descripcion del tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.COSTO IS 'Costo del tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.TIPEQU IS 'Codigo de tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.COSTO_REAL IS 'Costo real del tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.GRPTIPEQU IS 'Tipo de grupo del equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.ABREV IS 'Abreviatura';

COMMENT ON COLUMN OPERACION.TIPEQU.TIPO IS 'Tipo de equipo';

COMMENT ON COLUMN OPERACION.TIPEQU.MONEDA_ID IS 'Codigo de la moneda';

COMMENT ON COLUMN OPERACION.TIPEQU.TIPTEC IS 'Tecnología Equipo TN - Plataforma CS2K';

COMMENT ON COLUMN OPERACION.TIPEQU.IDPROTOCOLO IS 'Protocolo Equipo TN - Plataforma CS2K';

COMMENT ON COLUMN OPERACION.TIPEQU.NUMPORT IS 'Numero de Puertos TN - Plataforma CS2K';

COMMENT ON COLUMN OPERACION.TIPEQU.USUREG IS 'Usuario que inserto el
registro';

COMMENT ON COLUMN OPERACION.TIPEQU.TIPO_MATERIAL IS 'Tipo de Material';

COMMENT ON COLUMN OPERACION.TIPEQU.FECREG IS 'Fecha que inserto el registro';


