CREATE TABLE OPERACION.TIPOTPTOXSERVICIO
(
  CODSRV    CHAR(4 BYTE)                        NOT NULL,
  TIPOTPTO  NUMBER(2)                           NOT NULL,
  FECUSU    DATE                                DEFAULT SYSDATE               NOT NULL,
  CODUSU    VARCHAR2(30 BYTE)                   DEFAULT user                  NOT NULL
);

COMMENT ON TABLE OPERACION.TIPOTPTOXSERVICIO IS 'No es usada';

COMMENT ON COLUMN OPERACION.TIPOTPTOXSERVICIO.CODSRV IS 'Codigo de servicio';

COMMENT ON COLUMN OPERACION.TIPOTPTOXSERVICIO.TIPOTPTO IS 'Tipo de punto';

COMMENT ON COLUMN OPERACION.TIPOTPTOXSERVICIO.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.TIPOTPTOXSERVICIO.CODUSU IS 'Codigo de Usuario registro';


