CREATE TABLE OPERACION.TIPOPROYECTO_DTH
(
  IDTIPO       NUMBER(2),
  DESCRIPCION  VARCHAR2(100 BYTE),
  CODUSU       VARCHAR2(30 BYTE)                DEFAULT USER,
  FECREG       DATE                             DEFAULT SYSDATE
);


