CREATE TABLE OPERACION.TIPPROYECTO
(
  TIPPROYECTO  NUMBER(2)                        NOT NULL,
  DESCRIPCION  VARCHAR2(30 BYTE)
);

COMMENT ON TABLE OPERACION.TIPPROYECTO IS 'Tipo de Proyecto de la Solucion, 1=DTH, 2=HFC';

COMMENT ON COLUMN OPERACION.TIPPROYECTO.TIPPROYECTO IS 'Tipo de Proyecto de la Solucion';

COMMENT ON COLUMN OPERACION.TIPPROYECTO.DESCRIPCION IS 'Descripcion del Tipo de Proyecto de la Solucion';


