CREATE TABLE OPERACION.TIPTRAINCIXPAQ
(
  TIPTRA      NUMBER,
  CODSUBTYPE  NUMBER,
  IDPAQ       NUMBER,
  ESTADO      NUMBER                            DEFAULT 1,
  FECREG      DATE                              DEFAULT SYSDATE,
  USUREG      VARCHAR2(30 BYTE)                 DEFAULT USER
);

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.TIPTRA IS 'Tipo de Trabajo';

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.CODSUBTYPE IS 'Sub Tipo de Incidencia';

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.IDPAQ IS 'Id Paquete de Venta';

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.ESTADO IS 'Estado';

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.FECREG IS 'Fecha de Registro';

COMMENT ON COLUMN OPERACION.TIPTRAINCIXPAQ.USUREG IS 'Usuario de Registro';


