CREATE TABLE OPERACION.TMP_PUERTOXEQUIPO
(
  CODPUERTO       NUMBER(8)                     NOT NULL,
  CODPRD          NUMBER(5),
  CID             NUMBER(10),
  CODEQUIPO       NUMBER(6),
  CODTARJETA      NUMBER(6),
  DESCRIPCION     VARCHAR2(200 BYTE),
  ESTADO          NUMBER(1)                     DEFAULT 1,
  TIPO            CHAR(3 BYTE),
  SERVICIO        VARCHAR2(30 BYTE),
  FECASIG         DATE,
  FECINST         DATE,
  CODUSU          VARCHAR2(30 BYTE)             DEFAULT user                  NOT NULL,
  FECUSU          DATE                          DEFAULT SYSDATE               NOT NULL,
  CODUSUMOD       VARCHAR2(30 BYTE)             DEFAULT user                  NOT NULL,
  FECUSUMOD       DATE                          DEFAULT SYSDATE               NOT NULL,
  PUERTO          VARCHAR2(30 BYTE),
  FLG_ESTR        NUMBER(1),
  FLG_CAS         NUMBER(1),
  TS_NOUTILIZADO  NUMBER(3),
  DIRATM          VARCHAR2(50 BYTE),
  FLG_TSLIBRE     NUMBER(1)                     DEFAULT 0                     NOT NULL
);

COMMENT ON TABLE OPERACION.TMP_PUERTOXEQUIPO IS 'No es usada';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODPUERTO IS 'Codigo del puerto';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODPRD IS 'Codigo del producto corporativo';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CID IS 'Circuito id';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODEQUIPO IS 'Codigo del equipo';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODTARJETA IS 'Codigo de la tarjeta';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.DESCRIPCION IS 'Descripcion del puerto';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.ESTADO IS 'Estado del puerto';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.TIPO IS 'Tipo de puerto';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.SERVICIO IS 'Descripcion del servicio';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FECASIG IS 'Fecha de asignación';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FECINST IS 'Fecha de instalacion';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.CODUSUMOD IS 'Registra el usuario que modifica un dato';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FECUSUMOD IS 'Fecha de modificacion';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.PUERTO IS 'Identificador del puerto';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FLG_ESTR IS 'Flg_estr';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FLG_CAS IS 'Flg_cas';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.TS_NOUTILIZADO IS 'Ts no utilizado';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.DIRATM IS 'Direccion atm';

COMMENT ON COLUMN OPERACION.TMP_PUERTOXEQUIPO.FLG_TSLIBRE IS 'Flg_tslibre';


