CREATE TABLE OPERACION.TMP_INTERFACE_SAPSGA_PEP2
(
  A_NUMSCL        CHAR(10 BYTE),
  A_CODSOLOT      NUMBER(8),
  A_CFG           CHAR(3 BYTE),
  A_DI_FEC_VTA    DATE,
  ESTADO          NUMBER(1),
  USUARIO         VARCHAR2(30 BYTE),
  FECHAREGISTRO   DATE,
  FECHAEJECUCION  DATE
);


