CREATE TABLE OPERACION.TMP_SOLOT_CODIGO
(
  CODSOLOT        NUMBER(8)                     NOT NULL,
  ESTADO          NUMBER(1)                     NOT NULL,
  USUARIO         VARCHAR2(30 BYTE),
  FECHAREGISTRO   DATE,
  FECHAEJECUCION  DATE,
  ESTSOLOT        NUMBER(2),
  OBSERVACION     VARCHAR2(100 BYTE)
);


