CREATE TABLE OPERACION.TMP_OPE_BOUQUETPROM
(
  NUMREGISTRO            CHAR(10 BYTE),
  BOUQUET                VARCHAR2(10 BYTE),
  SERIE                  VARCHAR2(30 BYTE),
  TIPO                   CHAR(1 BYTE),
  FECHA_INICIO_VIGENCIA  DATE,
  FECHA_FIN_VIGENCIA     DATE,
  FLG_TRANSFERIR         NUMBER(1)              DEFAULT 0,
  USUREG                 VARCHAR2(30 BYTE)      DEFAULT USER,
  FECREG                 DATE                   DEFAULT SYSDATE
);

COMMENT ON TABLE OPERACION.TMP_OPE_BOUQUETPROM IS 'Tabla temporal de Bouquets promocionales.';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.NUMREGISTRO IS 'Identificador de Número de registro.';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.BOUQUET IS 'Identificador de Bouquet.';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.SERIE IS 'Identificador de Serie de Equipo';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.TIPO IS 'Indetificador de Proceso de Alta (A) o Baja (B) de Bouquets';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.FECHA_INICIO_VIGENCIA IS 'Fecha de Inicio de Vigencia Bouquet';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.FECHA_FIN_VIGENCIA IS 'Fecha de Fin de Vigencia Bouquet';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.FLG_TRANSFERIR IS 'Flag de transferir 1: Transferido, 0: Por trasnferir';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.USUREG IS 'Usuario que insertó el registro';

COMMENT ON COLUMN OPERACION.TMP_OPE_BOUQUETPROM.FECREG IS 'Fecha que inserto el registro';


