CREATE TABLE OPERACION.TMP_TARJETAS
(
  IDTARJETA     VARCHAR2(11 BYTE),
  CODCLI        CHAR(8 BYTE),
  NOMCLI        VARCHAR2(200 BYTE),
  TIPDOC        CHAR(3 BYTE),
  NUMDOC        VARCHAR2(15 BYTE),
  TELEFONO1     VARCHAR2(20 BYTE),
  CODSOLOT      NUMBER(8),
  NUMSLC        CHAR(10 BYTE),
  IDPAQ         NUMBER(10),
  UNITADDRESS   VARCHAR2(32 BYTE),
  TIPOENVIO     NUMBER,
  FLG_INCLUIDO  NUMBER,
  FECENV        DATE,
  IDENVIO       NUMBER(15),
  CODUSU        VARCHAR2(30 BYTE)               DEFAULT user,
  FECUSU        DATE                            DEFAULT sysdate,
  IDMOTIVO      NUMBER(2),
  ESTSID        NUMBER(2)
);

COMMENT ON COLUMN OPERACION.TMP_TARJETAS.IDMOTIVO IS 'Identificador del Motivo';

COMMENT ON COLUMN OPERACION.TMP_TARJETAS.ESTSID IS 'Estado de la Instancia de Servicio';


