CREATE TABLE OPERACION.TMP_MIGRACION_DTH
(
  IDTRANS        NUMBER(10)                     NOT NULL,
  NUMREGISTRO    CHAR(10 BYTE),
  TIPO           NUMBER(1),
  CODSOLOT       NUMBER(8),
  ESTSOL         NUMBER(2),
  IDWF_ANT       NUMBER(8),
  IDWF_NEW       NUMBER(8),
  CODINSSRV      NUMBER(10),
  ESTINSSRV_ANT  NUMBER(2),
  ESTINSSRV_NEW  NUMBER(2),
  PID            NUMBER(10),
  ESTINSPRD_ANT  NUMBER(2),
  ESTINSPRD_NEW  NUMBER(2),
  PROCESADO      NUMBER(1)                      DEFAULT 0,
  MENSAJE        VARCHAR2(1000 BYTE),
  FECUSU         DATE                           DEFAULT SYSDATE               NOT NULL,
  CODUSU         VARCHAR2(30 BYTE)              DEFAULT user                  NOT NULL
);

COMMENT ON TABLE OPERACION.TMP_MIGRACION_DTH IS 'temporal de cambios por migracion DTH';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.ESTINSSRV_ANT IS 'estado anterior';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.IDTRANS IS 'Identificador';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.NUMREGISTRO IS 'Numero de registro';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.TIPO IS '1:migracion,2:nuevo wf instalacion, 3:nuevo wf de baja, 4:estado inssrv,5:estado insprd';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.CODSOLOT IS 'Codigo de SOT';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.IDWF_ANT IS 'WF anterior';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.IDWF_NEW IS 'WF nuevo';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.CODINSSRV IS 'codigo de instancia de servicio';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.ESTINSSRV_NEW IS 'estado nuevo';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.PID IS 'Codigo de instancia de producto';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.ESTINSPRD_ANT IS 'estado anterior';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.ESTINSPRD_NEW IS 'estado nuevo';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.CODUSU IS 'Codigo de Usuario registro';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.MENSAJE IS 'Observacion';

COMMENT ON COLUMN OPERACION.TMP_MIGRACION_DTH.PROCESADO IS 'flag de proceso, 0:pendiente,1:OK,2:error';


