CREATE TABLE OPERACION.TRANSACCIONES_FCO
(
  IDTRANSFCO        NUMBER                      NOT NULL,
  NOMABR            VARCHAR2(20 BYTE),
  IDOPERADORFCO     NUMBER(4),
  TRANSACCION       VARCHAR2(50 BYTE),
  FECINI            DATE,
  FECFIN            DATE,
  ESTTRANSFCO       NUMBER(8),
  CODSOLOT          NUMBER(8),
  OBSERVACION       VARCHAR2(4000 BYTE),
  TIPO              NUMBER(8),
  CODCLI            CHAR(8 BYTE),
  CODMOTOTFCO       NUMBER(8),
  IDSUSPENSION_OLD  NUMBER(10),
  USUREG            VARCHAR2(30 BYTE),
  FECREG            DATE,
  USUMOD            VARCHAR2(30 BYTE),
  FECMOD            DATE,
  FLGVALIDO         NUMBER                      DEFAULT 0
);

COMMENT ON TABLE OPERACION.TRANSACCIONES_FCO IS 'Tabla de transacciones de las solicitudes de FCO';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.IDTRANSFCO IS 'Código de transación';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.NOMABR IS 'Número telefónico';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.IDOPERADORFCO IS 'Id Operador';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.TRANSACCION IS 'Tipode Transaccion';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.FECINI IS 'Fecha de incio de la transacción';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.FECFIN IS 'Fecha fin de la transacción';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.ESTTRANSFCO IS 'estado de la transacción';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.CODSOLOT IS 'Codigo de la solicitud de orden de trabajo';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.OBSERVACION IS 'observación';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.CODMOTOTFCO IS 'Codigo del motivo ';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.USUREG IS 'Usuario Registro';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.FECREG IS 'Fecha Registro';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.USUMOD IS 'Usuario Modificación';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.FECMOD IS 'Fecha Modificación';

COMMENT ON COLUMN OPERACION.TRANSACCIONES_FCO.FLGVALIDO IS 'Indica si genera SOT';


