CREATE TABLE OPERACION.TRASLADO_ALMACEN
(
  CODSOLOT       NUMBER                         NOT NULL,
  ORDEN          NUMBER                         NOT NULL,
  ORD_TRAS       NUMBER(8)                      NOT NULL,
  COD_SAP        VARCHAR2(18 BYTE),
  CENTRO_ORI     VARCHAR2(4 BYTE)               NOT NULL,
  ALMACEN_ORI    VARCHAR2(4 BYTE)               NOT NULL,
  TIPEQU         NUMBER(6),
  CENTRO_DES     VARCHAR2(4 BYTE)               NOT NULL,
  ALMACEN_DES    VARCHAR2(4 BYTE)               NOT NULL,
  CANTIDAD       NUMBER(8,2)                    DEFAULT 0                     NOT NULL,
  FLGSOL         NUMBER(3)                      DEFAULT 0                     NOT NULL,
  FLGREQ         NUMBER(3)                      DEFAULT 0                     NOT NULL,
  FLGFDIS        NUMBER(3)                      DEFAULT 0                     NOT NULL,
  FECFDIS        DATE,
  FECTRASLADO    DATE,
  NRO_RES        NUMBER,
  TRAN_SOLMAT    NUMBER,
  ID_SOL         NUMBER,
  USUGENRESERVA  VARCHAR2(30 BYTE),
  FECGENRESERVA  DATE,
  CODUSU         VARCHAR2(30 BYTE)              DEFAULT user                  NOT NULL,
  FECUSU         DATE                           DEFAULT SYSDATE               NOT NULL,
  OBSERVACION    VARCHAR2(400 BYTE),
  ESTADO         VARCHAR2(10 BYTE)
);

COMMENT ON TABLE OPERACION.TRASLADO_ALMACEN IS 'Tabla de generación de Traslado';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.CODSOLOT IS 'Código de SOT';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ORDEN IS 'Orden';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ORD_TRAS IS 'PK Tabla TRASLADO_ALMACEN';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.COD_SAP IS 'Código SAP';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.CENTRO_ORI IS 'Centro Origen';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ALMACEN_ORI IS 'Almacén Origen';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.TIPEQU IS 'Código de Tipo de Equipo';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.CENTRO_DES IS 'Centro Destino';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ALMACEN_DES IS 'Almacén Destino';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.CANTIDAD IS 'Cantidad de equipo';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FLGSOL IS 'Solicita Traslado';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FLGREQ IS 'Genero Reserva';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FLGFDIS IS 'Flag Fin de Diseño';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FECFDIS IS 'Fecha de Fin Diseño';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FECTRASLADO IS 'Fecha de Traslado';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.NRO_RES IS 'Número de Reserva';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.TRAN_SOLMAT IS 'Ticket de envío para la transacción a SAP';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ID_SOL IS 'Agrupador de Reservas';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.USUGENRESERVA IS 'Usuario de Generación de Reserva';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FECGENRESERVA IS 'Fecha de Generación de Reserva';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.CODUSU IS 'Código de Usuario registro';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.FECUSU IS 'Fecha de registro';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.OBSERVACION IS 'Observación';

COMMENT ON COLUMN OPERACION.TRASLADO_ALMACEN.ESTADO IS 'Estado de Linea';


