UPDATE OPERACION.SOLOTPTOEQU SET PEP_PE05 = PEP, PEPLEASING_PE05 = PEP_LEASING, CENTROSAP_PE05 = CENTROSAP;
UPDATE OPERACION.SOLOTPTOEQUCMP SET PEP_PE05 = PEP, PEPLEASING_PE05 = PEP_LEASING;
UPDATE OPERACION.SOLOTPTOETAACT SET PEP_PE05 = PEP;
UPDATE OPERACION.SOLOTPTOETAMAT SET PEPINVERSION_PE05 = PEP_INVERSION where PEP_INVERSION is not null /*or not PEPINVERSION =' '*/;
UPDATE OPERACION.DESPACHO_MASIVO SET PEP_PE05 = PEP, PEPLEASING_PE05 = PEP_LEASING, CENTROSAP_PE05 = CENTROSAP;
UPDATE OPERACION.SOLOT_PEP_ANTERIOR SET ELEMENTOPEP_PE05 = ELEMENTO_PEP;
commit;
