insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 1', 'HFCINS-ADNER 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 10', 'HFCINS-ADNER 10', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 11', 'HFCINS-ADNER 11', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 12', 'HFCINS-ADNER 12', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 13', 'HFCINS-ADNER 13', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 14', 'HFCINS-ADNER 14', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 15', 'HFCINS-ADNER 15', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 16', 'HFCINS-ADNER 16', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 17', 'HFCINS-ADNER 17', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 18', 'HFCINS-ADNER 18', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 19', 'HFCINS-ADNER 19', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 2', 'HFCINS-ADNER 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 3', 'HFCINS-ADNER 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 4', 'HFCINS-ADNER 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 5', 'HFCINS-ADNER 5', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 6', 'HFCINS-ADNER 6', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 7', 'HFCINS-ADNER 7', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 8', 'HFCINS-ADNER 8', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER 9', 'HFCINS-ADNER 9', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER HUACHO 1', 'HFCINS-ADNER HUACHO 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (131, 'HFCINS-ADNER HUACHO 2', 'HFCINS-ADNER HUACHO 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 1', 'HFCINS-CARLEI 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 2', 'HFCINS-CARLEI 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 3', 'HFCINS-CARLEI 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 4', 'HFCINS-CARLEI 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 5', 'HFCINS-CARLEI 5', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 6', 'HFCINS-CARLEI 6', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI 7', 'HFCINS-CARLEI 7', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (274, 'HFCINS-CARLEI HUACHO 1', 'HFCINS-CARLEI HUACHO 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 1', 'HFCINS-CONTACTE 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 2', 'HFCINS-CONTACTE 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 3', 'HFCINS-CONTACTE 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 4', 'HFCINS-CONTACTE 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 5', 'HFCINS-CONTACTE 5', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 6', 'HFCINS-CONTACTE 6', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (252, 'HFCINS-CONTACTE 7', 'HFCINS-CONTACTE 7', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 1', 'HFCINS-DIGETEL 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 10', 'HFCINS-DIGETEL 10', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 11', 'HFCINS-DIGETEL 11', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 12', 'HFCINS-DIGETEL 12', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 13', 'HFCINS-DIGETEL 13', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 14', 'HFCINS-DIGETEL 14', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 2', 'HFCINS-DIGETEL 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 3', 'HFCINS-DIGETEL 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 4', 'HFCINS-DIGETEL 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 5', 'HFCINS-DIGETEL 5', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 6', 'HFCINS-DIGETEL 6', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 7', 'HFCINS-DIGETEL 7', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 8', 'HFCINS-DIGETEL 8', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (128, 'HFCINS-DIGETEL 9', 'HFCINS-DIGETEL 9', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (296, 'HFCINS-DT 1', 'HFCINS-DT 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (296, 'HFCINS-DT 2', 'HFCINS-DT 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (296, 'HFCINS-DT 3', 'HFCINS-DT 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (296, 'HFCINS-DT 4', 'HFCINS-DT 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 1', 'HFCINS-SEVETEL 1', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 10', 'HFCINS-SEVETEL 10', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 11', 'HFCINS-SEVETEL 11', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 12', 'HFCINS-SEVETEL 12', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 13', 'HFCINS-SEVETEL 13', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 14', 'HFCINS-SEVETEL 14', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 15', 'HFCINS-SEVETEL 15', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 16', 'HFCINS-SEVETEL 16', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 17', 'HFCINS-SEVETEL 17', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 2', 'HFCINS-SEVETEL 2', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 3', 'HFCINS-SEVETEL 3', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 4', 'HFCINS-SEVETEL 4', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 5', 'HFCINS-SEVETEL 5', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 6', 'HFCINS-SEVETEL 6', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 7', 'HFCINS-SEVETEL 7', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 8', 'HFCINS-SEVETEL 8', null, 1, 1);

insert into OPERACION.CUADRILLAXCONTRATA (CODCON, CODCUADRILLA, NOMBRE_CUADRILLA, RPC, TIPO, ESTADO)
values (273, 'HFCINS-SEVETEL 9', 'HFCINS-SEVETEL 9', null, 1, 1);

