grant execute on OPERACION.PQ_IW_OPE to USREAISGA;
grant select, insert, update, delete on OPERACION.OPE_EQU_IW to USREAISGA;
grant select, insert, update, delete on OPERACION.solotptoequ to USREAISGA;
GRANT EXECUTE ON OPERACION.ARR_DAC to USREAISGA;
GRANT EXECUTE ON OPERACION.ARR_PACKETCABLEREPORT to USREAISGA;
GRANT EXECUTE ON OPERACION.ARR_DOCSISREPORT to USREAISGA;
GRANT EXECUTE ON OPERACION.ARR_REPORTOBJOUTPUT to USREAISGA;
 
