DROP TYPE OPERACION.ARR_REPORTOBJOUTPUT;
DROP TYPE OPERACION.ARR_DOCSISREPORT;
DROP TYPE OPERACION.ARR_PACKETCABLEREPORT;
DROP TYPE OPERACION.ARR_DAC;
DROP TYPE OPERACION.REPORTOBJOUTPUT;
DROP TYPE OPERACION.DOCSISREPORT;
DROP TYPE OPERACION.PACKETCABLEREPORT;
DROP TYPE OPERACION.DAC;

delete  OPERACION.constante where constante = 'KEY_IW';
delete  OPERACION.constante where constante = 'IDEMPRESACRM';
delete  OPERACION.constante where constante = 'TARGET_URL_IW';
delete  OPERACION.constante where constante = 'ACTION_URL_IW';
commit;

drop table OPERACION.OPE_EQU_IW;
drop table OPERACION.TRS_WS_SGA;
DROP sequence OPERACION.SEQ_EQU_IW;
DROP sequence OPERACION.SEQ_IW_IDTRANSACCION;
DROP index OPERACION.IDK_EQU_CLIENTE_SOT

