REVOKE SELECT, INSERT, UPDATE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF FROM USRWSBAMBAF;
REVOKE SELECT, INSERT, UPDATE, REFERENCES, ALTER, INDEX ON OPERACION.INSSRV FROM USRWSBAMBAF;
REVOKE SELECT, INSERT, UPDATE, REFERENCES, ALTER, INDEX ON OPERACION.OPEDD FROM USRWSBAMBAF;
REVOKE SELECT, INSERT, UPDATE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF_HIS FROM USRWSBAMBAF;
REVOKE SELECT, INSERT, UPDATE, REFERENCES, ALTER, INDEX ON OPERACION.TIPTRABAJO FROM USRWSBAMBAF;

DROP table OPERACION.TRSBAMBAF;
drop table OPERACION.TIPACCIONPV;
drop sequence operacion.SEQ_LOTE_BAM;
drop sequence operacion.SQ_IDBAM;
drop sequence operacion.SQ_TIPACCIONPV_LOG;
drop sequence operacion.SQ_TRSBAMBAF_LOG;
delete OPERACION.constante where constante in ('PWD_BSCS','USER_BSCS','BD_BSCS','DBPARM_BSCS');


COMMIT;

-- Grant/Revoke object privileges 
revoke execute on OPERACION.PQ_BAM from USREAISGA;