-- Drop columns 
alter table OPERACION.MOT_SOLUCIONXTIPTRA drop column APLICA_CONTRATA;
alter table OPERACION.MOT_SOLUCIONXTIPTRA drop column APLICA_PEXT;
-- Drop columns 
alter table OPERACION.SECUENCIA_ESTADOS_AGENDA drop column APLICA_PEXT;
alter table OPERACION.SECUENCIA_ESTADOS_AGENDA drop column IDSEQ;

drop table OPERACION.CIERRE_TAREA_AGENDA;
DROP sequence OPERACION.SQ_SEC_EST_AGE;
drop table OPERACION.OPE_CUADXDISTXDIA;