ALTER TABLE OPERACION.CFG_ENV_CORREO_CONTRATA DROP COLUMN TIPOFORMATO;
ALTER TABLE OPERACION.CFG_ENV_CORREO_CONTRATA DROP COLUMN CONDICION1;
ALTER TABLE OPERACION.CFG_ENV_CORREO_CONTRATA DROP COLUMN CAMPOFECHA;
ALTER TABLE OPERACION.CFG_ENV_CORREO_CONTRATA DROP COLUMN CAMPOSOT;
ALTER TABLE OPERACION.CFG_ENV_CORREO_CONTRATA DROP COLUMN CAMPOPROY;

DROP TABLE OPERACION.OPET_CFG_HORA_ENVIO;


DROP SEQUENCE OPERACION.SQ_OPET_CFG_HORA_ENVIO;






