-- Drop columns 
alter table OPERACION.CFG_ENV_CORREO_CONTRATA drop column PUBLICA;
alter table OPERACION.CFG_ENV_CORREO_CONTRATA drop column TITULO;
alter table OPERACION.CFG_ENV_CORREO_CONTRATA drop column DATAWINDOW;