insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'ServicePackageCRMID', null, 1, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'Hub', null, 2, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'Nodo', null, 3, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'CantCPE', null, 9, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'ActivationCode', null, 10, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'FIXED_IP_MAX', null, 18, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'ACTIVATION_CODE_EXPIRATION_DATE', '3', 19, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'ProfileCrmId', null, 3, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'ActivationCode', null, 7, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (600, 'ServidorEmailCRMId', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (600, 'Cantidad', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (600, 'QuotaMax', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom5', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'Hostname', null, 6, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'ProductName', null, 4, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom8', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom9', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom10', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom1', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'CmsCrmId', 'nortel', 1, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'Provisioning', '0', 5, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'PPVBaseBalance', '40', 7, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'PPVStartingBalance', '0', 9, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'PPVEnabled', '1', 8, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (626, 'snmpGroupCRMId', 'netbios-tcp', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'ProfileCrmId', 'ep-default', 3, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'CmsCrmId', 'nortel', 2, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (626, 'NoBoot', 'false', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'Username', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'Dominio', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'Password', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'DiskQuota', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'Noticias', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (602, 'Name', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (500, 'idTipoCliente', '100', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom2', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'USChannelId', null, 17, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'StartingBalance', null, 13, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'EnableAccounting', null, 14, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'BuscarTagCM', 'cmodem', 5, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'Docsis', '1.1', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'ProductName', null, 6, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'IspMtaCrmId', 'mta', 15, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'PrepaidPolicyCrmId', null, 8, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'location', null, 12, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'DSFreq', null, 11, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom3', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2022, 'smartCard', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'NoBoot', 'FALSE', 16, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom4', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom6', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'Custom7', null, null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (628, 'NoBoot', 'false', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'ispMTACrmId', 'mta', 2, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (820, 'SendToController', 'TRUE', 8, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'ControllerCRMId', 'DAC6000', 5, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'headEndCRMId', 'VES_DSP', 11, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'parentalControlEnabled', '0', 13, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'NVODEnabled', '1', 6, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'guideEnabled', '1', 10, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'Provisioning', '0', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'SendToController', 'TRUE', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (830, 'Active', '0', 1, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'BandPackageCrmId', '0', 7, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'idISPCRM', 'cpe', 4, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (620, 'PeriodicalBaseBalance', null, 12, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2050, 'ControllerCRMId', 'seachange', 1, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2050, 'STBProfileCRMId', 'bsghandle', 3, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2050, 'PurchaseCreditLimit', '210', 2, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2050, 'SendToController', 'TRUE', null, 1);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (500, 'Nombre', null, 1, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (500, 'Username', null, 2, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (500, 'Password', null, 3, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (500, 'EmailNoticias', null, 4, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'HomeExchangeCrmId', null, 1, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'EndPointNumber', null, 4, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (824, 'TN', null, 5, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (830, 'FeatureCrmId', null, 2, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'activationCode', null, 1, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'defaultProductCRMId', null, 2, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'channelMapCRMId', null, 3, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2020, 'defaultConfigCRMId', null, 4, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2030, 'productCRMId', null, 1, 2);

insert into OPERACION.INT_PARAMETRO (ID_INTERFACE, ID_PARAMETRO, ID_VALOR, ORDEN, TIPO)
values (2050, 'VODProfileCRMId', null, 4, 2);

commit;