insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW,  COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (1, 'o', 728, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (2, 'o', 728, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (3, 'o', 728, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (4, 'o', 728, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (5, 'o', 728, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (6, 'o', 731, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (7, 'o', 731, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (8, 'o', 731, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (9, 'o', 731, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (10, 'o', 731, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (11, 'o', 733, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (12, 'o', 733, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (13, 'o', 733, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (14, 'o', 733, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (15, 'o', 733, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (16, 'o', 732, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (17, 'o', 732, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (18, 'o', 732, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (19, 'o', 732, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (20, 'o', 732, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (21, 'o', 676, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (22, 'o', 676, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (23, 'o', 676, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (24, 'o', 676, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (25, 'o', 676, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (26, 'o', 785, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (27, 'o', 785, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (28, 'o', 785, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (29, 'o', 785, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (30, 'o', 785, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (31, 'o', 678, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (32, 'o', 678, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (33, 'o', 678, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (34, 'o', 678, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (35, 'o', 678, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (36, 'o', 801, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (37, 'o', 801, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (38, 'o', 801, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (39, 'o', 801, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (40, 'o', 801, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (41, 'o', 658, 1, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (42, 'o', 658, 2, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (43, 'o', 658, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (44, 'o', 658, 6, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (45, 'o', 658, 6, 29, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (46, 'a', 728, 4, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (47, 'a', 728, 6, 29, 29, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (48, 'a', 731, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (49, 'a', 731, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (50, 'a', 733, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (51, 'a', 733, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (52, 'a', 732, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (53, 'a', 732, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (54, 'a', 732, 7, null, 13, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (55, 'a', 732, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (56, 'a', 732, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (57, 'a', 732, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (58, 'a', 732, 5, null, 13, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (59, 'a', 676, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (60, 'a', 676, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (61, 'a', 676, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (62, 'a', 676, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (63, 'a', 676, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (64, 'a', 676, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (65, 'a', 676, 5, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (66, 'a', 785, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (67, 'a', 785, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (68, 'a', 785, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (69, 'a', 785, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (70, 'a', 785, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (71, 'a', 785, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (72, 'a', 785, 5, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (73, 'a', 678, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (74, 'a', 678, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (75, 'a', 678, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (76, 'a', 678, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (77, 'a', 678, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (78, 'a', 678, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (79, 'a', 678, 5, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (80, 'a', 801, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (81, 'a', 801, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (82, 'a', 801, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (83, 'a', 801, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (84, 'a', 801, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (85, 'a', 801, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (86, 'a', 801, 5, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (87, 'a', 658, 1, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (88, 'a', 658, 2, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (89, 'a', 658, 7, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (90, 'a', 658, 6, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (91, 'a', 658, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (92, 'a', 658, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (93, 'a', 658, 5, null, 13, 4, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (94, 's', 728, 4, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (95, 's', 728, 6, 29, 29, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (96, 's', 731, 1, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (97, 's', 731, 2, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (98, 's', 731, 7, null, 13, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (99, 's', 731, 6, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (100, 's', 731, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (101, 's', 731, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (102, 's', 731, 5, null, 13, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (103, 's', 733, 1, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (104, 's', 733, 2, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (105, 's', 733, 7, null, 13, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (106, 's', 733, 6, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (107, 's', 733, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (108, 's', 733, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (109, 's', 733, 5, null, 13, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (110, 's', 732, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (111, 's', 732, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (112, 's', 676, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (113, 's', 676, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (114, 's', 785, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (115, 's', 785, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (116, 's', 678, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (117, 's', 678, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (118, 's', 801, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (119, 's', 801, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (120, 's', 658, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (121, 's', 658, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (122, 'd', 728, 1, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (123, 'd', 728, 2, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (124, 'd', 728, 7, null, 13, 0, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (125, 'd', 728, 6, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (126, 'd', 728, 6, 29, 29, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (127, 'd', 728, 4, null, 12, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (128, 'd', 728, 5, null, 13, 3, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (129, 'd', 731, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (130, 'd', 731, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (131, 'd', 733, 6, 29, 29, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (132, 'd', 733, 4, null, 12, 2, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (133, 'd', 732, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (134, 'd', 732, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (135, 'd', 676, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (136, 'd', 676, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (137, 'd', 785, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (138, 'd', 785, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (139, 'd', 678, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (140, 'd', 678, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (141, 'd', 801, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (142, 'd', 801, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (143, 'd', 658, 6, 29, 29, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (144, 'd', 658, 4, null, 12, 1, 1, 'IT_CONSULTA', to_date('24-04-2017 17:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (145, 'g', 731, 0, null, 13, 2, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (146, 'g', 733, 0, null, 13, 2, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (147, 'g', 732, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (148, 'g', 676, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (149, 'g', 785, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (150, 'g', 678, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (151, 'g', 801, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (152, 'g', 658, 0, null, 13, 1, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (153, 'h', 676, 5, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (154, 'h', 676, 7, null, 15, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (155, 'h', 785, 5, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (156, 'h', 785, 7, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (157, 'h', 678, 5, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (158, 'h', 678, 7, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (159, 'h', 801, 5, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (160, 'h', 801, 7, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (161, 'h', 658, 5, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0);

insert into operacion.SGAS_CONF_VALIDASOT (COVSV_ID, COVSV_ESTBSCS, COVSV_TIPTRA, COVSV_TIPESTSOL, COVSV_ESTSOL, COVSV_ESTSOLNEW, COVSV_ESTSRVNEW, COVSV_ESTADO, COVSV_CODUSU, COVSV_FECUSU, COVSV_DIAS)
values (162, 'h', 658, 7, null, 13, 0, 1, 'IT_CONSULTA', to_date('06-05-2017 11:52:00', 'dd-mm-yyyy hh24:mi:ss'), 30);

COMMIT;
/
