create index OPERACION.IDX_AGENDAMIENTO_CODCON on OPERACION.AGENDAMIENTO(CODCON)
  tablespace OPERACION_IDX;

create index OPERACION.IDX_AGENDAMIENTO_ESTAGE on OPERACION.AGENDAMIENTO(ESTAGE)
  tablespace OPERACION_IDX;   
