Alter table OPERACION.OPE_SRV_RECARGA_DET add REQUEST  NUMBER; 
Alter table OPERACION.OPE_SRV_RECARGA_DET add REQUEST_PADRE NUMBER;
COMMIT;

comment on column OPERACION.OPE_SRV_RECARGA_DET.REQUEST is 'Request de BSCS LTE';
comment on column OPERACION.OPE_SRV_RECARGA_DET.REQUEST_PADRE is 'Request Padre de BSCS de LTE';