-- SCRIPT VENTA
      INSERT INTO OPERACION.TIPTRABAJO
        (TIPTRA, TIPTRS, DESCRIPCION)
      VALUES
        ((SELECT MAX(TIPTRA) + 1 FROM OPERACION.TIPTRABAJO),
         5,
         'BAJA TOTAL 3PLAY INALAMBRICO');
         
      INSERT INTO OPERACION.TIPTRABAJO
        (TIPTRA, TIPTRS, DESCRIPCION)
      VALUES
        ((SELECT MAX(TIPTRA) + 1 FROM OPERACION.TIPTRABAJO),
         4,
         'SUSPENSION 3PLAY INALAMBRICO');
         
      INSERT INTO OPERACION.TIPTRABAJO
        (TIPTRA, TIPTRS, DESCRIPCION)
      VALUES
        ((SELECT MAX(TIPTRA) + 1 FROM OPERACION.TIPTRABAJO),
         3,
         'RECONEXION 3PLAY INALAMBRICO');
commit;