-- Add/modify columns 
alter table ATCCORP.ATCINCIDENCEXSOLOT add CODCON number(6);
-- Add comments to the columns 
comment on column ATCCORP.ATCINCIDENCEXSOLOT.CODCON
  is 'Codigo de Contratista';


insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (164, 10, 'SUSPENSION LIMITE CREDITO CE EN HFC', 'Suspension de limite de credito de los servicios CE en HFC', 1, 0, 165, 19, 40, 0, -1, 'NO', 'NO', 'NO', 'NO', 'NO', 2, 165, null, 0, 0, 'NO', 1, null, 'NO', -1);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (165, 20, 'SUSPENSION FALTA DE PAGO', 'Suspension servicios por falta de pago', 2, 164, 166, 19, 41, 0, 16, 'NO', 'NO', 'NO', 'SI', 'NO', 1, null, 8,  0, 16, 'SI', 1, null, 'SI', 16);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (166, 30, 'CORTE SFP', 'Corte falta pago de servicios CE en HFC', 3, 165, 167, 19, 42, 7, 21, 'NO', 'NO', 'NO', 'NO', 'NO', 1, null, 9,   0, 16, 'SI', 1, null, 'NO', 21);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (167, 40, 'BAJA FALTA DE PAGO', '', 4, 166, 999, 19, 43, 0, 31, 'NO', 'NO', 'NO', 'NO', 'NO', 1, null, null,   0, 16, 'SI', 1, null, 'NO', 31);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (168, 100, 'RECONEXION SERVICIO SLC', '', 5, 164, 999, 19, 44, 0, -1, 'NO', 'NO', 'NO', 'NO', 'NO', 3, null, null, 0, 0, 'NO', 1, null, 'NO', -1);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (169, 200, 'RECONEXION SERVICIO SFP', '', 6, 165, 999, 19, 45, 0, -1, 'NO', 'NO', 'NO', 'NO', 'NO', 3, null, null, 0, 16, 'SI', 1, null, 'NO', -1);

insert into COLLECTIONS.cxc_transxgrupocorte (IDTRAGRUCORTE, ORDEN, DESABR, DESCRIPCION, IDTRANCORTE, IDTRAGRUCORTEANT, IDTRAGRUCORTESIG, IDGRUPOCORTE, IDPLANSOT, DIASDESNOTI, DIASEJETRAN, FLGFECREGCARTA, FLGGENCARTA, FLGENVCORREO, FLGFERFECVEN, FLGFERENTCAR, GRUPOEJECUCION, PRIORIDADSOBRE, IDCARTIP, DIASGENTRAN, DIASGRACIA, FLGDIASGRACIAUTIL, ESTADO, WFDEF, FLGFERFECVENSV, DIASGENTRANSV)
values (170, 300, 'RECONEXION SERVICIO CFP', '', 7, 166, 999, 19, 45, 0, -1, 'NO', 'NO', 'NO', 'NO', 'NO', 3, null, null, 0, 16, 'SI', 1, null, 'NO', -1);



insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (418, 164, 'IDE', 10, 'PQ_CXC_PROCESOS_CORTE.p_ide_tran_sus_lim_cre', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (419, 164, 'VAL', 20, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1 ,  'PQ_CXC_PROCESOS_CORTE.p_val_lim_cre');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (420, 164, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot_lim_cre', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (421, 164, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (422, 165, 'IDE', 10, 'PQ_CXC_PROCESOS_CORTE.p_ide_sus_falta_pago', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (423, 165, 'VAL', 20, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1, 'pq_cxc_procesos_corte.p_val_trans_corte');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (424, 165, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot', 1,  '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (425, 165, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (426, 166, 'IDE', 10, 'PQ_CXC_CORTE.p_sig_transaccion', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (427, 166, 'EJE', 20, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1, 'pq_cxc_procesos_corte.p_val_trans_corte');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (428, 166, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (429, 166, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (430, 167, 'IDE', 10, 'PQ_CXC_CORTE.p_sig_transaccion', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (431, 167, 'VAL', 20, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1, 'pq_cxc_procesos_corte.p_val_trans_corte');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (432, 167, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (433, 167, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (434, 168, 'VAL', 10, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1, 'PQ_CXC_PROCESOS_CORTE.p_val_rec_lim_cre');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (435, 168, 'EJE', 20, 'PQ_CXC_CORTE.p_generar_sot_lim_cre', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (436, 168, 'EJE', 30, 'PQ_CXC_CORTE.p_ejecutar_sot', 1,  '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (437, 169, 'VAL', 10, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1, 'PQ_CXC_PROCESOS_CORTE.p_val_rec');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (438, 169, 'EJE', 20, 'PQ_CXC_PROCESOS_CORTE.p_fuerza_cierre_sot', 1,  '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (439, 169, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot', 1,  '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (440, 169, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1,   '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (441, 170, 'VAL', 10, 'PQ_CXC_CORTE.p_transacciones_pendientes', 1,  'PQ_CXC_PROCESOS_CORTE.p_val_rec');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (442, 170, 'EJE', 20, 'PQ_CXC_PROCESOS_CORTE.p_fuerza_cierre_sot', 1,  '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (443, 170, 'EJE', 30, 'PQ_CXC_CORTE.p_generar_sot', 1, '');

insert into COLLECTIONS.cxc_procesotranscorte (IDPROCESOCORTE, IDTRAGRUCORTE, TIPOPROCESO, ORDENEJECUCION, PROCESO, ESTADO, PROCESOINTERNO)
values (444, 170, 'EJE', 40, 'PQ_CXC_CORTE.p_ejecutar_sot', 1,  '');



commit;


