ALTER TABLE OPERACION.SGAT_POSTV_PROYECTO_ORIGEN
ADD prorv_correo VARCHAR2(200);

ALTER TABLE OPERACION.SGAT_POSTV_PROYECTO_ORIGEN
ADD prorv_tpo_altas VARCHAR2(1);

ALTER TABLE OPERACION.SGAT_POSTV_PROYECTO_ORIGEN
ADD PRORV_COD_MOTIVO NUMBER;

comment on column OPERACION.SGAT_POSTV_PROYECTO_ORIGEN.prorv_correo
  is 'Correo';
  
comment on column OPERACION.SGAT_POSTV_PROYECTO_ORIGEN.prorv_tpo_altas
  is 'Tipo de Altas';
  
comment on column OPERACION.SGAT_POSTV_PROYECTO_ORIGEN.PRORV_COD_MOTIVO
  is 'Codigo de motivo';
  
alter table SALES.SISACT_POSTVENTA_DET_SERV_LTE modify flag_accion VARCHAR2(3);
  
COMMIT
/
