ALTER TABLE OPERACION.DETCP ADD IDCAB NUMBER;
ALTER TABLE OPERACION.DETCP ADD OBSERVACION VARCHAR2(100);
ALTER TABLE OPERACION.DETCP ADD TIPO_EQU_PROV VARCHAR2(20);
ALTER TABLE OPERACION.DETCP ADD CANT_TOTAL NUMBER;
ALTER TABLE OPERACION.DETCP ADD CANT_EFEC NUMBER;
ALTER TABLE OPERACION.CABCP ADD CODSOLOT NUMBER;
ALTER TABLE OPERACION.ACTIONCP ADD TIPSRV CHAR(1);