 insert into OPERACION.TIPOPEDD (DESCRIPCION, ABREV)
 values ('Estado de Fibra - LOG', 'APROV_ESTADO_FIBRA_LOG');

 insert into OPERACION.OPEDD ( CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
 values ( 1, 'Libre', 'LIBRE', (select TIPOPEDD from OPERACION.TIPOPEDD where ABREV='APROV_ESTADO_FIBRA_LOG'), NULL);

 COMMIT;
 /
