alter table OPERACION.SIAC_INSTANCIA
 add flg_tecn NUMBER(10) default 0;
comment on column OPERACION.SIAC_INSTANCIA.flg_tecn
  is 'Flag LTE = 1';

UPDATE OPERACION.opedd
SET CODIGON = 1242
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - TRASLADO EXTERNO';

UPDATE OPERACION.opedd
SET CODIGON = 1293
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - PUNTO ADICIONAL';

UPDATE OPERACION.opedd
SET CODIGON = 1292
where TIPOPEDD = 260 AND
DESCRIPCION = 'WLL/SIAC - TRASLADO INTERNO';
commit;
/
