INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA001', 'DISEÑO (PEXT - PINT)');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA003', 'PLAN DE SEÑALIZACION Y DESVIO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA004', 'POSTE (ACTIVIDAD)');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA002', 'IMPRESIÓN EXPEDIENTE PARA GESTION MUNICIPAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA005', 'INSTALACION DE FIBRA POR RED AEREA O CANALIZADA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA006', 'CABLE (FIBRA OPTICA PROYECTADA) ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA018', 'CAMARA PROYECTADA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (728, 'P', NULL, 1, 'MA018', 'CAMARA PROYECTADA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA019', 'OTROS CANALIZACION (REPOS, RELLENO - RETIRO DESMONTE) 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA020', 'OTROS CANALIZACION (REPOS, RELLENO - RETIRO DESMONTE) + DE 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (728, 'P', NULL, 1, 'MA020', 'OTROS CANALIZACION (REPOS, RELLENO - RETIRO DESMONTE) + DE 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA021', 'MARCO Y TAPA DE CAMARA - CANALIZACION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (714, 'P', NULL, 1, 'MA021', 'MARCO Y TAPA DE CAMARA - CANALIZACION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA022', 'LIQUIDACION PERMISOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (728, 'P', NULL, 1, 'MA022', 'LIQUIDACION PERMISOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (729, 'P', NULL, 1, 'MA004', 'POSTE (ACTIVIDAD)');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA007', 'OTROS TENDIDO (SOLDAR/DESOLDAR)');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA008', 'POSTE MATERIAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (729, 'P', NULL, 1, 'MA008', 'POSTE MATERIAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA009', 'MATERIAL PANDUIT / FUSION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA010', 'CABLE DE FIBRA OPTICA 96FSM');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA011', 'INSTALACION DE FIBRA POR RED AEREA O CANALIZADA CABLE 96FSM');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA012', 'POSTES EMPRESA ELECTRICA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA013', 'MATERIAL INPUT (DENTRO DEL LOCAL DEL CLIENTE)');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA014', 'PAGO MINISTERIO DE CULTURA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA015', 'PAGO A CONTRATA PARA GESTION DE PERMISOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA016', 'CANALIZACION PROYECTADA 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (639, 'N', NULL, 1, 'MA017', 'CANALIZACION PROYECTADA + DE 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (728, 'P', NULL, 1, 'MA017', 'CANALIZACION PROYECTADA + DE 1 VÍA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA023', 'FLETE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (729, 'P', NULL, 1, 'MA023', 'FLETE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA024', 'PASAJES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (729, 'P', NULL, 1, 'MA024', 'PASAJES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA025', 'HOSPEDAJE + ALIMENTACION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (729, 'P', NULL, 1, 'MA025', 'HOSPEDAJE + ALIMENTACION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_SRVC (EFESN_CODETA, EFESC_TIPPRC, EFESV_MODNEG, EFESN_ESTADO, EFESC_CODACT, EFESV_ACTIVIDAD)
VALUES (638, 'N', NULL, 1, 'MA026', 'MATERIAL DE FERRETERIA PARA INSTALACION DE FO AEREA');

COMMIT;
/
