INSERT INTO OPERACION.OPE_CAB_XML (IDCAB, PROGRAMA, NOMBREXML, TITULO, RFC, METODO, DESCRIPCION, XML, TARGET_URL, XMLCLOB )
VALUES ((SELECT MAX(IDCAB)+1 FROM OPERACION.OPE_CAB_XML), 'BSS_GestionSEFGIS', 'BSS_GestionSEF GIS', 'BSS_GestionSEFGIS', 'HTTP/1.1', null, 'BSS_GestionSEF GIS', null, 'http://172.17.51.149:21000/BSS_GestionSEFGIS/SRV_GestionSEFGIS/Service/Exposition/MED_GestionSEFGIS?wsdl',
'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/" xmlns:v1="http://claro.com.pe/esb/message/gestionSef/registrarSef/v1/">
   <soapenv:Header>
     <v2:headerRequest>
         <v2:channel></v2:channel>
         <v2:idApplication></v2:idApplication>
         <v2:userApplication></v2:userApplication>
         <v2:userSession></v2:userSession>
         <v2:idESBTransaction></v2:idESBTransaction>
         <v2:idBusinessTransaction></v2:idBusinessTransaction>
         <v2:startDate></v2:startDate>
         <v2:additionalNode></v2:additionalNode>
      </v2:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <v1:registrarSefRequest>
         <idTransaccion>@idTransaccion</idTransaccion>
         <indicador>0</indicador>
         <codigoDireccion>@codigoDireccion</codigoDireccion>
         <codigoSubdireccion>@codigoSubdireccion</codigoSubdireccion>
         <fechaUTC>@fechaUTC</fechaUTC>
         <codigoProyecto>@codigoProyecto</codigoProyecto>
         <codigoSucursal>@codigoSucursal</codigoSucursal>
         <idTrazabilidad>@idTrazabilidad</idTrazabilidad>
         <codigoRfs></codigoRfs>
         <kPuntoC></kPuntoC>
         <escenarioInicial></escenarioInicial>
         <codigoPop></codigoPop>
         <distPopCliente></distPopCliente>
         <distObraCliente></distObraCliente>
         <politica></politica>
         <equipoPint></equipoPint>
         <tipoFibra></tipoFibra>
         <listaRequestOpcional>
            <objetoOpcional clave="" valor=""/>
         </listaRequestOpcional>
      </v1:registrarSefRequest>
   </soapenv:Body>
</soapenv:Envelope>' );


UPDATE OPERACION.SGAT_EF_ETAPA_PRM
SET EFEPN_VALOR = 2
WHERE EFEPN_ID IN (1, 164);

UPDATE OPERACION.SGAT_EF_ETAPA_PRM
SET EFEPN_VALOR = 1
WHERE EFEPN_ID IN (24);

UPDATE OPERACION.SGAT_EF_ETAPA_PRM
SET EFEPN_VALOR = 1
WHERE EFEPN_ID IN (24);

UPDATE OPERACION.SGAT_EF_ETAPA_PRM
SET EFEPN_VALOR = 6
WHERE EFEPN_ID IN (25, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179);


INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (0, NULL, 'MENOR A 500 MB', 'ANCHO DE BANDA', 5, 1, 2, 'N', 500, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'ZONA_LIMA', 'REGLAS_POLITICA', 2, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'ZONA_PROVINCIA', 'REGLAS_NEGOCIO', 0, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, NULL, 'CANTIDAD_PERSONAL', 'ZONA_PROVINCIA', 1, 1, 194, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, NULL, 'DIAS_PERMANENCIA', 'ZONA_PROVINCIA', 1, 1, 194, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000011', 'LIMA (CERCADO)', 'ZONA_LIMA', NULL, 1, 193, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'CANALIZACION_PROYECTADA_VIA', 'REGLAS_NEGOCIO', 0, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (0, NULL, 'SA', 'CANALIZACION_PROYECTADA_VIA', 1, 1, 202, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, NULL, 'MMC', 'CANALIZACION_PROYECTADA_VIA', 1, 1, 202, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, NULL, 'CDS', 'CANALIZACION_PROYECTADA_VIA', 1, 1, 202, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'MATERIAL_PANDUIT_FUSION', 'REGLAS_NEGOCIO', 0, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, NULL, 'SA', 'MATERIAL_PANDUIT_FUSION', 1, 1, 206, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, NULL, 'MMC', 'MATERIAL_PANDUIT_FUSION', 1, 1, 206, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, NULL, 'CDS', 'MATERIAL_PANDUIT_FUSION', 1, 1, 206, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'MATERIAL_INPUT', 'REGLAS_NEGOCIO', 0, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (0, NULL, 'SA', 'MATERIAL_INPUT', 1, 1, 210, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (50, NULL, 'MMC', 'MATERIAL_INPUT', 1, 1, 210, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (100, NULL, 'CDS', 'MATERIAL_INPUT', 1, 1, 210, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'AUTORIZACION_MINISTERIO_CULTURA', 'REGLAS_POLITICA', 1, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'PERMISOS_MUNICIPALES', 'REGLAS_POLITICA', 2, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000026', 'MIRAFLORES', ' ', NULL, 1, 220, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000040', 'SAN ISIDRO', ' ', NULL, 1, 220, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000011', 'LIMA (CERCADO)', ' ', NULL, 1, 220, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000021', 'JESUS MARIA', ' ', NULL, 1, 220, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, '0000000026', 'MIRAFLORES', 'ZONA_LIMA', NULL, 1, 193, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'CONTRATA_LOCALIA', 'REGLAS_POLITICA', 2, 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1000, NULL, 'FLETE', 'ZONA_PROVINCIA', 1, 1, 194, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (100, NULL, 'COSTO_PASAJES', 'ZONA_PROVINCIA', 1, 1, 194, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (130, NULL, 'HOSPEDA_ALIMENTA', 'ZONA_PROVINCIA', 1, 1, 194, 'N', 0, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ESTADO, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (0, 'DNG', 'DIRECCION NO GEOREFERENCIADA', 'ESCENARIOS', 6, 1, 17, 'N', 0, NULL, NULL, NULL);

COMMIT;
/
