-- SCRIPT ALTER TABLE
-- Modificacion tabla OPERACION.SGAT_EF_ETAPA_CNFG
ALTER TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG DISABLE;

ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_DCMD TO EFECN_SUBESCEN1;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_MCMD TO EFECN_SUBESCEN2;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG RENAME COLUMN EFECN_MUMD TO EFECN_SUBESCEN3;
ALTER TABLE OPERACION.SGAT_EF_ETAPA_CNFG ADD EFECN_ELEMENTO_SM NUMBER DEFAULT 0 NOT NULL;

COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_SUBESCEN1 IS 'FLAG SUBESCENARIO 1';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_SUBESCEN2 IS 'FLAG SUBESCENARIO 2';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_SUBESCEN3 IS 'FLAG SUBESCENARIO 3';
COMMENT ON COLUMN OPERACION.SGAT_EF_ETAPA_CNFG.EFECN_ELEMENTO_SM IS 'LOGICA DE ELEMENTOS DE SMALLWOLRD PARA PARTIDAS EXTRAS';

ALTER TRIGGER OPERACION.SGATRU_EF_ETAPA_CNFG ENABLE;
ALTER TRIGGER OPERACION.SGATRI_EF_ETAPA_CNFG COMPILE;

-- Modificacion tabla OPERACION.SGAT_EF_ETAPA_PRM
ALTER TABLE  OPERACION.SGAT_EF_ETAPA_PRM 
ADD (
  EFEPN_CODN3       NUMBER(10),
  EFEPV_CODV3       VARCHAR2(100)
  );

-- Modificacion tabla OPERACION.EFPTO  
ALTER TABLE OPERACION.EFPTO 
  ADD (EFPTN_LONFIBRA_PROY NUMBER(8,2),
	   EFPTV_RFS_GIS       VARCHAR2(20),
	   EFPTV_POLITICA      VARCHAR2(10),
	   EFPTN_EQUIPOPINT    NUMBER(10));

COMMENT ON COLUMN OPERACION.EFPTO.EFPTN_LONFIBRA_PROY   IS 'Longitud de Fibra Proyectada';
COMMENT ON COLUMN OPERACION.EFPTO.EFPTV_RFS_GIS         IS 'Codigo de Proyecto RFS proveniente de GIS.';
COMMENT ON COLUMN OPERACION.EFPTO.EFPTV_POLITICA        IS 'Tipo de Regla de Politica para el costeo PEXT del EF.';
COMMENT ON COLUMN OPERACION.EFPTO.EFPTN_EQUIPOPINT      IS 'Codigo de modelo de equipo de acceso para Costo PINT';

