-- ADD/MODIFY COLUMNS 
ALTER TABLE OPERACION.SGAT_EF_EQUIPO_SRVC ADD EFEQN_MARCA NUMBER(2);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN OPERACION.SGAT_EF_EQUIPO_SRVC.EFEQN_MARCA
  IS 'ID DE MARCA DE EQUIPO';
