-- Update a tabla OPERACION.SGAT_EF_ETAPA_PRM
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPV_DESCRIPCION = 'TIPO 2'
 WHERE EFEPN_ID = 1;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPV_CODV = 'SFO', EFEPV_DESCRIPCION = 'SANGRADO DE FIBRA OPTICA'
 WHERE EFEPN_ID = 20;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_CODN = 1000, EFEPV_TRANSACCION = 'TIPO 1'
 WHERE EFEPN_ID = 22;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_CODN        = 1000,
		 EFEPV_CODV        = '0000000040',
		 EFEPV_DESCRIPCION = 'SAN ISIDRO',
		 EFEPV_TRANSACCION = 'TIPO 1'
 WHERE EFEPN_ID = 23;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPV_DESCRIPCION = 'ESCENARIOS',
		 EFEPV_TRANSACCION = 'REGLAS_NEGOCIO'
 WHERE EFEPN_ID = 17;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPV_TRANSACCION = 'ESCENARIOS'
 WHERE EFEPV_TRANSACCION = 'MODALIDAD_NEGOCIOS';
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPV_TRANSACCION = 'REGLAS_NEGOCIO'
 WHERE EFEPV_TRANSACCION = 'REGLAS_SMALLWORLD';
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_VALOR = NULL
 WHERE EFEPN_VALOR IS NOT NULL;
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_VALOR = 1
 WHERE EFEPN_ID IN (7, 8);
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_VALOR = 5
 WHERE EFEPN_ID IN (5, 6, 9, 10, 11, 12, 13, 14, 15);
 
UPDATE OPERACION.SGAT_EF_ETAPA_PRM
	SET EFEPN_VALOR = 6
 WHERE EFEPN_ID IN (18, 19, 20, 21);


COMMIT;
