INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'TIPO 1', 'REGLAS_POLITICA', NULL, NULL, 'S', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'FM', 'FACTIBILIDAD MANUAL', 'ESCENARIOS', 6, 17, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1000, '0000000026', 'MIRAFLORES', 'TIPO 2', NULL, 1, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1000, '0000000048', 'SANTIAGO DE SURCO', 'TIPO 2', NULL, 1, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1000, '0000000032', 'SAN BORJA', 'TIPO 2', NULL, 1, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 6, '01', 40220043, 'CANAVAL Y MOREYRA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (30, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 32, '01', 40220063, 'PASEO DE LA REPÚBLICA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '01', 40010117, 'DIONISIO DERTEANO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (33, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 36, '01', 40220020, 'REPUBLICA DE PANANA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '01', 40220005, 'DEL PARQUE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '01', 40010036, 'RICARDO RIVERA NAVARRETE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 5, '03', 40030220, 'CORONEL ANDRES REYES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (6, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 10, '03', 40030259, 'JUAN DE ARONA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '01', 40010015, 'REPUBLICA DE COLOMBIA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '01', 40010012, 'CAMINO REAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '01', 40220047, 'PASEO EL BOSQUE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (28, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 29, '01', 40010001, 'AREQUIPA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 5, '01', 40010009, 'JORGE BASADRE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '01', 40010010, 'VICTOR ANDRES BELAUNDE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '01', 40220039, 'SANTO TORIBIO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 8, '01', 40220028, 'EMILIO CAVENECIA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 6, '01', 40220044, 'PARDO Y ALIAGA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '01', 40220031, 'SANTA CRUZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (11, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 12, '01', 40010012, 'CAMINO REAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '01', 40220035, 'ALVAREZ CALDERON');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030296, 'VIA PRINCIPAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030134, 'LOS FLAMENCOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030033, 'LOS HALCONES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030013, 'MARIANO DE LOS SANTOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030078, 'ARMANDO BLONDET');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030128, 'MICAELA BASTIDAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030247, 'MIGUEL SEMINARIO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030044, 'GERMAN SCHREIBER');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 4, '03', 40030332, 'MANUEL AUGUSTO OLAECHEA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030135, 'LOS GAVILANES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030119, 'LOS CISNES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030099, 'LOS PELICANOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030030, 'LAS GOLONDRINAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030009, 'LOS TUCANES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030105, 'LOS ZORZALES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030410, 'OROPENDOLAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 8, '03', 40030255, 'LAS CAMELIAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 6, '03', 40030115, 'LAS ORQUIDEAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 5, '03', 40030263, 'FRANCISCO MASIAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '03', 40030377, 'LAS BEGONIAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030093, 'EL PARQUE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030405, 'AUGUSTO TAMAYO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 5, '03', 40030183, 'AMADOR MERINO REYNA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030095, 'LOS LIRIOS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030047, 'DEAN VALDIVIA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (8, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 10, '03', 40030019, 'CHINCHON');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (7, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '03', 40030082, 'ANTEQUERA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (6, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 6, '03', 40030361, 'CORONEL ODRIOZOLA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030104, 'LOS SAUCES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030043, 'SANTA LUISA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 4, '03', 40030087, 'MANUEL BAÑON');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030200, 'RICARDO PALMA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030185, 'TRADICIONES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '03', 40030408, 'CHOQUEHUANCA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (6, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 7, '01', 40010052, 'LOS LIBERTADORES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030039, 'VICTOR MAURTUA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030117, 'FRANCISCO TUDELA Y VARELA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '24', 40240001, 'ALMIRANTE LORD COCHRANE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030092, 'JOSE EMILIANO DEL LLANO ZAPATA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 2, '03', 40030376, 'MIGUEL DASSO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030049, 'LEONIDAS YEROVI');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030301, 'ALBERTO ULLOA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 1, '03', 40030153, 'MIGUEL DE CERVANTES SAAVEDRA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000040', 'SAN ISIDRO', 'TIPO 1', NULL, 24, 'N', 3, '03', 40030401, 'MANUEL ROAUD PAZ SOLDAN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 7, '01', 26010137, 'SANTA CRUZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (38, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 39, '01', 26010001, 'AREQUIPA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (7, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 8, '01', 26010006, 'ANGAMOS OESTE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '01', 26010006, 'ANGAMOS OESTE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '01', 26010144, 'COMANDANTE ESPINAR');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (41, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 51, '01', 26010101, 'PETIT THOUARS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '01', 26010025, 'DEL EJERCITO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (8, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 30, '01', 26010007, 'ALFREDO BENAVIDES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (61, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 62, '01', 26010024, 'REPUBLICA DE PANAMA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '01', 26010039, 'JOSE RAMIREZ GASTON');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '01', 26010037, 'LA MERCED');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 10, '01', 26010015, 'JOSE PARDO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '01', 26010014, 'RICARDO PALMA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '01', 26010126, 'GRAU');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (52, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 52, '01', 26010001, 'AREQUIPA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 13, '01', 26010011, 'LARCO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 10, '01', 26010010, 'LA PAZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (10, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 10, '01', 26010016, 'REDUCTO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 7, '01', 26010013, 'VASCO NUÑEZ DE BALBOA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '01', 26010105, 'BENAVIDES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 8, '01', 26010012, '28 DE JULIO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030209, 'ASUNCION');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030126, 'SANTA MARIA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030227, 'MANUEL DE FREYRE SANTANDER');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (7, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 8, '03', 26030051, 'CHICLAYO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (7, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 7, '03', 26030147, 'PIURA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (6, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 7, '03', 26030013, 'ARICA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '02', 26020104, 'VICTOR LARCO HERRERA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030131, 'AYACUCHO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030108, 'CONTRALMIRANTE LIZARDO MONTERO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030393, 'SALAVERRY');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030019, 'SCIPION LLONA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030453, 'GERVASIO SANTILLANA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 8, '03', 26030355, 'CORONEL INCLAN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '03', 26030395, 'GENERAL SILVA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 5, '03', 26030429, '15 DE ENERO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '01', 26010157, 'MANUEL VILLARAN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 4, '01', 26010157, 'MANUEL VILLARAN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 5, '03', 26030197, 'LOS CAPULIES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '01', 26010035, 'CASIMIRO ULLOA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (4, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 5, '03', 26030012, 'JUAN DE LA FUENTE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 4, '03', 26030068, 'FRANCISCO DE PAULA UGARRIZA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030102, 'IGNACIO LA PUENTE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '01', 26010044, 'GENERAL ERNESTO MONTAGNE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030181, 'RAMON ZAVALA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030373, 'GENERAL IGLESIAS');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '03', 26030339, 'JORGE CHAVEZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030013, 'ARICA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030383, 'BOLOGNESI');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '03', 26030157, 'ELIAS AGUIRRE');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (6, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 7, '03', 26030445, 'JOSE GALVEZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '03', 26030277, '2 DE MAYO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030010, 'GENERAL BORGOÑO');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030402, 'INDEPENDECIA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030133, 'BELLAVISTA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030355, 'CORONEL INCLAN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030015, 'LIBERTAD');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '03', 26030104, 'ATAHUALPA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030302, 'MARTIR JOSE OLAYA BALANDRA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '01', 26010065, 'DIAGONAL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 13, '03', 26030417, 'ALCANFORES');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030263, 'GRIMALDO DEL SOLAR');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (5, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 6, '03', 26030263, 'GRIMALDO DEL SOLAR');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '03', 26030125, 'SANTA ISABEL');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030111, 'MANUEL BONILLA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 1, '03', 26030119, 'ESPERANZA');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 4, '03', 26030009, 'BERLIN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (2, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 3, '03', 26030064, 'MANCO CAPAC');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (3, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 4, '03', 26030428, 'JUAN FANNING');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '03', 26030452, 'ARISTIDES ALJOVIN');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (1, '0000000026', 'MIRAFLORES', 'TIPO 1', NULL, 24, 'N', 2, '06', 26060005, 'ARMENDARIZ');

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'DISTRITO_CANALIZADO', 'REGLAS_POLITICA', 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, NULL, 'ELEMENTOS_SMALLWOLRD', 'REGLAS_NEGOCIO', 1, NULL, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (10, '0000000026', 'MIRAFLORES', 'DISTRITO CANALIZADO', NULL, 164, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (10, '0000000040', 'SAN ISIDRO', 'DISTRITO CANALIZADO', NULL, 164, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (10, '0000000021', 'JESUS MARIA', 'DISTRITO CANALIZADO', NULL, 164, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0001', 'DIST. CANALIZADO PROYECTADO', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0002', 'DIST. TENDIDO SUBTERRÁNEO', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0003', 'DIST. TENDIDO AÉREO', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0004', 'CANT. DE CÁMARAS PROYECTADAS', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0005', 'CANT. DE CÁMARAS EXISTENTES', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0006', 'CANT. POSTES EMP. ELÉCTRICAS', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0007', 'CANT. POSTES PROPIOS EXISTENTES', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0008', 'CANT. POSTES PROPIOS PROYECTADOS', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0009', 'DIST. TENDIDO A/S', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0010', 'CANT. DE CÁMARAS PROY/EXIST', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);

INSERT INTO OPERACION.SGAT_EF_ETAPA_PRM (EFEPN_CODN, EFEPV_CODV, EFEPV_DESCRIPCION, EFEPV_TRANSACCION, EFEPN_VALOR, EFEPN_ID_PADRE, EFEPV_SISTEMA, EFEPN_CODN2, EFEPV_CODV2, EFEPN_CODN3, EFEPV_CODV3)
VALUES (NULL, 'RN0011', 'ESCENARIO', 'ELEMENTOS_SMALLWOLRD', 6, 165, 'N', NULL, NULL, NULL, NULL);


COMMIT;
