 insert into OPERACION.TIPOPEDD (DESCRIPCION, ABREV)
 values ('Tipos de Proyecto a Costear', 'TIPO_SEF_COSTEO');

 insert into OPERACION.OPEDD ( CODIGOC, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
 values ( '0096', 'Red Privada Virtual Full Mesh', 'TIPSRV_DATOS_01', (select TIPOPEDD from OPERACION.TIPOPEDD where ABREV='TIPO_SEF_COSTEO'), NULL);

 insert into OPERACION.OPEDD ( CODIGOC, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
 values ( '0006', 'Acceso Dedicado a Internet', 'TIPSRV_INTERNET_01', (select TIPOPEDD from OPERACION.TIPOPEDD where ABREV='TIPO_SEF_COSTEO'), NULL);

 insert into OPERACION.OPEDD ( CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
 values ( 1, 'Instalacion', 'TIPTRA_01', (select TIPOPEDD from OPERACION.TIPOPEDD where ABREV='TIPO_SEF_COSTEO'), NULL);

 COMMIT;
 /
