DECLARE
  LN_COUNT NUMBER;
BEGIN
  /* INICIO INSERT CONFIGURACIONES */
  SELECT COUNT(*)
    INTO LN_COUNT
    FROM OPERACION.TIPOPEDD CAB
   WHERE CAB.ABREV = 'CONF_TIPTRA_UNIF';

  IF LN_COUNT = 0 THEN
    INSERT INTO OPERACION.TIPOPEDD
      (TIPOPEDD, DESCRIPCION, ABREV)
    VALUES
      ((SELECT MAX(TIPOPEDD) + 1 FROM OPERACION.TIPOPEDD),
       'CONF. TIPO TRABAJO UNIFICADO',
       'CONF_TIPTRA_UNIF');
    COMMIT;

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     695,
     'HFC/SIAC - CAMBIO DE PLAN',
     'MIGRACION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_UNIF'),
     NULL);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     753,
     'WLL/SIAC - CAMBIO DE PLAN',
     'MIGRACION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_UNIF'),
     NULL);
  COMMIT;
END IF;

SELECT COUNT(*)
  INTO LN_COUNT
  FROM OPERACION.TIPOPEDD CAB
 WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN';

IF LN_COUNT = 0 THEN
  INSERT INTO OPERACION.TIPOPEDD
    (TIPOPEDD, DESCRIPCION, ABREV)
  VALUES
    ((SELECT MAX(TIPOPEDD) + 1 FROM OPERACION.TIPOPEDD),
     'CONF. TIPO TRABAJO TRANSACCION',
     'CONF_TIPTRA_TRAN');
  COMMIT;

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     427,
     'HFC - CAMBIO DE PLAN',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     658,
     'HFC - SISACT INSTALACION PAQUETES TODO CLARO DIGITAL',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     676,
     'HFC - PORTABILIDAD INSTALACIONES PAQUETES CLARO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     678,
     'HFC/SISACT - MIGRACION SISACT',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     693,
     'HFC/SIAC - TRASLADO EXTERNO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     695,
     'HFC/SIAC - CAMBIO DE PLAN',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     785,
     'HFC/SISACT - MIGRACION SISACT SISTE',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     412,
     'HFC - TRASLADO EXTERNO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     744,
     'INSTALACION 3 PLAY INALAMBRICO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     753,
     'WLL/SIAC - CAMBIO DE PLAN',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     754,
     'WLL/SIAC - TRASLADO EXTERNO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     801,
     'WLL/LTE MIGRACION WIMAX - LTE',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     825,
     'PORTABILIDAD INSTALACION 3 PLAY INALAMBRICO',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);

  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'FTTH',
     830,
     'FTTH - SISACT INSTALACION PAQUETES TODO CLARO DIGITAL',
     'TRANSACCION',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_TIPTRA_TRAN'),
     1);
  COMMIT;
END IF;

SELECT COUNT(*)
  INTO LN_COUNT
  FROM OPERACION.TIPOPEDD CAB
 WHERE CAB.ABREV = 'CONF_MOTOT_UNIF';

IF LN_COUNT = 0 THEN
  INSERT INTO OPERACION.TIPOPEDD
    (TIPOPEDD, DESCRIPCION, ABREV)
  VALUES
    ((SELECT MAX(TIPOPEDD) + 1 FROM OPERACION.TIPOPEDD),
     'CONF. MOTIVOS UNIFICADA',
     'CONF_MOTOT_UNIF');
  COMMIT;
  
  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     709,
     'INALAMBRICO - CAMBIO DE PLAN (SIN VISITA TECNICA)',
     'LTE_SIN_VISITA',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_MOTOT_UNIF'),
     0);
  
  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'LTE',
     708,
     'INALAMBRICO - CAMBIO DE PLAN (CON VISITA TECNICA)',
     'LTE_CON_VISITA',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_MOTOT_UNIF'),
     1);
  
  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     1009,
     'HFC/SIAC CAMBIO PLAN(SIN VISITA TECNICA)',
     'HFC_SIN_VISITA',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_MOTOT_UNIF'),
     0);
  
  INSERT INTO OPERACION.OPEDD
    (IDOPEDD,
     CODIGOC,
     CODIGON,
     DESCRIPCION,
     ABREVIACION,
     TIPOPEDD,
     CODIGON_AUX)
  VALUES
    ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
     'HFC',
     1010,
     'HFC/SIAC CAMBIO PLAN(CON VISITA TECNICA)',
     'HFC_CON_VISITA',
     (SELECT TIPOPEDD
        FROM OPERACION.TIPOPEDD CAB
       WHERE CAB.ABREV = 'CONF_MOTOT_UNIF'),
     1);
  COMMIT;
END IF;
/* FIN    INSERT CONFIGURACIONES */
END;
/