DECLARE
  IDFLUJO NUMBER;
  IDPROCESO NUMBER;
  IDCONDICION NUMBER;
  V_TIPOPEDD NUMBER;
  V_OPEDD NUMBER;
  IDTIPOCONDICION NUMBER;
BEGIN
  SELECT CONTN_IDTIPOCONDICION
  INTO IDTIPOCONDICION
  FROM OPERACION.SGAT_DF_CONDICION_TIPO
  WHERE CONTV_ABREV = 'COND SCR';

  insert into operacion.SGAT_DF_CONDICION_CAB (CONCN_IDTIPOCONDICION, CONCV_ABREV, CONCV_DESCRIPCION, CONCN_ESTADO)
  values (IDTIPOCONDICION, 'CONDICION SP DEFAULT', 'Condicion Default', 1)
  RETURNING CONCN_IDCONDICION INTO IDCONDICION;
  
  insert into operacion.SGAT_DF_CONDICION_DET (CONDN_IDCONDICION, CONDN_ORDEN, CONDV_PARAMETRO, CONDN_IDEXPLOG, CONDV_VALOR, CONDN_IDEXPPOST, CONDN_CANTIDAD, CONDC_SCRIPT, CONDN_ESTADO)
  values (IDCONDICION, 1, 'PRODUCTO', null, 'HFC', null, 1, '<CLOB>', 1);

  insert into operacion.SGAT_DF_CONDICION_DET (CONDN_IDCONDICION, CONDN_ORDEN, CONDV_PARAMETRO, CONDN_IDEXPLOG, CONDV_VALOR, CONDN_IDEXPPOST, CONDN_CANTIDAD, CONDC_SCRIPT, CONDN_ESTADO)
  values (IDCONDICION, 2, 'TRANSACCION', null, 'CP', null, 1, '<CLOB>', 1);

  insert into operacion.SGAT_DF_FLUJO_CAB (FLUCN_TIPTRABAJO, FLUCV_TRANSACCION, FLUCV_TECNOLOGIA, FLUCV_ABREV, FLUCV_DESCRIPCION, FLUCN_ESTADO, FLUCN_TIPO)
  values (485, 'CP', 'HFC', 'GENERACION SOT', 'Flujo de actividades para la generación unificada de SOT', 1, 2)
  RETURNING FLUCN_IDFLUJO INTO IDFLUJO;
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'VALIDACION CARGA', 'Validación inicial de datos enviados en la trama postventa', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_VALIDACION_INICIAL_CP')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;
  
  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 1, IDPROCESO, '0', '2', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'VALIDACION TIPO DE RED', 'Validación del tipo de red', 1, 2, null)
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 2, IDPROCESO, '1', '3', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'GENERAR VENTA DE SERV MENORES', 'Crear cabecera de la venta de servicios menores', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_GENERA_VENTA_MENOR')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 3, IDPROCESO, '2', '4', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'GENERAR VENTA DE SERV MENORES DET', 'Crear detalle de la venta de servicios menores', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_GENERA_VENTA_MENOR_DET')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 4, IDPROCESO, '3', '5', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'GENERAR VENTA', 'Crear cabecera del proyecto de venta', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_GENERA_VENTA')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 5, IDPROCESO, '4', '6', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'GENERAR VENTA DET', 'Crear detalle del proyecto de venta', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_GENERA_VENTA_DET')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 6, IDPROCESO, '5', '7', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'REGISTRAR PID BAJA', 'Registrar PID para dar de baja', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_REG_PIDBAJA')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 7, IDPROCESO, '6', '8', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'ACTUALIZACION VENTA', 'Actualizar información del proyecto de venta', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_ACT_NUMSLC')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 8, IDPROCESO, '7', '9', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'REGISTRAR INSTANCIA PAQUETE', 'Registrar instancia del paquete de venta', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_LOAD_INSTANCIA_CAMBIO')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 9, IDPROCESO, '8', '10', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'REGISTRAR INTERFAZ SEF CONTRATO', 'Registrar tabla interfaz entre SEF y Contrato', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_REG_PRECON')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 10, IDPROCESO, '9', '11', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'VALIDAR TIPO SOLUCION', 'Validación del tipo de solución del proyecto', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_VALIDAR_TIPOSOL')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 11, IDPROCESO, '10', '12', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'VALIDAR PROYECTO VENTA', 'Validación del proyecto de venta', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_VALIDAR_PROYECTO')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 12, IDPROCESO, '11', '13', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'GENERACION SOT', 'Validación y generación de SOT', 1, 2, 'OPERACION.PKG_TRS_POSTVENTA.SGASS_PROYECTO_PREVENTA')
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 13, IDPROCESO, '12', '14', 'SI', null, IDCONDICION);
  --
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (4, 'VALIDACIONES FINALES', 'Validaciones finales', 1, 2, null)
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  insert into operacion.SGAT_DF_FLUJO_DET (FLUDN_IDFLUJO, FLUDN_ORDEN, FLUDN_IDPROCESO, FLUDV_PREPROCESO, FLUDV_POSTPROCESO, FLUDC_FLGMANDATORIO, FLUDN_ORDENCONDICION, FLUDN_IDCONDICION)
  values (IDFLUJO, 14, IDPROCESO, '13', '0', 'SI', null, IDCONDICION);
  --
  SELECT MAX(tipopedd) + 1 INTO V_TIPOPEDD FROM operacion.tipopedd;
  SELECT MAX(idopedd) + 1 INTO V_OPEDD FROM operacion.opedd;

  INSERT INTO OPERACION.TIPOPEDD (TIPOPEDD, DESCRIPCION, ABREV)
  VALUES (V_TIPOPEDD, 'CONF. GENERACION UNIFICADA SOT', 'GEN_UNIF_SOT');
  
  INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
  VALUES (V_OPEDD, null, IDFLUJO, 'Identificador del flujo sot', 'ID_GENSOT', V_TIPOPEDD, 0);
  
  insert into operacion.SGAT_DF_PROCESO_CAB (PROCN_IDTIPOPROCESO, PROCV_ABREV, PROCV_DESCRIPCION, PROCN_ESTADO, PROCN_IDSERVPROCESO, PROCV_RUTA)
  values (1, 'Flujo SOT', 'Flujo para la generacion de SOT', 1, null, null)
  RETURNING PROCN_IDPROCESO INTO IDPROCESO;

  INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
  VALUES (V_OPEDD + 1, null, IDPROCESO, 'Identificador del flujo primario', 'ID_TRANSV', V_TIPOPEDD, 0);

  COMMIT;
END;
/