--NUEVO CAMPO EN LA TABLA AGENDAMIENTO
ALTER TABLE OPERACION.AGENDAMIENTO ADD DNI_TECNICO VARCHAR2(20);

-- INSERT AGENLIQ.SGAT_PARAMETROCAB 
  INSERT INTO AGENLIQ.SGAT_PARAMETROCAB(PARCN_CODPARAMETRO,
                                        PARCV_DESCRIPCION,
										PARCN_ESTADO,
                                        PARCV_ABREVIATURA,
                                        PARCC_TIPO,
										PARCN_BORRADO,
                                        PARCD_FECRE,
                                        PARCV_USUCRE)
                                  VALUES(AGENLIQ.SGASEQ_PARAMETROCAB.NEXTVAL,
                                        'Cierre Valida WF APP',
										1,
                                        'Cierre_val_WF_APP',
                                        'P',
                                        0,
                                        SYSDATE,
                                       'APP Instalador');
										  
-- INSERT AGENLIQ.SGAT_PARAMETRODET 										  
-- 1 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES - DTH',
								  'Agendamiento Cable',
                                  'Cierre_val_WF_APP',
								  1,
                                  'operacion.PQ_CUSPE_OPE.p_filtratareaworkflow',
                                  'INTRAWAY.PQ_SOTS_AGENDADAS.P_REGISTRA_AGENDAMIENTO',
                                  419,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');
-- 2
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES - DTH',
								  'Asignar Responsable Cable',
                                  'Cierre_val_WF_APP',
								  2,
                                  'OPERACION.PQ_CUSPE_OPE.P_ASIGNA_RESP_CONTRATA',
                                  NULL,
                                  419,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');
-- 3
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES - DTH',
								  'Activación/Desactivacion del servicio',
                                  'Cierre_val_WF_APP',
								  3,
                                  'operacion.pq_cuspe_ope.p_actualizar_area_tareawf',
                                  'OPERACION.P_WF_POS_ACTSRV',
                                  419,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');								  
 
-- 1  485
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES DTH',
								  'Validación del Instalador del Servicio Claro TV Sat',
                                  'Cierre_val_WF_APP',
								  1,
                                  'sales.pq_dth_postventa.p_pre_postventa_dth',
                                  'sales.pq_dth_postventa.p_cerrar_val_instalador',
                                  485,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	 

-- 2  485
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES DTH',
								  'Inalambrico - Registro de datos',
                                  'Cierre_val_WF_APP',
								  2,
                                  'operacion.pq_inalambrico.p_cargar_datos_inalambrico',
                                  'operacion.pq_inalambrico.p_cerrar_datos_inalambrico',
                                  485,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	


-- 3  485								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES DTH',
								  'Inalambrico - Activación/Desactivacion Conax',
                                  'Cierre_val_WF_APP',
								  3,
                                  NULL,
                                  'operacion.pq_inalambrico.p_cerrar_transaccion_conax',
                                  485,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');
								  
-- 4  485								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES DTH',
								  'Validar instalacion',
                                  'Cierre_val_WF_APP',
								  4,
                                  NULL,
                                  'operacion.p_wf_pos_actsrv',
                                  485,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 5  485								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION PAQUETES DTH',
								  'Inalambrico - Programacion',
                                  'Cierre_val_WF_APP',
								  5,
                                  NULL,
                                  'operacion.pq_inalambrico.p_pos_agendamiento',
                                  485,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 1  498								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - MANTENIMIENTO DTH',
								  'Validacion Mantenimiento',
                                  'Cierre_val_WF_APP',
								  1,
                                  NULL,
                                  'OPERACION.P_WF_POS_ACTSRV',
                                  498,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	

-- 2  498								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - MANTENIMIENTO DTH',
								  'Inalambrico - Mantenimiento',
                                  'Cierre_val_WF_APP',
								  2,
                                  NULL,
                                  'OPERACION.PQ_INALAMBRICO.SP_CAMBIO_ESTADO_SOT',
                                  498,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 1  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Pre-Seleccion',
                                  'Cierre_val_WF_APP',
								  1,
                                  'sales.pkg_preseleccion.sgass_asignacion_pre_seleccion',
                                  NULL,
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');
								  
-- 2  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Pre-Selección Inversa',
                                  'Cierre_val_WF_APP',
								  2,
                                  'sales.pkg_preseleccion.sgass_asigna_pre_selec_inv',
                                  NULL,
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 3  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Validacion del Instalador del Servicio Claro TV Inalambrico',
                                  'Cierre_val_WF_APP',
								  3,
                                  NULL,
                                  'operacion.pq_3play_inalambrico.p_cerrar_val_instalador_lte',
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 4  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Programacion Inalambrico',
                                  'Cierre_val_WF_APP',
								  4,
                                  'operacion.pq_agendamiento.p_gen_agenda_sin_asignar_lte',
                                  'operacion.pq_inalambrico.p_pos_agendamiento_lte',
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	

-- 5  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Registro de datos Inalambricos',
                                  'Cierre_val_WF_APP',
								  5,
                                  'operacion.pq_inalambrico.p_cargar_datos_inalambrico_lte',
                                  'operacion.pq_inalambrico.p_cerrar_datos_inalambrico_lte',
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	

-- 6  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Activacion de Servicios Inalambricos',
                                  'Cierre_val_WF_APP',
								  6,
                                  NULL,
                                  'operacion.pq_3play_inalambrico.p_activacion_servicio_3play',
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	

-- 7  744								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INSTALACION 3 PLAY INALAMBRICO',
								  'Validacion de Instalacion de Servicio Inalambrico',
                                  'Cierre_val_WF_APP',
								  7,
                                  'operacion.pq_3play_inalambrico.p_actualizar_cnt_bscs',
                                  'operacion.pq_3play_inalambrico.p_validar_servicio_3playi',
                                  744,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');		

-- 1  793								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION DECO ADICIONAL DTH',
								  'Validacion Mantenimiento',
                                  'Cierre_val_WF_APP',
								  1,
                                  NULL,
                                  'OPERACION.P_WF_POS_ACTSRV',
                                  793,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 2  793								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - INSTALACION DECO ADICIONAL DTH',
								  'Inalambrico - Mantenimiento',
                                  'Cierre_val_WF_APP',
								  2,
                                  NULL,
                                  'OPERACION.PQ_INALAMBRICO.SP_CAMBIO_ESTADO_SOT',
                                  793,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

-- 1  794								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - DESINSTALACION DECO ADICIONAL DTH',
								  'Validacion Mantenimiento',
                                  'Cierre_val_WF_APP',
								  1,
                                  NULL,
                                  'OPERACION.P_WF_POS_ACTSRV',
                                  794,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');		

-- 2  794								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'INALAMBRICO - DESINSTALACION DECO ADICIONAL DTH',
								  'Inalambrico - Mantenimiento',
                                  'Cierre_val_WF_APP',
								  2,
                                  NULL,
								  'OPERACION.PQ_INALAMBRICO.SP_CAMBIO_ESTADO_SOT',
                                  794,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');		

-- 1  818								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'WLL/SIAC - BAJA DECO ALQUILER',
								  'Validacion del Instalador del Servicio Claro TV Inalambrico',
                                  'Cierre_val_WF_APP',
								  1,
                                  NULL,
								  'operacion.pq_3play_inalambrico.p_cerrar_val_instalador_lte',
                                  818,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');	

-- 2  818								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'WLL/SIAC - BAJA DECO ALQUILER',
								  'Programacion Inalambrico',
                                  'Cierre_val_WF_APP',
								  2,
                                  'operacion.pq_agendamiento.p_gen_agenda_sin_asignar_lte',
								  'operacion.pq_inalambrico.p_pos_agendamiento_lte',
                                  818,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');
								  
-- 3  818								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'WLL/SIAC - BAJA DECO ALQUILER',
								  'Desactivacion de Deco Adicional',
                                  'Cierre_val_WF_APP',
								  3,
                                  'OPERACION.PQ_INALAMBRICO.SGASI_CARGAR_RECARGA',
								 NULL,
                                  818,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');		

-- 4  818								 
 INSERT INTO AGENLIQ.SGAT_PARAMETRODET(PARCN_CODPARAMETRO,
                                  PARDN_CODVALOR,
                                  PARDV_DESCRIPCION,
								  PARDV_DESCRIPCION2,
                                  PARDV_ABREVIATURA,
								  PARDN_ORDEN,
                                  PARDV_VALOR1,
                                  PARDV_VALOR2,
                                  PARDN_VALORN1,
                                  PARDN_ESTADO,
                                  PARDN_BORRADO,
                                  PARDD_FECRE,
                                  PARDV_USUCRE)
                           VALUES((SELECT T.PARCN_CODPARAMETRO FROM AGENLIQ.SGAT_PARAMETROCAB T WHERE T.PARCV_ABREVIATURA = 'Cierre_val_WF_APP'),
                                  AGENLIQ.SGASEQ_PARAMETRODET.NEXTVAL,
                                  'WLL/SIAC - BAJA DECO ALQUILER',
								  'Validacion de Desinstalacion de Deco Adicional LTE',
                                  'Cierre_val_WF_APP',
								  4,
                                  NULL,
								  'OPERACION.PQ_DECO_ADICIONAL_LTE.SGASU_VALIDA_DES_DECO',
                                  818,
                                  1,
                                  0,
                                  SYSDATE,
                                  'APP Instalador');

/								  