DECLARE
  V_TIPOPEDD NUMBER;
  V_OPEDD NUMBER;
BEGIN
  SELECT MAX(tipopedd) + 1 INTO V_TIPOPEDD FROM operacion.tipopedd;
  SELECT MAX(idopedd) + 1 INTO V_OPEDD FROM operacion.opedd;

  INSERT INTO OPERACION.TIPOPEDD (TIPOPEDD, DESCRIPCION, ABREV)
  VALUES (V_TIPOPEDD, 'REINT. DE REGISTRO CLIENTE CCL', 'REINT_REG_CCL');
  
  INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
  VALUES (V_OPEDD, null, 3, 'Cantidad de reintentos', 'CANT_REINT', V_TIPOPEDD, 0);
  
  INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
  VALUES (V_OPEDD + 1, null, 4, 'Estado TAREA con ejecución exitosa', 'TAREA_EXITO', V_TIPOPEDD, 4);
  
  INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
  VALUES (V_OPEDD + 2, null, 27, 'Estado TAREA con ejecución error', 'TAREA_ERROR', V_TIPOPEDD, 2);
  
  COMMIT;
END;
/
