
insert into OPERACION.OPEDD (CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (1817, '3 PLAY INALAMBRICO', 'PLAN', (SELECT TIPOPEDD FROM TIPOPEDD WHERE ABREV = 'BSCS_CONTRATO'), 1);

COMMIT;

ALTER TABLE OPERACION.SGAT_SRVEQU_INCOGNITO
ADD (CODSOLOT_BAJA NUMBER(10) DEFAULT 0,
     ID_ACCION NUMBER(1) DEFAULT 0)

/