INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'consultaCapacidadSGA'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'consultarrequest', 'ws:consultarCapacidadSGARequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'consultaCapacidadSGA'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'request', 'request', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cancelarOrdenSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'consultarrequest', 'typ:cancelarOrdenSGARequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cancelarOrdenSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'request', 'typ:cadenaRequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'gestionarOrdenSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'consultarrequest', 'typ:gestionarOrdenSGARequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'gestionarOrdenSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'request', 'typ:cadenaRequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cargarInventarioTotalSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'consultarrequest', 'typ:cargarInventarioTotalSGARequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cargarInventarioTotalSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'request', 'typ:cadenaRequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cargarInventarioIncrementalSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'consultarrequest', 'cargarInventarioIncrementalSGARequest', 1);
INSERT INTO operacion.ope_det_xml (idcab, idseq, campo, nombrecampo, tipo) VALUES ((SELECT a.idcab FROM operacion.ope_cab_xml a WHERE a.programa = 'cargarInventarioIncrementalSGA_ADC'), (SELECT max(b.idseq)+1 FROM operacion.ope_det_xml b), 'request', 'typ:cadenaRequest', 1);
COMMIT;
/