ALTER TABLE OPERACION.SOLOT ADD CUSTOMER_ID NUMBER;
COMMENT ON COLUMN OPERACION.SOLOT.CUSTOMER_ID
  IS 'CLIENTE DE SISACT';

ALTER TABLE OPERACION.SOLOT ADD COD_ID NUMBER;
COMMENT ON COLUMN OPERACION.SOLOT.COD_ID
  IS 'CODIGO BASADO EN SISACT';