insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 658, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 404, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 692, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 689, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 679, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 676, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 675, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 498, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 498, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 485, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 480, 0, 0, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 438, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 427, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 419, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 418, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 415, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 413, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 412, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 432, 1, 1, 1, 'M', 'TODOS', 1, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 448, 0, 1, 1, 'A', 'ACOMETIDA', 1, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 448, 0, 1, 1, 'M', 'EQUIPOS', 1, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0059', 5, 0, 0, 1, 'M', 'TODOS', 1, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 408, 1, 1, 1, 'A', 'ACOMETIDA', 1, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0015', 160, 1, 1, 1, 'A', 'DISE?O', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0059', 394, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 497, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 497, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0077', 617, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 424, 1, 1, 1, 'A', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0059', 661, 0, 0, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0061', 700, 1, 1, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0059', 402, 0, 0, 1, 'M', 'TODOS', 0, 0);

insert into OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC ( TIPSRV, TIPTRA, CON_CAP_V, CON_CAP_P, CON_CAP_O, GEN_OT_AUT, TIPO_AGENDA, VALIDA_MOT, ESTADO)
values ('0062', 480, 0, 0, 1, 'M', 'TODOS', 0, 0);
commit;

