insert into operacion.tiptrabajo (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT)
values (653, 5, 'CDMA -  BAJA - HLR', to_date('20-12-2012 10:09:17', 'dd-mm-yyyy hh24:mi:ss'), 'EASTULLE', '', '', 0, 0, null, 0, '', null, null, '', '', 0, null, null, 0, 0);

insert into operacion.tiptrabajo (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT)
values (652, 4, 'CDMA -  RECONEXION - HLR', to_date('20-12-2012 10:09:17', 'dd-mm-yyyy hh24:mi:ss'), 'EASTULLE', '', '', 0, 0, null, 0, '', null, null, '', '', 0, null, null, 0, 0);

insert into operacion.tiptrabajo (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT)
values (651, 3, 'CDMA -  SUSPENSION - HLR', to_date('20-12-2012 10:09:17', 'dd-mm-yyyy hh24:mi:ss'), 'EASTULLE', '', '', 0, 0, null, 0, '', null, null, '', '', 0, null, null, 0, 0);

insert into operacion.tiptrabajo (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT)
values (650, 1, 'CDMA -  ALTA - HLR', to_date('20-12-2012 10:09:17', 'dd-mm-yyyy hh24:mi:ss'), 'EASTULLE', '', '', 0, 0, null, 0, '', null, null, '', '', 0, null, null, 0, 0);
commit;
/

