INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('FLAG DE ESTADO ADC', 'FLAG_ESTADO_ADC', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('SISTEMA', 'SISTEMA', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TRAMA_CAPACIDAD', 'CAPACIDAD', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TRAMA_SERVICIOS', 'SERVICIOS', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('CATEGORIA CLIENTE', 'CATEGORIA_CLIENTE', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TIPO_TECNOLOGIA', 'TIPO_TECNOLOGIA', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('PARAMETROS DE CREACIÓN DE OT', 'PARAM_CRE_OT', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TIPO_INTERFASE', 'TIPO_INTERFASE', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TIPO DE AGENDAMIENTO', 'TIPO_AGENDAMIENTO', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('ERROR ADC', 'ERROR_ADC', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('ERROR ADC SIN CAPACIDAD', 'ERROR_ADC_SIN_CAPACIDAD', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('TIPO DE TRABAJO PUERTA A PUERTA', 'TIPO_TRABAJO_PUERTA_PUERTA', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('RESPUESTA_ADC', 'RESPUESTA_ADC', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('CATEGORIA', 'CATEGORIA', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('CARACTERES ESPECIALES', 'CARACTERES_ESPECIALES', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('CANCELACION DE AGENDA', 'CANCELACION_AGENDA', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('BULK_COLLECT', 'BULK_COLLECT', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('DTH TIPO DE TRABAJO', 'DTH_TIPO_TRABAJO', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('DTH TIPO DE SERVICIO', 'DTH_TIPO_SERVICIO', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('DTH MOTIVO', 'DTH_MOTIVO', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('DTH ESTADO DE SOLOT', 'DTH_ESTADO_SOLOT', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('DTH CLIENTE CORPORATIVO', 'DTH_CLIENTE_CORPORATIVO', '1');
INSERT INTO operacion.parametro_cab_adc (descripcion, abreviatura, estado) VALUES ('ESTADOS A REAGENDAR', 'ESTADOS_REAGENDAR', '1');
COMMIT;
/
