
insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('HFCI', 'HFC INSTALACION', 'HFC', 1, 'Instalacion');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('HFCM', 'HFC MANTENIMIENTO', 'HFC', 1, 'Mantenimiento');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('HFCP', 'HFC POST-VENTA', 'HFC', 1,'Post-Venta');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('DTHI', 'DTH INSTALACION', 'DTH', 1, 'Instalacion');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('DTHM', 'DTH MANTENIMIENTO', 'DTH', 1, 'Mantenimiento');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('DTHP', 'DTH POST-VENTA', 'DTH', 1, 'Post-Venta');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('CAND', 'DTH BAJAS', 'DTH', 1, 'Bajas');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('CANH', 'HFC BAJAS', 'HFC', 1, 'Bajas');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION,  ESTADO) 
values ('LUN', 'ALMUERZO',  1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION,  ESTADO)
values ('BOD', 'ACTIVIDAD DEPOSITO',  1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION,  ESTADO)
values ('VEH', 'MANT. DE VEHICULO', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, ESTADO)
values ('CAP', 'CAPACITACION', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION,  ESTADO)
values ('CONT', 'CONTROL DE INVENTARIO', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, ESTADO)
values ('SIND', 'ACTIVIDAD SINDICAL', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, ESTADO)
values ('WTR', 'RAZON CLIMATICA',  1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO)
values ('ASIS', 'ASISTENCIA', 'TPI', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO)
values ('SP', 'SUPERVISION', 'TPI', 1);

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('ANAB', 'ANALOGICAS BAJAS', 'ANA', 1,'Bajas');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('ANAI', 'ANALOGICAS INSTALACION', 'ANA', 1, 'Instalacion');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('ANAP', 'ANALOGICAS POST-VENTA', 'ANA', 1,'Post-Venta');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('CANT', 'TPI BAJAS', 'TPI', 1, 'Bajas');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('TPII', 'TPI INSTALACION', 'TPI', 1,'Instalacion');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('TPIM', 'TPI MANTENIMIENTO', 'TPI', 1, 'Mantenimiento');

insert into OPERACION.TIPO_ORDEN_ADC ( COD_TIPO_ORDEN, DESCRIPCION, TIPO_TECNOLOGIA, ESTADO, TIPO_SERVICIO)
values ('TPIP', 'TPI POST VENTA', 'TPI', 1, 'Post-Venta');

commit;