--SCRIPT

INSERT INTO OPERACION.TIPOPEDD
  (DESCRIPCION, ABREV)
VALUES
  ('DIAS VENC.FECHA BAJA DEL SERV.', 'DIAS_VENC');
INSERT INTO OPERACION.OPEDD
  (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
VALUES
  ('0',
   60,
   'DIAS VENCIMIENTO FEC DE BAJA SERV',
   'DIAS.VENC',
   (select TIPOPEDD
	 from TIPOPEDD
	WHERE DESCRIPCION = 'DIAS VENC.FECHA BAJA DEL SERV.'
	  AND ABREV = 'DIAS_VENC'));
COMMIT;

