
insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BACH', 'HFC BAJAS - CORTE DE ACOMETIDA', 1 );

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BACT', 'TPI BAJAS - CORTE DE ACOMETIDA', 1 );

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BARD', 'DTH BAJAS - RECUPERO EQUIPOS', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BARH', 'HFC BAJAS - RECUPERO EQUIPOS', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BART', 'TPI BAJAS - RECUPERO EQUIPOS', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('DTHI', 'DTH - INSTALACION', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('DTHM', 'DTH - MANTENIMIENTO', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('DTHP', 'DTH - POSTVENTA', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('HFCIS', 'HFC - INSTALADOR SENIOR', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('HFCM', 'HFC - MANTENIMIENTO ', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('TPII', 'TPI - INSTALACION', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('TPIM', 'TPI - MANTENIMIENTO', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('TPIP', 'TPI - POST VENTA', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BACA', 'ANALOGICA BAJAS - CORTE DE ACOMETIDA', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('ANAIS', 'ANALOGICA - INSTALADOR SENIOR', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('ANAIJ', 'ANALOGICA - INSTALADOR JUNIOR', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('BACD', 'DTH BAJAS - CORTE DE ACOMETIDA', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('HFCIJ', 'HFC - INSTALADOR JUNIOR ', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('HFCPJ', 'HFC - POST VENTA JUNIOR', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('HFCPS', 'HFC - POST VENTA SENIOR', 1);

insert into OPERACION.WORK_SKILL_ADC ( COD_WORK_SKILL, DESCRIPCION, ESTADO)
values ('TECH', 'TECNICO EN HFC', 1);

commit;
