insert into OPERACION.ESTADO_ADC (ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values (1, 'PENDIENTE', 'PENDIENTE', '1');

insert into OPERACION.ESTADO_ADC ( ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values (2 , 'INICIADO', 'INICIADO', '1');

insert into OPERACION.ESTADO_ADC (ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values (3, 'SUSPENDIDO', 'SUSPENDIDO', '1');

insert into OPERACION.ESTADO_ADC ( ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values (4,  'NO REALIZADO', 'NO REALIZADO', '1');

insert into OPERACION.ESTADO_ADC (ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values (5, 'COMPLETADO', 'COMPLETADO=FINALIZADO', '1');

insert into OPERACION.ESTADO_ADC (ID_ESTADO, DESC_CORTA, DESC_LARGA, ESTADO)
values ( 6, 'CANCELADO', 'CANCELADO', '1');
commit;
