update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2273;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2274;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2282;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2285;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2286;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2288;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2289;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2291;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - MANTTO', id_serv_liquid = 3 where idliq = 2292;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2293;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2294;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2295;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2296;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2297;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2298;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2299;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2300;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2301;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2302;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2303;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2304;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2305;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2306;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2307;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2308;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2309;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2312;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2313;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2314;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2315;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2316;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2317;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2318;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2319;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2321;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2322;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2323;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2324;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2325;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2326;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2329;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2330;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES AREQUIPA', id_serv_liquid = 36 where idliq = 2331;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2332;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2333;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2334;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2335;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - TPI COAXIAL', id_serv_liquid = 54 where idliq = 2336;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2338;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2339;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2340;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2341;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2342;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2343;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2344;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2345;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2346;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2347;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2348;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2349;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2350;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2351;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2352;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2353;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2354;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2355;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2356;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2357;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2359;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2360;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2361;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2362;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2363;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2364;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2365;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2366;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2367;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2368;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2369;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2370;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2371;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2372;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2373;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2376;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2377;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2378;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2379;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2380;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2381;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2382;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2383;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2384;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2385;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - MANTTO', id_serv_liquid = 25 where idliq = 2386;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2387;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2388;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2389;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2390;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2391;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2392;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2393;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - MANTTO PEXT LIMA', id_serv_liquid = 47 where idliq = 2396;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - MANTTO PEXT LIMA', id_serv_liquid = 47 where idliq = 2399;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2400;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2402;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2403;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2404;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2405;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2406;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2407;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2408;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2410;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2411;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2413;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ICA', id_serv_liquid = 38 where idliq = 2417;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2418;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2419;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2420;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2421;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2422;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2423;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2424;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2426;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2430;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2431;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2432;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2433;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2434;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2435;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2438;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES AREQUIPA', id_serv_liquid = 36 where idliq = 2440;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED DISEÑO - MANTTO', id_serv_liquid = 27 where idliq = 2441;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2442;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2443;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2444;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2445;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2446;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2447;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2448;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2449;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2450;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2451;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2452;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2453;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2454;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2455;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2456;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2457;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2458;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2459;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2460;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2461;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2462;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2463;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2464;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2465;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2466;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2467;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2469;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2470;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2471;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2472;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2473;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2474;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2476;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 41 where idliq = 2477;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 35 where idliq = 2478;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 35 where idliq = 2480;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2482;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2483;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2484;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2485;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2486;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2487;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2488;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2489;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2490;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2491;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2492;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2493;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2494;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2495;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2496;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2497;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2498;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2501;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2502;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2503;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2504;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2505;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2506;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2507;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2512;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2513;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2514;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2515;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2516;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - INSTALACIONES', id_serv_liquid = 16 where idliq = 2517;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2521;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2523;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2524;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2526;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2527;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2528;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2529;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2530;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2536;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2537;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2538;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2540;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2541;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2542;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2543;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2544;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2546;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2547;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2548;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2549;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2550;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2551;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2552;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2553;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - TPI COAXIAL', id_serv_liquid = 54 where idliq = 2555;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2556;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2557;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2558;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2561;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2563;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2564;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2565;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2566;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2567;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2568;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2570;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2571;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2572;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2573;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2574;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2575;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2576;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2577;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - MANTTO', id_serv_liquid = 6 where idliq = 2578;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2579;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2580;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2581;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2582;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2583;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2584;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2585;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2586;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2587;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2588;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2589;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2590;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2591;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2592;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2594;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2595;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2598;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2599;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2602;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2604;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES AREQUIPA', id_serv_liquid = 36 where idliq = 2611;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2612;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2613;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2614;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2615;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2616;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2617;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2618;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2619;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2620;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS PIURA', id_serv_liquid = 51 where idliq = 2621;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2622;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2623;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2624;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2625;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2628;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2629;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2630;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2631;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2632;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2633;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2634;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2635;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2636;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2637;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2638;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2639;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2640;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2641;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2642;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ICA', id_serv_liquid = 38 where idliq = 2643;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2644;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2645;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2646;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2647;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2648;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2649;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2650;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2651;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2652;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2653;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2654;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2655;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2656;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2657;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2658;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2659;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2660;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2661;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2662;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2663;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2664;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2665;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2666;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2667;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2668;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2669;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2670;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2671;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2672;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2673;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2674;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2675;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2676;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2677;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2678;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2679;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2680;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2681;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2682;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2683;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2684;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2685;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2686;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2687;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2688;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2689;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2690;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2691;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2692;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2693;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2694;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - INSTALACIONES', id_serv_liquid = 16 where idliq = 2695;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - BAJAS', id_serv_liquid = 15 where idliq = 2696;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2697;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2698;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2699;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2700;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2701;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2702;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2703;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2704;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2705;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2706;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2707;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2708;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2709;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2710;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2711;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2712;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2713;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2715;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2716;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2717;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2718;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2719;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2720;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2721;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2722;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2723;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2724;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2731;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2732;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2733;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2734;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2735;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2736;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2737;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ANCASH', id_serv_liquid = 41 where idliq = 2738;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2739;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2740;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2741;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2742;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2743;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2744;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2745;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2746;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2747;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2748;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2749;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS PIURA', id_serv_liquid = 51 where idliq = 2750;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - TPI COAXIAL', id_serv_liquid = 54 where idliq = 2751;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - TPI COAXIAL', id_serv_liquid = 54 where idliq = 2752;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2753;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2754;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2755;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2757;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2758;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2759;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2760;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2761;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2762;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2763;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2764;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2765;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2766;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2767;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2768;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2769;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2770;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2771;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2772;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2773;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2774;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2775;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2776;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2777;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2779;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2780;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ICA', id_serv_liquid = 38 where idliq = 2781;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2782;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2783;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2784;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2785;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2786;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2787;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2788;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2789;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2790;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2791;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2792;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2793;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2794;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2795;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2796;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2797;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2799;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2800;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2801;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2802;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2803;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2804;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2805;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2806;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2807;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2808;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2809;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2810;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2811;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2812;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2813;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2814;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2815;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2816;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2817;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2818;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2819;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2820;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2821;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2822;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2823;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2824;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2825;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2826;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2827;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2828;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2829;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2830;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2831;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2832;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2833;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2834;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2835;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2836;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2838;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CLARO EMPRESAS', id_serv_liquid = 55 where idliq = 2839;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2840;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2841;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2842;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2843;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2844;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2845;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2847;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2848;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2849;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 35 where idliq = 2850;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2851;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2852;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2853;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2854;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2855;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2856;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2857;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2858;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2859;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 35 where idliq = 2860;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - EXPLOTACION', id_serv_liquid = 35 where idliq = 2861;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2862;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2863;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2864;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2865;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2866;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ANCASH', id_serv_liquid = 41 where idliq = 2867;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2868;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2869;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2870;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2871;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2872;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2873;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2874;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ICA', id_serv_liquid = 38 where idliq = 2875;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2878;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2879;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2880;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2881;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2882;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2883;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2884;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2885;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2886;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2887;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2888;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2889;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2890;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2891;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2892;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2893;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2894;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2895;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2896;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2897;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2898;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2899;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 2900;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2902;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 2903;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 2904;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2905;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2906;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2907;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2908;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2909;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2910;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2911;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2912;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2913;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2914;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2915;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2916;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2917;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 2918;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2920;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2921;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2922;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2923;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2924;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2925;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2926;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2927;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2928;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2929;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2930;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2931;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2932;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2933;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2934;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2935;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2936;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2937;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2938;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2939;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2940;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2941;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2942;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2943;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2944;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2945;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2946;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2947;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2948;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2949;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 2950;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2951;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2952;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2953;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2954;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2955;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2956;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2957;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS PIURA', id_serv_liquid = 51 where idliq = 2958;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 2959;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 2960;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 2961;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2962;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2963;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2964;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2965;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2966;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2967;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2968;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2969;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2970;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2971;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 2972;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2973;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2974;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2975;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 2976;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2977;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 2978;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 2979;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2980;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2981;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2982;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2983;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2984;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 2985;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 2986;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2987;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2988;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2989;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PINT - DISEÑO', id_serv_liquid = 10 where idliq = 2990;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2991;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2992;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - DISEÑO', id_serv_liquid = 10 where idliq = 2993;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 2994;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - TPI COAXIAL', id_serv_liquid = 54 where idliq = 2995;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 2996;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2997;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2998;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 2999;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3000;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3001;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3002;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3003;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3004;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3005;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3006;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3007;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3008;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3009;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 3010;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3011;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 3012;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CLARO EMPRESAS', id_serv_liquid = 55 where idliq = 3013;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 3014;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES AREQUIPA', id_serv_liquid = 36 where idliq = 3015;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3017;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3018;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 3019;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - IMPLEMENTACION', id_serv_liquid = 24 where idliq = 3020;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3021;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3022;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 3023;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 3024;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 3025;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3026;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - INSTALACIONES', id_serv_liquid = 16 where idliq = 3027;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - BAJAS', id_serv_liquid = 15 where idliq = 3028;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3029;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 3030;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 3031;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 3032;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS LIMA', id_serv_liquid = 50 where idliq = 3033;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 3034;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 3035;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3036;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3037;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES LIMA', id_serv_liquid = 39 where idliq = 3038;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - BAJAS', id_serv_liquid = 15 where idliq = 3039;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPE - INSTALACIONES', id_serv_liquid = 16 where idliq = 3040;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 3041;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ANCASH', id_serv_liquid = 41 where idliq = 3042;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ICA', id_serv_liquid = 38 where idliq = 3043;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 3044;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 3045;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 3046;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 3047;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - TRASLADOS', id_serv_liquid = 4 where idliq = 3048;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - BAJAS', id_serv_liquid = 1 where idliq = 3049;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO CORPORACIONES - INSTALACIONES', id_serv_liquid = 2 where idliq = 3050;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 3051;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 3052;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES PIURA', id_serv_liquid = 40 where idliq = 3053;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 3054;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES ANCASH', id_serv_liquid = 41 where idliq = 3055;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED DISEÑO - MANTTO', id_serv_liquid = 27 where idliq = 3056;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3057;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES CHICLAYO', id_serv_liquid = 37 where idliq = 3059;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3060;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3061;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3062;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3063;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 3064;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 3065;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3066;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 3067;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 3068;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3069;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI - INSTALACIONES', id_serv_liquid = 19 where idliq = 3070;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'TPI / CLARO EMPRESAS - BAJAS', id_serv_liquid = 20 where idliq = 3071;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3072;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'CLARO EMPRESAS - INSTALACIONES', id_serv_liquid = 5 where idliq = 3073;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - INSTALACIONES TRUJILLO', id_serv_liquid = 42 where idliq = 3074;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3075;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3076;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3077;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3078;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'PEXT - CLIENTES', id_serv_liquid = 9 where idliq = 3079;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3080;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3081;
update operacion.sot_liquidacion set area = 'DR', servicio = 'RED - PEXT', id_serv_liquid = 26 where idliq = 3082;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS TRUJILLO', id_serv_liquid = 53 where idliq = 3083;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS CHICLAYO', id_serv_liquid = 49 where idliq = 3084;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3085;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3086;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3087;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3088;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3089;
update operacion.sot_liquidacion set area = 'DMC', servicio = 'DPL - INSTALACIONES', id_serv_liquid = 8 where idliq = 3090;
update operacion.sot_liquidacion set area = 'DMMA', servicio = 'HFC - SERVICIOS PIURA', id_serv_liquid = 51 where idliq = 3091;
commit;	