insert into operacion.parametro_cab_adc(descripcion,abreviatura,estado) values('Validacion de Inventario','VAL_EQ_ITW','1');
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TG1662G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TG1672G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TG862A',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TG862G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TM502A',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TM502G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TM602G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TM604G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_TM608G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Arris_WTM652G',1,'Arris','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC2203',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC2203C',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC2420',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC2425R2',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC3925',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC3928CAD',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPC3928S',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPQ2425',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Cisco_DPQ3925',1,'Cisco','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW222B',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW222B.F',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW222B.G',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW3201B',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW324',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW325B',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW32D',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_DVW32E',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_U10C022',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_U10C022 (Ambit)',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_U10C034',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Ubee_U10C034 (Ambit)',1,'Ubee','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Technicolor_DWG855',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Technicolor_DWG875',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Technicolor_TC7300',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Technicolor_TC8305',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SBV5121',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SBV5222',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SBV5322',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SVG1202',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SVG1501',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SVG2501',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Motorola_SVG6541',1,'Technicolor','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Castlenet_CBV383Z2',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Castlenet_CBV3843Z4S-AC1600',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Hitron-CVE30360',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Pingcom_C1620-Y1',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Sagemcom_FAST3284 ',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('Thomson_ACG905',1,'Otros','EMTA','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));

insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DTA100',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DTA 101 HD',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCT700-TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCT3412-TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX700-TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX525e TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX3400',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCT3416-TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX3500',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX-3510',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
insert into operacion.parametro_det_adc(codigoc,codigon,descripcion,abreviatura,estado,id_parametro) values ('DCX3520e TWOWAY',2,'Decos (STB)','DECO','1',(select ID_PARAMETRO from operacion.parametro_cab_adc where abreviatura='VAL_EQ_ITW'));
commit;