/*****Grant/Revoke object privileges*****/
GRANT ALL ON OPERACION.SGA_VISITA_TECNICA_CE TO R_PROD;

GRANT ALL ON OPERACION.SGAT_POSTV_PROYECTO_ORIGEN TO R_PROD;

GRANT ALL ON OPERACION.SGAT_POSTVENTASCE_LOG TO R_PROD;
