-- Insert OPERACION.OPE_TIPOMASIVASOT_MAE 
insert into OPERACION.OPE_TIPOMASIVASOT_MAE(DESCRIPCION)  values ('Todos');
insert into OPERACION.OPE_TIPOMASIVASOT_MAE(DESCRIPCION)  values ('Cambio de Estado SOT');
insert into OPERACION.OPE_TIPOMASIVASOT_MAE(DESCRIPCION)  values ('Asignar WorkFlow');
insert into OPERACION.OPE_TIPOMASIVASOT_MAE(DESCRIPCION)  values ('Cancelar WorkFlow');
commit;
