UPDATE OPERACION.SOLOTPTOEQU SET PEP = PEP_PE05, PEP_LEASING = PEPLEASING_PE05, CENTROSAP = CENTROSAP_PE05;
UPDATE OPERACION.SOLOTPTOEQUCMP SET PEP = PEP_PE05, PEP_LEASING = PEPLEASING_PE05;
UPDATE OPERACION.SOLOTPTOETAACT SET PEP = PEP_PE05;
UPDATE OPERACION.SOLOTPTOETAMAT SET PEP_INVERSION = PEPINVERSION_PE05;
UPDATE OPERACION.DESPACHO_MASIVO SET PEP = PEP_PE05, PEP_LEASING = PEPLEASING_PE05, CENTROSAP = CENTROSAP_PE05;
UPDATE OPERACION.SOLOT_PEP_ANTERIOR SET ELEMENTO_PEP = ELEMENTOPEP_PE05;
commit;

