ALTER TABLE OPERACION.SOLOTPTOEQU DROP (PEP_PE05, PEPLEASING_PE05, CENTROSAP_PE05);
ALTER TABLE OPERACION.SOLOTPTOEQUCMP DROP (PEP_PE05, PEPLEASING_PE05);
ALTER TABLE OPERACION.SOLOTPTOETAACT DROP (PEP_PE05);
ALTER TABLE OPERACION.SOLOTPTOETAMAT DROP (PEPINVERSION_PE05);
ALTER TABLE OPERACION.DESPACHO_MASIVO DROP (PEP_PE05, PEPLEASING_PE05, CENTROSAP_PE05);
ALTER TABLE OPERACION.SOLOT_PEP_ANTERIOR DROP (ELEMENTOPEP_PE05);
