REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF FROM USRBDBTCHSGA;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX ON OPERACION.TRSBAMBAF_HIST FROM USRBDBTCHSGA;
drop table OPERACION.TRSBAMBAF_HIST;
COMMIT;
