DECLARE
  AN_ID_PARAMETRO    NUMBER;
  AN_TIPTRA_A        NUMBER;
  AN_TIPTRA_D        NUMBER;
  LN_COUNT           NUMBER;
AN_TIPOPEDD    NUMBER;
  
  BEGIN
  LN_COUNT := 0;  
  -- INSERCION DEL TIPTRABAJO - ACTIVAR                                    
    SELECT COUNT(*)
      INTO LN_COUNT 
      FROM TIPTRABAJO T
     WHERE T.DESCRIPCION = 'HFC - ACTIVAR BONO';
    IF LN_COUNT = 0 THEN
      SELECT MAX(T.TIPTRA)+1 INTO AN_TIPTRA_A FROM TIPTRABAJO T;
      IF AN_TIPTRA_A IS NOT NULL THEN
        INSERT INTO TIPTRABAJO (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT, ID_TIPO_ORDEN, ID_TIPO_ORDEN_CE)
        VALUES (AN_TIPTRA_A, NULL, 'HFC - ACTIVAR BONO', SYSDATE, 'IT_CONSULTA', NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, 0, NULL, NULL);
      END IF;
    END IF;  
  
    -- INSERCION DEL TIPTRABAJO - DESACTIVAR                                        
    SELECT COUNT(*)
      INTO LN_COUNT 
      FROM TIPTRABAJO T
     WHERE T.DESCRIPCION = 'HFC - DESACTIVAR BONO';
    IF LN_COUNT = 0 THEN
      SELECT MAX(T.TIPTRA)+1 INTO AN_TIPTRA_D FROM TIPTRABAJO T;
      IF AN_TIPTRA_D IS NOT NULL THEN
        INSERT INTO TIPTRABAJO (TIPTRA, TIPTRS, DESCRIPCION, FECUSU, CODUSU, CUENTA, CODDPT, FLGCOM, FLGPRYINT, CODMOTINSSRV, SOTFACTURABLE, BLOQUEO_DESBLOQUEO, HORAS, AGENDA, HORA_INI, HORA_FIN, AGENDABLE, NUM_REAGENDA, HORAS_ANTES, CORPORATIVO, SELPUNTOSSOT, ID_TIPO_ORDEN, ID_TIPO_ORDEN_CE)
        VALUES (AN_TIPTRA_D, NULL, 'HFC - DESACTIVAR BONO', SYSDATE, 'IT_CONSULTA', NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, 0, NULL, NULL);
      END IF;
    END IF;
  
  --INSERTAR CABECERA CONFIGURACIONJ
        INSERT INTO OPERACION.TIPOPEDD (DESCRIPCION, ABREV) VALUES ('BONO AUMENTA VELOCIDAD', 'FLAG_BONO_VEL');
             
	SELECT A.TIPOPEDD INTO AN_ID_PARAMETRO FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD';
     --INSERTAR DETALLE
	INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (AN_TIPTRA_A, 'HFC - ACTIVAR BONO', AN_ID_PARAMETRO);
             
	INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (AN_TIPTRA_D, 'HFC - DESACTIVAR BONO', AN_ID_PARAMETRO);
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (0, 'PROVISION INCOGNITO', AN_ID_PARAMETRO);

     --INSERT CABECERA

 	INSERT INTO OPERACION.TIPOPEDD (DESCRIPCION, ABREV) VALUES ('PARAMETROS BONO', 'PARAMETROS BONO');
                          
 	SELECT A.TIPOPEDD INTO AN_TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'PARAMETROS BONO';

   --INSERT DETALLE
 	INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('0006', 'TIPSRV_BONO', AN_TIPOPEDD);
             
 	INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('0062', 'TIPSRV_BONO', AN_TIPOPEDD);
             
   
 	INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (658, 'TIPTRA_BONO' , AN_TIPOPEDD);
             
 	INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (695, 'TIPTRA_BONO', AN_TIPOPEDD);


 	INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (0, 'IDSEQ_MIN_BONO' , AN_TIPOPEDD);

        COMMIT;
  END;
/