INSERT INTO OPERACION.OPEDD(CODIGOC,CODIGON,DESCRIPCION,ABREVIACION,TIPOPEDD)VALUES('ZD48DCROA4',647,'DECOD. ARION ARD-2810HP HD PVR 500GB HDD','DTH',197);
INSERT INTO OPERACION.OPEDD(CODIGOC,CODIGON,DESCRIPCION,TIPOPEDD)VALUES('2',15566,'Decodificador',373);
COMMIT;
