DECLARE
  LN_TIPODEDD NUMBER;
  LN_VAL      NUMBER;
BEGIN
  SELECT MAX(T.TIPOPEDD) INTO LN_TIPODEDD FROM OPERACION.TIPOPEDD T;

  LN_TIPODEDD := LN_TIPODEDD + 1;

  SELECT COUNT(1)
    INTO LN_VAL
    FROM OPERACION.TIPOPEDD T
   WHERE T.ABREV = 'ESTSERV_PORTOUT';
   
  IF LN_VAL = 0 THEN
    INSERT INTO OPERACION.TIPOPEDD
      (TIPOPEDD, DESCRIPCION, ABREV)
    VALUES
      (LN_TIPODEDD, 'Estado de Serv', 'ESTSERV_PORTOUT');
  
    INSERT INTO OPERACION.OPEDD
      (CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, Codigon_Aux)
    VALUES
      (1, 'Activo', 'ACTIVO', LN_TIPODEDD, 1);
  
    INSERT INTO OPERACION.OPEDD
      (CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, Codigon_Aux)
    VALUES
      (2, 'Suspendido', 'SUSPENDIDO', LN_TIPODEDD, 0);
  
    INSERT INTO OPERACION.OPEDD
      (CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, Codigon_Aux)
    VALUES
      (3, 'Cancelado', 'CANCELADO', LN_TIPODEDD, 0);
  
    COMMIT;
  END IF;

END;
/
