     --INSERTAR DETALLE
  -- INSERTAR VARIABLES DE FT_INSTDOCUMENTO
 INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (20, 'Componente_basico_I',
   (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD'));
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (99, 'MacAddress_CM',
   (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD'));
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (108, 'Model_CM', 
  (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD'));
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (97, 'SERVICE_ID', 
  (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD'));
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (98, 'serviceType', 
  (SELECT A.TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'BONO AUMENTA VELOCIDAD'));
  COMMIT;