ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA DROP CONSTRAINT PK_SEC_EST_AGE CASCADE;
UPDATE OPERACION.SECUENCIA_ESTADOS_AGENDA SET IDSEQ = OPERACION.SQ_SEC_EST_AGE.NEXTVAL;
ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA MODIFY IDSEQ NOT NULL;
ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA ADD CONSTRAINT PK_IDSEQ_SECUENCIAESTADOAGE PRIMARY KEY (IDSEQ);
