DECLARE
AN_TIPOPEDD    NUMBER;
V_CONTADOR NUMBER; 
BEGIN

--INSERT CABECERA
SELECT COUNT(*) INTO V_CONTADOR FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'PARAMETROS_DOCS_ELECT';
IF V_CONTADOR = 0 THEN
  INSERT INTO OPERACION.TIPOPEDD (DESCRIPCION, ABREV) VALUES ('PARAMETROS_DOCS_ELECT', 'PARAMETROS_DOCS_ELECT');
END IF;

SELECT A.TIPOPEDD INTO AN_TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'PARAMETROS_DOCS_ELECT';

--INSERT DETALLES
IF V_CONTADOR = 0 THEN

  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('SP', 'CODIGO_ARCHIVO_EMISION', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('AC', 'CODIGO_ARCHIVO_ANULACION', AN_TIPOPEDD);

  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('20467534026', 'RUC_CLARO', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('AM', 'RS_CLARO', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('PEN', 'MONEDA_SOLES', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('USD', 'MONEDA_DOLARES', AN_TIPOPEDD);

  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('14', 'CODIGO_RECIBO', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('87', 'CODIGO_NC', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('88', 'CODIGO_ND', AN_TIPOPEDD);

  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('REC', 'TIPO_RECIBO', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('N/C', 'TIPO_NC', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('N/D', 'TIPO_ND', AN_TIPOPEDD);
			 
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD) VALUES (0, 'Flag Enviar 37 Campos en el Anexo 1', 'FLAG_ANEXO_1' , AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGON, DESCRIPCION, TIPOPEDD) VALUES (100000, 'NRO_DOCUMENTOS_MAX' , AN_TIPOPEDD);
		
  -- ANULADOS
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('Recibo Anulado', 'MENSAJE_ANU_REC', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('Nota Credito Anulada', 'MENSAJE_ANU_NC', AN_TIPOPEDD);
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('Nota Debito Anulada', 'MENSAJE_ANU_ND', AN_TIPOPEDD);
  
  COMMIT;

END IF;

END;
/