insert into OPERACION.TIPOPEDD (DESCRIPCION, ABREV)
values ('codsrv de tystabsrv', 'CODSRV_TYSTABSRV');

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('9051', null, 'Pull de 4 IPs Fijas Adicionales CE en HFC 1', 'CODSRV', 
       (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'CODSRV_TYSTABSRV'), 1);
     
insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('APHI', null, 'Pull de 4 IPs Fijas Adicionales CE en HFC 2', 'CODSRV', 
       (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'CODSRV_TYSTABSRV'), 1);
     
insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('APSX', null, 'Pull de 4 IPs Fijas Adicionales CE en HFC 3', 'CODSRV', 
       (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'CODSRV_TYSTABSRV'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('BEDU', null, 'Pull de 4 IPs Fijas Adicionales CE en HFC 4', 'CODSRV', 
       (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'CODSRV_TYSTABSRV'), 1);

COMMIT
/