insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (1, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (1, 36, 'Ampliacion(24 horas)');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (1, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (4, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (4, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (16, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (16, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (22, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (22, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (36, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (36, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (40, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (41, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (43, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (44, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (45, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (51, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (51, 34, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (64, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (68, 2, 'Cerrar');

insert into OPERACION.SGAT_REGLAS_CIERRE (REGCN_ESTAGE_INICIAL, REGCN_ESTAGE_FINAL, REGCV_ACCION)
values (86, 2, 'Cerrar');

commit;