DECLARE
  LN_EXISTE NUMBER;
BEGIN
  SELECT COUNT(TP.TIPOPEDD) INTO LN_EXISTE
  FROM OPERACION.TIPOPEDD TP
  WHERE TP.ABREV = 'TIPO_ANTICIPACION_ALERTAS';
--ANTICIPACION DE ALERTAS: 
  IF LN_EXISTE=0 THEN
        INSERT INTO OPERACION.TIPOPEDD (TIPOPEDD, DESCRIPCION, ABREV)
              VALUES ((SELECT MAX(TIPOPEDD) + 1 FROM OPERACION.TIPOPEDD), 'Anticipación de alertas.', 'TIPO_ANTICIPACION_ALERTAS');

        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              7,
              '7 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            1);

        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              15,
              '15 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            3);
            
        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              30,
              '30 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            10);    
            
        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              60,
              '60 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            20); 
            
        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              90,
              '90 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            30);   
            
        INSERT INTO OPERACION.OPEDD (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
        VALUES (
            (SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD), 
            NULL,
              125,
              '125 Días', 
            'TIPO_ANTICIPACION_ALERTAS',
            (SELECT MAX(TIPOPEDD) FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV)='TIPO_ANTICIPACION_ALERTAS'),
            3);            
  END IF;          
COMMIT;
END;
/
