DECLARE 
 LN_CODETA NUMBER;
 LN_EFESN_ID OPERACION.SGAT_EF_ETAPA_SRVC.EFESN_ID%TYPE;
BEGIN
  LN_CODETA:=0;
--  LN_EFESN_ID:=0;
  /*ETAPA 1*/
  SELECT ET.CODETA
  INTO LN_CODETA
  FROM OPERACION.ETAPA ET 
  WHERE UPPER(ET.DESCRIPCION) = 'CLIENTE-INSTALACION DE ACCESO PEX-MANO DE OBRA-TENDIDO';

  SELECT SRVC.EFESN_ID INTO LN_EFESN_ID FROM OPERACION.SGAT_EF_ETAPA_SRVC SRVC WHERE SRVC.EFESN_CODETA = LN_CODETA;

  --Insertar Mano de Obra 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,14648,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,14647,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,10881,50,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,11056,10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,11053,10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,11058,10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,11052,2,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,10911,4,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,109020,2,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,109301,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,20105,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,14976,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,3244,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);

  --Insertar Materiales
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'001084',10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'000585',10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'000151',10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'007431',2,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'007157',0.1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'000542',10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'007772',10,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1);
  
  LN_CODETA:=0;
  /*ETAPA 2*/
  SELECT ET.CODETA
  INTO LN_CODETA
  FROM OPERACION.ETAPA ET 
  WHERE UPPER(ET.DESCRIPCION) = 'CLIENTE-INSTALACION DE ACCESO PEX -FIBRA';
  
  SELECT SRVC.EFESN_ID INTO LN_EFESN_ID FROM OPERACION.SGAT_EF_ETAPA_SRVC SRVC WHERE SRVC.EFESN_CODETA = LN_CODETA;
  
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'022960',75,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  LN_CODETA:=0;
  /*Etapa 3*/
  SELECT ET.CODETA
  INTO LN_CODETA
  FROM OPERACION.ETAPA ET 
  WHERE UPPER(ET.DESCRIPCION) = 'CLIENTE-INSTALACION DE ACCESO PEX-MATERIAL';
  
  SELECT SRVC.EFESN_ID INTO LN_EFESN_ID FROM OPERACION.SGAT_EF_ETAPA_SRVC SRVC WHERE SRVC.EFESN_CODETA = LN_CODETA;
  
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'000210',4,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'000628',2,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'006188',1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'006189',4,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'006187',1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,'026803',1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,1); 
       
  LN_CODETA:=0;
  /*Etapa 4*/
  SELECT ET.CODETA
  INTO LN_CODETA
  FROM OPERACION.ETAPA ET 
  WHERE UPPER(ET.DESCRIPCION) = 'CLIENTE-INSTALACION DE EQUIPOS-MANO DE OBRA';

  SELECT SRVC.EFESN_ID INTO LN_EFESN_ID FROM OPERACION.SGAT_EF_ETAPA_SRVC SRVC WHERE SRVC.EFESN_CODETA = LN_CODETA;

  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,13303,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,13304,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0); 
  INSERT INTO OPERACION.SGAT_EF_ETAPA_CNFG(EFESN_ID,EFECV_CODPAR,EFECN_CANTIDAD,EFECN_MCMD,EFECN_DCMD,EFECN_MUMD,EFECN_ESTADO,EFECV_USUREG, EFECD_FECREG,EFECV_USUMOD,EFECD_FECMOD,EFECN_TIPASG) VALUES (LN_EFESN_ID,13306,1,0,0,0,1,'EASTULLE',SYSDATE,NULL,NULL,0);   

  commit;
END;
/

