-- INSERTS TABLA TIPOPEDD
INSERT INTO OPERACION.TIPOPEDD(DESCRIPCION, ABREV) VALUES ('Tipo Trabajo - Tareas','TIPTRA_TAREAS'); 
COMMIT;

-- INSERTS TABLA OPEDD
INSERT INTO OPERACION.OPEDD(CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX) VALUES ('Generar Reserva IW',1019,'HFC/SISACT - MIGRACION SISACT','678',(SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'TIPTRA_TAREAS'),1);
INSERT INTO OPERACION.OPEDD(CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX) VALUES ('Generacion de Transaccion IW',10192,'HFC/SIAC - CAMBIO DE PLAN','695',(SELECT TIPOPEDD FROM OPERACION.TIPOPEDD T WHERE T.ABREV = 'TIPTRA_TAREAS'),1);
COMMIT;
