DECLARE
 LN_CANT NUMBER;
 LN_COUNT NUMBER;

BEGIN
 SELECT COUNT(1)
   INTO LN_CANT
   FROM TIPOPEDD T, OPEDD O
  WHERE T.TIPOPEDD = O.TIPOPEDD
    AND T.ABREV = 'ASIG_IP/MASK_SGA'
    AND O.ABREVIACION = 'IP_NO_ASIGNABLE';

  IF LN_CANT = 0 THEN 
    --internet
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.7.253',
        NULL,
       'IP tunel Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.7.254',
        NULL,
       'IP tunel Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
    --INTRANET
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.15.253',
        NULL,
       'IP tunel Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.15.254',
        NULL,
       'IP tunel Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);   
    --GESTION
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.23.253',
        NULL,
       'IP tunel Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '10.100.23.254',
        NULL,
       'IP tunel Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);  
    --INTERNET
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.19.253',
        NULL,
       'IP Loopback Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.19.254',
        NULL,
       'IP Loopback Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1); 
    --INTRANET
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.23.253',
        NULL,
       'IP Loopback Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.23.254',
        NULL,
       'IP Loopback Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);   
    --GESTION
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.27.253',
        NULL,
       'IP Loopback Principal',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1);
       
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD,
       CODIGOC,
       CODIGON,
       DESCRIPCION,
       ABREVIACION,
       TIPOPEDD,
       CODIGON_AUX)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '100.113.27.254',
        NULL,
       'IP Loopback Backup',
       'IP_NO_ASIGNABLE',
       (SELECT MAX(TIPOPEDD)
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'ASIG_IP/MASK_SGA'),
       1); 
    COMMIT;
  END IF;

  SELECT COUNT(1)
    INTO LN_COUNT
    FROM OPERACION.OPEDD
   WHERE ABREVIACION = 'Mascara_IP'
     AND CODIGON IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 26, 27, 31, 32);

  IF LN_COUNT = 0 THEN

    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.255.255',
       32,
       'Mascara IP 32',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.255.254',
       31,
       'Mascara IP 31',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.255.224',
       27,
       'Mascara IP 27',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.255.192',
       26,
       'Mascara IP 26',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.255.0',
       24,
       'Mascara IP 24',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.254.0',
       23,
       'Mascara IP 23',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.248.0',
       21,
       'Mascara IP 21',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.240.0',
       20,
       'Mascara IP 20',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.224.0',
       19,
       'Mascara IP 19',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.192.0',
       18,
       'Mascara IP 18',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.128.0',
       17,
       'Mascara IP 17',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.255.0.0',
       16,
       'Mascara IP 16',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.254.0.0',
       15,
       'Mascara IP 15',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.252.0.0',
       14,
       'Mascara IP 14',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.248.0.0',
       13,
       'Mascara IP 13',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.240.0.0',
       12,
       'Mascara IP 12',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.224.0.0',
       11,
       'Mascara IP 11',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.192.0.0',
       10,
       'Mascara IP 10',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.128.0.0',
       9,
       'Mascara IP 9',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '255.0.0.0',
       8,
       'Mascara IP 8',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '254.0.0.0',
       7,
       'Mascara IP 7',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '252.0.0.0',
       6,
       'Mascara IP 6',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
  
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '248.0.0.0',
       5,
       'Mascara IP 5',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
  
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '240.0.0.0',
       4,
       'Mascara IP 4',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '224.0.0.0',
       3,
       'Mascara IP 3',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '192.0.0.0',
       2,
       'Mascara IP 2',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
  
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '128.0.0.0',
       1,
       'Mascara IP 1',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
    INSERT INTO OPERACION.OPEDD
      (IDOPEDD, CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
    VALUES
      ((SELECT MAX(IDOPEDD) + 1 FROM OPERACION.OPEDD),
       '0.0.0.0',
       0,
       'Mascara IP 0',
       'Mascara_IP',
       (SELECT MAX(TIPOPEDD)
          FROM TIPOPEDD
         WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA'));
         
      UPDATE OPEDD O SET O.CODIGOC = '192.168.0.1' WHERE TIPOPEDD IN 
        (SELECT TIPOPEDD
           FROM TIPOPEDD
          WHERE UPPER(ABREV) = 'ASIG_IP/MASK_SGA')
          AND ABREVIACION = 'IP/MASK_WAN';
    COMMIT;
  END IF;
END;
/
