INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (3, 1, '010396         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (4, 1, '008723         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (5, 1, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (6, 1, '009372         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (7, 2, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (8, 2, '000738         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (1, 1, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (2, 1, '009349         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (9, 2, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (10, 2, '008723         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (11, 2, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (12, 2, '008721         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (13, 2, '008722         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (14, 3, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (15, 3, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (16, 3, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (17, 3, '017244         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (18, 3, '018831         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (19, 3, '018885         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (21, 4, '000738         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (22, 4, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (23, 4, '008723         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (24, 4, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (25, 4, '009373         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (26, 4, '009374         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (27, 5, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (28, 5, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (29, 5, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (30, 5, '017244         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (31, 5, '018921         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (32, 5, '018922         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (20, 4, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (33, 6, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (34, 6, '000738         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (35, 6, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (36, 6, '008723         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (37, 6, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (38, 6, '008721         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (39, 6, '016706         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (40, 8, '008217         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (41, 8, '009349         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (42, 8, '010396         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (43, 8, '008723         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (44, 8, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (45, 8, '009372         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (46, 8, '016707         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (47, 9, '000738         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (48, 9, '017613         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (49, 9, '009390         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (50, 9, '017595         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (51, 9, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (52, 9, '016706         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (53, 9, '017093         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (54, 11, '009349         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (55, 11, '010396         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (56, 11, '009390         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (57, 11, '017595         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (58, 11, '001437         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (59, 11, '016707         ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (60, 11, '017093         ');

COMMIT;

