
insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (100, 'psVoiceHfcMultidestino_Spr3', 1, 'HFC', 'psVoiceHfcMultidestino_Spr3', '1', '0004', '001', 'AELE', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (101, 'psVoiceHfcMin_Spr3', 2, 'HFC', 'psVoiceHfcMin_Spr3', '1', '0004', '001', 'AELE', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (102, 'psInternetHfc_Spr3', 3, 'HFC', 'psInternetHfc_Spr3', '1', '0006', '002', 'AEKX', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (103, 'psTvHfcBasic_Spr3', 4, 'HFC', 'psTvHfcBasic_Spr3', '1', '0062', '003', 'AHGA', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (104, 'psFixed', 5, 'HFC', 'psFixed', '0', '0004', '200', 'AJMB', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (105, 'psFixedPostHfcOnNetOptSpr3', 6, 'HFC', 'psFixedPostHfcOnNetOptSpr3', '0', '0004', '001', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (106, 'psFixedPostHfcOffNetOptSpr3', 7, 'HFC', 'psFixedPostHfcOffNetOptSpr3', '0', '0004', '001', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (107, 'psTvHfcChannelPckOptSpr3', 8, 'HFC', 'psTvHfcChannelPckOptSpr3', '0', '0009', '003', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (108, 'psTvHfcChannelPckOptSpr3', 9, 'HFC', 'psTvHfcChannelPckOptSpr3', '0', '0009', '003', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (109, 'psTvHfcChannelPckOptSpr3', 10, 'HFC', 'psTvHfcChannelPckOptSpr3', '0', '0009', '003', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (110, 'psTvDecoHFCAddOnSpr3', 11, 'HFC', 'psTvDecoHFCAddOnSpr3', '0', '0062', '005', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (111, 'psTvDecoHFCAddOnSpr3', 12, 'HFC', 'psTvDecoHFCAddOnSpr3', '0', '0062', '005', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (112, 'psTvDecoHFCAddOnSpr3', 13, 'HFC', 'psTvDecoHFCAddOnSpr3', '0', '0062', '005', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (113, 'psTvDecoHFCAddOnSpr3', 14, 'HFC', 'psTvDecoHFCAddOnSpr3', '0', '0062', '005', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (114, 'psTvDecoHFCAddOnSpr3', 15, 'HFC', 'psTvDecoHFCAddOnSpr3', '0', '0062', '005', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (115, 'psFixedTelEquipHfcSpr3', 16, 'HFC', 'psFixedTelEquipHfcSpr3', '0', '0004', '003', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (116, 'psFixedIntEquipHfcSpr3', 17, 'HFC', 'psFixedIntEquipHfcSpr3', '0', '0004', null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (117, 'psVoiceMultidestinoLTESpr3', 18, 'LTE', 'psVoiceMultidestinoLTESpr3', '1', '0004', '200', 'AOLU', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (118, 'psVoiceRpcLTE_Spr3', 19, 'LTE', 'psVoiceRpcLTE_Spr3', '1', '0004', '200', 'AJMB', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (119, 'psBasicInternetLteSpr3', 20, 'LTE', 'psBasicInternetLteSpr3', '1', '0006', '201', 'AODJ', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (120, 'psTvDTHBasicSpr3', 21, 'DTH', 'psTvDTHBasicSpr3', '1', '0062', '003', 'AEFR', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (121, 'psMultiDestInterLTESpr3', 22, 'LTE', 'psMultiDestInterLTESpr3', '1', '0004', '200', 'APCA', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (122, 'psTeleInterBasicLTESpr3', 23, 'LTE', 'psTeleInterBasicLTESpr3', '1', '0006', '200', 'AODJ', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (123, 'psFixed', 24, 'HFC', 'psFixed', '0', '0004', '001', null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (124, 'psClaroFijoOnNetLteOptSpr3', 25, 'LTE', 'psClaroFijoOnNetLteOptSpr3', '0', '0004', '200', 'BBEP', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (125, 'psFixedLteOffNetOptSpr3', 26, 'LTE', 'psFixedLteOffNetOptSpr3', '0', '0006', '206', 'BAUX', 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (126, 'psTvSapDTHChannelPckSpr3', 27, 'DTH', 'psTvSapDTHChannelPckSpr3', '0', null, null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (127, 'psTvDecoDTHSpr3', 28, 'DTH', 'psTvDecoDTHSpr3', '0', null, null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (128, 'psFixedTelEquipLteSpr3', 29, 'LTE', 'psFixedTelEquipLteSpr3', '0', '0004', null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (129, 'psBundleDecosSpr3', 30, 'HFC', 'psBundleDecosSpr3', '0', null, null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (126, 'psTvSapDTHChannelPckSpr3', 27, 'LTE', 'psTvSapDTHChannelPckSpr3', '0', null, null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (127, 'psTvDecoDTHSpr3', 28, 'LTE', 'psTvDecoDTHSpr3', '0', null, null, null, 1);

insert into OPERACION.SGAT_PS_TCRM (IDPS, CODPS, IDFAMILLIA, TIPO_TECNOLOGIA, DESCRIPCION, PRINCIPAL, TIPSRV, IDGRUPO_SISACT, CODSRV, ESTADO)
values (120, 'psTvDTHBasicSpr3', 21, 'LTE', 'psTvDTHBasicSpr3', '1', '0062', '203', 'AQBG', 1);
commit;