--Script Alter table
ALTER TABLE  OPERACION.EFPTO 
        ADD (EFPTV_ESCENARIO    VARCHAR2(5), 
			 EFPTV_TIPO_COSTEO  VARCHAR2(1));

COMMENT ON COLUMN OPERACION.EFPTO.EFPTV_ESCENARIO   IS 'Tipo de Escenarios';
COMMENT ON COLUMN OPERACION.EFPTO.EFPTV_TIPO_COSTEO IS 'Tipo de Costeo: M-Manual o A-Automatico';