INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('VOZ','SICORP','1','JCORTEZ',sysdate,'A','');
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('INTERNET','SICORP','1','JCORTEZ',sysdate,'B','');
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('DATOS','SICORP','1','JCORTEZ',sysdate,'C','');
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('TV PAGA','SICORP','1','JCORTEZ',sysdate,'D','');

INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('Vent_equipos','SICORP','2','JCORTEZ',sysdate,'0331','');
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('Vent_equiposRCE','SICORP','2','JCORTEZ',sysdate,'6543','');

INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('MERCA_CORP','SICORP','3','JCORTEZ',sysdate,'1','');

COMMIT;
