insert into OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('10231', null, 'Cambiar Estado a Pend Porta', 'TAREADEF_CTRL', (SELECT TIPOPEDD FROM TIPOPEDD WHERE ABREV = 'PORT_IN'), null);

commit;