GRANT EXECUTE ON operacion.PKG_MIGRACION_SGA_BSCS TO USRSISACT;  

GRANT SELECT  ON OPERACION.MIGRT_DET_TEMP_SOT TO USRSISACT;

GRANT SELECT, UPDATE  ON OPERACION.MIGRT_CAB_TEMP_SOT TO USRSISACT;

GRANT INSERT ON OPERACION.MIGRT_ERROR_MIGRACION TO USRSISACT;


