--VALORES CONFIGURAR LA RUTA
INSERT INTO OPERACION.CONSTANTE(CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES('MOVDESP','CODIGO DE MOVIMIENTO DEL DESPACHO','C','IT_CONSULTA',SYSDATE,'221','CODIGO DE MOVIMIENTO DEL DESPACHO -INTERFACE WEB SERVICE SAP');
COMMIT;
INSERT INTO OPERACION.CONSTANTE(CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES('RESP_WS_DESP','RESPUESTA DEL WEBSERVICE DESPACHO SIN CANTIDAD','C','IT_CONSULTA',SYSDATE,'ALutil.libre','VALIDACION DEL BAPI DEL SAP');
COMMIT;
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,VALOR,OBS)
VALUES
('TARGET_URL_DESP','Target URL de COM del servicio Despacho','C','http://172.19.67.97:7909/SAP_Services/Transaction/DespachoAutomatico?wsdl','');
COMMIT;
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,VALOR,OBS)
VALUES
('ACTION_URL_DESP','Target URL de COM del servicio de Despacho','C','http://claro.com.pe/eai/sapservices/DespachoAutomatico','');
commit;
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,VALOR,OBS)
VALUES
('ACTIVE_DESP','Activar envio a SAP para despacho','C','0','');
commit;
INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,VALOR,OBS)
VALUES
('OPERACIONES_SGA','Constante que indica el nombre de la aplicacion ','C','SGA Operaciones','');
commit;


  
 
  

