-- Drop sequence post pago
drop sequence operacion.sq_filename_arch_env_post;
-- Drop sequence pre pago
drop sequence operacion.sq_filename_arch_env_pre;

DELETE FROM OPERACION.OPEDD WHERE UPPER(ABREVIACION) LIKE '%SECUENCIA_PREPAGO%';
DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) LIKE '%SECUENCIA_PREPAGO%';


DELETE FROM OPERACION.OPEDD WHERE UPPER(ABREVIACION) LIKE '%SECUENCIA_POSTPAGO%';
DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) LIKE '%SECUENCIA_POSTPAGO%';

COMMIT;