--ELIMINAR REGISTROS DE OPERACION.ACTIONCP

DELETE FROM OPERACION.ACTIONCP WHERE CODACTION IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);
COMMIT;

--INSERTAR A OPERACION.ACTIONCP

INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (1, 'Agregar Servicio Internet',1,2,'I');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (2, 'Agregar Servicio Telefonia',1,1,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (3, 'Agregar Servicio Cable',1,1,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (4, 'Quitar Servicio Internet',1,2,'I');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (5, 'Quitar Servicio Telefonia',1,2,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (6, 'Quitar Servicio Cable',1,2,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (7, 'Cambiar Velocidad Internet',1,2,'I');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (8, 'Cambiar Minutos Telefonia',1,0,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (9, 'Agregar Servicio Adicional Telefonia',1,0,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (10, 'Quitar Servicio Adicional Telefonia',1,0,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (11, 'Cambiar Plan de Canales Cable',1,2,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (12, 'Agregar Deco Cable',1,1,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (13, 'Quitar Deco Cable',1,2,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (14, 'Agregar Paquete Cable',1,0,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (15, 'Quitar Paquete Cable',1,0,'C');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (16, 'Cambio equipo Telefonia',1,1,'T');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (17, 'Agregar Servicio Adicional Internet',1,0,'I');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (18, 'Quitar Servicio Adicional Internet',1,0,'I');
INSERT INTO OPERACION.ACTIONCP (CODACTION, DESCRIPTION, ACTIVE, VT, TIPSRV) VALUES (19, 'Cambio equipo Internet',1,1,'I');
COMMIT;
