INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (3, 'TM3000 HASTA 10KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (5, 'TM3000 DE 10KM HASTA 15KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (2, 'CMETRO SM HASTA 25 KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (4, 'CMETRO SM MAYOR 25 KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (1, 'CMETRO MM HASTA 3 KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (6, 'ITN CON TARJETA SM HASTA 25KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (7, 'ITN CON TARJETA SM MAYOR A 25KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (8, 'ITN CON TARJETA MM HASTA 3KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (9, 'ITN SIN TARJETA SM HASTA 25KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (10, 'ITN SIN TARJETA SM MAYOR A 25KM');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID, EFEQV_DESCRIPCION)
VALUES (11, 'ITN SIN TARJETA MM HASTA 3KM');

COMMIT;

