
insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '205', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '206', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '207', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '208', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '209', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '210', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '211', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '212', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '213', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '214', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '215', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '216', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '236', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '237', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '238', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (34, '265', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '239', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '240', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '241', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '242', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '81', '827', 'T', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '82', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '83', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '84', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '85', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '86', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '87', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '88', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '89', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '90', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '91', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '92', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (26, '93', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (26, '94', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (26, '95', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '96', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '97', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '98', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '99', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '100', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '101', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '102', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (28, '103', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (28, '104', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '138', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '118', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (27, '120', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '131', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '132', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '133', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '134', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (31, '135', '1004', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '141', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '142', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '143', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '144', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '145', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (36, '352', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (41, '346', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (41, '347', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (73, '351', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '146', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (35, '350', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '333', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '334', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '335', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '336', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '337', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '338', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '339', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '340', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '341', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '147', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '342', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '343', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '344', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '345', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (72, '349', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (8, '38', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (4, '41', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (4, '42', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (5, '43', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (6, '44', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (6, '45', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (6, '46', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '47', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '48', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '49', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '50', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '51', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '52', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '53', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '54', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '55', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (2, '56', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '60', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (8, '40', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '74', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '75', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (32, '148', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (33, '149', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (34, '150', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (35, '151', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (36, '152', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (44, '156', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '196', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '197', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '198', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '199', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '200', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '201', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '202', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '203', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '204', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '243', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '244', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '245', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '246', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '247', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '248', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (61, '251', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (60, '252', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (62, '253', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (62, '254', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (62, '255', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (62, '256', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (62, '257', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (41, '262', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '266', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '267', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '268', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '269', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '270', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '271', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '272', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '273', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '274', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '275', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (47, '155', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (36, '263', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '276', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '277', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '278', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '279', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '280', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '281', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '282', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '283', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '284', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '285', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '286', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '287', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '288', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '289', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '290', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '293', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '294', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '295', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '296', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '297', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '298', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '299', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '300', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '301', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '302', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '303', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '304', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '305', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '306', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '307', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '308', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '309', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (63, '310', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (63, '311', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (63, '312', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (63, '313', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (64, '314', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '315', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '316', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '291', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '292', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (49, '159', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '317', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (69, '318', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (68, '320', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (67, '321', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (67, '322', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (67, '323', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (70, '324', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (65, '325', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (65, '326', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (65, '327', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (65, '328', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (66, '329', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (66, '330', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (66, '331', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (71, '332', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (6, '117', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '121', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '122', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '123', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '124', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '125', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '126', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '127', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (1, '128', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (41, '157', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (48, '158', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '181', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '182', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '183', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '184', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '161', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '162', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '163', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '164', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '165', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '166', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '167', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '168', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '169', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '170', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (42, '171', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (50, '172', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (51, '173', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (52, '174', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (53, '175', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (54, '176', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (55, '177', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (56, '178', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '179', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '180', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '221', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '222', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '76', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '77', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '78', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '79', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (6, '116', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '185', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '186', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '187', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '188', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '189', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '190', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '191', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '192', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '193', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '194', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (57, '195', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '217', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '218', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '219', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (58, '220', '827', 'U', 1);

insert into OPERACION.SGAT_TIPTRA_TIPORD_PEP (ID_TIPO_ORDEN, ID_SUBTIPO_ORDEN, TIPTRA, INDPROC, ESTADO)
values (25, '80', '827', 'U', 1);
COMMIT;