--INSERT REGLA DE PROCESO
INSERT INTO OPERACION.SIAC_NEGOCIO_REGLA (idnegocio, orden, descripcion, sentencia, tipo, flg_activo)
VALUES (1, 1, 'EVALUAR CAMPOS NULOS', 'OPERACION.PQ_SIAC_POSTVENTA.REVIEW_NEGOCIO_PROCESO', 'PRE', 1);

INSERT INTO OPERACION.SIAC_NEGOCIO_REGLA (idnegocio, orden, descripcion, sentencia, tipo, flg_activo)
VALUES (1, 2, 'EVALUAR PRODUCTOS ACTIVOS', 'OPERACION.PQ_SIAC_POSTVENTA.HAS_ACTIVE_SERVICES', 'PRE', 1);

INSERT INTO OPERACION.SIAC_NEGOCIO_REGLA (idnegocio, orden, descripcion, sentencia, tipo, flg_activo)
VALUES (1, 1, 'LISTA DE SERVICIOS CAMBIO DE PLAN', 'OPERACION.PQ_SIAC_POSTVENTA.SET_HIST_SRV_CP', 'POS', 1);

COMMIT;
