insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 425, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 425, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 428, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 428, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 432, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 432, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 438, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 438, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 454, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 454, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 455, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 455, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 456, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 456, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 457, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 457, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 459, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 459, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 460, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 460, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 461, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 461, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 464, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 464, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 469, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 469, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 470, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 470, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 471, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 471, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 472, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 472, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 473, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 473, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 474, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 474, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 475, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 475, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 476, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 476, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 481, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 481, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 482, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 482, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 483, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 483, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 484, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 484, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 486, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 486, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 487, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 487, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 488, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 488, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 490, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 490, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 492, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 492, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 493, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 493, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 498, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 498, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 499, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 499, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 600, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 600, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 601, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 601, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 602, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 602, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 603, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 603, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 608, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 608, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 609, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 609, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 612, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 612, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 718, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 718, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 727, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 727, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 790, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('DTH', 790, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 404, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 404, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 407, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 407, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 424, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 424, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 480, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 480, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 489, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 489, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 610, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 610, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 658, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 658, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 661, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 661, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 676, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 676, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 725, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 725, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 770, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('HFC', 770, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 744, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 744, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 746, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 746, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 747, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 747, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 748, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 748, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 749, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 749, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 750, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 750, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 751, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 751, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 752, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 752, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 757, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 757, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 758, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 758, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 759, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 759, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 760, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 760, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 791, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('LTE', 791, 17);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('WIMAX', 726, 10);

insert into OPERACION.SGAT_TIPTRA_RECLA_SOT (TTRSV_PRODUCTO, TTRSN_TIPO_TRABAJO, TTRSN_ESTADO_SOT)
values ('WIMAX', 726, 17);

commit;