DECLARE
  CURSOR C_CABECERA IS
    SELECT TIPOPEDD
      FROM OPERACION.TIPOPEDD
     WHERE ABREV = 'CONF_PORTAL_CAUTIVO';
BEGIN
  FOR C_CAB IN C_CABECERA LOOP
  
    DELETE FROM OPERACION.OPEDD WHERE TIPOPEDD = C_CAB.TIPOPEDD;
    DELETE FROM OPERACION.TIPOPEDD WHERE TIPOPEDD = C_CAB.TIPOPEDD;
  
    COMMIT;
  END LOOP;

  DELETE FROM OPERACION.OPE_ESTADOSERVICIO_REL;
  DELETE FROM OPERACION.OPE_SEGMENTOMERCADO_REL;
  DELETE FROM OPERACION.OPE_SERVICIOMENSAJE_REL;
  DELETE FROM OPERACION.OPE_MENSAJES_MAE;
  DELETE FROM OPERACION.OPE_COMANDOPARAMETRO_REL;
  DELETE FROM OPERACION.OPE_COMANDO_REL;

  DELETE FROM OPE_GRUPOS_REL;
  DELETE FROM OPE_GRUPOMENSSOL_DET;
  DELETE FROM OPE_GRUPO_MENSAJES_DET;
  DELETE FROM OPERACION.OPE_PROCESOS_REL;

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/