insert into OPERACION.TIPROY_SINERGIA
  (TIPROY,
   PAIS,
   CLASEPROY,
   RUBROINV,
   PLATAFORMA,
   DESTIPROY,
   TIPORED,
   TIPOUBITEC,
   SOC_CO,
   SOC_FI,
   CECO_RES,
   PERFILPROY,
   SEGMENTO,
   PERFILGRAFO,
   CLASEGRAFO,
   PLANIF_NEC,
   CENTROGRAFO,
   FLAG_PLANO,
   GRUPOSERVICIO,
   CLAVECONTROL,
   FABRICANTE,
   CREA_PROYECTO,
   CECO_SOL,
   CLASE_ACTIVO,
   FLAG_MASIVO,
   PROY_INT_SINERGIA,
   TIPROY_SAP,
   TIPROY_PAD,
   ASIGNA_PEP)
values
  ('FUS',
   'PE',
   'H',
   'HF',
   'F',
   'FTTH-HUBS',
   'RF',
   'IN',
   'PE00',
   'PE02',
   '0211A00118',
   'ZPE2TVF',
   'F',
   'ZRFTVPE',
   'RFTV',
   'PF1',
   'P001',
   1,
   '10',
   'ZPEF',
   'NODO',
   '1',
   '0210AF@1I2',
   '9078',
   0,
   1,
   'FUS',
   null,
   0);
------
insert into OPERACION.tiproy_sinergia_pep
  (ID_SEQ,
   TIPROY,
   DESCRIPCION,
   RUBROINV,
   CLASIF_OBRA,
   NATURALEZA_PEP,
   NIVEL,
   ID_SEQ_PAD,
   ESTADO,
   AREA,
   CONSECUTIVO,
   CREA_GRAFO,
   CLASE_ACTIVO,
   TIPOPROYECTO,
   CECO_RES,
   CECO_SOL,
   GENERA_RESERVA,
   CREA_PEPN2,
   ID_SEQ_HIJO_NOP,
   ASIGNA_SOT_PEPN3,
   CODUSU,
   FECUSU,
   TIPSRV,
   ASIGNA_CECO_PRY,
   PEP_ETAPA)
values
  ((select max(ID_SEQ) + 1 from operacion.tiproy_sinergia_pep),
   'FUS',
   'INFRAESTRUCTURA FTTH',
   'HF',
   null,
   null,
   2,
   null,
   1,
   null,
   null,
   0,
   '9078',
   null,
   null,
   null,
   0,
   '1',
   null,
   0,
   user,
   sysdate,
   null,
   0,
   0);

---------------

insert into OPERACION.tiproy_sinergia_pep
  (ID_SEQ,
   TIPROY,
   DESCRIPCION,
   RUBROINV,
   CLASIF_OBRA,
   NATURALEZA_PEP,
   NIVEL,
   ID_SEQ_PAD,
   ESTADO,
   AREA,
   CONSECUTIVO,
   CREA_GRAFO,
   CLASE_ACTIVO,
   TIPOPROYECTO,
   CECO_RES,
   CECO_SOL,
   GENERA_RESERVA,
   CREA_PEPN2,
   ID_SEQ_HIJO_NOP,
   ASIGNA_SOT_PEPN3,
   CODUSU,
   FECUSU,
   TIPSRV,
   ASIGNA_CECO_PRY,
   PEP_ETAPA)
values
  ((select max(ID_SEQ) + 1 from operacion.tiproy_sinergia_pep),
   'FTN',
   'NECESIDAD OPERACIONAL PLANTA EXT.',
   'RF-HF',
   null,
   'EXPA',
   3,
   (select ID_SEQ
      from operacion.tiproy_sinergia_pep
     where TIPROY = 'FUS'
       and DESCRIPCION = 'INFRAESTRUCTURA FTTH'),
   0,
   'INGE',
   null,
   0,
   '9078',
   'PE-RF-HF-PEH',
   '0211A00118',
   '0210AF@1I2',
   0,
   '1',
   null,
   1,
   user,
   sysdate,
   null,
   0,
   0);

insert into OPERACION.tiproy_sinergia_pep
  (ID_SEQ,
   TIPROY,
   DESCRIPCION,
   RUBROINV,
   CLASIF_OBRA,
   NATURALEZA_PEP,
   NIVEL,
   ID_SEQ_PAD,
   ESTADO,
   AREA,
   CONSECUTIVO,
   CREA_GRAFO,
   CLASE_ACTIVO,
   TIPOPROYECTO,
   CECO_RES,
   CECO_SOL,
   GENERA_RESERVA,
   CREA_PEPN2,
   ID_SEQ_HIJO_NOP,
   ASIGNA_SOT_PEPN3,
   CODUSU,
   FECUSU,
   TIPSRV,
   ASIGNA_CECO_PRY,
   PEP_ETAPA)
values
  ((select max(ID_SEQ) + 1 from operacion.tiproy_sinergia_pep),
   'FUS',
   'CONTRUCCION DE HUBS',
   'RF-HF',
   null,
   'NUEV',
   3,
   (select ID_SEQ
      from operacion.tiproy_sinergia_pep
     where TIPROY = 'FUS'
       and DESCRIPCION = 'INFRAESTRUCTURA FTTH'),
   1,
   'INGE',
   'HU',
   0,
   '9078',
   'PE-RF-HF-HUS',
   '0211A00118',
   '0210AF@1I2',
   0,
   '1',
   null,
   1,
   user,
   sysdate,
   null,
   0,
   0);

insert into OPERACION.tiproy_sinergia_pep
  (ID_SEQ,
   TIPROY,
   DESCRIPCION,
   RUBROINV,
   CLASIF_OBRA,
   NATURALEZA_PEP,
   NIVEL,
   ID_SEQ_PAD,
   ESTADO,
   AREA,
   CONSECUTIVO,
   CREA_GRAFO,
   CLASE_ACTIVO,
   TIPOPROYECTO,
   CECO_RES,
   CECO_SOL,
   GENERA_RESERVA,
   CREA_PEPN2,
   ID_SEQ_HIJO_NOP,
   ASIGNA_SOT_PEPN3,
   CODUSU,
   FECUSU,
   TIPSRV,
   ASIGNA_CECO_PRY,
   PEP_ETAPA)
values
  ((select max(ID_SEQ) + 1 from operacion.tiproy_sinergia_pep),
   'FUS',
   'NECESIDAD OPERACIONAL HUBS',
   'RF-HF',
   null,
   'EXPA',
   3,
   (select ID_SEQ
      from operacion.tiproy_sinergia_pep
     where TIPROY = 'FUS'
       and DESCRIPCION = 'INFRAESTRUCTURA FTTH'),
   0,
   'INGE',
   null,
   0,
   '9078',
   'PE-RF-HF-HUS',
   '0211A00118',
   '0210AF@1I2',
   0,
   '1',
   null,
   1,
   user,
   sysdate,
   null,
   0,
   0);

insert into OPERACION.tiproy_sinergia_pep
  (ID_SEQ,
   TIPROY,
   DESCRIPCION,
   RUBROINV,
   CLASIF_OBRA,
   NATURALEZA_PEP,
   NIVEL,
   ID_SEQ_PAD,
   ESTADO,
   AREA,
   CONSECUTIVO,
   CREA_GRAFO,
   CLASE_ACTIVO,
   TIPOPROYECTO,
   CECO_RES,
   CECO_SOL,
   GENERA_RESERVA,
   CREA_PEPN2,
   ID_SEQ_HIJO_NOP,
   ASIGNA_SOT_PEPN3,
   CODUSU,
   FECUSU,
   TIPSRV,
   ASIGNA_CECO_PRY,
   PEP_ETAPA)
values
  ((select max(ID_SEQ) + 1 from operacion.tiproy_sinergia_pep),
   'FTN',
   'PLANTA EXTERNA',
   'RF-HF',
   null,
   'NUEV',
   3,
   (select ID_SEQ
      from operacion.tiproy_sinergia_pep
     where TIPROY = 'FUS'
       and DESCRIPCION = 'INFRAESTRUCTURA FTTH'),
   1,
   'INGE',
   'PE',
   0,
   '9078',
   'PE-RF-HF-PEH',
   '0211A00118',
   '0210AF@1I2',
   0,
   '1',
   null,
   1,
   user,
   sysdate,
   null,
   0,
   0);

commit;
/