-- Agregar campos a: OPERACION.SGAT_APINT_IMAGEN
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN ADD apintn_idagenda NUMBER(8);
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN ADD apintv_cod_tipo_foto VARCHAR2(10);
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN ADD apintv_desc_img_1 VARCHAR2(100);
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN ADD apintb_img_1 BLOB;
ALTER TABLE OPERACION.SGAT_APINT_IMAGEN ADD apintn_flag_carga NUMBER(1) default 0;

-- Add comments to the columns 
comment on column OPERACION.SGAT_APINT_IMAGEN.apintn_idagenda
  is 'Codigo de Id agenda';
comment on column OPERACION.SGAT_APINT_IMAGEN.apintv_cod_tipo_foto
  is 'Codigo de la foto en la matriz (Gestion Fotografica)';
comment on column OPERACION.SGAT_APINT_IMAGEN.apintv_desc_img_1
  is 'Descripcion de la imagen subida por el tecnico';
comment on column OPERACION.SGAT_APINT_IMAGEN.apintb_img_1
  is 'Imagen subida por el tecnico';
comment on column OPERACION.SGAT_APINT_IMAGEN.apintn_flag_carga
  is 'Flag de carga de la imagen';
  
-- INSERT OPERACION.SGAT_MATRIZ_SERV

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 1 Play Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 8, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 1 Play Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('instalación 1 Play TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 2 Play Internet + Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 8, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 2 Play Internet + TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 11, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 2 Play Voz + TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Instalación 3 Play (Internet + Voz + TV)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 1, 'INSTALACION', 12, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Externo (se registra de acuerdo al plan de instalación contratado) (idem a Instalación)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 1, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Tv', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Internet y Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Internet y TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Voz y TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno Servicio de Internet, Voz y TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Traslado Interno, Cambio de eMTA u ONT por actualización tecnológica', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet se adiciona servicio de Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet se adiciona servicio de TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet se adiciona servicio de TV+Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, se modifica BW de Internet que involucra cambio de equipo eMTA u ONT', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Voz se adiciona servicio de Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Voz se adiciona servicio de TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Voz se adiciona servicio de TV+Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 8, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, TV se adiciona servicio de Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, TV se adiciona servicio de Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, TV se adiciona servicio de Internet+Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 8, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + Voz se adiciona servicio de TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + Voz se adiciona servicio de TV y se cambia eMTA u ONT', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + TV se adiciona servicio de Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, TV + Voz se adiciona servicio de Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira Internet+Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira Internet + TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3 Play se retira Voz+TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3Play se retira decos (sigue siendo 3play)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3Play se retira decos (sigue siendo 3play) y cambio de BW', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, 3Play se adicionan decos (sigue siendo 3play) + cambio de BW', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + Voz se retira Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + Voz se retira Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + TV se retira TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Internet + TV se retira Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Voz + TV se retira TV', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, Voz + TV se retira Voz', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, se modifica Plan TV involucra cambio de modelo de decos (# número de decos)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, se modifica Plan de Internet y TV, solo involucra cambio de decos', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Plan, se modifica Plan de Internet y TV que involucra cambio de eMTA u ONT y cambio de decos', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente  (cuando tenemos 1Play TV)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente  (cuando tenemos 2Play TV + IAV)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente  (cuando tenemos 2Play TV+IAV) + cambio de eMTA u ONT', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente (cuando tenemos 2Play  TV + Voz)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente  (cuando tenemos 3Play)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Decodificador adicional / Decodificador pendiente  (cuando tenemos 3Play) + cambio de eMTA u ONT', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Router adicional / PLC adicional', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Punto Adicional de Voz (anexo)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Punto Adicional de Internet', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('ADICIONAL: Instalación accesorio de Internet propiedad del Cliente', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Baja decodificador de Alquiler (cuando tenemos 3Play, 2Play IAV+TV o 2Play Fono+TV)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Baja decodificador de Alquiler (cuando tenemos 1 Play TV)', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 3, 'POSTVENTA', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('CLARO EMPRESAS HFC - SERVICIOS MENORES - Fijacion de ip', null, null, null, null, null, null, null, 4, 0);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - Control Remoto no funciona', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - Cambio de PLC / ROUTER', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - Instalación de PLC / ROUTER', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT por Cambio de tecnología / Fidelización', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT problemas del equipo', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT dañado por el Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - ROUTER dañado por el Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - Reposicion de eMTA u ONT por robo/pérdida ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT problemas del equipo + Cambio de Acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 9, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT dañado por el Cliente + Cambio de Acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 10, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT problemas del equipo + cambio de Cable interno', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 9, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT dañado por el Cliente + cambio de cable interno', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 10, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - STB problemas del equipo + Cambio de Acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - STB dañado por Cliente + Cambio de Acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - STB problemas del equipo', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - STB dañado por Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - Reposicion de STB por robo/pérdida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Faltó la instalación de uno o más decodificadores', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - STB problema del equipo + cambio de Cable interno', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - STB dañado por el Cliente + cambio de cable interno', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - TELEFONO problema del equipo', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Teléfono dañado por el Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT problemas del equipo - Negocios + IP FIJA', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT dañado por el Cliente - NEGOCIOS + IP FIJA', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - EMTA u ONT por cambio de tecnología / Fidelización - Negocios + IP FIJA', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Control remoto roto o sin pilas', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - TV/Control Remoto desprogramado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente desconfiguro el Router', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente modificó cableado interno', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente cambio los conectores y/o divisores internos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente movió EMTA u ONT a otro lugar', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente movió ROUTER a otro lugar', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente movió STB a otro lugar', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Cliente agregó anexos telefónicos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Se encontró varias computadoras conectadas (Cabina)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE -Uso indebido del Servicio - Antena Repartidora', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto PIRATERIA - Cliente comparte señal a otras personas o vecinos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Equipo telefonico desconfigurado (en pulso y no en tono)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Equipo telef. mal conectado al eMTA (en línea 2 y no en 1)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT desconectado de la corriente eléctrica', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - STB desconectado de la corriente eléctrica', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - eMTA u ONT mal conectado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Router mal conectado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - STB mal conectado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Prob. con las tomas de corriente eléctrica en el domicilio del Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - No cuenta con minutos para llamar', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - TV del Cliente Malogrado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Se encontro direccion IP Fija y/o DNS de otro Operador', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Problemas con la PC del Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Problemas con Equipos propiedad del Cliente', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Reinstalación por incendio, remodelación o construcción (3Play)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 8, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Envio de comandos de Central STB', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Reactivacion de Paquetes adicionales', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Configuración Avanzada (3 a mas equipos)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Configuración de Puerto eMTA u ONT', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - WIFI Cambio de clave', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - WIFI Cliente se olvido su clave', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - WIFI Cambio de Modo de Encriptación', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Problema Extensión de cobertura Wifi', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Pruebas de servicio de Internet (ping, test de velocidad, tracert,etc)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Reinicio de EMTA u ONT - problema de Internet', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CONFIGURACION - Reinicio de EMTA u ONT - problema de Telefonía', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - Línea no activada', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - Llamadas no se concretan a ciertos números determinados', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - Problemas para recibir o llamar a ciertos países y/o provincias', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - Operadora indica que numero no existe (llamada entrante). ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - No funciona correctamente la Central Virtual', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - CONMUTACION - No funciona el Hunting', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 3, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA -  Mala Señal  (TV Analógico)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA -  Mala Señal  (TV Digital)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA -  Niveles RF Altos / Bajos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA - Enlace Lento', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA - Intermitencia / Pérdida de paquetes', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA - Corte de energia en la zona ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DERIVADO - PLANTA EXTERNA - Sin Servicio / Averia Masiva', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cliente daño el cable de audio video y/o HDMI', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cable de audio y video averiado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cable HDMI averiado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - NO dejaron cable de video / HDMI / UTP', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cambio de acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto TERCEROS - Acometida roto o robada', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cambio de acometida + Cambio de cables internos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 9, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto TERCEROS - Acometida roto o robada + Cambio de cables internos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 9, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cable telefónico averiado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - MANIPULACION CLIENTE - Cables internos averiado ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Cable interno dañado o roto', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cable interno averiado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Cambio de Fuente Decodificador', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Conector Óptico sucio', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Conectores y/o Divisores sulfatados', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conectores y/o Divisores flojos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Reacomodo de acometida', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Roseta averiada', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto DISPOSITIVO INTERNO - Roseta ÓPTICA averiada', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conector mal preparado en cable de acometida ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conector mal preparado en cable que conecta solo al eMTA u ONT', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conector mal preparado en cable que conecta solo al STB ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conector mal preparado en cable lineal telefónico', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Conector mal preparado en cable lineal de datos', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 6, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Inspeccion Tecnica - Verificación de servicio Cable contratado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Inspeccion Tecnica - Verificación de servicio Internet contratado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 5, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Inspeccion Tecnica - Verificación de servicio Telefonía contratado', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Mala ubicación de los equipos (Decodificador)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Mala ubicación de los equipos (eMTA u ONT)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Mala ubicación de los equipos (Teléfono)', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - Mala distribucion cambio de cables', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto INSTALACION - NO cambiaron el cableado interno que era de otro operador ', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto TERCEROS - Reconexión', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto TERCEROS - Acometida desconectada del borne del TAP', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 7, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CAMBIO DE EQUIPO - STB por cambio de tecnología / Fidelización', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto CLIENTE - PROB. CLIENTE - Problemas con Software terminal', null, 3, 'HFC / FTTH', 5, 'Residencial / Claro Empresas / Claro Empresas + IP / CATV Analogico', 2, 'MANTENIMIENTO', 4, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de Tarjeta de TAP', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 4, 'CAMBIO DE TAP', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Cambio de TAP saturado en poste/edificio', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 4, 'CAMBIO DE TAP', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Auditoría de TAP en poste/edificio y limpieza de TAP', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 4, 'CAMBIO DE TAP', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Registro de niveles en TAP', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 4, 'CAMBIO DE TAP', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Auditoría de TAP instalado', null, 3, 'HFC / FTTH', 6, 'Residencial / Claro Empresas / Claro Empresas + IP', 4, 'CAMBIO DE TAP', 2, 1);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Cliente dará de baja el servicio', null, null, null, null, null, null, null, 2, 0);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Cliente esta Ausente', null, null, null, null, null, null, null, 2, 0);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Cliente informa Servicio conforme-visita técnica', null, null, null, null, null, null, null, 2, 0);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - Cliente informa ya no desea asistencia técnica', null, null, null, null, null, null, null, 2, 0);

insert into OPERACION.SGAT_MATRIZ_SERV (SERVV_DESCRIPCION, SERVN_TIPTRA, SERVN_ID_TIPORED, SERVV_TIPORED, SERVN_ID_TIPOSERV, SERVV_TIPOSERV, SERVN_ID_TIPO_TRABAJO, SERVV_TIPO_TRABAJO, SERVN_CANT_FOTOS, SERVN_FLAG_ACTIVO)
values ('Mantto MOVILIZACION - No Hay facilidades tecnicas ', null, null, null, null, null, null, null, 3, 0);

-- INSERT OPERACION.SGAT_MATRIZ_FOTO


insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN01', 'Foto panorámica de ubicación encontrada del eMTA u ONT, caso de falla física mostrar detalle', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN02', 'Foto del lado posterior del eMTA u ONT (se debe visualizar las conexiones)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN03', 'Foto panorámica de ubicación encontrada del Decodificador, caso falla física mostrar detalle', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN04', 'Foto panorámica de ubicación anterior del Teléfono, de tener falla física mostrar detalle', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN05', 'Foto de registros en el eMTA u ONT que muestren Niveles de señal y/o SNR y/o configuraciones incorrectas', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN06', 'Foto de Niveles de operatividad de los Decodificadores, Otros de Operatividad', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN07', 'Foto del primer splitter instalado / splitters en servicio', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN08', 'Foto panorámico del (los) control (es) remoto (s) averiado (s)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN09', 'Foto del equipo Router instalado', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN10', 'Foto de jumper RF, AV y/o HDMI averiado', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN11', 'Foto del conector/splitter/roseta defectuos/tomas eléctricas; casos de acometida FTTH mostrar deficiencias del conector SC', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN12', 'Foto del cable interno defectuoso', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN13', 'Foto de Acometida deteriorada / mal instalada', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN14', 'Configuración errada', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN15', 'Foto con registro de conectividad nula, sin IP, asignaciones erradas, sin tono etc ', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN16', 'Foto con Inconveniente en Internet', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN17', 'Foto con inconvenientes en Video', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN18', 'Nombre y numeración de la casa/edificio frente al poste donde se encuentra el TAP PRINCIPAL saturado', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN19', 'Vista del TAP PRINCIPAL mostrando su valor, bornes y cintillos identificados', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN20', 'Vista del TAP ANTERIOR del poste/piso mostrando su valor, bornes y cintillos identificados', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN21', 'Vista del TAP POSTERIOR del poste/piso mostrando su valor, bornes y cintillos identificados', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN22', 'Vista de los niveles del TAP existente (empleando DISAM o eMTA)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('AN23', 'Vista de los insertables encontrados en el TAP a reemplazar', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP01', 'Foto de la fachada o lugar del domicilio o ambiente del domicilio del Cliente que confirme Coordenadas de la dirección de atención', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP02', 'Foto cercana del TAP o Splitter óptico (FAT), debe visualizarce # de cintillo o puerto de identificación', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP03', 'Foto panorámica del TAP o Splitter óptico visualizando el loop, peinado y recorrido inicial del cable', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP04', 'Foto del recorrido del cable externo mostrando la chapa "Q" de sujeción', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP05', 'Foto del punto de anclaje de la acometida a la casa', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP06', 'Foto de los divisores (splitters) instalados/usados en la distribución interna', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP07', 'Foto de los conectores instalados, para acometida FTTH mostrar el conector SC', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP08', 'Foto en el lugar del  divisor luego de ejecutado el (los)  retiro (s) del (los) servicio (s)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP09', 'Foto del cableado interior (sea el caso: RG6, Telefónico, UTP de datos)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP10', 'Acta de Servicio Técnico', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP11', 'Topología de red interna. Se debe de mostrar longitudes de jumpers y ubicación de los equipos en el interior del domicilio.', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP12', 'Arquitectura de Red', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP13', 'Foto del lado posterior del eMTA u ONT (se debe visualizar las conexiones)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP14', 'Foto panorámica de ubicación del eMTA u ONT, con vista de PC/Laptop/Notebook con página abierta. Para CE # de fotos igual a # de eMTA', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP15', 'Foto de niveles RF en el eMTA u ONT. Para CE # de fotos igual a la cantidad de eMTA', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP16', 'Foto de test de Ping Extendido a DNS de Claro 190.113.220.18 / 51 / 54. # de paquetes de prueba es de 100', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP17', 'Fotos de configuración Wifi en eMTA u ONT, 2.4 GHz y/o 5GHz (de tener el equipo)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP18', 'Foto de configuración Port Forwarding en eMTA u ONT', 0, 1);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP19', 'Cambio a modo Bridge / Configuracion Passthrough', 0, 1);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP20', 'Foto de equipo fijo/móvil conectado al servicio instalado / Idem Repetidor (01 foto por equipo del Cliente)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP21', 'Operatividad de Internet: Test de velocidad en puerta del equipo', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP22', 'Foto de portadoras Wifi a 5 mts de distancia del equipo en ambiente instalado (vista con aplicativo Wifi analyzer)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP23', 'Operatividad de Internet: test de velocidad Wifi a 5 mts de distancia (resultados por cada equipo propiedad del Cliente)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP24', 'Foto del lado posterior del decodificador (se debe visualizar las conexiones)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP25', 'Foto panorámica de ubicación de los Deco mostrando imagen en TV y control remoto', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP26i', 'Foto de Diagnóstico Inband Status de los decos instalados en las pantallas del TV', 1, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP26o', 'Foto de Diagnóstico OOB Status de los decos instalados en las pantallas del TV', 1, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP27', 'Foto panorámica de la ubicación del telefóno. Para CE # de fotos igual a la cantidad de Teléfonos', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP28', 'Foto del lado posterior del telefóno (se debe visualizar las conexiones)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP29', 'Foto de roseta(s) de existir extensión telefónica. Para CE # de fotos igual a la cantidad de extensiones realizadas', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP30', 'Foto de problemas de infraestructura Externa (Amp. Robado / Pasivo robado / poste caido)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP31', 'Foto del nuevo Jumper, HDMI instalado', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP32', 'Foto de la falta de Facilidad técnica / motivo de fraude / Uso indebido (Antena repartidora, cabina)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP33', 'Foto de conexión del punto de Red físico a equipo del Cliente (laptop de prueba) hasta una distancia de 45 mts', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP34', 'Foto de equipos (deco, eMTA, ONT) o partes retiradas', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP35', 'Foto de la(s) configuración(es) del Repetidor (es) propiedad del Cliente', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP36', 'Foto panorámica que muestre el (los) accesorio (s) de Internet propiedad del Cliente instalado (s)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP37', 'Vista del nuevo TAP instalado (limpiado) mostrando el valor y los bornes  (conectados y libres)', 0, 0);

insert into operacion.sgat_matriz_foto (FOTOV_COD_MATRIZ, FOTOV_DESC_MATRIZ, FOTON_FLAG_DECO, FOTON_FLAG_EMP)
values ('DP38', 'Vista de los niveles del TAP reemplazado (empleando DISAM o eMTA)', 0, 0);


-- INSERT OPERACION.SGAT_MATRIZ_REPORT

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 24, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 26, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 33, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 38, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 39, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 40, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 41, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (1, 42, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (2, 24, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (2, 26, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (2, 33, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (2, 38, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (2, 51, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 24, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 26, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 33, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 34, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 49, 1);

insert into OPERACION.SGAT_MATRIZ_REPORT (REPORTN_ID_SERV, REPORTN_ID_FOTO, REPORTN_FLAG_ACTIVO)
values (3, 50, 1);

/