DELETE FROM OPERACION.SGAT_EF_EQUIPO_CNFG;

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (3, 1, '10396          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (4, 1, '8723           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (5, 1, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (6, 1, '9372           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (7, 2, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (8, 2, '738            ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (1, 1, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (2, 1, '9349           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (9, 2, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (10, 2, '8723           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (11, 2, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (12, 2, '8721           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (13, 2, '8722           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (14, 3, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (15, 3, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (16, 3, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (17, 3, '17244          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (18, 3, '18831          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (19, 3, '18885          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (21, 4, '738            ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (22, 4, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (23, 4, '8723           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (24, 4, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (25, 4, '9373           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (26, 4, '9374           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (27, 5, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (28, 5, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (29, 5, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (30, 5, '17244          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (31, 5, '18921          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (32, 5, '18922          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (20, 4, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (33, 6, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (34, 6, '738            ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (35, 6, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (36, 6, '8723           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (37, 6, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (38, 6, '8721           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (39, 6, '16706          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (40, 8, '8217           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (41, 8, '9349           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (42, 8, '10396          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (43, 8, '8723           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (44, 8, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (45, 8, '9372           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (46, 8, '16707          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (47, 9, '738            ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (48, 9, '17613          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (49, 9, '9390           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (50, 9, '17595          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (51, 9, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (52, 9, '16706          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (53, 9, '17093          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (54, 11, '9349           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (55, 11, '10396          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (56, 11, '9390           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (57, 11, '17595          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (58, 11, '1437           ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (59, 11, '16707          ');

INSERT INTO OPERACION.SGAT_EF_EQUIPO_CNFG (EFQCN_ID, EFEQN_ID, EFQCV_CODMAT)
VALUES (60, 11, '17093          ');

COMMIT;
