--alter a campos NOMBAN
alter table CUSBRA.CXCBOLETO modify NOMBAN VARCHAR2(100);
alter table PRODUCCION.CAREMI modify NOMBAN VARCHAR2(100);
alter table PRODUCCION.CTBBANCOS modify NOMBAN VARCHAR2(100);
alter table COLLECTIONS.TABBAN modify NOMBAN VARCHAR2(100);
alter table CUSPER.OPE_INALAMBRICO_DOCUMENTOS modify NOMBAN VARCHAR2(100);
alter table SOPFIJA.TABPAGOS modify NOMBAN VARCHAR2(100);
alter table ATCCORP.TEMP_DETALLE_PAGO modify NOMBAN VARCHAR2(100);
/
