declare

begin

insert into OPERACION.TIPOPEDD (DESCRIPCION, ABREV)
values ('Envio mail - Configuracion', 'ENVIO_MAIL');
     
 commit;
end;
/

declare
ln_tipopedd number;

begin
select TIPOPEDD into ln_tipopedd from OPERACION.TIPOPEDD where abrev='ENVIO_MAIL';

insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (1,3,'Suspendida', 'TIPESTSOL', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (1,131,'CONFIGURACION', 'TIPTRA', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (1,102,'VENTAS CORPORATIVO', 'AREASOL', ln_tipopedd);

insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (2,4,'Cerrada', 'TIPESTSOL', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (2,131,'CONFIGURACION', 'TIPTRA', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (2,102,'VENTAS CORPORATIVO', 'AREASOL', ln_tipopedd);

insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (3,5,'Anulada', 'TIPESTSOL', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (3,131,'CONFIGURACION', 'TIPTRA', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (3,102,'VENTAS CORPORATIVO', 'AREASOL', ln_tipopedd);

insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (4,7,'Rechazada', 'TIPESTSOL', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (4,131,'CONFIGURACION', 'TIPTRA', ln_tipopedd);
insert into OPERACION.OPEDD (CODIGOC,CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)values (4,102,'VENTAS CORPORATIVO', 'AREASOL', ln_tipopedd);
commit;
end;
/
