insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Claro Hogar', 407);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Otros', 407);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Otros', 725);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Otros', 726);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Otros', 727);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Productos Corporativos', 725);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'Productos Corporativos', 726);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'TV Satelital', 727);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC RECLAMOS', 'TV Satelital', 790);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC HFC', 'Claro Hogar', 407);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC HFC', 'Claro Hogar', 725);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC LTE', 'Claro Hogar  (LTE TDD)', 752);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC LTE', 'Claro Hogar  (LTE TDD)', 791);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC POSTPAGO', 'TV Satelital', 727);

insert into OPERACION.SGAT_TIPTRA_RECLA (TTREV_APLICACION, TTREV_SERVICIO, TTREN_TIPO_TRABAJO)
values ('SIAC POSTPAGO', 'TV Satelital', 790);

commit;