alter table operacion.trsoac  drop column OBSERVACION;

DELETE
  FROM OPEDD
 WHERE TIPOPEDD IN
       (SELECT TIPOPEDD FROM TIPOPEDD WHERE ABREV = 'IDTRANCORTE_SUS');


DELETE FROM TIPOPEDD WHERE ABREV = 'IDTRANCORTE_SUS';


COMMIT; 