-- Add/modify columns 
alter table OPERACION.OPE_RESERVAHFC_BSCS modify respuestaxml VARCHAR2(4000);
ALTER TABLE PRODUCCION.FACSUSREC_REV  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.SOLOT  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.TIPINFOTXMOTOT  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.T_CMD  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.INTERFTELEFONIALOG  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.INT_SOLOT  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.MOTOTXAREA  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.OT  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.PLANFLUJO  MODIFY  CODMOTOT NUMBER;
ALTER TABLE ATCCORP.ATCINCIDENCEXSOLOT  MODIFY  CODMOTOT NUMBER;
ALTER TABLE SALES.CONFSOTBAJA  MODIFY  CODMOTOT NUMBER;
ALTER TABLE ATCCORP.CASE_ATENTION  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.TIPOTRANSACCION  MODIFY  CODMOTOT NUMBER;
ALTER TABLE OPERACION.MOTIVO_TIPTRABAJO  MODIFY  CODMOTOT NUMBER;
ALTER TABLE HISTORICO.OPE_OT_LOG  MODIFY  CODMOTOT NUMBER;
ALTER TABLE ATCCORP.CASEXTYPESERVICE  MODIFY  CODMOTOT NUMBER;


COMMIT;
/