--Parámetro Configuración generación de trama/SOT

INSERT INTO OPERACION.PARAMETRO_CAB_ADC (DESCRIPCION, ABREVIATURA, ESTADO) VALUES ('CONF. FLAG AGENLIQ.SGAT_AGENDA', 'FLAG_SGAT_AGENDA', '1');

--Parámetro Configuración de Inserción a tabla SGAT_AGENDA_SERVINST

INSERT INTO OPERACION.PARAMETRO_CAB_ADC (DESCRIPCION, ABREVIATURA, ESTADO) VALUES ('CONF.ESTADO ACCIONES EN TABLA SGAT_AGENDA_SERVINST','EST_AGEN_SERV','1');
COMMIT;
