DELETE FROM OPERACION.OPEDD WHERE UPPER(ABREVIACION) LIKE '%AREASOL%';
DELETE FROM OPERACION.OPEDD WHERE UPPER(ABREVIACION) LIKE '%TIPTRA%';
DELETE FROM OPERACION.OPEDD WHERE UPPER(ABREVIACION) LIKE '%TIPESTSOL%';
DELETE FROM OPERACION.TIPOPEDD WHERE UPPER(ABREV) LIKE '%ENVIO_MAIL%';
COMMIT;
--Procedimiento
drop procedure operacion.p_envia_correo_sot_atendida;
commit;
