insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00024', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00025', 'DTH', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00075', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00076', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00002', 'HFC', '020990', 'Tel.analógico,ITC-G009W,Blanco', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00003', 'HFC', '024672', 'EMTA ARRIS TG862A DOCSIS3.0 S. SLOT - NON BATETTERY', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00004', 'HFC', '024672', 'EMTA ARRIS TG862A DOCSIS3.0 S. SLOT - NON BATETTERY', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00005', 'HFC', '024672', 'EMTA ARRIS TG862A DOCSIS3.0 S. SLOT - NON BATETTERY', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00006', 'HFC', '024672', 'EMTA ARRIS TG862A DOCSIS3.0 S. SLOT - NON BATETTERY', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00007', 'HFC', '023554', 'EMTA ARRIS TG862G/CE-8 DOCSIS 3.0', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00008', 'HFC', '023554', 'EMTA ARRIS TG862G/CE-8 DOCSIS 3.0', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00009', 'HFC', '026922', 'MODEM EMTA DUAL BAND DPC3940L-A07-K9', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00010', 'HFC', '026824', 'MODEM SAGEMCOM 3686AC 24X8 3.0 S/BAT', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00011', 'HFC', '026824', 'MODEM SAGEMCOM 3686AC 24X8 3.0 S/BAT', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00012', 'HFC', '026824', 'MODEM SAGEMCOM 3686AC 24X8 3.0 S/BAT', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00013', 'HFC', '026824', 'MODEM SAGEMCOM 3686AC 24X8 3.0 S/BAT', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00014', 'HFC', '024495', 'DTA ARRIS HD-DTA100U MPEGG4 HDMI OUTPUT', 2, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00014', 'HFC', '015804', 'Set Top Box DCT700 - HD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00015', 'HFC', '020928', 'Set Top Box DCX700', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00015', 'HFC', '015804', 'Set Top Box DCT700 - HD', 2, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00016', 'HFC', '020928', 'Set Top Box DCX700', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00016', 'HFC', '015804', 'Set Top Box DCT700 - HD', 2, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00048', 'HFC', '015804', 'Set Top Box DCT700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00049', 'HFC', '024072', 'DECODIFICADOR MOTOROLA DCX3510 SEPTOPBOX DVR', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00050', 'HFC', '020928', 'Set Top Box DCX700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00051', 'HFC', '015804', 'Set Top Box DCT700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00052', 'HFC', '020928', 'Set Top Box DCX700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00053', 'HFC', '015804', 'Set Top Box DCT700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00054', 'HFC', '024072', 'DECODIFICADOR MOTOROLA DCX3510 SEPTOPBOX DVR', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00055', 'HFC', '020928', 'Set Top Box DCX700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00056', 'HFC', '015804', 'Set Top Box DCT700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00057', 'HFC', '020928', 'Set Top Box DCX700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00058', 'HFC', '015804', 'Set Top Box DCT700', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00059', 'HFC', '024072', 'DECODIFICADOR MOTOROLA DCX3510 SEPTOPBOX DVR', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00085', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00086', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 2, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00087', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 3, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00088', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 4, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00089', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00090', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00089', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00090', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 2, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00080', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00081', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00082', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00075', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00076', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00077', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00078', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00079', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00024', 'LTE', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00025', 'LTE', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00023', 'LTE', '022533', 'DECODIFICADOR AF-5012S - ARION', 2, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00083', 'LTE', '026484', 'TERMINAL HUAWEI LTE TDD RED', 1, '209', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00019', 'LTE', '025193', 'CAJA LTE TDD CPE B2268S', 1, '209', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00019', 'LTE', '024557', 'SIM CARD LTE', 1, '209', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00023', 'DTH', '022533', 'DECODIFICADOR AF-5012S - ARION', 2, '008', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00077', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00078', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00079', 'DTH', '023512', 'DECODIFICADOR HD ARION AF-5210VHD', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00080', 'DTH', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00081', 'DTH', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);

insert into OPERACION.SGAT_PO_EQUIPO_TCRM (IDPO, TIPO_TECNOLOGIA, CODTIPEQU, DESCRIPCION, CANTIDAD, MODALIDAD, ESTADO)
values ('00082', 'DTH', '021790', 'DECODIFICADOR HD ARION AF-2710VHDPR', 1, '009', 1);
COMMIT;