DECLARE
AN_TIPOPEDD    NUMBER;
V_CONTADOR NUMBER; 
BEGIN

--OBTENER CABECERA
SELECT A.TIPOPEDD INTO AN_TIPOPEDD FROM OPERACION.TIPOPEDD A WHERE A.DESCRIPCION = 'PARAMETROS_DOCS_ELECT';

SELECT COUNT(*) INTO V_CONTADOR FROM OPERACION.OPEDD A WHERE A.DESCRIPCION = 'SERIES_PERMITIDAS' AND A.TIPOPEDD = AN_TIPOPEDD;

--INSERT DETALLES
IF V_CONTADOR = 0 THEN
  INSERT INTO OPERACION.OPEDD (CODIGOC, DESCRIPCION, TIPOPEDD) VALUES ('0', 'SERIES_PERMITIDAS', AN_TIPOPEDD);
  COMMIT;
END IF;

END;
/