INSERT INTO OPEDD
(CODIGON,DESCRIPCION, ABREVIACION, TIPOPEDD)
VALUES(1,'FLAG CONTROL ADICIONALES TELEFONIA FIJA','ADIC_TELFIJA', (select TIPOPEDD from TIPOPEDD where ABREV = 'MIGR_SGA_BSCS'));
commit;
