INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (11, 5, 8, '1', '8', '1', 'MO', 11, 0, 6, 11, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (12, 5, 8, '1', '8', '1', 'MO', 14, 0, 7, 12, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (13, 5, 8, '1', '8', '1', 'MU', 9, 0, 8, 13, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (14, 5, 8, '1', '8', '1', 'MU', 12, 0, 0, 14, 'MO');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (15, 5, 8, '1', '8', '0', 'MO', 11, 0, 9, 15, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (16, 5, 8, '1', '8', '0', 'MO', 14, 0, 10, 16, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (17, 5, 8, '1', '8', '0', 'MU', 9, 0, 11, 17, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (18, 5, 8, '1', '8', '0', 'MU', 12, 0, 0, 18, 'MO');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (19, 5, 8, '0', '0', '2', '00', 0, 5, 0, 19, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (20, 5, 5, '1', '0', '2', 'MO', 10, 0, 3, 20, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (21, 5, 5, '1', '0', '2', 'MO', 15, 0, 5, 21, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (22, 5, 5, '1', '0', '2', 'MO', 13, 1, 0, 22, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (23, 5, 5, '1', '0', '2', 'MU', 0, 1, 0, 23, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (24, 5, 5, '0', '0', '2', '00', 0, 1, 0, 24, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (25, 5, 1, '1', '7', '1', 'MO', 11, 0, 2, 25, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (26, 5, 1, '1', '7', '1', 'MO', 14, 0, 4, 26, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (27, 5, 1, '1', '7', '1', 'MU', 9, 0, 1, 27, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (28, 5, 1, '1', '7', '1', 'MU', 12, 0, 0, 28, 'MO');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (29, 5, 1, '1', '7', '0', '00', 0, 0, -1, 29, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (5, 6, 5, '0', '0', '2', '00', 0, 1, 0, 5, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (1, 6, 5, '1', '0', '2', 'MO', 10, 0, 3, 1, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (6, 6, 1, '1', '7', '1', 'MO', 11, 0, 2, 6, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (7, 6, 1, '1', '7', '1', 'MO', 14, 0, 4, 7, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (8, 6, 1, '1', '7', '1', 'MU', 9, 0, 1, 8, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (9, 6, 1, '1', '7', '1', 'MU', 12, 0, 0, 9, 'MO');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (10, 6, 1, '1', '7', '0', '00', 0, 0, -1, 10, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (4, 6, 5, '1', '0', '2', 'MU', 0, 1, 0, 4, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (2, 6, 5, '1', '0', '2', 'MO', 15, 0, 5, 2, '00');

INSERT INTO OPERACION.SGAT_EF_REGLACOSTEO_PINT (EFRCN_ID, EFRCN_AB_ID, EFRCN_TIP_EQUIPO, EFRCC_COND_1, EFRCV_CONCEPTO, EFRCC_COND_2, EFRCV_TIP_FIBRA, EFRCN_DIST_ID, EFRCN_CONTINUAR, EFRCN_PINT, EFRCN_PRIORIDAD, EFRCV_CONTINUAR2)
VALUES (3, 6, 5, '1', '0', '2', 'MO', 13, 1, 0, 3, '00');

COMMIT;