INSERT INTO OPERACION.SGAT_RESERVA_TOA (RESTV_NRO_ORDEN,RESTN_SECUENCIA,RESTN_ESTADO)
VALUES ('RT1000',1000,2);

ALTER TABLE OPERACION.MATRIZ_TYSTIPSRV_TIPTRA_ADC
  ADD FLAG_RESERVA NUMBER(1) DEFAULT 0;
  
insert into operacion.tipopedd (DESCRIPCION, ABREV)
values ('HFC CE Transacciones Postventa', 'CEHFCPOST');

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 823, 'CE HFC - DECO ADICIONAL', 'CEHFC_INSDECO', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 822, 'CE HFC - PUNTO ADICIONAL', 'CEHFC_INSPTO', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 0);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 824, 'CE HFC - RETIRO DECO ADICIONAL', 'CEHFC_DESDECO', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('T', 820, 'CE HFC - TRASLADO EXTERNO', 'CEHFC_TRSEXT', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 821, 'CE HFC - TRASLADO INTERNO', 'CEHFC_TRSINT', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('T', 620, 'CLARO EMPRESAS HFC - SERVICIOS MENORES', 'CEHFC_CP', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'CEHFCPOST'), 0);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('37','No se puede realizar agendamiento en línea, falta configurar bucket','ORA-29276: transfer timeout','MSJ_TIM_OUT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','689','HFC/SIAC - DECO ADICIONAL','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','693','HFC/SIAC - TRASLADO EXTERNO','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','694','HFC/SIAC - TRASLADO INTERNO','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','695','HFC/SIAC - CAMBIO DE PLAN','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','700','HFC/SIAC - PUNTO ADICIONAL','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','705','HFC/SIAC - BAJA DECO ALQUILER','SISACT',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','754','WLL/SIAC - TRASLADO EXTERNO','DIA_SIGUIENTE',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','755','WLL/SIAC - TRASLADO INTERNO','DIA_SIGUIENTE',1);

INSERT INTO OPERACION.PARAMETRO_DET_ADC (ID_PARAMETRO,CODIGOC,CODIGON,DESCRIPCION,ABREVIATURA,ESTADO) 
VALUES ('53','O','762','WLL/SIAC - PUNTO ADICIONAL','DIA_SIGUIENTE',1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('1', 833, 'HFC/SIAC - CAMBIO DE EQUIPO', 'SIAC-HFC-CAMBIO_EQUIPO', (select o.tipopedd from operacion.tipopedd o where o.abrev = 'TIPO_TRANS_SIAC'), 10);

commit
/