GRANT SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_WEBSERVICE TO USREAISGA;
GRANT SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_ESCENARIOS TO USREAISGA;
GRANT SELECT, UPDATE, INSERT, DELETE ON OPERACION.WIMAX_PARAM_ING TO USREAISGA;

GRANT SELECT, UPDATE ON OPERACION.OT TO USREAISGA; 
GRANT SELECT, UPDATE ON OPERACION.SOLOT TO USREAISGA; 
GRANT SELECT, UPDATE ON OPERACION.SOLOTPTO TO USREAISGA; 
GRANT SELECT, UPDATE ON OPERACION.TMP_SOLOT_CODIGO TO USREAISGA; 
GRANT SELECT, UPDATE ON OPERACION.TRANSACCIONES TO USREAISGA; 
GRANT SELECT, UPDATE ON OPERACION.TRANSACCIONES_CABLE TO USREAISGA; 

GRANT SELECT ON OPERACION.ENVCORREO TO USREAISGA; 
GRANT SELECT ON OPERACION.ESTSOL TO USREAISGA; 
GRANT SELECT ON OPERACION.INCIDENCE_DTH TO USREAISGA; 
GRANT SELECT ON OPERACION.INSSRV TO USREAISGA; 
GRANT SELECT ON OPERACION.OPEDD TO USREAISGA; 
GRANT SELECT ON OPERACION.REGINSDTH TO USREAISGA; 
GRANT SELECT ON OPERACION.SOLOTCHGEST TO USREAISGA;
GRANT SELECT ON OPERACION.TIPESTSOL TO USREAISGA; 
GRANT SELECT ON OPERACION.TIPOPEDD TO USREAISGA; 
GRANT SELECT ON OPERACION.TIPTRABAJO TO USREAISGA;