-- Add/modify columns 
UPDATE OPERACION.TRSRECEAI SET IDOAC = NULL;
ALTER TABLE OPERACION.TRSRECEAI MODIFY FECUSU DEFAULT SYSDATE;
ALTER TABLE OPERACION.TRSRECEAI MODIFY CODUSU DEFAULT USER;
ALTER TABLE OPERACION.TRSRECEAI ADD TIPTRS NUMBER;
-- Add comments to the columns 
comment on column OPERACION.TRSRECEAI.tiptrs
  is 'Tipo de transaccion 3 Suspension,4 Reconexion';

--Tiptrabajo
DECLARE
  LN_TIPTRA   NUMBER;
  LN_TIPOPEDD NUMBER;
  LN_IDOPEDD  NUMBER;
  LN_CODMOTOT NUMBER;
  LN_WFDEF    NUMBER;
  LN_TAREA    NUMBER;
BEGIN
--  GENERA TIPTRABAJO
    BEGIN
    SELECT TIPTRA
      INTO LN_TIPTRA
      FROM OPERACION.TIPTRABAJO
     WHERE DESCRIPCION LIKE '%HFC/EAI - RECONEXION DEL SERVICIO%';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      SELECT MAX(TIPTRA) + 1 INTO LN_TIPTRA FROM OPERACION.TIPTRABAJO;
      INSERT INTO OPERACION.TIPTRABAJO
        (TIPTRA, TIPTRS, DESCRIPCION)
      VALUES
        (LN_TIPTRA, 4, 'HFC/EAI - RECONEXION DEL SERVICIO');
    
      SELECT MAX(TIPOPEDD) + 1 INTO LN_TIPOPEDD FROM OPERACION.TIPOPEDD;
    
      INSERT INTO OPERACION.TIPOPEDD
        (TIPOPEDD, DESCRIPCION, ABREV)
      VALUES
        (LN_TIPOPEDD, 'Provision de HFC directo EAI', 'PROVISION_EAI');
      SELECT MAX(IDOPEDD) + 1 INTO LN_IDOPEDD FROM OPERACION.OPEDD;
    
      INSERT INTO OPERACION.OPEDD
        (IDOPEDD, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
      VALUES
        (LN_IDOPEDD,
         LN_TIPTRA,
         'Provision de HFC directo EAI',
         'PROVISION_EAI',
         LN_TIPOPEDD);
  END;

  BEGIN
    SELECT TIPTRA
      INTO LN_TIPTRA
      FROM OPERACION.TIPTRABAJO
     WHERE DESCRIPCION LIKE '%HFC/EAI - SUSPENSION DEL SERVICIO%';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      SELECT MAX(TIPTRA) + 1 INTO LN_TIPTRA FROM OPERACION.TIPTRABAJO;
      INSERT INTO OPERACION.TIPTRABAJO
        (TIPTRA, TIPTRS, DESCRIPCION)
      VALUES
        (LN_TIPTRA, 3, 'HFC/EAI - SUSPENSION DEL SERVICIO');
      BEGIN
        SELECT TIPOPEDD
          INTO LN_TIPOPEDD
          FROM OPERACION.TIPOPEDD
         WHERE ABREV = 'PROVISION_EAI';
      
        SELECT MAX(IDOPEDD) + 1 INTO LN_IDOPEDD FROM OPERACION.OPEDD;
      
        INSERT INTO OPERACION.OPEDD
          (IDOPEDD, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
        VALUES
          (LN_IDOPEDD,
           LN_TIPTRA,
           'Provision de HFC directo EAI',
           'PROVISION_EAI',
           LN_TIPOPEDD);
      
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
        
          SELECT MAX(TIPOPEDD) + 1 INTO LN_TIPOPEDD FROM OPERACION.TIPOPEDD;
        
          INSERT INTO OPERACION.TIPOPEDD
            (TIPOPEDD, DESCRIPCION, ABREV)
          VALUES
            (LN_TIPOPEDD, 'Provision de HFC directo EAI', 'PROVISION_EAI');
          SELECT MAX(IDOPEDD) + 1 INTO LN_IDOPEDD FROM OPERACION.OPEDD;
        
          INSERT INTO OPERACION.OPEDD
            (IDOPEDD, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
          VALUES
            (LN_IDOPEDD,
             LN_TIPTRA,
             'Provision de HFC directo EAI',
             'PROVISION_EAI',
             LN_TIPOPEDD);
      END;
  END;
  
  /*GENERA MOTIVO*/
  BEGIN
    SELECT CODMOTOT
      INTO LN_CODMOTOT
      FROM OPERACION.MOTOT
     WHERE DESCRIPCION = 'OAC-SAC';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      SELECT MAX(CODMOTOT) + 1 INTO LN_CODMOTOT FROM OPERACION.MOTOT;
      INSERT INTO OPERACION.MOTOT
        (CODMOTOT, DESCRIPCION, FLGCOM)
      VALUES
        (LN_CODMOTOT, 'OAC-SAC', 0);
    
      SELECT MAX(TIPOPEDD) + 1 INTO LN_TIPOPEDD FROM OPERACION.TIPOPEDD;
    
      INSERT INTO OPERACION.TIPOPEDD
        (TIPOPEDD, DESCRIPCION, ABREV)
      VALUES
        (LN_TIPOPEDD, 'Provision de HFC directo EAI', 'OAC_SAC_EAI');
      SELECT MAX(IDOPEDD) + 1 INTO LN_IDOPEDD FROM OPERACION.OPEDD;
    
      INSERT INTO OPERACION.OPEDD
        (IDOPEDD, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD)
      VALUES
        (LN_IDOPEDD,
         LN_TIPTRA,
         'Provision de HFC directo EAI',
         'OAC_SAC_EAI',
         LN_TIPOPEDD);
  END;
--  GENERA WF
  SELECT MAX(WFDEF) + 1 INTO LN_WFDEF FROM OPEWF.WFDEF;
  INSERT INTO OPEWF.WFDEF
    (WFDEF, ESTADO, DESCRIPCION)
  VALUES
    (LN_WFDEF, 1, 'RECONEXIÓN DIRECTO EAI');

  SELECT MAX(TAREA) + 1 INTO LN_TAREA FROM OPEWF.TAREAWFDEF;
  INSERT INTO OPEWF.TAREAWFDEF
    (TAREA,
     DESCRIPCION,
     ORDEN,
     TIPO,
     AREA,
     RESPONSABLE,
     WFDEF,
     TAREADEF,
     PRE_MAIL,
     POS_MAIL,
     PRE_TAREAS,
     POS_TAREAS,
     PLAZO,
     ESTADO,
     AREA_FACTIBILIDAD,
     AGRUPA,
     FRECUENCIA,
     FLGANULAR,
     FLGCONDICION,
     CONDICION,
     REGLA_ASIG_CONTRATA,
     REGLA_ASIG_FECPROG,
     AREA_DERIVA_CORREO,
     TIPO_AGENDA,
     FLG_ASIGNAAREA,
     F_ASIGNAAREA,
     FLG_OPC)
    SELECT LN_TAREA,
           DESCRIPCION,
           ORDEN,
           TIPO,
           AREA,
           RESPONSABLE,
           LN_WFDEF,
           TAREADEF,
           PRE_MAIL,
           POS_MAIL,
           PRE_TAREAS,
           POS_TAREAS,
           PLAZO,
           ESTADO,
           AREA_FACTIBILIDAD,
           AGRUPA,
           FRECUENCIA,
           FLGANULAR,
           FLGCONDICION,
           CONDICION,
           REGLA_ASIG_CONTRATA,
           REGLA_ASIG_FECPROG,
           AREA_DERIVA_CORREO,
           TIPO_AGENDA,
           FLG_ASIGNAAREA,
           F_ASIGNAAREA,
           FLG_OPC
      FROM OPEWF.TAREAWFDEF
     WHERE TAREA = 19702;

  SELECT MAX(WFDEF) + 1 INTO LN_WFDEF FROM OPEWF.WFDEF;
  INSERT INTO OPEWF.WFDEF
    (WFDEF, ESTADO, DESCRIPCION)
  VALUES
    (LN_WFDEF, 1, 'SUSPENSIÓN DIRECTO EAI');

  SELECT MAX(TAREA) + 1 INTO LN_TAREA FROM OPEWF.TAREAWFDEF;

  INSERT INTO OPEWF.TAREAWFDEF
    (TAREA,
     DESCRIPCION,
     ORDEN,
     TIPO,
     AREA,
     RESPONSABLE,
     WFDEF,
     TAREADEF,
     PRE_MAIL,
     POS_MAIL,
     PRE_TAREAS,
     POS_TAREAS,
     PLAZO,
     ESTADO,
     AREA_FACTIBILIDAD,
     AGRUPA,
     FRECUENCIA,
     FLGANULAR,
     FLGCONDICION,
     CONDICION,
     REGLA_ASIG_CONTRATA,
     REGLA_ASIG_FECPROG,
     AREA_DERIVA_CORREO,
     TIPO_AGENDA,
     FLG_ASIGNAAREA,
     F_ASIGNAAREA,
     FLG_OPC)
    SELECT LN_TAREA,
           DESCRIPCION,
           ORDEN,
           TIPO,
           AREA,
           RESPONSABLE,
           LN_WFDEF,
           TAREADEF,
           PRE_MAIL,
           POS_MAIL,
           PRE_TAREAS,
           POS_TAREAS,
           PLAZO,
           ESTADO,
           AREA_FACTIBILIDAD,
           AGRUPA,
           FRECUENCIA,
           FLGANULAR,
           FLGCONDICION,
           CONDICION,
           REGLA_ASIG_CONTRATA,
           REGLA_ASIG_FECPROG,
           AREA_DERIVA_CORREO,
           TIPO_AGENDA,
           FLG_ASIGNAAREA,
           F_ASIGNAAREA,
           FLG_OPC
      FROM OPEWF.TAREAWFDEF
     WHERE TAREA = 19702;

  INSERT INTO CUSBRA.BR_SEL_WF
    (TIPTRA, WFDEF)
  VALUES
    ((SELECT TIPTRA
       FROM OPERACION.TIPTRABAJO
      WHERE DESCRIPCION = 'HFC/EAI - RECONEXION DEL SERVICIO'),
     (SELECT WFDEF FROM OPEWF.WFDEF WHERE DESCRIPCION = 'RECONEXIÓN DIRECTO EAI'));

  INSERT INTO CUSBRA.BR_SEL_WF
    (TIPTRA, WFDEF)
  VALUES
    ((SELECT TIPTRA
       FROM OPERACION.TIPTRABAJO
      WHERE DESCRIPCION = 'HFC/EAI - SUSPENSION DEL SERVICIO'),
     (SELECT WFDEF FROM OPEWF.WFDEF WHERE DESCRIPCION = 'SUSPENSIÓN DIRECTO EAI'));
END;
/
COMMIT;