INSERT INTO OPERACION.TIPOPEDD (TIPOPEDD,DESCRIPCION,ABREV)
VALUES (
(SELECT MAX(TIPOPEDD)+1 FROM OPERACION.TIPOPEDD )
,'MATRIZ_DECOS_LTE'
,'MATRIZ_DECOS_LTE'
);
COMMIT;

INSERT INTO OPERACION.OPEDD(IDOPEDD,CODIGOC,CODIGON,DESCRIPCION,ABREVIACION,TIPOPEDD,CODIGON_AUX)
VALUES(
(SELECT MAX(IDOPEDD)+1 FROM OPERACION.OPEDD),'LTE',1,'SD','MATRIZ_DECOS_LTE'
,(select D.TIPOPEDD from TIPOPEDD D WHERE D.DESCRIPCION ='MATRIZ_DECOS_LTE'),4);

INSERT INTO OPERACION.OPEDD(IDOPEDD,CODIGOC,CODIGON,DESCRIPCION,ABREVIACION,TIPOPEDD,CODIGON_AUX)
VALUES(
(SELECT MAX(IDOPEDD)+1 FROM OPERACION.OPEDD),'LTE',1,'HD','MATRIZ_DECOS_LTE'
,(select D.TIPOPEDD from TIPOPEDD D WHERE D.DESCRIPCION ='MATRIZ_DECOS_LTE'),4);

INSERT INTO OPERACION.OPEDD(IDOPEDD,CODIGOC,CODIGON,DESCRIPCION,ABREVIACION,TIPOPEDD,CODIGON_AUX)
VALUES(
(SELECT MAX(IDOPEDD)+1 FROM OPERACION.OPEDD),'LTE',2,'DVR','MATRIZ_DECOS_LTE'
,(select D.TIPOPEDD from TIPOPEDD D WHERE D.DESCRIPCION ='MATRIZ_DECOS_LTE'),4);

COMMIT;

insert into operacion.opedd ( CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('EN DESINSTALACION', 11, 'A Desinstalarse', 'DESIS', (select t.tipopedd from operacion.tipopedd t where t.descripcion='OP-Estado EquipoxOT'), null);

insert into OPERACION.TIPOPEDD (DESCRIPCION, ABREV)
values ('Config. Equipos HFC/LTE', 'CONF_EQU_TIPO');

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1001', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1101', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1004', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1213', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1308', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-2710', 'TMX1309', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1007', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1103', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1107', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1113', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1117', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1204', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1315', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1320', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1321', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1327', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1411', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1417', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 14269, 'AF-5012S ', 'TMX1505', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1104', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1108', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1316', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1409', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1410', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1504', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1509', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1322', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 15267, 'AF-5210VHD ', 'TMX1328', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 18215, 'AF-8013H', 'TMX1528', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 18215, 'AF-8013H', 'TMX1607', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 18215, 'AF-8013H', 'TMX1611', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 18215, 'AF-8013H', 'TMX1615', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 18215, 'AF-8013H', 'TMX1708', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('DVR', 15566, 'ARD-2810HP', 'TMX1112', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('DVR', 15566, 'ARD-2810HP', 'TMX1302', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 8450, 'handam', '1', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('SD', 8450, 'handam', '0', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values ('HD', 19027, 'KAON', 'C', (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 2);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 7242, null, null, (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 1);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 16308, null, null, (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 3);

insert into OPERACION.OPEDD (CODIGOC, CODIGON, DESCRIPCION, ABREVIACION, TIPOPEDD, CODIGON_AUX)
values (null, 16939, null, null, (SELECT TIPOPEDD FROM OPERACION.TIPOPEDD WHERE ABREV = 'CONF_EQU_TIPO'), 4);
COMMIT;

alter table operacion.siac_postventa_proceso add trama clob;
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD IDINTERACCION VARCHAR2(50);
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD FLAG_ACT_DIR_FACT VARCHAR2(2);
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD tiptra number;
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD TIPO_PRODUCTO VARCHAR2(10);
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD CODMOTOT NUMBER;
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD CARGO NUMBER;
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD TIPOSERVICIO VARCHAR2(4);
ALTER TABLE OPERACION.SIAC_POSTVENTA_PROCESO ADD COD_CASO VARCHAR2(1);