INSERT INTO OPERACION.CONSTANTE ( CONSTANTE, DESCRIPCION, TIPO, VALOR)
       VALUES ( 'OPTHFCUSER', 'HFC USER', 'C', 'OPERACION');
INSERT INTO OPERACION.CONSTANTE ( CONSTANTE, DESCRIPCION, TIPO, VALOR)
       VALUES ( 'OPTHFCPWD', 'HFC PWD', 'C', 'OPERACION');
INSERT INTO OPERACION.CONSTANTE ( CONSTANTE, DESCRIPCION, TIPO, VALOR)
       VALUES ( 'OPTHFCURL', 'HFC URL', 'C', 'jdbc:oracle:thin:@172.19.74.104:1521:SGADBUAT');
INSERT INTO OPERACION.CONSTANTE ( CONSTANTE, DESCRIPCION, TIPO, VALOR)
       VALUES ( 'OPTHFCNUM', 'HFC NUM HILOS', 'N', '2');

COMMIT;
       