INSERT INTO OPERACION.TIPTRABAJO (TIPTRA,TIPTRS,DESCRIPCION) VALUES (666,1,'TPI- CAMBIO DE TITULARIDAD');

INSERT INTO operacion.opet_servxtrabajo(STRAN_TIPTRABAJO,STRAN_ESTSOL,STRAN_GRADO,STRAN_CODMOTOT,STRAN_AREA,stran_estado,strac_tipsrv) 
VALUES (666,11,1,15,203 ,1,'0059');

INSERT INTO OPERACION.CONSTANTE (CONSTANTE,DESCRIPCION,TIPO,CODUSU,FECUSU,VALOR,OBS)
VALUES ('SOTTIPSRV','Tipo de servicio para generar SOT Administrativa','C','EASTULLE',sysdate,'0059','Tipo de servicio para generar SOT Administrativa');

 

COMMIT;

