CREATE OR REPLACE PROCEDURE OPERACION.P_ACT_MOTOT_MNT ( a_codot in number, a_tipinfot in number) IS
BEGIN

   UPDATE OT SET CODMOTOT = (SELECT CODMOTOT FROM Tipinfotxmotot WHERE TIPINFOT = A_TIPINFOT )
   WHERE CODOT = A_CODOT;
END;
/


