CREATE OR REPLACE PROCEDURE OPERACION.P_ACTUALIZAR_ESTADOOTPTO(L_CODSOLOT NUMBER,L_PUNTO NUMBER) IS
BEGIN
  UPDATE SOLOTPTO_ID SET ESTADO = 'No Factible'
  WHERE  CODSOLOT = L_CODSOLOT AND PUNTO = L_PUNTO;
END;
/


