CREATE OR REPLACE PROCEDURE OPERACION.P_AUDIT_LOGON(AN_LOGONID in NUMBER) IS

LS_OSUSER AUDIT_LOGON.OSUSER%TYPE;
BEGIN
	  SELECT OSUSER INTO LS_OSUSER FROM SYS.V_$SESSION WHERE AUDSID = USERENV('SESSIONID');

      INSERT INTO AUDIT_LOGON(LOGONID,OSUSER)
	  VALUES (AN_LOGONID ,LS_OSUSER);

END;
/


