CREATE OR REPLACE PROCEDURE OPERACION.P_CAMBIAR_CLIENTE_OPERACIONES (A_NUMSLC IN CHAR, A_CODCLI IN CHAR ) IS

BEGIN

UPDATE INSSRV SET CODCLI = A_CODCLI WHERE
   CODINSSRV IN (SELECT NUMCKT FROM VTADETPTOENL WHERE NUMSLC = A_NUMSLC) AND
   ESTINSSRV <> 3;

UPDATE ACCESO SET CODCLI = A_CODCLI WHERE
   CODINSSRV IN (SELECT NUMCKT FROM VTADETPTOENL WHERE NUMSLC = A_NUMSLC) ;

UPDATE EF SET CODCLI = A_CODCLI WHERE NUMSLC = A_NUMSLC;

UPDATE SOLOT SET CODCLI = A_CODCLI WHERE NUMSLC = A_NUMSLC;

UPDATE ANARED SET CODCLI = A_CODCLI WHERE NUMSLC = A_NUMSLC;





/*
FALTAN

OPERACION CTRLDOC
OPERACION DOCARCHIVO
OPERACION DOCXCLIENTE

YA ESTAN

* OPERACION EF
* OPERACION INSSRV
* OPERACION SOLOT
* OPERACION V_OFERTA_COMERCIAL
* ENCUESTA ANARED

TODAVIA NO

-- METASOLV ACCESO
-- METASOLV CIRCUITO

   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       Null;
     WHEN OTHERS THEN
       Null;

*/


END;
/


