CREATE OR REPLACE PACKAGE OPERACION.PKG_COMP_ELECTRON_SGA IS

  PROCEDURE SGASS_LISTADO_TRAMA(K_CURSOR  OUT SYS_REFCURSOR,
                                K_CODIGO  OUT PLS_INTEGER,
                                K_MENSAJE OUT VARCHAR2);

END PKG_COMP_ELECTRON_SGA;
/