create or replace package COLLECTIONS.PKG_LICITACION is

  -- Author  : JEAN
  -- Created : 18/07/2013 01:56:43 p.m.
  -- Purpose : PKG_LICITACION
  
  -- Public type declarations
  TYPE VG_CURSOR IS REF CURSOR;  
  PROCEDURE SP_LISTA_CLIENTE(P_NOMCLI VARCHAR2,P_CODCLI VARCHAR2 , PO_CURSOR OUT VG_CURSOR);
   
  PROCEDURE SP_LISTA_SERVICIO(P_TIPSRV VARCHAR2,P_NOMABR VARCHAR2, PO_CURSOR OUT VG_CURSOR);
  PROCEDURE SP_LISTA_PROYECTO_FIJA(P_NOMCLI VARCHAR2,P_COD_CLI VARCHAR2, P_NUMSLC VARCHAR2,PO_CURSOR OUT VG_CURSOR);
   

end PKG_LICITACION;