ALTER TABLE OPERACION.ACTETAPAXFOR ADD (
  CONSTRAINT FK_ACTETAPAXFOR_ETAPA 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_ACTETAPAXFOR_FORMULA 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_ACTETAPAXFOR_MATOPE 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT));
