ALTER TABLE OPERACION.ACTXPRECIARIO ADD (
  CONSTRAINT FK_ACTXPRECIARIO_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_ACTXPRECIARIO_PRECIARIO 
 FOREIGN KEY (CODPREC) 
 REFERENCES OPERACION.PRECIARIO (CODPREC));
