ALTER TABLE OPERACION.ACTXACT ADD (
  CONSTRAINT FK_ACTXACT_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_ACTXACT_ACTIVIDAD_DES 
 FOREIGN KEY (CODACT_DES) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT));
