ALTER TABLE OPERACION.ACTXCONTRATAXPREC ADD (
  CONSTRAINT FK_ACTXCONTRATAXPREC_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_ACTXPRECIARIOXPRECPRECIARIO 
 FOREIGN KEY (CODPREC) 
 REFERENCES OPERACION.PRECIARIO (CODPREC));
