ALTER TABLE OPERACION.AGENDAMIENTO ADD (
  CONSTRAINT FK_AGENDAMIENTOTAREA_CODSOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_AGENDAMIENTOTAREA_NUMSLC 
 FOREIGN KEY (NUMSLC) 
 REFERENCES SALES.VTATABSLCFAC (NUMSLC),
  CONSTRAINT FK_AGENDAMIENTOTAREA_CODCNT 
 FOREIGN KEY (CODCNT) 
 REFERENCES MARKETING.VTATABCNTCLI (CODCNT),
  CONSTRAINT FK_AGENDAMIENTOTAREA_CODSUC 
 FOREIGN KEY (CODSUC) 
 REFERENCES MARKETING.VTASUCCLI (CODSUC),
  CONSTRAINT FK_AGENDAMIENTO_01 
 FOREIGN KEY (AREA) 
 REFERENCES OPERACION.AREAOPE (AREA));
