ALTER TABLE OPERACION.CMPXTIPEQU ADD (
  CONSTRAINT FK_CMPXTIPEQU_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU),
  CONSTRAINT FK_CMPXTIPEQU_TIPEQU2 
 FOREIGN KEY (TIPEQUCMP) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
