ALTER TABLE OPERACION.CONTRATAXAREA ADD (
  CONSTRAINT FK_CONTRATAXAREA_AREAOPE 
 FOREIGN KEY (AREA) 
 REFERENCES OPERACION.AREAOPE (AREA),
  CONSTRAINT FK_CONTRATAXAREA_CONTRATA 
 FOREIGN KEY (CODCON) 
 REFERENCES OPERACION.CONTRATA (CODCON));
