ALTER TABLE OPERACION.DESPACHO_MASIVO ADD (
  CONSTRAINT FK_DESPACHO_MASIVO_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_DESPACHO_MASIVO_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
