ALTER TABLE OPERACION.EF ADD (
  CONSTRAINT FK_EF_CLIENTEINT 
 FOREIGN KEY (CLIINT) 
 REFERENCES OPERACION.CLIENTEINT (CLIINT),
  CONSTRAINT FK_EF_PRECIARIO 
 FOREIGN KEY (CODPREC) 
 REFERENCES OPERACION.PRECIARIO (CODPREC));
