ALTER TABLE OPERACION.EFHISMOD ADD (
  CONSTRAINT FK_EFHISMOD_EF 
 FOREIGN KEY (CODEF) 
 REFERENCES OPERACION.EF (CODEF),
  CONSTRAINT FK_EFHISMOD_EFMOTIVOMOD 
 FOREIGN KEY (IDMOTIVO) 
 REFERENCES OPERACION.EFMOTIVOMOD (IDMOTIVO));
