ALTER TABLE OPERACION.EFPTOETAACT ADD (
  CONSTRAINT FK_EFPTOETAACT_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_EFPTOETAACT_EFPTOETA 
 FOREIGN KEY (CODEF, PUNTO, CODETA) 
 REFERENCES OPERACION.EFPTOETA (CODEF,PUNTO,CODETA),
  CONSTRAINT FK_EFPTOETAACT_PRECIARIO 
 FOREIGN KEY (CODPREC) 
 REFERENCES OPERACION.PRECIARIO (CODPREC));
