ALTER TABLE OPERACION.EFPTOEQUCMP_STD ADD (
  CONSTRAINT FK_EFPTOEQUCMP_EFPTOEQU_STD 
 FOREIGN KEY (IDPAQ, PUNTO, ORDEN) 
 REFERENCES OPERACION.EFPTOEQU_STD (IDPAQ,PUNTO,ORDEN)
    ON DELETE CASCADE,
  CONSTRAINT FK_EFPTOEQUCMP_TIPEQU_STD 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
