ALTER TABLE OPERACION.EFPTO ADD (
  CONSTRAINT FK_EFPTO_EF 
 FOREIGN KEY (CODEF) 
 REFERENCES OPERACION.EF (CODEF),
  CONSTRAINT FK_EFPTO_INSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_EFPTO_TIPTRAEF 
 FOREIGN KEY (TIPTRAEF) 
 REFERENCES OPERACION.TIPTRAEF (TIPTRAEF));
