ALTER TABLE OPERACION.EFPTOEQU ADD (
  CONSTRAINT FK_EFPTOEQU_EFPTO 
 FOREIGN KEY (CODEF, PUNTO) 
 REFERENCES OPERACION.EFPTO (CODEF,PUNTO),
  CONSTRAINT FK_EFPTOEQU_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
