ALTER TABLE OPERACION.EFPTOEQUCMP ADD (
  CONSTRAINT FK_EFPTOEQUCMP_EFPTOEQU 
 FOREIGN KEY (CODEF, PUNTO, ORDEN) 
 REFERENCES OPERACION.EFPTOEQU (CODEF,PUNTO,ORDEN)
    ON DELETE CASCADE,
  CONSTRAINT FK_EFPTOEQUCMP_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
