ALTER TABLE OPERACION.EFPTOETAACT_STD ADD (
  CONSTRAINT FK_EFPTOETAACT_ACTIVIDAD_STD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_EFPTOETAACT_EFPTOETA_STD 
 FOREIGN KEY (IDPAQ, PUNTO, CODETA) 
 REFERENCES OPERACION.EFPTOETA_STD (IDPAQ,PUNTO,CODETA),
  CONSTRAINT FK_EFPTOETAACT_PRECIARIO_STD 
 FOREIGN KEY (CODPREC) 
 REFERENCES OPERACION.PRECIARIO (CODPREC));
