ALTER TABLE OPERACION.ETAPAXAREA ADD (
  CONSTRAINT FK_ETAPAXAREA_AREAOPE 
 FOREIGN KEY (AREA) 
 REFERENCES OPERACION.AREAOPE (AREA),
  CONSTRAINT FK_ETAPAXAREA_ETAPA 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA));
