-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE OPERACION.SGAT_POSTV_SERV_EXT
  ADD CONSTRAINT FK_PSRVT_TEXTT FOREIGN KEY (ID_POSTV_SERV)
  REFERENCES OPERACION.SGAT_POSTV_SERV (ID_POSTV_SERV);
