-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE OPERACION.SGAT_POSTV_EXT
  ADD CONSTRAINT FK_POSTT_TEXTT FOREIGN KEY (IDPROCESS)
  REFERENCES OPERACION.SGAT_POSTV (IDPROCESS);
