-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE OPERACION.SGAT_CID_SERV_LICENCIA
  ADD CONSTRAINT PK_SGA_PROCESO_CID_SERV PRIMARY KEY (SERLN_CID, SERLI_SECUENCIA)
  USING INDEX 
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

ALTER TABLE OPERACION.SGAT_CID_SERV_LICENCIA
  ADD CONSTRAINT FK_LCABT_SERLT FOREIGN KEY (SERLC_NUMSLC)
  REFERENCES OPERACION.SGAT_PROCESO_LIC_CAB (LCABC_NUMSLC);
