ALTER TABLE OPERACION.FORXACT ADD (
  CONSTRAINT FK_FORXACT_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_FORXACT_FORMULA 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR));
