ALTER TABLE OPERACION.INSPRDSLA ADD (
  CONSTRAINT FK_INSPRDSLA_PID 
 FOREIGN KEY (PID) 
 REFERENCES OPERACION.INSPRD (PID),
  CONSTRAINT FK_INSPRDSLA_SLA 
 FOREIGN KEY (IDSLA) 
 REFERENCES SALES.VTATABSLA (IDSLA),
  CONSTRAINT FK_PRDSLA_INSSLA 
 FOREIGN KEY (IDINSSLA) 
 REFERENCES SALES.VTAINSSLA (IDINSSLA));
