ALTER TABLE OPERACION.INSSRVXINSSRV ADD (
  CONSTRAINT FK_INSSRVXINSSRV_INSSRV_HIJO 
 FOREIGN KEY (CODINSSRV_HIJO) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_INSSRVXINSSRV_INSSRV_PADRE 
 FOREIGN KEY (CODINSSRV_PADRE) 
 REFERENCES OPERACION.INSSRV (CODINSSRV));
