ALTER TABLE OPERACION.INSSRVSLA ADD (
  CONSTRAINT FK_INSSRVSLA_SID 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_SRVSLA_INSSLA 
 FOREIGN KEY (IDINSSLA) 
 REFERENCES SALES.VTAINSSLA (IDINSSLA),
  CONSTRAINT FK_INSSRVSLA_SLA 
 FOREIGN KEY (IDSLA) 
 REFERENCES SALES.VTATABSLA (IDSLA));
