ALTER TABLE OPERACION.INSSRV ADD (
  CONSTRAINT FK_INSSRV_ESTINSSRV 
 FOREIGN KEY (ESTINSSRV) 
 REFERENCES OPERACION.ESTINSSRV (ESTINSSRV),
  CONSTRAINT FK_INSSRV_INSSRV_DES 
 FOREIGN KEY (CODINSSRV_DES) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_INSSRV_INSSRV_ORI 
 FOREIGN KEY (CODINSSRV_ORI) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_INSSRV_INSSRV_PAD 
 FOREIGN KEY (CODINSSRV_PAD) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_INSSRV_MOTINSSRV 
 FOREIGN KEY (CODMOTINSSRV) 
 REFERENCES OPERACION.MOTINSSRV (CODMOTINSSRV),
  CONSTRAINT FK_INSSRV_TIPINSSR 
 FOREIGN KEY (TIPINSSRV) 
 REFERENCES OPERACION.TIPINSSRV (TIPINSSRV),
  CONSTRAINT FK_INSSRV_VTATABDST 
 FOREIGN KEY (CODUBI) 
 REFERENCES MARKETING.VTATABDST (CODUBI));
