ALTER TABLE OPERACION.INSSRVEQU ADD (
  CONSTRAINT FK_INSSRVEQU_INSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_INSSRVEQU_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
