ALTER TABLE OPERACION.MATETAPAXFOR ADD (
  CONSTRAINT FK_MATETAPAXFOR_FORMULA 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_MATETAPAXFOR_ETAPA 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_MATETAPAXFOR_3 
 FOREIGN KEY (CODMAT) 
 REFERENCES PRODUCCION.ALMTABMAT (CODMAT));
