ALTER TABLE OPERACION.MATXFOR ADD (
  CONSTRAINT FK_MATXFOR_FORMULA 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_MATXFOR_MATOPE 
 FOREIGN KEY (CODMAT) 
 REFERENCES OPERACION.MATOPE (CODMAT));
