ALTER TABLE OPERACION.OPE_FORMULA_ACTIVIDAD_DET ADD (
  CONSTRAINT FK_OPE_FORMULA_ACTIVIDAD_DET_1 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_OPE_FORMULA_ACTIVIDAD_DET_2 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_OPE_FORMULA_ACTIVIDAD_DET_3 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT));
