ALTER TABLE OPERACION.OPE_SRV_RECARGA_CAB ADD (
  CONSTRAINT FK_OPE_SRV_RECARGA_CAB_1 
 FOREIGN KEY (CODCLI) 
 REFERENCES MARKETING.VTATABCLI (CODCLI),
  CONSTRAINT FK_OPE_SRV_RECARGA_CAB_2 
 FOREIGN KEY (IDPAQ) 
 REFERENCES SALES.PAQUETE_VENTA (IDPAQ),
  CONSTRAINT FK_OPE_SRV_RECARGA_CAB_3 
 FOREIGN KEY (NUMSLC) 
 REFERENCES SALES.VTATABSLCFAC (NUMSLC) DISABLE);
