ALTER TABLE OPERACION.OPE_PLANOXCONTRATA_REL ADD (
  CONSTRAINT PK_OPE_PLANOXCONTRATA_REL
 PRIMARY KEY
 (CODCON, IDPLANO, TIPTRA),
  CONSTRAINT UK_PRIORIDAD_PLANO
 UNIQUE (IDPLANO, TIPTRA, PRIORIDAD));
