ALTER TABLE OPERACION.OPE_FORMULA_MATERIAL_DET ADD (
  CONSTRAINT FK_OPE_FORMULA_MATERIAL_DET_1 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_OPE_FORMULA_MATERIAL_DET_2 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_OPE_FORMULA_MATERIAL_DET_3 
 FOREIGN KEY (CODMAT) 
 REFERENCES PRODUCCION.ALMTABMAT (CODMAT));
