ALTER TABLE OPERACION.OPE_INS_EQUIPO_DET ADD (
  CONSTRAINT FK_EQUIPO_DET_CODINSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_OPE_INS_EQUIPO_DET_TIPEQU 
 FOREIGN KEY (IDINS_EQUIPO) 
 REFERENCES OPERACION.OPE_INS_EQUIPO_CAB (IDINS_EQUIPO));
