ALTER TABLE OPERACION.OPE_AGENDA_MASIVA_REG ADD (
  CONSTRAINT FK_OPE_AGENDA_MASIVA_REG_1 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_OPE_AGENDA_MASIVA_REG_2 
 FOREIGN KEY (CODCON) 
 REFERENCES OPERACION.CONTRATA (CODCON),
  CONSTRAINT FK_OPE_AGENDA_MASIVA_REG_3 
 FOREIGN KEY (IDAGENDA) 
 REFERENCES OPERACION.AGENDAMIENTO (IDAGENDA));
