ALTER TABLE OPERACION.OT ADD (
  CONSTRAINT FK_OT_ESTOT 
 FOREIGN KEY (ESTOT) 
 REFERENCES OPERACION.ESTOT (ESTOT),
  CONSTRAINT FK_OT_MOTOT 
 FOREIGN KEY (CODMOTOT) 
 REFERENCES OPERACION.MOTOT (CODMOTOT),
  CONSTRAINT FK_OT_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_OT_TIPTRABAJO 
 FOREIGN KEY (TIPTRA) 
 REFERENCES OPERACION.TIPTRABAJO (TIPTRA),
  CONSTRAINT PK_OT_AREAOPE 
 FOREIGN KEY (AREA) 
 REFERENCES OPERACION.AREAOPE (AREA));
