ALTER TABLE OPERACION.OTPTOEQUCMP ADD (
  CONSTRAINT FK_OTPTOEQUCMP_OTPTOEQU 
 FOREIGN KEY (CODOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.OTPTOEQU (CODOT,PUNTO,ORDEN),
  CONSTRAINT FK_OTPTOEQUCMP_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
