ALTER TABLE OPERACION.OTPTOETACON ADD (
  CONSTRAINT FK_OTPTOETACON_CONTRATA 
 FOREIGN KEY (CODCON) 
 REFERENCES OPERACION.CONTRATA (CODCON),
  CONSTRAINT FK_OTPTOETACON_OTPTOETA 
 FOREIGN KEY (CODOT, PUNTO, CODETA) 
 REFERENCES OPERACION.OTPTOETA (CODOT,PUNTO,CODETA));
