ALTER TABLE OPERACION.OTPTOETAMAT ADD (
  CONSTRAINT FK_OTPTOETAMAT_MATOPE 
 FOREIGN KEY (CODMAT) 
 REFERENCES OPERACION.MATOPE (CODMAT),
  CONSTRAINT FK_OTPTOETAMAT_OTPTOETA 
 FOREIGN KEY (CODOT, PUNTO, CODETA) 
 REFERENCES OPERACION.OTPTOETA (CODOT,PUNTO,CODETA));
