ALTER TABLE OPERACION.OTPTOETAFOR ADD (
  CONSTRAINT FK_OTPTOETAFOR_FORMULA 
 FOREIGN KEY (CODFOR) 
 REFERENCES OPERACION.FORMULA (CODFOR),
  CONSTRAINT FK_OTPTOETAFOR_OTPTOETA 
 FOREIGN KEY (CODOT, PUNTO, CODETA) 
 REFERENCES OPERACION.OTPTOETA (CODOT,PUNTO,CODETA));
