ALTER TABLE OPERACION.OTPTOETA ADD (
  CONSTRAINT FK_OTPTOETA_ETAPA 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_OTPTOETA_OTPTO 
 FOREIGN KEY (CODOT, PUNTO) 
 REFERENCES OPERACION.OTPTO (CODOT,PUNTO));
