ALTER TABLE OPERACION.OTPTO ADD (
  CONSTRAINT FK_OTPTO_ESTOTPTO 
 FOREIGN KEY (ESTOTPTO) 
 REFERENCES OPERACION.ESTOTPTO (ESTOTPTO),
  CONSTRAINT FK_OTPTO_INSSRV2 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_OTPTO_OT 
 FOREIGN KEY (CODOT) 
 REFERENCES OPERACION.OT (CODOT));
