-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE OPERACION.SGAT_EF_EQUIPO_CNFG
  ADD CONSTRAINT PK_SGAT_EF_EQUIPO_CNFG PRIMARY KEY (EFQCN_ID)
  USING INDEX 
  TABLESPACE OPERACION_DAT
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
ALTER TABLE OPERACION.SGAT_EF_EQUIPO_CNFG
  ADD CONSTRAINT FK_EFQC_EFEQ FOREIGN KEY (EFEQN_ID)
  REFERENCES OPERACION.SGAT_EF_EQUIPO_SRVC (EFEQN_ID);
