ALTER TABLE OPERACION.PLANO ADD (
  CONSTRAINT FK_PLANO_SOLOTPTOETA 
 FOREIGN KEY (CODSOLOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.SOLOTPTOETA (CODSOLOT,PUNTO,ORDEN),
  CONSTRAINT FK_PLANO_TAREAWF 
 FOREIGN KEY (IDTAREAWF) 
 REFERENCES OPEWF.TAREAWF (IDTAREAWF));
