ALTER TABLE OPERACION.PRESUPUESTO ADD (
  CONSTRAINT FK_PRESUPUESTO_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_PRESUPUESTO_TIPTRABAJO 
 FOREIGN KEY (TIPTRA) 
 REFERENCES OPERACION.TIPTRABAJO (TIPTRA));
