ALTER TABLE OPERACION.PREUBI ADD (
  CONSTRAINT FK_PREUBI_INSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_PREUBI_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT));
