ALTER TABLE OPERACION.REGINSPROF24H ADD (
  CONSTRAINT FK_REGINSPROF24H_ESTPROF24H 
 FOREIGN KEY (ESTPROF24H) 
 REFERENCES OPERACION.ESTPROF24H (ESTPROF24H),
  CONSTRAINT FK_REGINSPROF24H_MITELMEX 
 FOREIGN KEY (CORREO) 
 REFERENCES OPERACION.USUARIOMITELMEX (CORREO));
