ALTER TABLE OPERACION.SECUENCIA_ESTADOS_AGENDA ADD (
  CONSTRAINT FK_SECUENCIA_ESTADOS_AGENDA1 
 FOREIGN KEY (ESTAGENDAINI) 
 REFERENCES OPERACION.ESTAGENDA (ESTAGE),
  CONSTRAINT FK_SECUENCIA_ESTADOS_AGENDA2 
 FOREIGN KEY (ESTAGENDAFIN) 
 REFERENCES OPERACION.ESTAGENDA (ESTAGE));
