ALTER TABLE OPERACION.SOLOT_ANULA ADD (
  CONSTRAINT FK_SOLOT_ANULA_CODSOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_SOLOT_ANULA_CODSOLOT_ANULA 
 FOREIGN KEY (CODSOLOT_ANULA) 
 REFERENCES OPERACION.SOLOT (CODSOLOT));
