ALTER TABLE OPERACION.SOLOTPTOETAACT ADD (
  CONSTRAINT FK_SOLOTPTOETAACT_ACTIVIDAD 
 FOREIGN KEY (CODACT) 
 REFERENCES OPERACION.ACTIVIDAD (CODACT),
  CONSTRAINT FK_SOLOTPTOETAACT_PRECIARIO 
 FOREIGN KEY (CODPRECDIS) 
 REFERENCES OPERACION.PRECIARIO (CODPREC),
  CONSTRAINT FK_SOLOTPTOETAACT_PRECIARIO1 
 FOREIGN KEY (CODPRECLIQ) 
 REFERENCES OPERACION.PRECIARIO (CODPREC),
  CONSTRAINT FK_SOLOTPTOETAACT_SOLOTPTOETA 
 FOREIGN KEY (CODSOLOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.SOLOTPTOETA (CODSOLOT,PUNTO,ORDEN));
