ALTER TABLE OPERACION.SOLOTPTO_ID ADD (
  CONSTRAINT FK_SOLOTPTO_ID_ESTDOCOPE 
 FOREIGN KEY (ESTDOCOPE) 
 REFERENCES OPERACION.ESTDOCOPE (ESTDOCOPE),
  CONSTRAINT FK_SOLOTPTO_ID_SOLOTPTO 
 FOREIGN KEY (CODSOLOT, PUNTO) 
 REFERENCES OPERACION.SOLOTPTO (CODSOLOT,PUNTO)
    ON DELETE CASCADE);
