ALTER TABLE OPERACION.SOLOTPTOEQUCMP ADD (
  CONSTRAINT FK_SOLOTPTOEQUCMP_SOLOTPTOEQU 
 FOREIGN KEY (CODSOLOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.SOLOTPTOEQU (CODSOLOT,PUNTO,ORDEN),
  CONSTRAINT FK_SOLOTPTOEQUCMP_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
