ALTER TABLE OPERACION.SOLOTXSOLOT ADD (
  CONSTRAINT FK_SOLOTXSOLOT_SOLOT 
 FOREIGN KEY (CODSOLOT_P) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_SOLOTXSOLOT_SOLOT1 
 FOREIGN KEY (CODSOLOT_H) 
 REFERENCES OPERACION.SOLOT (CODSOLOT));
