ALTER TABLE OPERACION.SOLOTPTOETAMAT ADD (
  CONSTRAINT FK_SOLOTPTOETAMAT_MATOPE 
 FOREIGN KEY (CODMAT) 
 REFERENCES OPERACION.MATOPE (CODMAT),
  CONSTRAINT FK_SOLOTPTOETAMAT_SOLOTPTOETA 
 FOREIGN KEY (CODSOLOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.SOLOTPTOETA (CODSOLOT,PUNTO,ORDEN));
