ALTER TABLE OPERACION.SOLOTPTOEQU ADD (
  CONSTRAINT FK_SOLOTPTOEQU_SOLOTPTO 
 FOREIGN KEY (CODSOLOT, PUNTO) 
 REFERENCES OPERACION.SOLOTPTO (CODSOLOT,PUNTO),
  CONSTRAINT FK_SOLOTPTOEQU_TIPEQU 
 FOREIGN KEY (TIPEQU) 
 REFERENCES OPERACION.TIPEQU (TIPEQU));
