ALTER TABLE OPERACION.SOLOTPTO ADD (
  CONSTRAINT FK_SOLOTPTO_INSPRD1 
 FOREIGN KEY (PID) 
 REFERENCES OPERACION.INSPRD (PID),
  CONSTRAINT FK_SOLOTPTO_INSPRD2 
 FOREIGN KEY (PID_OLD) 
 REFERENCES OPERACION.INSPRD (PID),
  CONSTRAINT FK_SOLOTPTO_INSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_SOLOTPTO_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_SOLOTPTO_TIPTRAEF 
 FOREIGN KEY (TIPTRAEF) 
 REFERENCES OPERACION.TIPTRAEF (TIPTRAEF));
