ALTER TABLE OPERACION.SOLOTANULA ADD (
  CONSTRAINT FK_SOLOTANULA_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT),
  CONSTRAINT FK_SOLOTANULA_SOLOT_PADRE 
 FOREIGN KEY (CODPADRE) 
 REFERENCES OPERACION.SOLOT (CODSOLOT));
