ALTER TABLE OPERACION.SOLOTPTO_ID_HISTORICO ADD (
  CONSTRAINT FK_SOLOTPTO_ID_HISTORICO_SOLOT 
 FOREIGN KEY (CODSOLOT, PUNTO) 
 REFERENCES OPERACION.SOLOTPTO (CODSOLOT,PUNTO),
  CONSTRAINT FK_SOLOTPTO_ID_HIS_ESTDOCOPE 
 FOREIGN KEY (ESTDOCOPE) 
 REFERENCES OPERACION.ESTDOCOPE (ESTDOCOPE));
