ALTER TABLE OPERACION.SOLOTPTOETAFAC ADD (
  CONSTRAINT FK_SOLOTPTOETAFAC_SOLOTPTOETA 
 FOREIGN KEY (CODSOLOT, PUNTO, ORDEN) 
 REFERENCES OPERACION.SOLOTPTOETA (CODSOLOT,PUNTO,ORDEN),
  CONSTRAINT FK_SOLOTPTOETA_FACTURAPEX 
 FOREIGN KEY (FACTURA) 
 REFERENCES OPERACION.FACTURAPEX (FACTURA));
