ALTER TABLE OPERACION.TIPEQU ADD (
  CONSTRAINT FK_TIPEQU_ESTEQU 
 FOREIGN KEY (ESTEQU) 
 REFERENCES OPERACION.ESTEQU (ESTEQU),
  CONSTRAINT FK_TIPEQU_GRPTIPEQU 
 FOREIGN KEY (GRPTIPEQU) 
 REFERENCES OPERACION.GRPTIPEQU (GRPTIPEQU),
  CONSTRAINT FK_TIPEQU_3 
 FOREIGN KEY (IDPROTOCOLO) 
 REFERENCES METASOLV.PROTOCOLO (IDPROTOCOLO));
