ALTER TABLE OPERACION.TIPINFOTXETAPA ADD (
  CONSTRAINT FK_TIPINFOTXETAPA_ETAPA 
 FOREIGN KEY (CODETA) 
 REFERENCES OPERACION.ETAPA (CODETA),
  CONSTRAINT FK_TIPINFOTXETAPA_TIPINFOT 
 FOREIGN KEY (TIPINFOT) 
 REFERENCES OPERACION.TIPINFOT (TIPINFOT));
