ALTER TABLE OPERACION.TIPINFOTXMOTOT ADD (
  CONSTRAINT FK_TIPINFOTXMOTOT_MOTOT 
 FOREIGN KEY (CODMOTOT) 
 REFERENCES OPERACION.MOTOT (CODMOTOT),
  CONSTRAINT FK_TIPINFOTXMOTOT_TIPINFOT 
 FOREIGN KEY (TIPINFOT) 
 REFERENCES OPERACION.TIPINFOT (TIPINFOT));
