ALTER TABLE OPERACION.TIPO_AGENDA ADD (
  CONSTRAINT FK_TIPO_AGENDA_IDFLUJO 
 FOREIGN KEY (IDFLUJO) 
 REFERENCES OPERACION.FLUJO_AGENDA (IDFLUJO) DISABLE,
  CONSTRAINT FK_TIPO_AGENDA_TIPAGENDA 
 FOREIGN KEY (CLASEAGENDA) 
 REFERENCES OPERACION.CLASEAGENDA (CLASEAGENDA));
