ALTER TABLE OPERACION.TIPTRAXAREA ADD (
  CONSTRAINT FK_TIPTRAXAREA_AREAOPE 
 FOREIGN KEY (AREA) 
 REFERENCES OPERACION.AREAOPE (AREA),
  CONSTRAINT FK_TIPTRAXAREA_TIPTRABAJO 
 FOREIGN KEY (TIPTRA) 
 REFERENCES OPERACION.TIPTRABAJO (TIPTRA));
