ALTER TABLE OPERACION.TIPTRABAJO ADD (
  CONSTRAINT FK_TIPTRABAJO_MOTINSSRV 
 FOREIGN KEY (CODMOTINSSRV) 
 REFERENCES OPERACION.MOTINSSRV (CODMOTINSSRV),
  CONSTRAINT FK_TIPTRA_BLOQUEO 
 FOREIGN KEY (BLOQUEO_DESBLOQUEO) 
 REFERENCES OPERACION.BLOQUEO_DESBLOQUEO (BLOQUEO_DESBLOQUEO));
