ALTER TABLE OPERACION.TRSINSSRV ADD (
  CONSTRAINT FK_TRSINSSRV_ESTTRS 
 FOREIGN KEY (ESTTRS) 
 REFERENCES OPERACION.ESTTRS (ESTTRS),
  CONSTRAINT FK_TRSINSSRV_OT 
 FOREIGN KEY (CODOT) 
 REFERENCES OPERACION.OT (CODOT),
  CONSTRAINT FK_TRSINSSRV_TIPTRS 
 FOREIGN KEY (TIPTRS) 
 REFERENCES OPERACION.TIPTRS (TIPTRS),
  CONSTRAINT FK_TRSINSSR_ESTINSSRV 
 FOREIGN KEY (ESTINSSRV) 
 REFERENCES OPERACION.ESTINSSRV (ESTINSSRV),
  CONSTRAINT FK_TRSINSSR_ESTINSSRVANT 
 FOREIGN KEY (ESTINSSRVANT) 
 REFERENCES OPERACION.ESTINSSRV (ESTINSSRV));
