ALTER TABLE OPERACION.TRSSOLOT ADD (
  CONSTRAINT FK_TRSSOLOT_ESTTRS 
 FOREIGN KEY (ESTTRS) 
 REFERENCES OPERACION.ESTTRS (ESTTRS),
  CONSTRAINT FK_TRSSOLOT_INSPRD1 
 FOREIGN KEY (PID) 
 REFERENCES OPERACION.INSPRD (PID),
  CONSTRAINT FK_TRSSOLOT_INSPRD2 
 FOREIGN KEY (PID_OLD) 
 REFERENCES OPERACION.INSPRD (PID),
  CONSTRAINT FK_TRSSOLOT_INSSRV 
 FOREIGN KEY (CODINSSRV) 
 REFERENCES OPERACION.INSSRV (CODINSSRV),
  CONSTRAINT FK_TRSSOLOT_SOLOT 
 FOREIGN KEY (CODSOLOT) 
 REFERENCES OPERACION.SOLOT (CODSOLOT));
