ALTER TABLE OPERACION.VIGRESUMEN ADD (
  CONSTRAINT FK_VIGRESUMEN_VIGETAPA 
 FOREIGN KEY (IDETAPA) 
 REFERENCES OPERACION.VIGETAPA (IDETAPA),
  CONSTRAINT FK_VIGRESUMEN_VIGFASE 
 FOREIGN KEY (FASE) 
 REFERENCES OPERACION.VIGFASE (FASE),
  CONSTRAINT FK_VIGRESUMEN_VIGTIPO 
 FOREIGN KEY (TIPO) 
 REFERENCES OPERACION.VIGTIPO (TIPO));
