CREATE OR REPLACE VIEW OPERACION.V_OPE_SRV_RECARGA_CAB
AS 
select "NUMREGISTRO","CODIGO_RECARGA","FECINIVIG","FECFINVIG","FECALERTA","FECCORTE","FLG_RECARGA","TIPORECARGA","CODCLI","NUMSLC","CODSOLOT","IDPAQ","ESTADO","CODUSU","FECUSU" from ope_srv_recarga_cab;


