CREATE OR REPLACE VIEW OPERACION.V_SIN_SINONIMO
AS 
(  
SELECT A.OBJECT_TYPE, A.NOMBRE TABLA, B.NOMBRE SINOM, 'CREATE PUBLIC SYNONYM '||A.NOMBRE|| ' FOR '||A.OWNER||'.'||A.NOMBRE||';' FROM  
(SELECT OBJECT_TYPE, OBJECT_NAME NOMBRE ,OWNER FROM ALL_OBJECTS WHERE OBJECT_TYPE in('TABLE','VIEW','FUNCTION','PROCEDURE') and OWNER in ( 'OPERACION', 'METASOLV','ENCUESTA') ) A,  
(SELECT OBJECT_NAME NOMBRE FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'SYNONYM' AND OWNER = 'PUBLIC') B  
WHERE  A.NOMBRE = B.NOMBRE (+) and B.NOMBRE is null  
);


